### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity$DefaultDrop.stack()" because "drop" is null

### ISSUE THREAD

**Issue by KioProject123** [PaperSpigot/Paper#10004]
### Expected behavior

No error is reported, and the mobs drop items normally.

### Observed/Actual behavior

```
[17:45:52 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInUseEntity@59517911, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity$DefaultDrop.stack()" because "drop" is null
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:975) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1839) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1733) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1556) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:319) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1326) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2181) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2778) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2702) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

```
    @EventHandler
    public void onPlayerInteract(final EntityDeathEvent e) {
        final Chest chest = (Chest) Material.CHEST.createBlockData().createBlockState();
        final List<LootTables> lootTables = Arrays.stream(LootTables.values()).filter(lootTable -> lootTable.getKey().getKey().startsWith("chests")).toList();
        lootTables.get(ThreadLocalRandom.current().nextInt(lootTables.size())).getLootTable()
                  .fillInventory(chest.getBlockInventory(), new Random(), new LootContext.Builder(e.getEntity().getLocation()).build());

        e.getDrops().addAll(Arrays.asList(chest.getInventory().getStorageContents()));
    }
```
1、Use the above plugin
2、Kill any mobs

### Plugin and Datapack List

Only test plugins

### Paper version

[17:51:10 INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version
Previous version: git-kiocg-"2355ead" (MC: 1.20.2)

**Comment by electronicboy** [comment]
You put a null entry into the drops list, don't do that; idk if we'll protect against this
