### ISSUE TITLE
Online-mode proxy failing to login player to backend server

### ISSUE THREAD

**Issue by Dean904** [PaperSpigot/Paper#10098]
### Stack trace

```
[15:04:00 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-00ef92bc-b312)...
[15:04:00 INFO]: Loading localizations...
[15:04:00 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[15:04:00 INFO]: Loading plugins...
[15:04:00 INFO]: Loaded 0 plugins
[15:04:01 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25555
[15:04:01 INFO]: Done (0.68s)!
[15:04:12 INFO]: [connected player] Borox1 (/127.0.0.1:55366) has connected
[15:04:12 INFO]: [server connection] Borox1 -> lobby has connected
[15:04:12 ERROR]: [server connection] Borox1 -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.LoginSessionHandler@712b526d
java.lang.IllegalStateException: Backend server is online-mode!
        at com.velocitypowered.proxy.connection.backend.LoginSessionHandler.handle(LoginSessionHandler.java:81) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.protocol.packet.EncryptionRequest.handle(EncryptionRequest.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-00ef92bc-b312)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[15:04:12 INFO]: [server connection] Borox1 -> lobby has disconnected
```

### Plugin and Datapack List

[15:07:45 INFO]: Server Plugins (2):
[15:07:45 INFO]: Bukkit Plugins:
[15:07:45 INFO]:  - FastAsyncWorldEdit, myPaperPlugin

[15:08:27 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[15:08:27 INFO]: There are no more data packs available

### Paper version

[15:07:23 INFO]: Checking version, please wait...
[15:07:23 INFO]: This server is running Paper version git-Paper-363 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3484ae9)
You are running the latest version
Previous version: git-Paper-350 (MC: 1.20.4)

**Comment by lynxplay** [comment]
This seems more like a configuration issue than anything else.

Please checkout https://docs.papermc.io/velocity/player-information-forwarding. Any further questions are best asked in our [discord](https://discord.gg/papermc).
