### ISSUE TITLE
[User Err] Unable to retrieve blocks in negative coordinates

### ISSUE THREAD

**Issue by JewishBanana** [PaperSpigot/Paper#10104]
### Expected behavior

Spigot-like behaviour where when fetching a block or location with a negative Y coordinate it works like any other block or location object.

### Observed/Actual behavior

```
[16:37:51 WARN]: java.lang.IllegalArgumentException: y out of range (expected 0-256, got -32)
[16:37:51 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463)
[16:37:51 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:401)
[16:37:51 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftChunk.getBlock(CraftChunk.java:109)
[16:37:51 WARN]:        at DeadlyDisastersPRO-V14.3.jar//deadlydisasters.listeners.spawners.InfestedSpawner.onChunkLoad(InfestedSpawner.java:59)
[16:37:51 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source)
[16:37:51 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[16:37:51 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[16:37:51 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:37:51 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[16:37:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[16:37:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[16:37:51 WARN]:        at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:785)
[16:37:51 WARN]:        at net.minecraft.world.level.chunk.Chunk.onChunkLoad(Chunk.java:737)
[16:37:51 WARN]:        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1339)
[16:37:51 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1382)
[16:37:51 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1366)
[16:37:51 WARN]:        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1319)
[16:37:51 WARN]:        at net.minecraft.server.level.ChunkProviderServer.s(ChunkProviderServer.java:430)
[16:37:51 WARN]:        at net.minecraft.server.level.ChunkProviderServer$b.x(ChunkProviderServer.java:868)
[16:37:51 WARN]:        at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:426)
[16:37:51 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1446)
[16:37:51 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1358)
[16:37:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bu(IAsyncTaskHandler.java:114)
[16:37:51 WARN]:        at net.minecraft.server.MinecraftServer.executeModerately(MinecraftServer.java:1329)
[16:37:51 WARN]:        at net.minecraft.server.MinecraftServer.prepareLevels(MinecraftServer.java:819)
[16:37:51 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.createWorld(CraftServer.java:1391)
[16:37:51 WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:815)
[16:37:51 WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:502)
[16:37:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[16:37:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[16:37:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[16:37:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[16:37:51 WARN]:        at Multiverse-Core-4.3.1.jar//com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[16:37:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[16:37:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
[16:37:51 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[16:37:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[16:37:51 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637)
[16:37:51 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548)
[16:37:51 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673)
[16:37:51 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433)
[16:37:51 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[16:37:51 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1132)
[16:37:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[16:37:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps/models to reproduce

`e.getChunk().getBlock(0, -32, 0).getBiome()`

### Plugin and Datapack List

Not plugin related issue

### Paper version

This server is running Paper version git-Paper-349 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: dc62150)

### Other

This has been a bug since 1.17 paper and I just haven't reported it until now

**Comment by Machine-Maker** [comment]
The min/max values for that check is not hardcoded, it's taken directly from the world's min build height and max build height. 

Can you replicate this on a new world?

**Comment by JewishBanana** [comment]
> The min/max values for that check is not hardcoded, it's taken directly from the world's min build height and max build height.
> 
> Can you replicate this on a new world?

Yes, this is done on a new world. I can go into negative coordinates and build no problem. If I use the same code and same world on spigot equivalent version it has no problems. I originally assumed it was a problem with spigot when 1.17 came out and reported it to md5 and he told me it was a paper bug and he is correct.

**Comment by Machine-Maker** [comment]
It works fine for me on a new world. 

All I had was this in a plugin, **no** other plugins.
```java
    @Override
    public void onEnable() {
        this.getServer().getPluginManager().registerEvents(this, this);

        final WorldCreator worldCreator = new WorldCreator(new NamespacedKey(this, "test_world"));
        worldCreator.environment(World.Environment.NORMAL);
        final World world = worldCreator.createWorld();
    }

    @EventHandler
    public void onEvent(ChatEvent event) {
        System.out.println(event.getPlayer().getChunk().getBlock(0, -32, 0).getBiome());
    }
```

Can you replicate this without any plugins except what I have above?

**Comment by TonytheMacaroni** [comment]
I am able to replicate the error with this code:

```yml
@EventHandler
public void onEvent(ChunkLoadEvent e) {
    e.getChunk().getBlock(0, -32, 0).getBiome();
}
```

With the error (on startup):
```
[18:55:22] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to Test v1.0
java.lang.IllegalArgumentException: y out of range (expected 0-256, got -32)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftChunk.validateChunkCoordinates(CraftChunk.java:401) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftChunk.getBlock(CraftChunk.java:109) ~[paper-1.20.2.jar:git-Paper-318]
	at me.tonythemacaroni.test.TestListener.onEvent(TestListener.java:11) ~[Test.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:785) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:737) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1339) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1382) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1366) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1319) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:783) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:63) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:491) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by lynxplay** [comment]
@TonytheMacaroni can you provide your worlds level.dat file ?

**Comment by TonytheMacaroni** [comment]
In updating to a fresh 1.20.4 world, I realized that the errors were purely coming from chunks in the nether and end, which do follow a 0-256 Y range. As such, I did not replicate the original issue, if there is one.

**Comment by JewishBanana** [comment]
> In updating to a fresh 1.20.4 world, I realized that the errors were purely coming from chunks in the nether and end, which do follow a 0-256 Y range. As such, I did not replicate the original issue, if there is one.

Smh, I didn't realize this until now but you are right. Paper must be pre-loading the chunks from the end and nether which spigot does not do and this led me to believe that the error was being thrown from me being in the server and the chunks around me loading. I wish the error would have specified the world lol. Thanks bro!
