### ISSUE TITLE
EncoderException in UTFDataFormatException of shulker box

### ISSUE THREAD

**Issue by 0-9** [PaperSpigot/Paper#10132]
### Stack trace

```
[12:04:31] [Netty Server IO #1/ERROR]: Packet encoding of packet ClientboundSetEntityDataPacket (ID: 86) threw (skippable? false)
io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: encoded string (".$$aaaa...aaaaaaa") too long: 65537 bytes
	at net.minecraft.network.FriendlyByteBuf.writeNbt(FriendlyByteBuf.java:612) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.writeItem(FriendlyByteBuf.java:657) ~[?:?]
	at net.minecraft.network.syncher.EntityDataSerializers$1.write(EntityDataSerializers.java:45) ~[?:?]
	at net.minecraft.network.syncher.EntityDataSerializers$1.copy(EntityDataSerializers.java:42) ~[?:?]
	at net.minecraft.network.syncher.SynchedEntityData$DataValue.write(SynchedEntityData.java:394) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:18) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[paper-1.20.4.jar:git-Paper-377]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.4.jar:git-Paper-377]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.io.UTFDataFormatException: encoded string (".$$aaaa...aaaaaaa") too long: 65537 bytes
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:369) ~[?:?]
	at java.io.DataOutputStream.writeUTF(DataOutputStream.java:333) ~[?:?]
	at io.netty.buffer.ByteBufOutputStream.writeUTF(ByteBufOutputStream.java:143) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.nbt.StringTag.write(StringTag.java:70) ~[?:?]
	at net.minecraft.nbt.CompoundTag.writeNamedTag(CompoundTag.java:539) ~[?:?]
	at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:181) ~[?:?]
	at net.minecraft.nbt.CompoundTag.writeNamedTag(CompoundTag.java:539) ~[?:?]
	at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:181) ~[?:?]
	at net.minecraft.nbt.NbtIo.writeAnyTag(NbtIo.java:353) ~[?:?]
	at net.minecraft.network.FriendlyByteBuf.writeNbt(FriendlyByteBuf.java:609) ~[?:?]
	... 32 more
```

### Plugin and Datapack List

none

### Actions to reproduce (if known)
https://www.youtube.com/watch?v=NEAoUV6dkmg
1. place the shulker box with some items and 65535 bytes of CustomName
2. break the shulker box
3. Players near the item entity of the shulker box are disconnected with the following error: Internal Exception: io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: encoded string (".$$aaaa...aaaaaaa") too long: 65537 bytes

### Paper version

This server is running Paper version git-Paper-377 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 25a99b1)
You are running the latest version
Previous version: git-Paper-373 (MC: 1.20.4)

**Comment by jihwan0511** [comment]
its works only 1.20.4

**Comment by kennytv** [comment]
How did you set the display name/get the item?

**Comment by jihwan0511** [comment]
> How did you set the display name/get the item?

i used nbt editer
https://www.curseforge.com/minecraft/mc-mods/nbt-editor
