### ISSUE TITLE
minecraft server failed to load datapacks, can't proceed with server load.

### ISSUE THREAD

**Issue by Monstrai** [PaperSpigot/Paper#10214]
### Stack trace

[17:32:56] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:32:58] [ServerMain/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Overworld settings missing
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:289) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.Main.main(Main.java:324) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: Overworld settings missing
	at net.minecraft.world.level.levelgen.WorldDimensions.<init>(WorldDimensions.java:42) ~[paper-1.20.1.jar:git-Paper-196]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$1.lambda$decode$0(RecordCodecBuilder.java:185) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[paper-1.20.1.jar:?]
	at com.mojang.serialization.DataResult.map(DataResult.java:111) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$1.lambda$decode$1(RecordCodecBuilder.java:184) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$15(DataResult.java:144) ~[datafixerupper-6.0.8.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$17(DataResult.java:143) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[paper-1.20.1.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$1.decode(RecordCodecBuilder.java:183) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:249) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.20.1.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Decoder.decode(Decoder.java:22) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:26) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.world.level.storage.LevelStorageSource.readWorldGenSettings(LevelStorageSource.java:158) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource.lambda$getLevelData$4(LevelStorageSource.java:312) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource.readLevelData(LevelStorageSource.java:264) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.getDataTag(LevelStorageSource.java:551) ~[?:?]
	at net.minecraft.server.Main.lambda$main$1(Main.java:262) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.WorldLoader.load(WorldLoader.java:35) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.Main.lambda$main$2(Main.java:258) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.Util.blockUntilDone(Util.java:821) ~[?:?]
	at net.minecraft.Util.blockUntilDone(Util.java:816) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:257) ~[paper-1.20.1.jar:git-Paper-196]
	... 3 more

### Plugin and Datapack List

Plugins:
Bettertridents-2.2.6 
CombatWeaponaryPlus v1.5.7
GravesStonesPlus
iShop-2.25
voicechat-bukkit-2.4.24

Datapacks:
arwensfurniture
Better Hanging Signs v3
cacernous-r-2-0-1
furnicraft v1.2
joshs-more-foods-datapack-v.4.1.4
update-aquatic-2-data-pack-v1-1

### Paper version

Paper 196 (1.20.1)

**Comment by electronicboy** [comment]
Unsupported version, and this is generally an issue down to incompatible datapacks

**Comment by Monstrai** [comment]
> Unsupported version, and this is generally an issue down to incompatible datapacks

And why did work before?

**Comment by electronicboy** [comment]
You would need to work out what is wrong, vanilla generally doesn't make diagnosing this easy, nor is this the place for support

**Comment by Monstrai** [comment]
> You would need to work out what is wrong, vanilla generally doesn't make diagnosing this easy, nor is this the place for support

Thanks for nothing

**Comment by Monstrai** [comment]
> You would need to work out what is wrong, vanilla generally doesn't make diagnosing this easy, nor is this the place for support

What do you even by "nor is this the place for support" ??

**Comment by electronicboy** [comment]
This is an issue tracker, for reporting issues with supported versions of the software. Not for support, as there are better avenues for that for supported versions of the software which don't flood everybodies emails needlessly, i.e. discord/the forums.
