### ISSUE TITLE
Running Paper on MacOS works but throws an error on startup due to .DS_Store

### ISSUE THREAD

**Issue by tastybento** [PaperSpigot/Paper#10213]
### Expected behavior

No error, it's just a hidden system file.

### Observed/Actual behavior

On server start this error is shown:

```
Loading libraries, please wait...
[22:29:03 ERROR]: [EntrypointUtil] Directory 'plugins/.DS_Store' is not a jar file, cannot load a plugin from it!
java.lang.IllegalArgumentException: Directory 'plugins/.DS_Store' is not a jar file, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.prepareContext(FileProviderSource.java:45) ~[paper-1.20.4.jar:git-Paper-406]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$prepareContext$1(DirectoryProviderSource.java:34) ~[paper-1.20.4.jar:git-Paper-406]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:58) ~[paper-1.20.4.jar:git-Paper-406]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:32) ~[paper-1.20.4.jar:git-Paper-406]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:16) ~[paper-1.20.4.jar:git-Paper-406]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.4.jar:git-Paper-406]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[paper-1.20.4.jar:git-Paper-406]
	at net.minecraft.server.Main.main(Main.java:131) ~[paper-1.20.4.jar:git-Paper-406]
	at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:git-Paper-406]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Steps/models to reproduce

Use Paper 1.20.4 build 406 or later on a Mac. Build 405 does not throw the error.

### Plugin and Datapack List

No plugins, just server.

### Paper version

> version
[22:49:37 INFO]: Checking version, please wait...
[22:49:38 INFO]: This server is running Paper version git-Paper-407 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 8bc5be8)
You are running the latest version
Previous version: git-Paper-405 (MC: 1.20.4)

**Comment by Warriorrrr** [comment]
This is already fixed in build 407

**Comment by tastybento** [comment]
I think you mean 408, but yes, it's fixed on 408.
