### ISSUE TITLE
ConcurrentModificationException on GoalSelector#tick

### ISSUE THREAD

**Issue by MarvinKlar** [PaperSpigot/Paper#10222]
### Expected behavior

The mentioned error should not occur.

### Observed/Actual behavior

I got the following Exception on my Server:

```
[01:13:16] [Server thread/ERROR]: Entity threw exception at world:-804.5000776586575,46.9375,-232.63654721077813
java.util.ConcurrentModificationException: null
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756) ~[?:?]
    at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778) ~[?:?]
    at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:85) ~[app:?]
    at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:841) ~[app:?]
    at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3189) ~[app:?]
    at net.minecraft.world.entity.Mob.aiStep(Mob.java:625) ~[app:?]
    at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[app:?]
    at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:59) ~[app:?]
    at net.minecraft.world.entity.animal.Wolf.aiStep(Wolf.java:193) ~[app:?]
    at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2915) ~[app:?]
    at net.minecraft.world.entity.Mob.tick(Mob.java:393) ~[app:?]
    at net.minecraft.world.entity.animal.Wolf.tick(Wolf.java:209) ~[app:?]
    at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1120) ~[app:?]
    at net.minecraft.world.level.Level.guardEntityTick(Level.java:977) ~[app:?]
    at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
    at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1627) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
    at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Steps/models to reproduce

I was not able to reproduce the bug yet, since I don't know which player caused the bug to occour.

### Plugin and Datapack List

Plugins (77): AnnouncerPlus, Armor, ArrowBreaker, Automation, BanItem, BKCommonLib, BossShopPro, CalendarEvents, CleanroomGenerator, ClientChecker, ConditionalEvents, CoreProtect, Courier, CraftBook, Crafting, CustomSpawner, CustomTime, Dialog, DiscordHook, Dynasty, dynmap, Dynmap-WorldGuard*, Essentials, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), Gringotts, GSit, Illness, Inscriptions, ItemJoin, LightCleaner, Locks, LuckPerms, LuckPermsAddon, LWC, MicroJump*, MoneyTracker, MoreCrafting, Multiverse-Core, Multiverse-Inventories, MyCommand, MythicCrucible, MythicMobs, OtherDrops, PlaceholderAPI, Plants, PlugManX (PlugMan), Points, PrometheusExporter, ProtocolLib, PvPManager, QuestItems, RecipeBook, Resources, RocketPlaceholders, Roleplay, Rotten, SafeRestart, SavageGraveyards, SchematicBrushReborn, SimpleRename, Skin, Swim, Ticket, TitleManager, TreasureChest, Unconscious, Vault, VentureChat, ViaVersion, VIP, VirtualBooks, Votifier, Warns, WorldBorder, WorldGuard, WorldGuardEvents

### Paper version

This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-84 (MC: 1.17.1)

**Comment by electronicboy** [comment]
Unsupported version of paper, and stuff like this is generally down to things messing with entities improperly
