### ISSUE TITLE
Rare error when loading plugins

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#10236]
### Expected behavior

This error should probably be handled, currently it isn't and causes a pretty catastrophic error causing no plugins to load at all, the server does not crash however

### Observed/Actual behavior

[11:34:48] [ServerMain/ERROR]: [EntrypointUtil] java.nio.file.NoSuchFileException: plugins/TestPlugin-1.0.jar
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: plugins/TestPlugin-1.0.jar
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87) ~[?:?]
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:132) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.walkFiles(DirectoryProviderSource.java:59) ~[paper-1.20.4.jar:git-Paper-"9e171ef"]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:31) ~[paper-1.20.4.jar:git-Paper-"9e171ef"]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.prepareContext(DirectoryProviderSource.java:17) ~[paper-1.20.4.jar:git-Paper-"9e171ef"]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.4.jar:git-Paper-"9e171ef"]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:101) ~[paper-1.20.4.jar:git-Paper-"9e171ef"]
	at net.minecraft.server.Main.main(Main.java:131) ~[paper-1.20.4.jar:git-Paper-"9e171ef"]
	at org.bukkit.craftbukkit.Main.main(Main.java:326) ~[paper-1.20.4.jar:git-Paper-"9e171ef"]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.nio.file.NoSuchFileException: plugins/TestPlugin-1.0.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:226) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277) ~[?:?]
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374) ~[?:?]
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83) ~[?:?]
	... 18 more

### Steps/models to reproduce

IDK

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version git-Paper-"9e171ef" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
You are 7 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"c5d168c" (MC: 1.20.4)

**Comment by Malfrador** [comment]
I am unable to reproduce this without any reproduction steps. Both the latest build and 409 start and load plugins without any errors, on both Linux and Windows systems.

How are you running the server? Are you using symlinks or something similar? Are you using modified Paper in some way (considering its not a build from our website)?

**Comment by Owen1212055** [comment]
It should be noted that now plugin loading errors like this will cause the server to not load. This is intentional, as in general, we want to be more careful in the plugin lifecycle process as we continue to expose more registry-related stuff... and with that, plugins that are unloaded could cause potential data loss.

**Comment by lynxplay** [comment]
Closing this as stale, without reproduction steps we cannot investigate this further, sorry.
