### ISSUE TITLE
Error when kick player on PlayerJoinEvent

### ISSUE THREAD

**Issue by extremall-dev** [PaperSpigot/Paper#10291]
### Expected behavior

To kick the player on join without errors.

### Observed/Actual behavior

I saw this error:
[01:58:47 ERROR]: Couldn't place player in world
java.lang.IllegalArgumentException: arraySize cannot be negative but was: -1
        at com.google.common.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:40) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.Lists.computeArrayListCapacity(Lists.java:152) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.Lists.newArrayListWithExpectedSize(Lists.java:197) ~[guava-32.1.2-jre.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:362) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:134) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-436]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-436]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Steps/models to reproduce

@EventHandler
public void onJoin(PlayerJoinEvent event)
{
    event.getPlayer().kickPlayer("kick");
}

### Plugin and Datapack List

Plugins are custom.

### Paper version

This server is running Paper version git-Paper-436 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 850b736)

**Comment by Sytm** [comment]
The PlayerJoinEvent is called in a critical piece of code, so kicking the player or teleporting him is not supported. Either wait a single tick using the scheduler or use the AsyncPlayerPreLoginEvent events and set a disconnect message there

**Comment by electronicboy** [comment]
There is generally little interest in trying to make the server support removing a player from the world in these weird areas of chunk system interaction, there is a whole bunch of logic intermingled with this stuff and it's generally not worth it when there are much more suitable events for kicking a player from the server before they're in the process of being registered with the world.

**Comment by stonar96** [comment]
Sorry for commenting on such an old and closed issue. I just randomly stumbled across this while searching for another issue.

Another reason, not yet mentioned, why this should even intentionally lead to an error is that this could potentially lead to unexpected behavior in other plugins expecting `PlayerJoinEvent` -> `PlayerQuitEvent` order. For example:

BadPlugin: `EventPriority.LOW` `PlayerJoinEvent`: Kick player.
GoodPlugin: `EventPriority.NORMAL` `PlayerJoinEvent`: Add player data to map.
GoodPlugin: `EventPriority.NORMAL` `PlayerQuitEvent`: Remove player data from map.

Assuming a naively implemented fix of this issue: In this scenario `PlayerQuitEvent` would be called before `PlayerJoinEvent` in GoodPlugin, since the player is kicked by BadPlugin before `PlayerJoinEvent` in GoodPlugin is called. This leaves invalid state in GoodPlugin.

Keep this in mind in case someone tries to fix this issue or tries to make improvements in this area in the future. However, as @lynxplay already said, I would rather

> properly run into the error that prevents kicking on joining

Also for reference https://github.com/PaperMC/Folia/issues/125.
