### ISSUE TITLE
NPE when getting dropped items from BlockState

### ISSUE THREAD

**Issue by KioProject123** [PaperSpigot/Paper#10363]
### Expected behavior

Get dropped items normally, or throw a more appropriate exception

### Observed/Actual behavior

```
[19:18:21 ERROR]: Error occurred while enabling KioCG-TEST v2021 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getHandle()" because "this.world" is null
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockState.getDrops(CraftBlockState.java:359) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockState.getDrops(CraftBlockState.java:348) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_20_R3.block.CraftBlockState.getDrops(CraftBlockState.java:343) ~[paper-1.20.4.jar:git-Paper-462]
        at com.kiocg.TEST.TEST.onEnable(TEST.java:22) ~[KioCG-TEST.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-462]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-462]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-462]
```

### Steps/models to reproduce

```
    @Override
    public void onEnable() {
        Material.DIAMOND_ORE.createBlockData().createBlockState().getDrops();
    }
```

### Plugin and Datapack List

no other plugins

### Paper version

[19:24:47 INFO]: Checking version, please wait...
[19:24:48 INFO]: This server is running Paper version git-Paper-462 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 00fd87a)
You are running the latest version

**Comment by electronicboy** [comment]
This is 100% expected with the way spigot designed this, there is no real way to fix this directly as-is which isn't somewhat stupid
