### ISSUE TITLE
Error sending packet clientbound/minecraft:disconnect

### ISSUE THREAD

**Issue by Tencryn** [PaperSpigot/Paper#10662]
### Stack trace

```
[20:51:10 ERROR]: Error sending packet clientbound/minecraft:disconnect (skippable? false)
io.netty.handler.codec.EncoderException: Sending unknown packet 'clientbound/minecraft:disconnect'
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:46) ~[paper-1.20.6.jar:git-Paper-38]
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[paper-1.20.6.jar:git-Paper-38]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[paper-1.20.6.jar:git-Paper-38]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[paper-1.20.6.jar:git-Paper-38]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:748) ~[paper-1.20.6.jar:git-Paper-38]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:503) ~[paper-1.20.6.jar:git-Paper-38]
        at net.minecraft.network.Connection.sendPacket(Connection.java:485) ~[paper-1.20.6.jar:git-Paper-38]
        at net.minecraft.network.Connection.send(Connection.java:447) ~[paper-1.20.6.jar:git-Paper-38]
        at net.minecraft.network.Connection.send(Connection.java:433) ~[paper-1.20.6.jar:git-Paper-38]
        at net.minecraft.network.Connection.exceptionCaught(Connection.java:219) ~[paper-1.20.6.jar:git-Paper-38]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.exceptionCaught(FlushConsolidationHandler.java:159) ~[netty-handler-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Plugin and Datapack List

Bukkit Plugins:
- CMI, CMILib, LuckPerms, Vault, WorldEdit

There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

### Paper version

git-Paper-38 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 5632210)

### Other

Not sure on what may have caused it. This one specifically occurred minutes after server startup, but I've had one that happened around 28 minutes after. My assumption is a bot joined and disconnected, but never encountered an error like this before. Due to the nature of the error, it's difficult to replicate so was unable to see if the error still occurs on Build 39 but as that build doesn't appear to contain packet changes, I would _assume_ this error would still occur.

**Comment by alexfry756** [comment]
With my plugins: Citizens, CMI, CMILib, DeluxeMenus, FastAsyncWorldEdit, PL-Hide, PlaceholderAPI, WorldGuard

Shows the same thing

**Comment by yannicklamprecht** [comment]
Stumbled on that as well. I experienced it without plugins, using runDev via IDE. My client pinged the server fairly early using the mulitplayer serverlist actively spamming the refresh.

**Comment by electronicboy** [comment]
Pretty sure that this is purely due to a race condition in the vanilla server init logic, the connection exists before the packets are actually registered or something

**Comment by alexfry756** [comment]
Let's hope that it will be fixed soon :)

**Comment by yannicklamprecht** [comment]
> Let's hope that it will be fixed soon :)

It's nothing that harms the server. So no real issues, just a cosmetic problem in the log.

**Comment by Tencryn** [comment]
> Stumbled on that as well. I experienced it without plugins, using runDev via IDE. Server was in startup and my client pinged the server fairly early using the mulitplayer serverlist actively spamming the refresh.

I can replicate that, so it may be the same issue however it's not exclusive to server start up as I've had it occur long after. I cannot replicate it after startup, but I am locally hosting so that's probably why.

**Comment by alexfry756** [comment]
please, add to this issuse status tags - type: bug, and version: 1.20.6

**Comment by alexfry756** [comment]
the author of the paper core.. Please read this and fix it, this error is clogging up the console very much(

**Comment by electronicboy** [comment]
well, another report of this somewhat suggest that maybe it's not a race and something is trying to send a disconnection in the wrong protocol phase

**Comment by kennytv** [comment]
Yes, this can happen without any plugins or config changes

**Comment by Luftwaffle46** [comment]
It is a bit annoying though, is there a workaround to get rid of it? Or do we just wait for a patch?

**Comment by CodeByCam** [comment]
> It is a bit annoying though, is there a workaround to get rid of it? Or do we just wait for a patch?

You could use a plugin like [LogFilter](https://hangar.papermc.io/4drian3d/LogFilter) to just hide the message for the time being.

**Comment by alexfry756** [comment]
but will this mistake really remain and we will have to hide it through workarounds? This mistake never happened, and now it will forever remind you of itself as a flawed flaw.

**Comment by CodeByCam** [comment]
> but will this mistake really remain and we will have to hide it through workarounds? This mistake never happened, and now it will forever remind you of itself as a flawed flaw.

It will eventually be fixed, but it is a low priority as it is harmless (PRs welcome)!

@Luftwaffle46 please don't make nasty comments to other users.

**Comment by andrewkm** [comment]
I too am experiencing this during my initial 1.20.6 test runs.
Appreciate it being marked as accepted, thank you! :)

**Comment by electronicboy** [comment]
https://bugs.mojang.com/browse/MC-271325

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/commit/8e6554a80a1efefa48adb1f7733554e528fb45f5

**Comment by andrewkm** [comment]
Confirmed fixed. :)

**Comment by ledlamp** [comment]
vanilla still have it :(
