### ISSUE TITLE
Cant use .setItem(x, x) in normal Inventories 

### ISSUE THREAD

**Issue by LouisDerEchte** [PaperSpigot/Paper#10678]
### Expected behavior

I expect to see a inv with my contents. However I get kicked every time I try to open it. 

### Observed/Actual behavior

Player got kicked from server

### Steps/models to reproduce

inventory.setItem(x, ItemStack);

### Plugin and Datapack List

only my own plugin and Spark

### Paper version

1.20.6

### Other

[10:45:10 ERROR]: Error sending packet clientbound/minecraft:container_set_content (skippable? false)
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_content'
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[paper-1.20.6.jar:git-Paper-53]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:749) ~[paper-1.20.6.jar:git-Paper-53]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:504) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:489) ~[paper-1.20.6.jar:git-Paper-53]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: io.netty.handler.codec.EncoderException: String too big (was 36 characters, max 16)
        at net.minecraft.network.Utf8String.write(Utf8String.java:35) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.ByteBufCodecs$12.encode(ByteBufCodecs.java:271) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.ByteBufCodecs$12.encode(ByteBufCodecs.java:263) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.ByteBufCodecs$18.encode(ByteBufCodecs.java:363) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.ByteBufCodecs$18.encode(ByteBufCodecs.java:353) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.StreamCodec$9.encode(StreamCodec.java:166) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.core.component.DataComponentPatch$1.encodeComponent(DataComponentPatch.java:146) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:127) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.core.component.DataComponentPatch$1.encode(DataComponentPatch.java:66) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:193) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.world.item.ItemStack$1.encode(ItemStack.java:157) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:413) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket.write(ClientboundContainerSetContentPacket.java:57) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[paper-1.20.6.jar:git-Paper-53]
        ... 32 more
[10:45:10 INFO]: Looligeslol lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:container_set_content'

**Comment by kennytv** [comment]
Closing as this is most likely a plugin issue, but here's also a PR to add validation in the API https://github.com/PaperMC/Paper/pull/10680
