### ISSUE TITLE
[ERROR] Error sending packet clientbound/minecraft:update_recipes (skippable? false)

### ISSUE THREAD

**Issue by mei1012** [PaperSpigot/Paper#10706]
### Expected behavior

1. Connect to server
2. Works

### Observed/Actual behavior

1. Connect to server
2. Kicked

### Steps/models to reproduce

1. Use Paper 
2. Connect to server
3. Kicked

### Plugin and Datapack List

12.05 16:56:34 [Server] [INFO] Server Plugins (41):
12.05 16:56:34 [Server] [INFO] Paper Plugins:
12.05 16:56:34 [Server] [INFO] - EconomyShopGUI
12.05 16:56:34 [Server] [INFO] Bukkit Plugins:
12.05 16:56:34 [Server] [INFO] - AntiCombatLog, AntiVoidTPStyle, AuctionHouse, AxKills, Citizens, CombatWeaponryPlus, CraftEnhance, CrisTreeCapitator, *CustomNukes, DeathChest
12.05 16:56:34 [Server] [INFO] DiscordSRV, Essentials, EssentialsChat, *FarmProtect, floodgate, Geyser-Spigot, GeyserHacks, InventoryRollbackPlus, LibsDisguises, LuckPerms
12.05 16:56:34 [Server] [INFO] Maintenance, MeltItems, motdgg, NoteBlockAPI, ore-control, PlaceholderAPI, PlayerEconomy, PlayerWarps, ProtocolLib, QualityArmory
12.05 16:56:34 [Server] [INFO] Simple-Drugs, *SimpleSit, SimpleTpa, Skript, Themis, ViaBackwards, ViaRewind, ViaVersion, WildRTP, WorldEdit

### Paper version

12.05 16:55:17 [Server] [INFO] Checking version, please wait...
12.05 16:55:18 [Server] [INFO] This server is running Paper version git-Paper-"812ccb9" (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 812ccb9)
12.05 16:55:18 [Server] [INFO] You are 52 version(s) behind
12.05 16:55:18 [Server] [INFO] Download the new version at: https://papermc.io/downloads/paper
12.05 16:55:18 [Server] [INFO] Previous version: git-Purpur-2199 (MC: 1.20.6)

### Other
```
12.05 16:55:06 [PebbleHost] MEI1012 ran command Message of the Day
12.05 16:55:07 [Server] [ERROR] Error sending packet clientbound/minecraft:update_recipes (skippable? false)
12.05 16:55:07 [Server] [INFO] io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:update_recipes'
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:20) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.Connection$2.write(Connection.java:748) ~[?:?]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.Connection.doSendPacket(Connection.java:503) ~[?:?]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:488) ~[?:?]
12.05 16:55:07 [Server] [INFO] at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
12.05 16:55:07 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
12.05 16:55:07 [Server] [INFO] Caused by: io.netty.handler.codec.EncoderException: Empty ItemStack not allowed
12.05 16:55:07 [Server] [INFO] at net.minecraft.world.item.ItemStack$2.encode(ItemStack.java:214) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.world.item.ItemStack$2.encode(ItemStack.java:201) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.world.item.crafting.SmithingTransformRecipe$Serializer.toNetwork(SmithingTransformRecipe.java:137) ~[?:?]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.StreamCodec$1.encode(StreamCodec.java:24) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.StreamCodec$6.encode(StreamCodec.java:107) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.StreamCodec$8.encode(StreamCodec.java:141) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:413) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.ByteBufCodecs$19.encode(ByteBufCodecs.java:395) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.StreamCodec$7.encode(StreamCodec.java:122) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:88) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:78) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] ... 32 more
12.05 16:55:07 [Disconnect] User MEI1012 has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:update_recipes'
```

**Comment by electronicboy** [comment]
```
12.05 16:55:07 [Server] [INFO] Caused by: io.netty.handler.codec.EncoderException: Empty ItemStack not allowed
12.05 16:55:07 [Server] [INFO] at net.minecraft.world.item.ItemStack$2.encode(ItemStack.java:214) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.world.item.ItemStack$2.encode(ItemStack.java:201) ~[paper-1.20.6.jar:git-Paper-"812ccb9"]
12.05 16:55:07 [Server] [INFO] at net.minecraft.world.item.crafting.SmithingTransformRecipe$Serializer.toNetwork(SmithingTransformRecipe.java:137) ~[?:?]
```

Something on your server created an invalid recipe, that is also a relatively really old version of paper

**Comment by Machine-Maker** [comment]
If you download build 71 for 1.20.6, you should get a better idea of what plugin is adding an illegal recipe.

**Comment by mei1012** [comment]
I used trial and error to figure out what it was. Just a bad plugin
