### ISSUE TITLE
Can't iterate over Recipes on the server

### ISSUE THREAD

**Issue by deadbeef-enc0de** [PaperSpigot/Paper#10715]
### Expected behavior

The ability to use `Server.recipeIterator()` to iterate over the recipes the server has

### Observed/Actual behavior

```
[08:30:31 WARN]: [PaperTest] Task #2 for PaperTest v0.0.1 generated an exception
java.lang.IllegalArgumentException: Recipe cannot have an empty result.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.inventory.SmithingRecipe.<init>(SmithingRecipe.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.SmithingTrimRecipe.<init>(SmithingTrimRecipe.java:37) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.inventory.CraftSmithingTrimRecipe.<init>(CraftSmithingTrimRecipe.java:17) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.world.item.crafting.SmithingTrimRecipe.toBukkitRecipe(SmithingTrimRecipe.java:119) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolder.java:15) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.craftbukkit.inventory.RecipeIterator.next(RecipeIterator.java:24) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.craftbukkit.inventory.RecipeIterator.next(RecipeIterator.java:10) ~[paper-1.20.6.jar:git-Paper-72]
	at PaperTest-0.0.1.jar/net.mctitan.test.PaperTest$1.run(PaperTest.java:16) ~[PaperTest-0.0.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:git-Paper-72]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1705) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1577) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1237) ~[paper-1.20.6.jar:git-Paper-72]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-72]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Steps/models to reproduce

The following plugin causes this to happen.

```
package net.mctitan.test;

import org.bukkit.inventory.Recipe;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.Iterator;

public class PaperTest extends JavaPlugin {
    @Override
    public void onEnable() {
        Iterator<Recipe> recipes = getServer().recipeIterator();
        while (recipes.hasNext()) {
            Recipe recipe = recipes.next();
        }
    }
}
```

### Plugin and Datapack List

Just the above plugin

### Paper version

[08:31:44 INFO]: Checking version, please wait...
[08:31:44 INFO]: This server is running Paper version git-Paper-72 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 0688f21)
You are running the latest version

### Other

This started with Paper-71 and does not happen with Paper-70

You can put iterator code into a runnable and run later (I tested 1 tick later and 100 ticks later) and it still fails

The server tested has the default generated files (server.properties, bukkit.yml, etc)

**Comment by lynxplay** [comment]
Replicable, SmithingTrimRecipe invokes its parent constructor with AIR as trim recipes don't have a specific result item stack.
