### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by XiaoYu5530s** [PaperSpigot/Paper#10738]
### Stack trace

[15:36:39 ERROR]: Packet encoding of packet ID 85 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:631) ~[fastutil-8.5.9.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$FastEntryIterator.next(Object2ObjectOpenHashMap.java:746) ~[fastutil-8.5.9.jar:?]
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$FastEntryIterator.next(Object2ObjectOpenHashMap.java:741) ~[fastutil-8.5.9.jar:?]
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:472) ~[?:?]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:740) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:728) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.network.FriendlyByteBuf.writeItem(FriendlyByteBuf.java:703) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEquipmentPacket.write(ClientboundSetEquipmentPacket.java:47) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.lumine.mythic.lib.util.network.LightInjector$PacketHandler.write(LightInjector.java:523) ~[MythicLib-dist-1.6.2-20240221.182953-33.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115) ~[TAB v4.1.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at com.ticxo.modelengine.v1_19_R3.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:111) ~[Model-Engine-R4.0.5-dev-all.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.lumine.mythic.core.volatilecode.v1_19_R3.packets.VolatileChannelHandler.write(VolatileChannelHandler.java:80) ~[MythicMobs-5.6.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at kr.toxicity.hud.nms.v1_19_R3.NMSImpl$PlayerBossBar.write(NMSImpl.kt:432) ~[BetterHud-beta-23.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:469) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:443) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin and Datapack List

Bukkit Plugins: (80):
- AdvancedRegionMarket, AquaticCrates, *AreaShow, BattlePass, BeautyQuests, BeautyQuestsAddon, BetterHud, BetterHudMMOCore, BigDoors, BossShopPro
 Citizens, CMI, *CMIEInjector, CMILib, Codex, Cupido, DamageIndicatorHider, Dantiao, DeluxeMenus, Denizen
*Disposal, dtlTradersPlus, EasyBackup, EasyBackupCore, EasyKeyBinder, FarmProtect, Fashion, FastAsyncWorldEdit, FlipCard, GPS
 Guaranteed, HolographicDisplays, HungerIsStamina, Images, Interactions, InteractiveChat, ItemRarityGlow, ItemsAdder, LiteSignIn, LoneLibs
LotteryItem, LuckPerms, *MailBox, MCPets, *Minerals, *MmBossScore, MMOCore, MMOItems, MobRespawnTimeAPI, ModelEngine
MoneyFromMobs, MoreBagPro, Multiverse-Core, Multiverse-Inventories, *MySpawn, MythicDungeons, MythicLib, MythicMobs, NBTAPI, *NoDrop
NoNetherPortal, *NoSwapping, Parties, PlaceholderAPI, PlayerGuild, PlayerKits, PlayerPoints, PlayerTitle, ProtocolLib, RandomShop
RPGInventory, RPGMarketPlace, SetJoinQuit, spark, TAB, TradeMe, UltraBar, Vault, WorldGuard, YukiNoaAPI

----------------------------------------------------------------------------------------------------------------------------------------------
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Actions to reproduce (if known)

![image](https://github.com/PaperMC/Paper/assets/165585708/b2290d4c-ae67-46ce-9c8c-be2868ec2d8b)

### Paper version

Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Paper-550 (MC: 1.19.4)
* You are running the latest version

**Comment by XiaoYu5530s** [comment]
> 你既不是運行文件，也不是支援的版本。
> 
> 從表面上看，這可能是由插件修改線程狀態引起的，但不能保證。
> 
> 將其關閉為不支援。

I don't know what is causing this, so how do I solve this problem and where do I start?

**Comment by lynxplay** [comment]
See https://docs.papermc.io/paper/basic-troubleshooting#find-the-culprit on how to isolate a plugin that might cause this.

Again, you are not running a supported version, you are on your own to fix this.

**Comment by XiaoYu5530s** [comment]
> 請參閱https://docs.papermc.io/paper/basic-troubleshooting#find-the-culprit了解如何隔離可能導致此問題的插件。
> 
> 同樣，您運行的不是受支援的版本，您需要自行修復此問題。

Does the unsupported version refer to "plug-in", "paper" or "purpur"?

**Comment by XiaoYu5530s** [comment]
> A) purpur B) 1.19.4（僅支援 1.20.4 和 1.20.6） C) 插件問題

But my problem is "When multiplayer players attack monsters at fixed points, players will randomly disconnect." Others won't.

**Comment by electronicboy** [comment]
The issue tracker is for reporting bugs, not for seeing support. Your issue is 1) Likely down to plugins messing with internals 2) on an unsupported version of Minecraft 3) On software that isn't even ours.
