### ISSUE TITLE
Minecraft aliases object (items / command) is not detected

### ISSUE THREAD

**Issue by Shiratsui** [PaperSpigot/Paper#10752]
### Expected behavior

No error on items and commands with `minecraft` tag
Example: `minecraft:spruce_log` / `minecraft:tp`

### Observed/Actual behavior

Error, this when using `minecraft:` tagged item, error example is `minecraft:spruce_log`
For this error, I assume it's a minor error, because I still get the item
```2024-05-20 21:51:41 mc-shockbyte  | [14:51:41 ERROR]: [CraftMagicNumbers] Exception modifying ItemStack
2024-05-20 21:51:41 mc-shockbyte  | java.lang.Throwable: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]
2024-05-20 21:51:41 mc-shockbyte  |     at org.bukkit.craftbukkit.util.CraftMagicNumbers.modifyItemStack(CraftMagicNumbers.java:306) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.MetaItemStack.canSpawn(MetaItemStack.java:134) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
2024-05-20 21:51:41 mc-shockbyte  |     at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.commands.Commandgive.run(Commandgive.java:55) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
2024-05-20 21:51:41 mc-shockbyte  |     at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:175) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
2024-05-20 21:51:41 mc-shockbyte  |     at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:170) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
2024-05-20 21:51:41 mc-shockbyte  |     at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:871) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
2024-05-20 21:51:41 mc-shockbyte  |     at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onCommand(Essentials.java:770) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
2024-05-20 21:51:41 mc-shockbyte  |     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
2024-05-20 21:51:41 mc-shockbyte  |     at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.Commands.performCommand(Commands.java:349) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1514) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1414) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1380) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-85-7d2e5c3]
2024-05-20 21:51:41 mc-shockbyte  |     at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
2024-05-20 21:51:41 mc-shockbyte  | Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]
```

But when it's about minecraft command, example I use is `minecraft:tp` it's not working
`[14:53:56] Incorrect argument for command ...ecraft:tp @p 221 66 16<--[HERE]`

I assume both of them are related

### Steps/models to reproduce

Giving minecraft tagged items or Executing minecraft tagged commands

### Plugin and Datapack List

Plugins:  CoreProtect, EntityClear, Essentials, EssentialsChat, EssentialsSpawn, FarmProtection, GSit, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, PlaceholderAPI, ProtocolLib, ServerBackup, SkinsRestorer, TAB, Vault

Datapacks: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

### Paper version

1.20.6-84-591521e (MC: 1.20.6)

**Comment by electronicboy** [comment]
your give command is upset because it's being hijacked by essentials
