### ISSUE TITLE
Server Crash on Start with old paper 1.12.2 configs

### ISSUE THREAD

**Issue by FemBoysAreCut3** [PaperSpigot/Paper#10909]
### Stack trace

```
[21:20:46] [Paper Plugin Remapper Thread - 1/INFO]: [ReobfServer] Remapping server...
[21:20:57] [Paper Plugin Remapper Thread - 1/INFO]: [ReobfServer] Done remapping server in 11812ms.
[21:20:58] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[21:20:58] [Yggdrasil Key Fetcher/ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/publickeys due to api.minecraftservices.com
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.54.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.54.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:114) ~[authlib-6.0.54.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo$1.run(YggdrasilServicesKeyInfo.java:89) ~[authlib-6.0.54.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.net.UnknownHostException: api.minecraftservices.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.base/java.net.Socket.connect(Socket.java:751) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1282) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123) ~[?:?]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675) ~[?:?]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531) ~[?:?]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307) ~[?:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.54.jar:?]
	... 9 more
[21:21:02] [ServerMain/INFO]: Loaded 1290 recipes
[21:21:02] [ServerMain/INFO]: Loaded 0 advancements
[21:21:08] [Server thread/INFO]: Starting minecraft server version 1.21
[21:21:08] [Server thread/INFO]: Loading properties
[21:21:09] [Server thread/INFO]: This server is running Paper version 1.21-4-master@090775e (2024-06-18T13:42:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
[21:21:10] [Server thread/INFO]: Using 4 threads for Netty based IO
[21:21:10] [Server thread/INFO]: Server Ping Player Sample Count: 12
[21:21:11] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[21:21:11] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and population gen parallelism of 2 threads
[21:21:11] [Server thread/ERROR]: Encountered an unexpected exception
org.spongepowered.configurate.serialize.SerializationException: [anticheat, anti-xray, hidden-blocks, 9] of type java.util.List<net.minecraft.world.level.block.Block>: Missing value in Registry[ResourceKey[minecraft:root / minecraft:block] (Stable)] with key minecraft:lit_redstone_ore
	at io.papermc.paper.configuration.serializer.registry.RegistryValueSerializer.convertFromResourceKey(RegistryValueSerializer.java:26) ~[paper-1.21.jar:1.21-4-090775e]
	at io.papermc.paper.configuration.serializer.registry.RegistryEntrySerializer.deserialize(RegistryEntrySerializer.java:42) ~[paper-1.21.jar:1.21-4-090775e]
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:156) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:121) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:61) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:76) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:56) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:230) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.serialize.TypeSerializer.deserialize(TypeSerializer.java:96) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:76) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:56) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:230) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.serialize.TypeSerializer.deserialize(TypeSerializer.java:96) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:76) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:56) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:230) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.get0(AbstractConfigurationNode.java:203) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:161) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:521) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:408) ~[configurate-core-4.2.0-SNAPSHOT.jar:?]
	at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:178) ~[paper-1.21.jar:1.21-4-090775e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:227) ~[paper-1.21.jar:1.21-4-090775e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-4-090775e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-4-090775e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:21:11] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Rena\Desktop\Citybuild\crash-reports\crash-2024-06-18_21.21.11-server.txt
[21:21:11] [Server thread/INFO]: Stopping server
[21:21:11] [Server thread/INFO]: Saving players
[21:21:11] [Server thread/INFO]: Saving worlds
[21:21:11] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

```

### Plugin and Datapack List

none

### Actions to reproduce (if known)

started server?

### Paper version

i cannot enter a command if the server doesnt start but it is the latest build (experimental) (build 4)

**Comment by electronicboy** [comment]
You will need to manually update the configuration file to account for the different blocks or regenerate the config, there is no logic for automatically dealing with that and given the lack of a Minecraft data version, will likely never happen

**Comment by CodeByCam** [comment]
To add to what electronicboy said, just backup your config files, regenerate them (they'll now be in `config/` in your root server directory). Then just adjust them using your backup as a reference. You can use [the wiki](https://docs.papermc.io/paper/reference/configuration) as a very helpful reference too.
