### ISSUE TITLE
PluginRemapper breaks Dynmap and Dynmap-Essentials after Paper update

### ISSUE THREAD

**Issue by McJones9631** [PaperSpigot/Paper#11001]
### Expected behavior

When using build 138, all plugins loaded properly. 

### Observed/Actual behavior

When using build 147, I receive PluginRemapper errors, specifically on Dynmap and Dynmap-Essentials.

### Steps/models to reproduce

- Download Paper build 147 from site
- Rename file to `server.jar`
- Replace original `server.jar` within server folder
- Run `start.sh` as a program.

### Plugin and Datapack List

- Chunky
- Dynmap
- Dynmap-Essentials
- Dynmap-WorldGuard
- Essentials
- EssentialsChat
- EssentialsDiscord
- EssentialsDiscordLink
- Geyser-Spigot
- LuckPerms
- Maintenance
- ProtocolLib
- spark
- Vault
- ViaBackwards
- ViaRewind
- ViaVersion
- WorldEdit
- WorldGuard

### Paper version

This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-137-bd5867a (MC: 1.20.6)

### Other

`== Log ==
[13:12:26] [Paper Plugin Remapper Thread - 2/INFO]: [PluginRemapper] Remapping plugin 'plugins/Dynmap-3.7-beta-6-fabric-1.21.jar'...
[13:12:26] [Paper Plugin Remapper Thread - 1/INFO]: [PluginRemapper] Remapping plugin 'plugins/geyser-fabric-2.4.0-SNAPSHOT+build.585.jar'...
[13:12:26] [Paper Plugin Remapper Thread - 0/INFO]: [PluginRemapper] Remapping plugin 'plugins/worldedit-bukkit-7.3.4-beta-01.jar'...
[13:12:27] [Paper Plugin Remapper Thread - 0/INFO]: [PluginRemapper] Done remapping plugin 'plugins/worldedit-bukkit-7.3.4-beta-01.jar' in 1291ms.
[13:12:27] [Paper Plugin Remapper Thread - 1/INFO]: [PluginRemapper] Done remapping plugin 'plugins/geyser-fabric-2.4.0-SNAPSHOT+build.585.jar' in 1547ms.
[13:12:27] [Paper Plugin Remapper Thread - 2/INFO]: [PluginRemapper] Done remapping plugin 'plugins/Dynmap-3.7-beta-6-fabric-1.21.jar' in 1703ms.
[13:12:28] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/Dynmap-3.7-beta-6-fabric-1.21.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/Dynmap-3.7-beta-6-fabric-1.21.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:81) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/Dynmap-3.7-beta-6-fabric-1.21.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	... 9 more
[13:12:28] [ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/geyser-fabric-2.4.0-SNAPSHOT+build.585.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/geyser-fabric-2.4.0-SNAPSHOT+build.585.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:81) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/geyser-fabric-2.4.0-SNAPSHOT+build.585.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	... 9 more
[13:12:30] [ServerMain/WARN]: resource-pack-id missing, using default of b0150b94-1a4c-3af4-ada1-fd7eb4bc7105
[13:12:30] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:12:31] [ServerMain/INFO]: Loaded 1175 recipes
[13:12:31] [ServerMain/INFO]: Loaded 1276 advancements
[13:12:31] [Server thread/INFO]: Starting minecraft server version 1.20.6
[13:12:31] [Server thread/INFO]: Loading properties
[13:12:31] [Server thread/INFO]: This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[13:12:32] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:12:32] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:12:32] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[13:12:32] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[13:12:32] [Server thread/INFO]: Default game type: SURVIVAL
[13:12:32] [Server thread/INFO]: Generating keypair
[13:12:32] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:12:32] [Server thread/INFO]: Using epoll channel type
[13:12:32] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[13:12:32] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[13:12:32] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/.paper-remapped/Dynmap-Essentials-0.91.jar' in 'plugins/.paper-remapped'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [dynmap]. Please download and install these plugins to run 'Dynmap-Essentials'.
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:532) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:12:32] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/.paper-remapped/Dynmap-WorldGuard-1.2.jar' in 'plugins/.paper-remapped'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [dynmap]. Please download and install these plugins to run 'Dynmap-WorldGuard'.
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:532) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:12:33] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v5.0.2-SNAPSHOT
[13:12:33] [Server thread/INFO]: [ViaVersion] ViaVersion 5.0.2-SNAPSHOT is now loaded. Registering protocol transformers and injecting...`

**Comment by Warriorrrr** [comment]
> Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/Dynmap-3.7-beta-6-fabric-1.21.jar' does not contain a paper-plugin.yml or plugin.yml!

You downloaded the fabric version of dynmap which is why it's unable to enable, dynmap essentials is failing to load because it depends on dynmap which isn't present.

**Comment by McJones9631** [comment]
> > Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/Dynmap-3.7-beta-6-fabric-1.21.jar' does not contain a paper-plugin.yml or plugin.yml!
> 
> You downloaded the fabric version of dynmap (same with geyser) which is why it's unable to enable, dynmap essentials is failing to load because it depends on dynmap which isn't present.

Well I guess that's what I get for trying to script a fast install process. Thank you for this information!
