### ISSUE TITLE
parse custom name

### ISSUE THREAD

**Issue by seema84** [PaperSpigot/Paper#11021]
### Expected behavior

I'm not sure if it's a paper bug, but it seems to be a server internal.

### Server Log

<details>
  <summary>Log</summary>

```
[Server thread/WARN]: Failed to parse custom name from string 'Player's Kiste', discarding
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 13 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.1.jar:?]
	at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:304) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.BlockEntity.parseCustomNameSafe(BlockEntity.java:365) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.BaseContainerBlockEntity.loadAdditional(BaseContainerBlockEntity.java:42) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.ShulkerBoxBlockEntity.loadAdditional(ShulkerBoxBlockEntity.java:242) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.BlockEntity.loadWithComponents(BlockEntity.java:94) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.BlockEntity.lambda$loadStatic$5(BlockEntity.java:205) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.loadStatic(BlockEntity.java:203) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:291) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:276) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:266) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:411) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.inventory.CraftMetaBlockState.<init>(CraftMetaBlockState.java:240) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.bukkit.craftbukkit.inventory.SerializableMeta.deserialize(SerializableMeta.java:75) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:49) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:201) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:185) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:473) ~[snakeyaml-2.2.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Metadata.ItemDatabase.lambda$updateMetadataVersion$0(ItemDatabase.java:103) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Libs.ORMlite.stmt.StatementExecutor.doCallBatchTasks(StatementExecutor.java:652) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Libs.ORMlite.stmt.StatementExecutor.doCallBatchTasks(StatementExecutor.java:623) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Libs.ORMlite.stmt.StatementExecutor.callBatchTasks(StatementExecutor.java:603) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Libs.ORMlite.dao.BaseDaoImpl.callBatchTasks(BaseDaoImpl.java:734) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Metadata.ItemDatabase.updateMetadataVersion(ItemDatabase.java:94) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Metadata.ItemDatabase.handleMetadataUpdate(ItemDatabase.java:58) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Metadata.ItemDatabase.<init>(ItemDatabase.java:45) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:161) ~[ChestShop.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 13 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.1.jar:?]
	... 58 more
[21:09:40] [Server thread/ERROR]: Tried to load invalid item: 'Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: minecraft:wooden_slab'
[21:09:40] [Server thread/ERROR]: Tried to load invalid item: 'Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: minecraft:reeds'
[21:09:40] [Server thread/ERROR]: Tried to load invalid item: 'Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: minecraft:reeds'
[21:09:40] [Server thread/ERROR]: Tried to load invalid item: 'Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: minecraft:reeds'
[21:09:40] [Server thread/ERROR]: Tried to load invalid item: 'Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: minecraft:reeds'
[21:09:40] [Server thread/ERROR]: Tried to load invalid item: 'Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: minecraft:reeds'
[21:09:40] [Server thread/ERROR]: Tried to load invalid item: 'Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: minecraft:dye'
[21:09:40] [Server thread/ERROR]: Tried to load invalid item: 'Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: minecraft:log'
[21:09:40] [Server thread/WARN]: Failed to parse custom name from string 'Shulker Box', discarding
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.1.jar:?]
	at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:304) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.BlockEntity.parseCustomNameSafe(BlockEntity.java:365) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.BaseContainerBlockEntity.loadAdditional(BaseContainerBlockEntity.java:42) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.ShulkerBoxBlockEntity.loadAdditional(ShulkerBoxBlockEntity.java:242) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.BlockEntity.loadWithComponents(BlockEntity.java:94) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.world.level.block.entity.BlockEntity.lambda$loadStatic$5(BlockEntity.java:205) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.loadStatic(BlockEntity.java:203) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:291) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:276) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:266) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:411) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.inventory.CraftMetaBlockState.<init>(CraftMetaBlockState.java:240) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.bukkit.craftbukkit.inventory.SerializableMeta.deserialize(SerializableMeta.java:75) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:576) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:210) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:552) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:597) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:49) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:201) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:185) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:473) ~[snakeyaml-2.2.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Metadata.ItemDatabase.lambda$updateMetadataVersion$0(ItemDatabase.java:103) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Libs.ORMlite.stmt.StatementExecutor.doCallBatchTasks(StatementExecutor.java:652) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Libs.ORMlite.stmt.StatementExecutor.doCallBatchTasks(StatementExecutor.java:623) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Libs.ORMlite.stmt.StatementExecutor.callBatchTasks(StatementExecutor.java:603) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Libs.ORMlite.dao.BaseDaoImpl.callBatchTasks(BaseDaoImpl.java:734) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Metadata.ItemDatabase.updateMetadataVersion(ItemDatabase.java:94) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Metadata.ItemDatabase.handleMetadataUpdate(ItemDatabase.java:58) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.Metadata.ItemDatabase.<init>(ItemDatabase.java:45) ~[ChestShop.jar:?]
	at ChestShop.jar/com.Acrobot.ChestShop.ChestShop.onEnable(ChestShop.java:161) ~[ChestShop.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 10 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.1.jar:?]
	... 58 more
```
</details>

However, if I only replace the Items.db, the error does not seem to occur.

### Steps/models to reproduce

see chestshop issue

### Plugin and Datapack List

Chestshop build 419

### Paper version

Paper version 1.20.6-147-ver/1.20.6@e41d44f

### Other

The course so far  ->
https://github.com/ChestShop-authors/ChestShop-3/issues/600

**Comment by lynxplay** [comment]
The plugin loaded an skull item stack that contained malformed data.
What you got there was a warning including the stack trace.
That is not a bug, it is just invalid data attempted to be loaded by the plugin.

The warning is safe to ignore to the degree that it will not break your server, however the skull items loaded will loose their custom name.
This smells like a general case of a plugin using spigots broken af BukkitObjectOutputStream (or to that extend YamlConfiguration) to store ItemStacks and hence the items were not ran through data converter when loaded in a new version.
