### ISSUE TITLE
Using custom damage types with DamageSource#builder without direct entity and applying with Player#damage leads to NullPointerException

### ISSUE THREAD

**Issue by Chaosdave34** [PaperSpigot/Paper#11036]
### Expected behavior

Damage should be applied even without a direct entity.

### Observed/Actual behavior

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.distanceToSqr(net.minecraft.world.entity.Entity)" because "entity2" is null
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1537) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:1001) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1204) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at org.bukkit.craftbukkit.entity.CraftLivingEntity.damage(CraftLivingEntity.java:440) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at org.bukkit.craftbukkit.entity.CraftLivingEntity.damage(CraftLivingEntity.java:433) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at kitpvp-1.0.0-SNAPSHOT-all.jar/io.github.chaosdave34.kitpvp.listener.GameListener.onPlayerMoveElytra(GameListener.kt:382) ~[kitpvp-1.0.0-SNAPSHOT-all.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor66.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1517) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:75) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1541) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1518) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1511) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1470) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1477) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1322) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-server-userdev-1.21-R0.1-SNAPSHOT.jar:1.21-44-8d91b85]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
	```

### Steps/models to reproduce

1. Create Damage Types
```java
class DamageTypes {
    private var registry : Registry<NmsDamageType> = CraftRegistry.getMinecraftRegistry(Registries.DAMAGE_TYPE)

    companion object {
        lateinit var LAND: DamageType
        lateinit var ESCAPE: DamageType
        lateinit var BLACK_HOLE: DamageType
    }

    init {
        ReflectionUtils.unfreezeRegistry(registry)
        LAND = registerDamageType(NmsDamageType("land", DamageScaling.NEVER, 0f, DamageEffects.HURT))
        ESCAPE = registerDamageType(NmsDamageType("escape", DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER, 0f, DamageEffects.HURT))
        BLACK_HOLE = registerDamageType(NmsDamageType("black_hole", DamageScaling.NEVER, 0f, DamageEffects.HURT))
    }

    private fun registerDamageType(damageType: NmsDamageType): DamageType {
        registry.createIntrusiveHolder(damageType)
        Registry.register(registry, NamespacedKey.minecraft(damageType.msgId).asString(), damageType)

        return CraftDamageType.minecraftToBukkit(damageType)
    }
}
```

2. Apply damage to player without direct entity
```java
player.damage(maxDamage, DamageSource.builder(DamageTypes.LAND).build())
```

### Plugin and Datapack List

- Only my plugin
- No Datapacks

### Paper version

`This server is running Paper version 1.21-44-master@8d91b85 (2024-07-04T18:58:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)`

### Other

The exact same code does work in 1.20.5 and 1.20.6 and is broken in 1.21.

There seem to have been changes in LivingEntity#hurt from 1.20.5 to 1.21

**Snippets from LivingEntity#hurt**
- 1.20.5
```java

if (flag1) {
    if (flag) {
        this.level().broadcastEntityEvent(this, (byte) 29);
    } else {
        this.level().broadcastDamageEvent(this, source);
    }

    if (!source.is(DamageTypeTags.NO_IMPACT) && !flag) { // CraftBukkit - Prevent marking hurt if the damage is blocked
        this.markHurt();
    }

    if (entity1 != null && !source.is(DamageTypeTags.NO_KNOCKBACK)) {
        final boolean far = entity1.distanceToSqr(this) > (200.0 * 200.0); // Paper - Improve boat collision performance
        double d0 = far ? (Math.random() - Math.random()) : entity1.getX() - this.getX(); // Paper - Improve boat collision performance

        double d1;

        for (d1 = far ? Math.random() - Math.random() : entity1.getZ() - this.getZ(); d0 * d0 + d1 * d1 < 1.0E-4D; d1 = (Math.random() - Math.random()) * 0.01D) { // Paper - Improve boat collision performance
            d0 = (Math.random() - Math.random()) * 0.01D;
        }

        this.knockback(0.4000000059604645D, d0, d1, entity1, entity1 == null ? EntityKnockbackEvent.KnockbackCause.DAMAGE : EntityKnockbackEvent.KnockbackCause.ENTITY_ATTACK); // CraftBukkit
        if (!flag) {
            this.indicateDamage(d0, d1);
        }
    }
}
```

- 1.21
```java
if (flag1) {
    if (flag) {
        this.level().broadcastEntityEvent(this, (byte) 29);
    } else {
        this.level().broadcastDamageEvent(this, source);
    }
  
    if (!source.is(DamageTypeTags.NO_IMPACT) && !flag) { // CraftBukkit - Prevent marking hurt if the damage is blocked
        this.markHurt();
    }
  
    if (!source.is(DamageTypeTags.NO_KNOCKBACK)) {
        double d0 = 0.0D;
        double d1 = 0.0D;
        Entity entity2 = source.getDirectEntity();
        // Paper start - improve boat collision performance
        final boolean far = entity2.distanceToSqr(this) > (200.0D * 200.0D);
        if (far) {
            d0 = Math.random() - Math.random();
            d1 = Math.random() - Math.random();
        } else if (entity2 instanceof Projectile) {
            // Paper end - improve boat collision performance
            Projectile iprojectile = (Projectile) entity2;
            DoubleDoubleImmutablePair doubledoubleimmutablepair = iprojectile.calculateHorizontalHurtKnockbackDirection(this, source);
  
            d0 = -doubledoubleimmutablepair.leftDouble();
            d1 = -doubledoubleimmutablepair.rightDouble();
        } else if (source.getSourcePosition() != null) {
            d0 = source.getSourcePosition().x() - this.getX();
            d1 = source.getSourcePosition().z() - this.getZ();
        }
  
        this.knockback(0.4000000059604645D, d0, d1, entity1, entity1 == null ? io.papermc.paper.event.entity.EntityKnockbackEvent.Cause.DAMAGE : io.papermc.paper.event.entity.EntityKnockbackEvent.Cause.ENTITY_ATTACK); // CraftBukkit // Paper - knockback events
        if (!flag) {
            this.indicateDamage(d0, d1);
        }
    }
}
```

- 1.20.5
```java
final boolean far = entity1.distanceToSqr(this) > (200.0 * 200.0);
``` 

- 1.21
 ```java
final boolean far = entity2.distanceToSqr(this) > (200.0D * 200.0D);
```

- In both versions:
```java
Entity entity1 = source.getEntity();
```

- In 1.21:
```java
Entity entity2 = source.getDirectEntity();
```

**Comment by kennytv** [comment]
Thanks for the detailed report :)
