### ISSUE TITLE
When breaking in any way the End Crystal generated in the end towers automatically crashes

### ISSUE THREAD

**Issue by piodois** [PaperSpigot/Paper#11064]
### Stack trace

[04:13:51] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21-57-0e02aa5 (MC: 1.21) ---
[04:13:51] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[04:13:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:13:51] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[04:13:51] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:player, entity class: net.minecraft.server.level.ServerPlayer
[04:13:51] [Paper Watchdog Thread/ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[04:13:51] [Paper Watchdog Thread/ERROR]: Entity UUID: e7c91a5b-e9cd-37dd-87ad-66fcbbb7ad72
[04:13:51] [Paper Watchdog Thread/ERROR]: Position: world: 'world_the_end' at location (36.10833162332814, 101.74405402714046, 25.331300356583597)
[04:13:51] [Paper Watchdog Thread/ERROR]: Velocity: (0.0, 0.0, 0.0) (in blocks per tick)
[04:13:51] [Paper Watchdog Thread/ERROR]: Entity AABB: AABB[35.80833161140721, 101.74405402714046, 25.031300344662668] -> [36.40833163524907, 103.54405397945675, 25.631300368504526]
[04:13:51] [Paper Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 2661
[04:13:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:13:51] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[04:13:51] [Paper Watchdog Thread/ERROR]: 	PID: 38 | Suspended: false | Native: false | State: RUNNABLE
[04:13:51] [Paper Watchdog Thread/ERROR]: 	Stack:
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Explosion.explode(Explosion.java:508)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.explode(Level.java:1466)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1753)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.explode(Level.java:1428)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.entity.boss.enderdragon.EndCrystal.hurt(EndCrystal.java:135)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.entity.player.Player.attack(Player.java:1344)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2418)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2796)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2707)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PacketUtils$$Lambda/0x0000002003130c20.run(Unknown Source)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.TickTask.run(TickTask.java:18)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1622)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda/0x0000002001c52f98.run(Unknown Source)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
[04:13:51] [Paper Watchdog Thread/ERROR]: 		java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
[04:13:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:13:51] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[04:13:51] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:13:54] [Async Chat Thread - #0/INFO]: [Not Secure] ɴᴇᴡʙɪᴇ SoloKiuz: carajo
[04:13:56] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21-57-0e02aa5 (MC: 1.21) ---
[04:13:56] [Paper Watchdog Thread/ERROR]: The server has not responded for 15 seconds! Creating thread dump
[04:13:56] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:13:56] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[04:13:56] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:player, entity class: net.minecraft.server.level.ServerPlayer
[04:13:56] [Paper Watchdog Thread/ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[04:13:56] [Paper Watchdog Thread/ERROR]: Entity UUID: e7c91a5b-e9cd-37dd-87ad-66fcbbb7ad72
[04:13:56] [Paper Watchdog Thread/ERROR]: Position: world: 'world_the_end' at location (36.10833162332814, 101.74405402714046, 25.331300356583597)
[04:13:56] [Paper Watchdog Thread/ERROR]: Velocity: (0.0, 0.0, 0.0) (in blocks per tick)
[04:13:56] [Paper Watchdog Thread/ERROR]: Entity AABB: AABB[35.80833161140721, 101.74405402714046, 25.031300344662668] -> [36.40833163524907, 103.54405397945675, 25.631300368504526]
[04:13:56] [Paper Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 2661
[04:13:56] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:13:56] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[04:13:56] [Paper Watchdog Thread/ERROR]: 	PID: 38 | Suspended: false | Native: false | State: RUNNABLE
[04:13:56] [Paper Watchdog Thread/ERROR]: 	Stack:
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Explosion.explode(Explosion.java:508)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.explode(Level.java:1466)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1753)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.explode(Level.java:1428)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.entity.boss.enderdragon.EndCrystal.hurt(EndCrystal.java:135)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.entity.player.Player.attack(Player.java:1344)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2418)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2796)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2707)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PacketUtils$$Lambda/0x0000002003130c20.run(Unknown Source)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.TickTask.run(TickTask.java:18)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1622)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda/0x0000002001c52f98.run(Unknown Source)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
[04:13:56] [Paper Watchdog Thread/ERROR]: 		java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
[04:13:56] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:13:56] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[04:13:56] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:14:01] [spark-async-sampler-worker-thread/WARN]: [spark] Timed out waiting for world statistics
[04:14:01] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - 1.21-57-0e02aa5 (MC: 1.21) ---
[04:14:01] [Paper Watchdog Thread/ERROR]: The server has not responded for 20 seconds! Creating thread dump
[04:14:01] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:14:01] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[04:14:01] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:player, entity class: net.minecraft.server.level.ServerPlayer
[04:14:01] [Paper Watchdog Thread/ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[04:14:01] [Paper Watchdog Thread/ERROR]: Entity UUID: e7c91a5b-e9cd-37dd-87ad-66fcbbb7ad72
[04:14:01] [Paper Watchdog Thread/ERROR]: Position: world: 'world_the_end' at location (36.10833162332814, 101.74405402714046, 25.331300356583597)
[04:14:01] [Paper Watchdog Thread/ERROR]: Velocity: (0.0, 0.0, 0.0) (in blocks per tick)
[04:14:01] [Paper Watchdog Thread/ERROR]: Entity AABB: AABB[35.80833161140721, 101.74405402714046, 25.031300344662668] -> [36.40833163524907, 103.54405397945675, 25.631300368504526]
[04:14:01] [Paper Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 2661
[04:14:01] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:14:01] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[04:14:01] [Paper Watchdog Thread/ERROR]: 	PID: 38 | Suspended: false | Native: false | State: RUNNABLE
[04:14:01] [Paper Watchdog Thread/ERROR]: 	Stack:
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Explosion.explode(Explosion.java:508)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.explode(Level.java:1466)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1753)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.explode(Level.java:1428)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.entity.boss.enderdragon.EndCrystal.hurt(EndCrystal.java:135)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.entity.player.Player.attack(Player.java:1344)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2418)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl$3.onAttack(ServerGamePacketListenerImpl.java:2796)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:29)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2707)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.protocol.PacketUtils$$Lambda/0x0000002003130c20.run(Unknown Source)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.TickTask.run(TickTask.java:18)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1622)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda/0x0000002001c52f98.run(Unknown Source)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596)
[04:14:01] [Paper Watchdog Thread/ERROR]: 		java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)
[04:14:01] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:14:01] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[04:14:01] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:14:06] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:14:06] [Paper Watchdog Thread/ERROR]: The server has stopped responding! This is (probably) not a Paper bug.
[04:14:06] [Paper Watchdog Thread/ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author
[04:14:06] [Paper Watchdog Thread/ERROR]: 	 *Especially* if it looks like HTTP or MySQL operations are occurring
[04:14:06] [Paper Watchdog Thread/ERROR]: If you see a world save or edit, then it means you did far more than your server can handle at once
[04:14:06] [Paper Watchdog Thread/ERROR]: 	 If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
[04:14:06] [Paper Watchdog Thread/ERROR]: If you are unsure or still think this is a Paper bug, please report this to https://github.com/PaperMC/Paper/issues
[04:14:06] [Paper Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[04:14:06] [Paper Watchdog Thread/ERROR]: Paper version: 1.21-57-0e02aa5 (MC: 1.21)
[04:14:06] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:14:06] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[04:14:06] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:player, entity class: net.minecraft.server.level.ServerPlayer
[04:14:06] [Paper Watchdog Thread/ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[04:14:06] [Paper Watchdog Thread/ERROR]: Entity UUID: e7c91a5b-e9cd-37dd-87ad-66fcbbb7ad72
[04:14:06] [Paper Watchdog Thread/ERROR]: Position: world: 'world_the_end' at location (36.10833162332814, 101.74405402714046, 25.331300356583597)
[04:14:06] [Paper Watchdog Thread/ERROR]: Velocity: (0.0, 0.0, 0.0) (in blocks per tick)
[04:14:06] [Paper Watchdog Thread/ERROR]: Entity AABB: AABB[35.80833161140721, 101.74405402714046, 25.031300344662668] -> [36.40833163524907, 103.54405397945675, 25.631300368504526]
[04:14:06] [Paper Watchdog Thread/ERROR]: Total packets processed on the main thread for all players: 2661
[04:14:06] [Paper Watchdog Thread/ERROR]: ------------------------------
[04:14:06] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[04:14:06] [Paper Watchdog Thread/ERROR]: 	PID: 38 | Suspended: false | Native: false | State: RUNNABLE

### Plugin and Datapack List

![prueba](https://github.com/user-attachments/assets/0dea3f53-4552-4d4a-afd9-34f8342b9bca)

### Actions to reproduce (if known)

al llegar al end y romper los cristales del end generados en las torres crashea automaticamente

### Paper version

[04:14:19] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[04:14:21] [ServerMain/INFO]: Loaded 1290 recipes
[04:14:21] [ServerMain/INFO]: Loaded 1399 advancements
[04:14:22] [Server thread/INFO]: Starting minecraft server version 1.21
[04:14:22] [Server thread/INFO]: Loading properties
[04:14:22] [Server thread/INFO]: This server is running Paper version 1.21-57-master@0e02aa5 (2024-07-11T19:34:02Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
[04:14:23] [Server thread/INFO]: Server Ping Player Sample Count: 12
[04:14:23] [Server thread/INFO]: Using 4 threads for Netty based IO
[04:14:23] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and population gen parallelism of 1 threads
[04:14:24] [Server thread/INFO]: Default game type: SURVIVAL
[04:14:24] [Server thread/INFO]: Generating keypair
[04:14:24] [Server thread/INFO]: Starting Minecraft server on *:25565
[04:14:24] [Server thread/INFO]: Using epoll channel type

**Comment by piodois** [comment]
---- Minecraft Network Protocol Error Report ----
// It's the tubes, they're clogged!

Time: 2024-07-13 00:07:36
Description: Packet handling error

java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:254)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Client IO #19
Stacktrace:
	at wf.a(SourceFile:33)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: Paper
Stacktrace:
	at wf.a(SourceFile:33)
	at zj.a(SourceFile:62)
	at fzc.a(SourceFile:136)
	at fzc.a(SourceFile:127)
	at vt.exceptionCaught(SourceFile:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.2, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 235232936 bytes (224 MiB) / 1342177280 bytes (1280 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8188.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5599
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 46495.41
	Virtual memory used (MiB): 14899.30
	Swap memory total (MiB): 13824.00
	Swap memory used (MiB): 82.30
	Space in storage for jna.tmpdir (MiB): available: 197225.25, total: 976084.31
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 197225.25, total: 976084.31
	Space in storage for io.netty.native.workdir (MiB): available: 197225.25, total: 976084.31
	Space in storage for java.io.tmpdir (MiB): available: 197225.25, total: 976084.31
	Space in storage for workdir (MiB): available: 197225.25, total: 976084.31
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by CatBang** [comment]
duplicate? https://github.com/PaperMC/Paper/issues/11059

Your version may be outdated, please try the latest build version #62+.
