### ISSUE TITLE
Lake feature crashes server

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11084]
### Stack trace

If i make a dimension with custom features all of the features work except for lakes, for some reason they attempt to get biome during world gen (no other features do this) which causes server to crash: https://0bin.net/paste/GAqifVkm#KtLtjtDme8Jax0s4ld6TlCYsK7gX1WF3blXSScKNps4

It shouldn't be crashing when its trying to get the biome.

LavaFeature.java in paper code:

```java
if (blockState.getFluidState().is(FluidTags.WATER)) {
                for (int ab = 0; ab < 16; ab++) {
                    for (int ac = 0; ac < 16; ac++) {
                        int ad = 4;
                        BlockPos blockPos4 = blockPos.offset(ab, 4, ac);
                        if (worldGenLevel.getBiome(blockPos4).value().shouldFreeze(worldGenLevel, blockPos4, false) // here is where it blows up
                            && this.canReplaceBlock(worldGenLevel.getBlockState(blockPos4))) {
                            worldGenLevel.setBlock(blockPos4, Blocks.ICE.defaultBlockState(), 2);
                        }
                    }
                }
            }
```
            
```
            java.lang.IllegalStateException: Requested chunk unavailable during world generation
	at net.minecraft.server.level.WorldGenRegion.getChunk(WorldGenRegion.java:168)
	at net.minecraft.world.level.LevelReader.getNoiseBiome(LevelReader.java:73)
	at net.minecraft.world.level.biome.BiomeManager.getBiome(BiomeManager.java:64)
	at net.minecraft.world.level.LevelReader.getBiome(LevelReader.java:53)
	at net.minecraft.world.level.levelgen.feature.LakeFeature.place(LakeFeature.java:137)
```

### Plugin and Datapack List

I am adding the features via code, not a datapack, but im 99% sure it would be the same situation using a datapack
```
  Holder<ConfiguredFeature<LakeFeature.Configuration, ?>> hadradaLake = CustomFeatures.registerFeatureConfig(
                "hadrada_lake", Feature.LAKE, new LakeFeature.Configuration(BlockStateProvider.simple(WATER), BlockStateProvider.simple(STONE)));

        CustomFeatures.registerPlacedFeature("hadrada_lake", hadradaLake, RarityFilter.onAverageOnceEvery(3), InSquarePlacement.spread(), hadradaHeightRange);
```

### Paper version

This server is running Paper version 1.21-DEV-master@34a2917 (2024-07-14T13:04:22Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 6 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-63-2288e13 (MC: 1.21)

**Comment by jpenilla** [comment]
Original report is incomplete and reporter has deleted their account
