### ISSUE TITLE
Constructor `SimpleCommandMap(Server)` is available with Spigot 1.20.6 API, but can't be found in Paper 1.20.6

### ISSUE THREAD

**Issue by willkroboth** [PaperSpigot/Paper#11106]
### Expected behavior

On Spigot, my command works:

```basic
>version
[10:31:48] [Server thread/INFO]: This server is running CraftBukkit version 4195-Spigot-fcd94e2-f057cf4 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[10:31:48] [Server thread/INFO]: Checking version, please wait...
[10:31:49] [Thread-8/INFO]: You are 33 version(s) behind
>test command1
[10:31:54] [Server thread/INFO]: You ran the command1 subcommand with arguments []
>test command2
[10:31:58] [Server thread/INFO]: You ran the command2 subcommand with arguments []
>test command3
>test
>test command1 hello
[10:32:46] [Server thread/INFO]: You ran the command1 subcommand with arguments [hello]
>test command1 hello world
[10:32:49] [Server thread/INFO]: You ran the command1 subcommand with arguments [hello, world]
```

### Observed/Actual behavior

On Paper, when my plugin enables, this exception occurs:

```java
[10:36:14 INFO]: [BukkitTestPlugin] Enabling BukkitTestPlugin v1.0-SNAPSHOT
[10:36:14 ERROR]: Error occurred while enabling BukkitTestPlugin v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.command.SimpleCommandMap.<init>(org.bukkit.Server)'
        at BukkitTestPlugin-1.0-SNAPSHOT.jar/me.willkroboth.bukkittestplugin.BukkitTestPlugin.onEnable(BukkitTestPlugin.java:19) ~[BukkitTestPlugin-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[10:36:14 INFO]: [BukkitTestPlugin] Disabling BukkitTestPlugin v1.0-SNAPSHOT
```

### Steps/models to reproduce

I wrote a plugin like so with `org.spigotmc:spigot-api:1.20.6-R0.1-SNAPSHOT`

```java
public class BukkitTestPlugin extends JavaPlugin {
    private SimpleCommandMap subCommandMap;

    @Override
    public void onEnable() {
        getCommand("test").setExecutor(this::executeTestCommand);

        subCommandMap = new SimpleCommandMap(Bukkit.getServer());
        // Clear default commands
        subCommandMap.clearCommands();

        subCommandMap.registerAll("fallback", List.of(
                createCommand("command1"),
                createCommand("command2")
        ));
    }

    private boolean executeTestCommand(CommandSender sender, Command command, String s, String[] strings) {
        String subCommand = String.join(" ", strings);
        return subCommandMap.dispatch(sender, subCommand);
    }

    private Command createCommand(final String name) {
        return new Command(name) {
            @Override
            public boolean execute(CommandSender commandSender, String s, String[] strings) {
                commandSender.sendMessage("You ran the " + name + " subcommand with arguments " + Arrays.toString(strings));

                return true;
            }
        };
    }
}
```

On Spigot 1.20.6, the constructor `new SimpleCommandMap(Bukkit.getServer())` is available through their API (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/command/SimpleCommandMap.html#%3Cinit%3E(org.bukkit.Server)). On the latest 1.20.6 Paper, this method cannot be found.

### Plugin and Datapack List

```basic
> plugins
[10:39:39 INFO]: Server Plugins (1):
[10:39:39 INFO]: Bukkit Plugins:
[10:39:39 INFO]:  - BukkitTestPlugin
> datapack list
[10:39:50 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[10:39:50 INFO]: There are no more data packs available
```

### Paper version

```basic
> version
[10:40:13 INFO]: Checking version, please wait...
[10:40:14 INFO]: This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
```

**Comment by electronicboy** [comment]
That implementation class is not explictly considered API, and now solely exists as a wrapper API for the internal command system to maintain legacy compt.

**Comment by willkroboth** [comment]
If it's not intended to be Spigot API, then why is it in the `spigot-api` module? I would expect it to be placed in `spigot-server` like CraftCommandMap if it wasn't intended to be accessible. As shown in the example plugin, I think it is a useful part of the API, making it easy to implement sub-commands in a way that works on Spigot.

I believe Paper could still provide access to this part of Spigot API like so:

```java
public class SimpleCommandMap implements CommandMap {
    // Old constructor
    public SimpleCommandMap(Server server) {
        this(server, new HashMap<>());
    }

    // New constructor added by https://github.com/PaperMC/Paper/pull/8235
    // Paper start
    @org.jetbrains.annotations.ApiStatus.Internal
    public SimpleCommandMap(@NotNull final Server server, Map<String, Command> backing) {
        this.knownCommands = backing;
    // Paper end
        this.server = server;
        setDefaultCommands();
    }
}
```

I've heard that Paper is planning to hard fork from Spigot eventually, where API incompatibilities like this will be inevitable, but it doesn't seem too hard to keep this feature around while Paper is still otherwise compatible with Spigot plugins.

**Comment by powercasgamer** [comment]
Classing beginning with "Simple" are implementation classes, see the javadoc description
> Implementation classes. Concrete implementation classes packaged with Bukkit (eg those beginning with Simple) are not API. You should access them via their interfaces instead.

**Comment by electronicboy** [comment]
Bundling implementation inside of the api does not explicitly mean that it's intended for plugin devs to poke at it, this was not a use case we ever expected anybody to be doing.

This was explicitly a case of bukkit bundling their command system inside of the API to have a simple implementation of it existing around for implementers of the API to use.
