### ISSUE TITLE
Crafter crafting level 3 Rockets istantly crashes the server 

### ISSUE THREAD

**Issue by Toastbrot2811** [PaperSpigot/Paper#11116]
### Stack trace

---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-07-19 16:52:54
Description: Exception ticking world

java.lang.ClassCastException: class org.bukkit.craftbukkit.inventory.CraftComplexRecipe cannot be cast to class org.bukkit.inventory.CraftingRecipe (org.bukkit.craftbukkit.inventory.CraftComplexRecipe and org.bukkit.inventory.CraftingRecipe are in unnamed module of loader java.net.URLClassLoader @7857fe2)
	at net.minecraft.world.level.block.CrafterBlock.dispenseFrom(CrafterBlock.java:169)
	at net.minecraft.world.level.block.CrafterBlock.tick(CrafterBlock.java:94)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1221)
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1235)
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192)
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:716)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1594)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1301)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.block.CrafterBlock.dispenseFrom(CrafterBlock.java:169)
	at net.minecraft.world.level.block.CrafterBlock.tick(CrafterBlock.java:94)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1221)
	at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1235)
	at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192)
	at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89)

### Plugin and Datapack List

Essentials, LuckPerms, msMMOHorse, SilkSpawners, Vault, VeinMiner, WorldEdit

### Actions to reproduce (if known)

Use a Crafter to craft level 2 or level 3 fire work rockets. Level 1 Rockets wor just fine 

### Paper version

This server is running Paper version 1.21-97-master@e71c1df (2024-07-19T11:57:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-96-7ea4039 (MC: 1.21)

### Other

The bug still persists with only paper installed and no other plugins installed. We tested this on the Aternos server provider

**Comment by lynxplay** [comment]
A build with a fix is published at https://github.com/PaperMC/Paper/pull/11114, should be merged shortly 👍

**Comment by YoungSoulluoS** [comment]
I think this fix has presented another problem. Now the crash also happens with a regular workbench.

https://paste.gg/p/anonymous/f4ab6227bf4a406bb788ee4e148b1f73

**Comment by lynxplay** [comment]
Refresh dependencies, you are presumably running the server with an outdated paper-api dependency.
