### ISSUE TITLE
I can' open my plugin to the server!!!

### ISSUE THREAD

**Issue by Hamster67-NOT-USE-NOW** [PaperSpigot/Paper#11134]
### Expected behavior

No Error

### Observed/Actual behavior

It have this error:
[12:24:42 ERROR]: [DirectoryProviderSource] Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/FRFly.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/FRFly.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:86) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[paper-1.21.jar:1.21-106-3a47518]
        at net.minecraft.server.Main.main(Main.java:122) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[paper-1.21.jar:1.21-106-3a47518]
        at org.bukkit.craftbukkit.Main.main(Main.java:287) ~[paper-1.21.jar:1.21-106-3a47518]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/.paper-remapped/FRFly.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        ... 10 more

### Steps/models to reproduce

![螢幕擷取畫面 2024-07-21 203132](https://github.com/user-attachments/assets/b4a83833-71f5-4576-9ed6-9fc207084102)

### Plugin and Datapack List

FRFly.jar(Plugin I made)

### Paper version

Paper 1.21

### Other

--------------------------------------------------------------------------------
command.java :
--------------------------------------------------------------------------------
package ham67.fr.fly.commands;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;

public class FlyCommand implements CommandExecutor {

    @Override
    public boolean onCommand(@NotNull CommandSender commandSender, @NotNull Command command, @NotNull String s, @NotNull String[] strings) {

        if (commandSender instanceof Player){
            Player player = (Player) commandSender;
            if(player.hasPermission("flyplugin.fly")){
                player.setAllowFlight(true);
                player.sendMessage(ChatColor.YELLOW + "你現在可以飛行了!");
            }
        }

        return true;
    }
}
--------------------------------------------------------------------------------
fly.java
--------------------------------------------------------------------------------
package ham67.fr.fly;

import ham67.fr.fly.commands.FlyCommand;
import org.bukkit.plugin.java.JavaPlugin;

public final class Fly extends JavaPlugin {

    @Override
    public void onEnable() {
        // Plugin startup logic

        getCommand('fly').setExecutor(new FlyCommand());
    }
}

--------------------------------------------------------------------------------
paper-plugin.yml
--------------------------------------------------------------------------------
name: Fly
version: '1.0'
main: ham67.fr.fly.Fly
api-version: '1.21'
prefix: FasterRunnerFlyPlugin
load: STARTUP
authors: [ XIaocang67(Owner) ]
description: It's a Fly Plugin.
website: www.fasterrunner.cloudns.be
commands:
  fly:
    description: Fly free like a brid.
    usage: /<command>
--------------------------------------------------------------------------------

**Comment by electronicboy** [comment]
Please use the discord for support, this is often going to be something down to mispackaging of the plugin jar
