### ISSUE TITLE
Failed to save entity data - Saving entity NBT

### ISSUE THREAD

**Issue by andrewkm** [PaperSpigot/Paper#11136]
### Expected behavior

No errors in console.

### Observed/Actual behavior

```
[11:05:18] [Server thread/ERROR]: [ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder] Failed to save entity data (371,245) in world 'mining'
net.minecraft.ReportedException: Saving entity NBT
	at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2565) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:2383) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:2369) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.world.entity.Entity.save(Entity.java:2399) ~[paper-1.21.jar:1.21-106-3a47518]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.saveEntityChunk0(ChunkEntitySlices.java:116) ~[paper-1.21.jar:1.21-106-3a47518]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.saveEntityChunk(ChunkEntitySlices.java:94) ~[paper-1.21.jar:1.21-106-3a47518]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.save(ChunkEntitySlices.java:146) ~[paper-1.21.jar:1.21-106-3a47518]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.saveEntities(NewChunkHolder.java:1858) ~[paper-1.21.jar:1.21-106-3a47518]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.save(NewChunkHolder.java:1729) ~[paper-1.21.jar:1.21-106-3a47518]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.autoSave(ChunkHolderManager.java:245) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:413) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:401) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:414) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:732) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1805) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1597) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-106-3a47518]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalStateException: Value must be within range [1;99]: 144
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.world.item.ItemStack.save(ItemStack.java:622) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.world.entity.item.ItemEntity.addAdditionalSaveData(ItemEntity.java:420) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.world.entity.Entity.addAdditionalSaveData(Entity.java:2730) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2513) ~[paper-1.21.jar:1.21-106-3a47518]
	... 19 more
```

### Steps/models to reproduce

Not entirely sure, it happens ever so often.
I do see a similar issue marked fixed here: https://github.com/PaperMC/Paper/issues/10728
Doesn't seem to be the case however on our end.

### Plugin and Datapack List

On request via Discord.

### Paper version

This server is running Paper version 1.21-106-master@3a47518 (2024-07-21T02:47:23Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Comment by lynxplay** [comment]
Well something created an itemstack that is oversized. May be related to some funky armorstand issues?

**Comment by lynxplay** [comment]
Random shot in the wild, does this happen on a server with creative mode permissions for clients?

**Comment by andrewkm** [comment]
> Random shot in the wild, does this happen on a server with creative mode permissions for clients?

We do not give creative anywhere on our servers.

**Comment by andrewkm** [comment]
> Okay. Well this issue is kinda rough then.
> 
> Without any context as to *where* those items came from, it is hard to debug.
> 
> 
> 
> There are some known waits to cheat in items with a too large item count that could cause such a break, but that requires creative mode or command permissions from my knowledge.
> 
> 
> 
> Have you checked the chunk that failed to save?

I believe @electronicboy just forwarded me a paper jar to get more input / information. Will have more information hopefully after 24ish hours.

**Comment by lynxplay** [comment]
Sweet, thank you :)

**Comment by andrewkm** [comment]
Issue was on our end. Thank you for your responses though! :)
@electronicboy can comment more if needed/requested.
Fixed here.

**Comment by servicomcr** [comment]
I'm experiencing the same error too.


[05:22:53 ERROR]: [ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder] Failed to save entity data (10,-995) in world 'survival'
net.minecraft.ReportedException: Saving entity NBT
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2594) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:2407) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:2393) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.world.entity.Entity.save(Entity.java:2423) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.saveEntityChunk0(ChunkEntitySlices.java:116) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.saveEntityChunk(ChunkEntitySlices.java:94) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.save(ChunkEntitySlices.java:146) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.saveEntities(NewChunkHolder.java:1843) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.save(NewChunkHolder.java:1714) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.autoSave(ChunkHolderManager.java:245) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:413) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:401) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:415) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1843) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Value must be within range [1;99]: 108
        at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
        at net.minecraft.world.item.ItemStack.save(ItemStack.java:624) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.world.entity.item.ItemEntity.addAdditionalSaveData(ItemEntity.java:435) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.world.entity.Entity.addAdditionalSaveData(Entity.java:2764) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2537) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        ... 19 more
