### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11148]
### Expected behavior

I thought I could join on my server as always

### Observed/Actual behavior

I could only join once after a restart, but then I couldn't join again

### Steps/models to reproduce

I don't know how to reproduce this problem, but my error is:

[14:38:37 WARN]: Failed to handle packet for /:49168
net.minecraft.server.v1_8_R3.ReportedException: Sending packet
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:925) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:334) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[?:?]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:911) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 11 more
[14:38:37 INFO]: Kalibrier lost connection: Internal server error
[14:38:37 INFO]: Kalibrier left the game.

### Plugin and Datapack List

[14:42:45 INFO]: Plugins (9): LuckPerms, Essentials, EssentialsChat, ProtocolLib, Multiverse-Core, Citizens, StrikePractice, BungeeGuard, GrimAC

### Paper version

>version
[14:41:25 INFO]: This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[14:41:25 INFO]: Checking version, please wait...
[14:41:25 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://ci.destroystokyo.com/job/PaperSpigot/lastSuccessfulBuild/buildNumber
[14:41:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897)
[14:41:25 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
[14:41:25 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[14:41:25 WARN]:        at java.net.URL.openStream(URL.java:1093)
[14:41:25 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:87)
[14:41:25 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
[14:41:25 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:106)
[14:41:25 WARN]:        at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:254)
[14:41:25 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:191)
[14:41:25 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$0(VersionCommand.java:185)
[14:41:25 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:176)
[14:41:25 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:41:25 INFO]: Error obtaining version information

**Comment by lynxplay** [comment]
1.8 is no longer supported.

**Comment by aarondsyt** [comment]
usercache.json delete
