### ISSUE TITLE
1.21 update: Encountered exception remapping plugins: java.lang.IllegalStateException: Duplicate entries detected

### ISSUE THREAD

**Issue by BigScary** [PaperSpigot/Paper#11152]
### Expected behavior

Plugins load (or fail with error text I can understand and fix?)

### Observed/Actual behavior

Encountered exception remapping plugins
Failed to remap plugin jar 'plugins\IslandsWorldGen.jar'
java.lang.IllegalStateException: Duplicate entries detected

See below for full error:

[20:31:06] [ServerMain/ERROR]: [PluginRemapper] Encountered exception remapping plugins
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\IslandsWorldGen.jar'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\IslandsWorldGen.jar'
	at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:358) ~[paper-1.21.jar:1.21-108-73a863b]
	... 5 more
Caused by: java.lang.IllegalStateException: Duplicate entries detected: me/ryanhamshire/BigScaryIslands/EmptyWorldGenerator.class
	at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:207) ~[paper-1.21.jar:?]
	at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:95) ~[paper-1.21.jar:?]
	at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[paper-1.21.jar:1.21-108-73a863b]
	... 5 more

### Steps/models to reproduce

I just started the server. All my other plugins loaded fine, and this one is extremely simple (just a world generator where everything is air). It has been working for years without errors, across many Paper versions. But this update, I got this error I don't understand how to respond to it.

### Plugin and Datapack List

AdvancedEnchantments, GriefPrevention, GriefPreventionFlags, *PermissionsBukkit, PhantomAdmin

### Paper version

This server is running Paper version 1.21-108-master@73a863b (2024-07-22T13:23:21Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-496 (MC: 1.20.4)

**Comment by BigScary** [comment]
Update I have one other plugin hitting this, similar error. For what it's worth, I dev them both. Maybe I...  compiled them weird..? Then again, some others plugins I run in production, I also deved and they aren't doing this.

Caused by: java.lang.IllegalStateException: Duplicate entries detected: me/ryanhamshire/BigScaryIslands/AutomaticBroadcaster.class, me/ryanhamshire/BigScaryIslands/BigScaryIslands$ExperienceBlockResetter.class, me/ryanhamshire/BigScaryIslands/BigScaryIslands$LateInitializer.class, me/ryanhamshire/BigScaryIslands/BigScaryIslands$ThrottledBlockUpdater.class, me/ryanhamshire/BigScaryIslands/BigScaryIslands$ThrottledChunkExplorer.class, me/ryanhamshire/BigScaryIslands/BigScaryIslands$ThrottledChunkLoader.class, me/ryanhamshire/BigScaryIslands/BigScaryIslands$TickTimestamper.class, me/ryanhamshire/BigScaryIslands/BigScaryIslands$TimedSubtitleSender.class, me/ryanhamshire/BigScaryIslands/BigScaryIslands.class, me/ryanhamshire/BigScaryIslands/BiomeIndexer$BiomeCategory.class, me/ryanhamshire/BigScaryIslands/BiomeIndexer.class, me/ryanhamshire/BigScaryIslands/BlockChangeItem.class, me/ryanhamshire/BigScaryIslands/ChunkComparisonJob.class, me/ryanhamshire/BigScaryIslands/ChunkComparisonProcessor.class, me/ryanhamshire/BigScaryIslands/Coords.class, me/ryanhamshire/BigScaryIslands/Coords3D.class, me/ryanhamshire/BigScaryIslands/DataStore.class, me/ryanhamshire/BigScaryIslands/Island.class, me/ryanhamshire/BigScaryIslands/IslandAssignmentDateComparator.class, me/ryanhamshire/BigScaryIslands/IslandCoordRuleSet.class, me/ryanhamshire/BigScaryIslands/IslandManager.class, me/ryanhamshire/BigScaryIslands/IslandSampleJob$IslandJobPriority.class, me/ryanhamshire/BigScaryIslands/IslandSampleJob.class, me/ryanhamshire/BigScaryIslands/IslandTemplate.class, me/ryanhamshire/BigScaryIslands/JoinDelayer.class, me/ryanhamshire/BigScaryIslands/PlayerData$DataLoader.class, me/ryanhamshire/BigScaryIslands/PlayerData$DataSaver.class, me/ryanhamshire/BigScaryIslands/PlayerData.class, me/ryanhamshire/BigScaryIslands/SampleLocation.class, me/ryanhamshire/BigScaryIslands/SnowPopulator.class, me/ryanhamshire/BigScaryIslands/Test_Coords.class, me/ryanhamshire/BigScaryIslands/Test_Coords3D.class, me/ryanhamshire/BigScaryIslands/Test_IslandManager.class, me/ryanhamshire/BigScaryIslands/Test_IslandTemplate.class

**Comment by kennytv** [comment]
Your have multiple instances of the same classes included in your jar, makes sure individual modules aren't shaded twice. for more help, you can join our Discord and use the build-tooling-help channel

**Comment by BigScary** [comment]
Post mortem: This was a super odd "just me" thing. I had a bin folder with some class files in it, which was being exported to the jar alongside my target folder. So double the class files. Probably some file leftovers from years ago when I built another way.

**Comment by 1CHENYAOXIN0712** [comment]
[10:10:55 ERROR]: [PluginRemapper] Encountered exception remapping plugins
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\[C]CosmeticsCore_1.3.11.jar'
        at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:359) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:364) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:670) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:503) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]
        Suppressed: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\[C]CustomFishing-2.3.22.jar'
                at java.base/java.util.concurrent.CompletableFuture.wrapInCompletionException(CompletableFuture.java:323) ~[?:?]
                at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:359) ~[?:?]
                at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:364) ~[?:?]
                at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:670) ~[?:?]
                at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:503) ~[?:?]
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090) ~[?:?]
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614) ~[?:?]
                at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]
        Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\[C]CustomFishing-2.3.22.jar'
                at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:358) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
                at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:667) ~[?:?]
                ... 4 more
        Caused by: java.lang.RuntimeException: Failed to execute task net/momirealms/customfishing/bukkit/nms/impl/r26_1/Heart
                at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:56) ~[AutoRenamingTool-2.0.3.jar:?]
                at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
                at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:161) ~[paper-1.21.4.jar:?]
                at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:79) ~[paper-1.21.4.jar:?]
                at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
                at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:667) ~[?:?]
                ... 4 more
        Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
                at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:124) ~[?:?]
                at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:193) ~[?:?]
                at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:52) ~[AutoRenamingTool-2.0.3.jar:?]
                at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
                at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:161) ~[paper-1.21.4.jar:?]
                at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:79) ~[paper-1.21.4.jar:?]
                at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
                at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:667) ~[?:?]
                ... 4 more
        Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
                at org.objectweb.asm.ClassReader.readShort(ClassReader.java:3635) ~[asm-9.7.1.jar:9.7.1]
                at org.objectweb.asm.ClassReader.<init>(ClassReader.java:198) ~[asm-9.7.1.jar:9.7.1]
                at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.7.1.jar:9.7.1]
                at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.7.1.jar:9.7.1]
                at net.neoforged.art.internal.ClassProviderImpl$ClassInfo.<init>(ClassProviderImpl.java:104) ~[AutoRenamingTool-2.0.3.jar:?]
                at net.neoforged.art.internal.ClassProviderBuilderImpl.lambda$addClass$1(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
                at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1724) ~[?:?]
                at net.neoforged.art.internal.ClassProviderBuilderImpl.addClass(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
                at net.neoforged.art.internal.RenamerImpl.lambda$run$2(RenamerImpl.java:162) ~[paper-1.21.4.jar:?]
                at net.neoforged.art.internal.AsyncHelper.lambda$null$0(AsyncHelper.java:33) ~[AutoRenamingTool-2.0.3.jar:?]
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328) ~[?:?]
                ... 3 more
Caused by: java.lang.RuntimeException: Failed to remap plugin jar 'plugins\[C]CosmeticsCore_1.3.11.jar'
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:358) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:667) ~[?:?]
        ... 4 more
Caused by: java.lang.RuntimeException: Failed to execute task dev/lone/cosmeticscore/nms/camera/impl/v26_1_1
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:56) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:161) ~[paper-1.21.4.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:79) ~[paper-1.21.4.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:667) ~[?:?]
        ... 4 more
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:124) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:193) ~[?:?]
        at net.neoforged.art.internal.AsyncHelper.invokeAll(AsyncHelper.java:52) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.AsyncHelper.consumeAll(AsyncHelper.java:36) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:161) ~[paper-1.21.4.jar:?]
        at net.neoforged.art.internal.RenamerImpl.run(RenamerImpl.java:79) ~[paper-1.21.4.jar:?]
        at io.papermc.paper.pluginremap.PluginRemapper.lambda$remap$7(PluginRemapper.java:355) ~[paper-1.21.4.jar:1.21.4-232-12d8fe0]
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:667) ~[?:?]
        ... 4 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
        at org.objectweb.asm.ClassReader.readShort(ClassReader.java:3635) ~[asm-9.7.1.jar:9.7.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:198) ~[asm-9.7.1.jar:9.7.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.7.1.jar:9.7.1]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.7.1.jar:9.7.1]
        at net.neoforged.art.internal.ClassProviderImpl$ClassInfo.<init>(ClassProviderImpl.java:104) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.ClassProviderBuilderImpl.lambda$addClass$1(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1756) ~[?:?]
        at net.neoforged.art.internal.ClassProviderBuilderImpl.addClass(ClassProviderBuilderImpl.java:64) ~[AutoRenamingTool-2.0.3.jar:?]
        at net.neoforged.art.internal.RenamerImpl.lambda$run$2(RenamerImpl.java:162) ~[paper-1.21.4.jar:?]
        at net.neoforged.art.internal.AsyncHelper.lambda$null$0(AsyncHelper.java:33) ~[AutoRenamingTool-2.0.3.jar:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328) ~[?:?]
        ... 3 more

**Comment by mbax** [comment]
@1CHENYAOXIN0712 please do try to take over existing issues for your own help. Update your server to latest Paper and visit the support discord if you need help on that.
