### ISSUE TITLE
1.21 huge fortune enchantments (i.e. 255) cause item drops with count more than 99

### ISSUE THREAD

**Issue by BaffledHedgehog** [PaperSpigot/Paper#11202]
### Expected behavior

In vanilla, item gets stacked in different stacks on drop and there is no errors or corrupted entity data

### Observed/Actual behavior

item spawns with count more than 99 and it causes a lot of console errors, huge tps drop, and any '/data' command gets unexpected error message. (breaks any datapack functions that uses '/data' command)

console spam (only if `/data` command used in mcfunctions towards corrupted item entity):
```
[17:54:18 WARN]: Failed to execute function lbc:tick1s
net.minecraft.ReportedException: Saving entity NBT
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2565) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2404) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.arguments.selector.options.EntitySelectorOptions.lambda$bootStrap$50(EntitySelectorOptions.java:349) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.Util.lambda$allOf$9(Util.java:352) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.level.ServerLevel.lambda$getEntities$12(ServerLevel.java:1414) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup.get(EntityLookup.java:207) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:1413) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.arguments.selector.EntitySelector.addEntities(EntitySelector.java:174) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.arguments.selector.EntitySelector.findEntities(EntitySelector.java:158) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.arguments.EntityArgument.getOptionalEntities(EntityArgument.java:67) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.commands.ExecuteCommand.lambda$register$6(ExecuteCommand.java:153) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at com.mojang.brigadier.context.ContextChain.runModifier(ContextChain.java:60) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.BuildContexts.execute(BuildContexts.java:69) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.tasks.BuildContexts$Unbound.execute(BuildContexts.java:173) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.tasks.BuildContexts$Unbound.execute(BuildContexts.java:167) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.ServerFunctionManager.execute(ServerFunctionManager.java:81) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.level.timers.FunctionCallback.lambda$handle$0(FunctionCallback.java:21) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.world.level.timers.FunctionCallback.handle(FunctionCallback.java:21) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.level.timers.FunctionCallback.handle(FunctionCallback.java:14) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.level.timers.TimerQueue.tick(TimerQueue.java:63) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.level.ServerLevel.tickTime(ServerLevel.java:767) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:665) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalStateException: Value must be within range [1;99]: 337
        at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
        at net.minecraft.world.item.ItemStack.save(ItemStack.java:622) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.item.ItemEntity.addAdditionalSaveData(ItemEntity.java:420) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.Entity.addAdditionalSaveData(Entity.java:2730) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2513) ~[paper-1.21.jar:1.21-123-0a1be9a]
        ... 32 more
```

### Steps/models to reproduce

step 1: obtain an item with high fortune level
`/give @p iron_hoe[enchantments={levels:{"minecraft:fortune":255}}]`
step 2: 
break a block that has a drop affected by fortune (for hoe there is minecraft:short_grass). Wait for it to drop item entity with count>99
step 3:
try to get (or modify) data of this item entity: 
`/data get entity @e[type=item,limit=1,sort=nearest]`
it gives you that error:
![image](https://github.com/user-attachments/assets/c0737a2f-b2cc-47e5-8ac9-f07e781c22e8)
and message in server console:
```
[17:54:18 ERROR]: Command exception: /data get entity @e[type=item,limit=1,sort=nearest]
net.minecraft.ReportedException: Saving entity NBT
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2565) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2404) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.advancements.critereon.NbtPredicate.getEntityTagToCompare(NbtPredicate.java:36) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.commands.data.EntityDataAccessor.getData(EntityDataAccessor.java:57) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.commands.data.DataCommands.getData(DataCommands.java:404) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.commands.data.DataCommands.lambda$register$10(DataCommands.java:83) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalStateException: Value must be within range [1;99]: 337
        at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
        at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
        at net.minecraft.world.item.ItemStack.save(ItemStack.java:622) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.item.ItemEntity.addAdditionalSaveData(ItemEntity.java:420) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.Entity.addAdditionalSaveData(Entity.java:2730) ~[paper-1.21.jar:1.21-123-0a1be9a]
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2513) ~[paper-1.21.jar:1.21-123-0a1be9a]
        ... 30 more
```

### Plugin and Datapack List

plugins: LANBroadcaster
datapacks: Swarog's Skywars, Baffled Lucky Blocks (both made by me & friend, the issue not caused by them, they work great in vanilla)

### Paper version

This server is running Paper version 1.21-123-master@0a1be9a (2024-07-31T02:57:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-109-5a5035b (MC: 1.21)

### Other

auto-unstack overstacked item entities in different item entities with correct count

**Comment by lynxplay** [comment]
Can you replicate this without your datapacks?
Any configuration options changed from their default?

on a fresh server, the stacks split correctly.
![image](https://github.com/user-attachments/assets/db3ae824-6873-49f5-92f0-19b4ce15c76e)

**Comment by lynxplay** [comment]
Specifically your value for https://docs.papermc.io/paper/reference/world-configuration#fixes_split_overstacked_loot would be interesting.

**Comment by lynxplay** [comment]
Sweet, yea that would do it xD Glad we figured it out so fast!
