### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null Crashing Server

### ISSUE THREAD

**Issue by WillowAmos1** [PaperSpigot/Paper#11205]
### Stack trace

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-08-01 00:55:05
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.ObjectOpenHashSet$SetIterator.next(ObjectOpenHashSet.java:575)
	at net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket.<init>(ClientboundUpdateAttributesPacket.java:34)
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:413)
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:227)
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:982)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:403)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:705)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1796)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1601)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1308)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.ObjectOpenHashSet$SetIterator.next(ObjectOpenHashSet.java:575)
	at net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket.<init>(ClientboundUpdateAttributesPacket.java:34)
	at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:413)
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:227)
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:982)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:403)

-- Affected level --
Details:
	All players: 12 total; [ServerPlayer['EleKtr0n_7410'/3014, uuid='c9234f0c-7bc6-4306-b1b2-46a5b4db442a', l='ServerLevel[world]', x=2.30, y=90.00, z=-3.07, cpos=[0, -1], tl=3665904, v=true](EleKtr0n_7410 at 2.300000011920929,90.0,-3.074999988079071), ServerPlayer['angeloLOLZ'/2726, uuid='08d91871-234a-4ec4-a371-326e9b22f261', l='ServerLevel[world]', x=2.03, y=89.00, z=10.16, cpos=[0, 0], tl=372455, v=true](angeloLOLZ at 2.029312850002618,89.0,10.164223981672187), ServerPlayer['Acegaming5296'/5836, uuid='6400df7c-d1c1-4d5e-8dea-4582447d5f3d', l='ServerLevel[world]', x=0.92, y=89.00, z=116.49, cpos=[0, 7], tl=2297683, v=true](Acegaming5296 at 0.9245468483835116,89.0,116.4916989039484), ServerPlayer['themanofdonkes'/6312, uuid='6e111f67-c8df-413c-a699-3067ed63e873', l='ServerLevel[world]', x=34.14, y=82.00, z=266.57, cpos=[2, 16], tl=467466, v=true](themanofdonkes at 34.13892944673853,82.0,266.5657112664481), ServerPlayer['EchannelYT'/6347, uuid='1b09d420-6342-4b1a-8420-1a0cf3ef7727', l='ServerLevel[world]', x=-2.66, y=88.00, z=116.90, cpos=[-1, 7], tl=337758, v=true](EchannelYT at -2.663392421053333,88.0,116.89623522675922), ServerPlayer['NightlyFall'/6367, uuid='7ac09745-f59c-445c-9ec6-4692c5fc121a', l='ServerLevel[world]', x=27.62, y=79.56, z=260.81, cpos=[1, 16], tl=1002206, v=true](NightlyFall at 27.620554357718476,79.5625,260.8089579720614), ServerPlayer['Nvots'/6401, uuid='c12d53ec-a4cc-49ef-be8f-227a1c048e03', l='ServerLevel[world]', x=-9.67, y=83.17, z=73.62, cpos=[-1, 4], tl=4694, v=true](Nvots at -9.673430965140907,83.16610926093821,73.61833915838918), ServerPlayer['Kneeonhigh'/6404, uuid='5f2c2147-4a97-45f4-81e0-f15e2d0fd2f2', l='ServerLevel[world]', x=5.51, y=89.00, z=16.15, cpos=[0, 1], tl=671579, v=true](Kneeonhigh at 5.512499988079071,89.0,16.15460777087494), ServerPlayer['FunkyTime'/6406, uuid='51e58d40-0dc8-4b26-a9f5-7c62102515af', l='ServerLevel[world]', x=10.56, y=83.42, z=220.22, cpos=[0, 13], tl=1252346, v=true](FunkyTime at 10.560467806863947,83.41999998688698,220.21739662031922), ServerPlayer['Disrelation'/6412, uuid='2c5e3a54-4c60-4f7f-a2e1-92d85bba1d8f', l='ServerLevel[world]', x=-1.51, y=85.00, z=46.85, cpos=[-1, 2], tl=1815, v=true](Disrelation at -1.512581952880685,85.0,46.85012840228068), ServerPlayer['Skeleno'/6413, uuid='80101b93-4d2d-487e-b0aa-793140c57a0d', l='ServerLevel[world]', x=3.82, y=89.00, z=6.95, cpos=[0, 0], tl=1683, v=true](Skeleno at 3.819046398073238,89.0,6.95317903889942), ServerPlayer['E7D4'/6418, uuid='30e35e6e-654c-4db0-be0d-ac7c73eb18c6', l='ServerLevel[world]', x=3.25, y=89.00, z=6.16, cpos=[0, 0], tl=16, v=true](E7D4 at 3.248089850199217,89.0,6.163756546880438)]
	Chunk stats: 3153
	Level dimension: minecraft:overworld
	Level spawn location: World: (3,89,6), Section: (at 3,9,6 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 16927799 game time, 24000 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: false
	Level weather: Rain time: 17354 (now: false), thunder time: 19955 (now: false)
	Known server brands: vanilla, Paper
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 25
Stacktrace:
	at net.minecraft.server.level.ServerLevel.fillReportDetails(ServerLevel.java:2438)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1601)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1308)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Plugin and Datapack List

[13:25:49 INFO]: Server Plugins (24):

[13:25:49 INFO]: Bukkit Plugins:

[13:25:49 INFO]: - Citizens, DecentHolograms, DiSky, Essentials, EssentialsChat, EssentialsSpawn, LightAntiCheat, LuckPerms, Multiverse-Core, Multiverse-Inventories

[13:25:49 INFO]: PlaceholderAPI, PlugManX, SkBee, SkHttp, Skript, skript-gui, skript-placeholders, TAB, Tebex, Vault

[13:25:49 INFO]: ViaBackwards, ViaRewind, ViaVersion, VoxelSniper

### Actions to reproduce (if known)

Left the server running, Crashes after a seeming random amount of time (one was 20 minutes, one was over a day)

### Paper version

version

[13:25:06 INFO]: This server is running Paper version 1.21-47-master@62ed302 (2024-07-07T17:34:15Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

You are 76 version(s) behind

Download the new version at: https://papermc.io/downloads/paper

### Other

The server is hosted on minefort.com

**Comment by powercasgamer** [comment]
You are 76 builds out of date. Reproduce on latest.

**Comment by electronicboy** [comment]
This is pretty much the defacto MO of fastutil collections when stuff messes with them concurrently, i.e. plugins

**Comment by WillowAmos1** [comment]
Could you help me figure out which one of my plugins is causing this issue?

**Comment by electronicboy** [comment]
This is not the place for support, and diagnosing without ripping plugins apart is generally more https://docs.papermc.io/paper/basic-troubleshooting#binary-search
