### ISSUE TITLE
"wrappedGoal2" is null

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11216]
### Expected behavior

I keep getting this error in the console.

### Observed/Actual behavior

Entity threw exception at world:-2338.5,19.0,245.5
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.goal.WrappedGoal.isRunning()" because "wrappedGoal2" is null

### Steps/models to reproduce

.

### Plugin and Datapack List

.

### Paper version

Paper version 1.21-126-master@7e44684 (2024-08-05T19:10:11Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Comment by fadfhkdfga** [comment]
+ Entity threw exception at world:-3431.5,47.0,1138.5
java.lang.NullPointerException: null

**Comment by jpenilla** [comment]
Please provide the entire log, we can't do anything with a single line of the stacktrace
https://mclo.gs may be useful

**Comment by WhiteCodeC** [comment]
> Please provide the entire log, we can't do anything with a single line of the stacktrace https://mclo.gs may be useful

[16:46:59] [Server thread/ERROR]: Entity threw exception at world:-172.5,-27.0,-65.5
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.goal.WrappedGoal.isRunning()" because "wrappedGoal2" is null
at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:105) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:938) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3470) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.entity.Mob.aiStep(Mob.java:678) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:273) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.entity.Mob.tick(Mob.java:445) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:241) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]


### Plugins
AltDetector, AuthMe, BlueMap, CoreProtect, DeadChest, Essentials, EssentialsSpawn, FarmControl, FastLogin, Geyser-Spigot
GriefPrevention, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LagFixer, LetMeDespawn, LuckPerms, OreAnnouncer, packetevents, PlaceholderAPI, PlayerCrasher, *PlayTime, ProtocolLib, PvPManager, RealScoreboard, RHLeafDecay, SkinsRestorer, TAB, TCPShield, Vault, Vulcan, WorldEdit, WorldGuard

### Paper Version

Paper 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT

**Comment by electronicboy** [comment]
I don't really see how such a thing could occur without it being down to a plugin messing with server internals improperly. The server blew up because something inserted an illegal value until the entity's running goals, and this is pretty much impossible to occur within the standard control flow of the server.

**Comment by megoRU** [comment]
I was running around the server alone, there aren't many plugins

```java
[09:02:24 ERROR]: Entity threw exception at world:-700.5,-6.0,9.5
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.ai.goal.WrappedGoal.isRunning()" because "wrappedGoalx" is null
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:100) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:785) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3529) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:526) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:46) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.entity.monster.AbstractSkeleton.aiStep(AbstractSkeleton.java:132) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3307) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.entity.Mob.tick(Mob.java:392) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.entity.monster.Skeleton.tick(Skeleton.java:69) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1316) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1434) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:839) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:821) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1807) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1618) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.server.dedicated.DedicatedServer.tickServer(DedicatedServer.java:430) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:384) ~[paper-1.21.10.jar:1.21.10-113-9fc21bc]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by MiniDigger** [comment]
please open a new issue with all required info
