### ISSUE TITLE
Index error when trying to clear inventory of a donkey with chests

### ISSUE THREAD

**Issue by jayjay2080** [PaperSpigot/Paper#11210]
### Stack trace

```
[14:49:16] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to MagicPluginV1.10 v1.0-SNAPSHOT
java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at java.base/java.util.Arrays$ArrayList.set(Arrays.java:4271) ~[?:?]
	at net.minecraft.core.NonNullList.set(NonNullList.java:50) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.world.SimpleContainer.setItem(SimpleContainer.java:224) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at org.bukkit.craftbukkit.inventory.CraftInventoryAbstractHorse.setItem(CraftInventoryAbstractHorse.java:65) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at org.bukkit.craftbukkit.inventory.CraftInventory.clear(CraftInventory.java:445) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at org.bukkit.craftbukkit.inventory.CraftInventory.clear(CraftInventory.java:451) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at MagicPluginV1.10-1.0-SNAPSHOT.jar/org.lemonkingdommods.magicpluginv1.Spells.HealingMagic.ResurrectArea.executeEffect(ResurrectArea.java:61) ~[MagicPluginV1.10-1.0-SNAPSHOT.jar:?]
	at MagicPluginV1.10-1.0-SNAPSHOT.jar/org.lemonkingdommods.magicpluginv1.Spells.SpellCastType.ChanneledSpell.cast(ChanneledSpell.java:25) ~[MagicPluginV1.10-1.0-SNAPSHOT.jar:?]
	at MagicPluginV1.10-1.0-SNAPSHOT.jar/org.lemonkingdommods.magicpluginv1.Spells.Data.SpellLoader.onPlayerSneak(SpellLoader.java:89) ~[MagicPluginV1.10-1.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor46.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-79-a6ceda1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2541) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:46) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:18) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1533) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1510) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1503) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1462) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1469) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1314) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-79-a6ceda1]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:49:29] [Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to MagicPluginV1.10 v1.0-SNAPSHOT
java.lang.ArrayIndexOutOfBoundsException: null
```

### Plugin and Datapack List

[15:44:30 INFO]: Bukkit Plugins:
[15:44:30 INFO]:  - Citizens, MagicPluginV1.10, PIT
[15:44:55 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]

Citizens-2.0.35-b3492
MagicPluginV1.10-1.0-SNAPSHOT (my plugin)
PIT-1.0-SNAPSHOT (also my plugin)

### Actions to reproduce (if known)

create a plugin, with someway to get an entity (specifically a donkey) from the world, cast to inventory holder and get the donkey's inventory with getInventory(), then use clear() with no argument on it and you will get the index out of bounds error, the donkey must be tamed and have chests and saddle equip, also checking the size of the inventory returns 17 when there are clearly only 16 slots in the ui (including the saddle slot)

### Paper version

[15:41:54 INFO]: Checking version, please wait...
[15:41:54 INFO]: This server is running Paper version 1.21-124-master@df3b654 (2024-08-02T00:02:38Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-79-a6ceda1 (MC: 1.21)

**Comment by Machine-Maker** [comment]
The stacktrace you posted is not from the version you have listed. The stacktrace you posted is from build 79 of Paper 1.21, the version you posted is build 124. Please try to reproduce the error on the latest paper build.

**Comment by jayjay2080** [comment]
okay so i thought i tested on the latest version as well but it appears to work on this version so i guess its fixed, sorry about that and thanks for the help
