### ISSUE TITLE
1.19.2Shop must register into ShopManager before loading.

### ISSUE THREAD

**Issue by SGDanDan** [PaperSpigot/Paper#11249]
### Stack trace

```[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-99.0,y=54.0,z=-3.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: CHEST
[17:48:58 WARN] [QuickShop]: #######################################
[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-99.0,y=54.0,z=-4.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: TRAPPED_CHEST
[17:48:58 WARN] [QuickShop]: #######################################
[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-99.0,y=54.0,z=-5.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: CHEST
[17:48:58 WARN] [QuickShop]: #######################################
[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-98.0,y=53.0,z=-3.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: CHEST
[17:48:58 WARN] [QuickShop]: #######################################
[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-98.0,y=53.0,z=-4.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: TRAPPED_CHEST
[17:48:58 WARN] [QuickShop]: #######################################
[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-98.0,y=53.0,z=-5.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: CHEST
[17:48:58 WARN] [QuickShop]: #######################################
[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-99.0,y=54.0,z=-9.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: CHEST
[17:48:58 WARN] [QuickShop]: #######################################
[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-99.0,y=54.0,z=-10.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: TRAPPED_CHEST
[17:48:58 WARN] [QuickShop]: #######################################
[17:48:58 WARN] [QuickShop]: ##########FAILED TO LOAD SHOP##########
[17:48:58 WARN] [QuickShop]:   >> Error Info:
[17:48:58 WARN] [QuickShop]: Shop must register into ShopManager before loading.
[17:48:58 WARN] [QuickShop]:   >> Error Trace
[17:48:58 ERROR] [STDERR]: java.lang.IllegalStateException: Shop must register into ShopManager before loading.
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:1043)
[17:48:58 ERROR] [STDERR]:      at org.maxgamer.quickshop.shop.ShopLoader.lambda$loadShops$0(ShopLoader.java:194)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.19.2-1.0.5-696a298/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zdd000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[17:48:58 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[17:48:58 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:58 WARN] [QuickShop]:   >> Target Location Info
[17:48:58 WARN] [QuickShop]: Location: Location{world=CraftWorld{name=zc},x=-99.0,y=54.0,z=-11.0,pitch=0.0,yaw=0.0}
[17:48:58 WARN] [QuickShop]: Block: CHEST
[17:48:58 WARN] [QuickShop]: #######################################
paste your stack trace or a paste.gg link here!
```

### Plugin and Datapack List

1

### Actions to reproduce (if known)

1

### Paper version

1

### Other

1

**Comment by lynxplay** [comment]
A) This is a plugin issue, you should report it to them
B) This is paper, not arclight
C) Only 1.21.1 is supported.
