### ISSUE TITLE
Validate block state is failing during world gen on rare occasions

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#11315]
### Stack trace

This error happened at an ocean ruin, probably during/just after world gen, seems like the structure placed a chest over a brushable block. 

```
[10:25:34] [Server thread/ERROR]: Failed to create block entity minecraft:brushable_block
java.lang.IllegalStateException: Invalid block entity minecraft:brushable_block // net.minecraft.world.level.block.entity.BrushableBlockEntity state at BlockPos{x=26055, y=43, z=-6938}, got Block{minecraft:chest}[facing=north,type=single,waterlogged=false]
	at net.minecraft.world.level.block.entity.BlockEntity.validateBlockState(BlockEntity.java:70) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.world.level.block.entity.BlockEntity.<init>(BlockEntity.java:61) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.world.level.block.entity.BrushableBlockEntity.<init>(BrushableBlockEntity.java:61) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.world.level.block.entity.BlockEntityType.create(BlockEntityType.java:297) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.world.level.block.entity.BlockEntity.lambda$loadStatic$4(BlockEntity.java:211) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.loadStatic(BlockEntity.java:209) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.lambda$postLoadChunk$10(ChunkSerializer.java:595) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.world.level.chunk.LevelChunk.runPostLoad(LevelChunk.java:644) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:74) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:746) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:372) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:393) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.level.ServerLevel.moonrise$midTickTasks(ServerLevel.java:341) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1430) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-DEV-b4bc512]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
	
```

### Plugin and Datapack List

N/A

### Paper version

This server is running Paper version 1.21.1-DEV-master@b4bc512 (2024-08-18T22:23:43Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-DEV-52ae4ad (MC: 1.21.1)

**Comment by Machine-Maker** [comment]
Can you please provide the world seed?

**Comment by YuanYuanOwO** [comment]
I have same issue,my world seed is `Seed: [4582130043017388758]`  
and here is my logs  
```
[00:32:37] [Server thread/ERROR]: Failed to create block entity minecraft:sculk_sensor
java.lang.IllegalStateException: Invalid block entity minecraft:sculk_sensor // net.minecraft.world.level.block.entity.SculkSensorBlockEntity state at BlockPos{x=1645, y=-47, z=-5927}, got Block{minecraft:sculk_catalyst}[bloom=false]
	at net.minecraft.world.level.block.entity.BlockEntity.validateBlockState(BlockEntity.java:70) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntity.<init>(BlockEntity.java:61) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.SculkSensorBlockEntity.<init>(SculkSensorBlockEntity.java:32) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.SculkSensorBlockEntity.<init>(SculkSensorBlockEntity.java:38) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntityType.create(BlockEntityType.java:297) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntity.lambda$loadStatic$4(BlockEntity.java:211) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.loadStatic(BlockEntity.java:209) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.lambda$postLoadChunk$10(ChunkSerializer.java:595) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.chunk.LevelChunk.runPostLoad(LevelChunk.java:644) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:74) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:746) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:372) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.moonrise$executeMidTickTasks(MinecraftServer.java:393) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerLevel.moonrise$midTickTasks(ServerLevel.java:341) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1430) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:32:37] [Server thread/WARN]: Skipping BlockEntity with id minecraft:sculk_sensor
[00:32:38] [Server thread/ERROR]: Failed to create block entity minecraft:sculk_shrieker
java.lang.IllegalStateException: Invalid block entity minecraft:sculk_shrieker // net.minecraft.world.level.block.entity.SculkShriekerBlockEntity state at BlockPos{x=1791, y=-50, z=-5904}, got Block{minecraft:sculk_catalyst}[bloom=false]
	at net.minecraft.world.level.block.entity.BlockEntity.validateBlockState(BlockEntity.java:70) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntity.<init>(BlockEntity.java:61) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.SculkShriekerBlockEntity.<init>(SculkShriekerBlockEntity.java:66) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntityType.create(BlockEntityType.java:297) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntity.lambda$loadStatic$4(BlockEntity.java:211) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.loadStatic(BlockEntity.java:209) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.lambda$postLoadChunk$10(ChunkSerializer.java:595) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.chunk.LevelChunk.runPostLoad(LevelChunk.java:644) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:74) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:746) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1525) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:32:38] [Server thread/WARN]: Skipping BlockEntity with id minecraft:sculk_shrieker
[00:32:38] [Server thread/ERROR]: Failed to create block entity minecraft:sculk_sensor
java.lang.IllegalStateException: Invalid block entity minecraft:sculk_sensor // net.minecraft.world.level.block.entity.SculkSensorBlockEntity state at BlockPos{x=1751, y=-50, z=-5980}, got Block{minecraft:sculk_catalyst}[bloom=false]
	at net.minecraft.world.level.block.entity.BlockEntity.validateBlockState(BlockEntity.java:70) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntity.<init>(BlockEntity.java:61) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.SculkSensorBlockEntity.<init>(SculkSensorBlockEntity.java:32) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.SculkSensorBlockEntity.<init>(SculkSensorBlockEntity.java:38) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntityType.create(BlockEntityType.java:297) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.block.entity.BlockEntity.lambda$loadStatic$4(BlockEntity.java:211) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.BlockEntity.loadStatic(BlockEntity.java:209) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.lambda$postLoadChunk$10(ChunkSerializer.java:595) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.world.level.chunk.LevelChunk.runPostLoad(LevelChunk.java:644) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.task.ChunkFullTask.run(ChunkFullTask.java:74) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:370) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:746) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:337) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1525) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:32:38] [Server thread/WARN]: Skipping BlockEntity with id minecraft:sculk_sensor
```

**Comment by Machine-Maker** [comment]
So I checked the default installation of `Lootin`, as that was the plugin that exposed a similar bug in the past, but that didn't cause this error when I generated the world and teleported to that location. Can you perform a binary search of your plugins, on a complete copy of your server/world? Essentially copy your server, delete the world (cause it has to "generate" to cause this issue). Then remove half your plugins, generate world, see if that exception happens. If it does, you know the issue is in that half of the plugins, otherwise its in the other half. adjust your installed plugins, delete the world and check again.

**Comment by Jckf** [comment]
I just had this too. Although I am running plain old Spigot on my test server, I hope the information is still useful.

Seed: 4113167221189323283

```
[02:09:30] [Server thread/ERROR]: Failed to create block entity minecraft:brushable_block
java.lang.IllegalStateException: Invalid block entity minecraft:brushable_block // net.minecraft.world.level.block.entity.BrushableBlockEntity state at BlockPosition{x=3570, y=51, z=-271}, got Block{minecraft:chest}[facing=north,type=single,waterlogged=false]
	at net.minecraft.world.level.block.entity.TileEntity.a(TileEntity.java:66) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.block.entity.TileEntity.<init>(TileEntity.java:58) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.block.entity.BrushableBlockEntity.<init>(BrushableBlockEntity.java:61) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.block.entity.TileEntityTypes.a(SourceFile:99) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.block.entity.TileEntity.lambda$loadStatic$4(TileEntity.java:202) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.world.level.block.entity.TileEntity.a(TileEntity.java:200) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.chunk.Chunk.a(Chunk.java:724) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.chunk.Chunk.a(Chunk.java:376) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.chunk.Chunk.c_(Chunk.java:360) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.chunk.Chunk.a(Chunk.java:473) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.world.level.chunk.storage.ChunkRegionLoader.a(ChunkRegionLoader.java:402) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:858) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.level.PlayerChunkMap.d(PlayerChunkMap.java:821) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.level.PlayerChunkMap.b(PlayerChunkMap.java:529) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:483) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:360) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:412) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1472) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4318-Spigot-a759b62-98c57cb]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[02:09:30] [Server thread/WARN]: Skipping BlockEntity with id minecraft:brushable_block
[02:09:30] [Server thread/WARN]: Tried to load a block entity for block Block{minecraft:chest}[facing=north,type=single,waterlogged=false] but failed at location BlockPosition{x=3570, y=51, z=-271}
```

**Comment by Machine-Maker** [comment]
@Jckf and did you have any datapacks (world-gen related ones) or plugins?

**Comment by Jckf** [comment]
@Machine-Maker Develop branch of [this plugin](https://github.com/Jckf/DH-Support/) was the only thing. The only interaction it has with the world is through reading, but it will read chunks that don't exist if requested - and hence cause them to be generated.

**Comment by Machine-Maker** [comment]
@Jckf so your specific issue should already be fixed on Paper. 

Still unsure what caused the original stacktrace for this issue. We haven't been able to reproduce anything on Paper with or without plugins (am not gonna install 80 plugins) with a specific seed yet. Until we do, its going to be very hard to track down.
