### ISSUE TITLE
 FAILED TO BIND TO PORT!

### ISSUE THREAD

**Issue by kkk2z123** [PaperSpigot/Paper#11324]
### Stack trace

error log
```
[22:40:52 WARN]: **** FAILED TO BIND TO PORT!
[22:40:52 WARN]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
[22:40:52 WARN]: Perhaps a server is already running on that port?
[22:40:52 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to bind to port
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-41-fcedb49]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
[22:40:52 ERROR]: This crash report has been saved to: /workspaces/1.21-Eagler-server/server/crash-reports/crash-2024-08-24_22.40.52-server.txt
[22:40:52 INFO]: Stopping server
[22:40:52 INFO]: Saving players
[22:40:53 INFO]: Saving worlds
> WARN StatusConsoleListener Advanced terminal features are not available in this environment
[22:40:53 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```

### Plugin and Datapack List

[viaversion5.0.3](https://viaversion.com/)
[Viabackwards5.0.3](https://viaversion.com/)
[ViaRewind4.0.2](https://viaversion.com/)
 [UltimateAutoRestart](https://polymart.org/resource/ultimateautorestart.35)
[Lunachat](https://github.com/ucchyocean/LunaChat/releases/tag/v3.0.16)

### Paper version

[bootstrap] Loading Paper 1.21.1-41-master@fcedb49 (2024-08-24T09:02:10Z) for Minecraft 1.21.1

PaperMC1.21.1#41

### Other

server-Sourcecode
```
https://github.com/kkk2z123/1.21-Eagler-server
```
crash-report
```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2024-08-24 22:34:04
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to bind to port
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.5.0-1022-azure
	Java Version: 21.0.4, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 225744728 bytes (215 MiB) / 566231040 bytes (540 MiB) up to 2080374784 bytes (1984 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7763 64-Core Processor
	Identifier: AuthenticAMD Family 25 Model 1 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 2
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 3964.78
	Virtual memory used (MiB): 2972.76
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 42724.98, total: 45046.83
	Space in storage for workdir (MiB): available: 19578.34, total: 32077.81
	JVM Flags: 0 total; 
	CraftBukkit Information: 
   BrandInfo: Paper (papermc:paper) version 1.21.1-41-master@fcedb49 (2024-08-24T09:02:10Z)
   Running: Paper version 1.21.1-41-fcedb49 (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT) false
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Notification Thread: [], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:209), io.netty.channel.epoll.Native.epollWait(Native.java:202), io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:316), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:373), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.4/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.4/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.4/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.4/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)], WAITING RegionFile I/O Thread #0: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.4/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.4/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.4/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.4/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING pool-8-thread-1: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758), java.base@21.0.4/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@21.0.4/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)], RUNNABLE Reference Handler: [java.base@21.0.4/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@21.0.4/java.lang.ref.Reference.processPendingReferences(Reference.java:246), java.base@21.0.4/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)], TIMED_WAITING Timer hack thread: [java.base@21.0.4/java.lang.Thread.sleep0(Native Method), java.base@21.0.4/java.lang.Thread.sleep(Thread.java:509), net.minecraft.Util$7.run(Util.java:785)], RUNNABLE Server thread: [java.base@21.0.4/java.lang.Thread.dumpThreads(Native Method), java.base@21.0.4/java.lang.Thread.getAllStackTraces(Thread.java:2521), org.bukkit.craftbukkit.CraftCrashReport.get(CraftCrashReport.java:35), org.bukkit.craftbukkit.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.setDetail(SystemReport.java:71), net.minecraft.CrashReport.<init>(CrashReport.java:40), net.minecraft.server.MinecraftServer.constructOrExtractCrashReport(MinecraftServer.java:1421), net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338), net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330), net.minecraft.server.MinecraftServer$$Lambda/0x00007f464cc7b418.run(Unknown Source), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Common-Cleaner: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847), java.base@21.0.4/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71), java.base@21.0.4/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143), java.base@21.0.4/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218), java.base@21.0.4/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583), java.base@21.0.4/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)], TIMED_WAITING process reaper: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.4/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.4/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.4/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.4/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583), java.base@21.0.4/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)], TIMED_WAITING Paper Watchdog Thread: [java.base@21.0.4/java.lang.Thread.sleep0(Native Method), java.base@21.0.4/java.lang.Thread.sleep(Thread.java:509), org.spigotmc.WatchdogThread.run(WatchdogThread.java:240)], WAITING Paper Common Worker #0: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], WAITING Worker-Main-1: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371), java.base@21.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519), java.base@21.0.4/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780), java.base@21.0.4/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725), java.base@21.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707), java.base@21.0.4/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)], WAITING Finalizer: [java.base@21.0.4/java.lang.Object.wait0(Native Method), java.base@21.0.4/java.lang.Object.wait(Object.java:366), java.base@21.0.4/java.lang.Object.wait(Object.java:339), java.base@21.0.4/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48), java.base@21.0.4/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158), java.base@21.0.4/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89), java.base@21.0.4/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.4/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.4/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.4/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.4/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Keep-Alive-Timer: [java.base@21.0.4/java.lang.Thread.sleep0(Native Method), java.base@21.0.4/java.lang.Thread.sleep(Thread.java:509), java.base@21.0.4/sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:238), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583), java.base@21.0.4/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.4/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.4/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.4/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.4/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371), java.base@21.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519), java.base@21.0.4/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780), java.base@21.0.4/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725), java.base@21.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707), java.base@21.0.4/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:81), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:73)], TIMED_WAITING JNA Cleaner: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847), java.base@21.0.4/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71), java.base@21.0.4/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143), java.base@21.0.4/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218), com.sun.jna.internal.Cleaner$CleanerThread.run(Cleaner.java:154)], RUNNABLE Signal Dispatcher: [], RUNNABLE Server console handler: [java.base@21.0.4/java.io.FileInputStream.read0(Native Method), java.base@21.0.4/java.io.FileInputStream.read(FileInputStream.java:231), org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:117)], TIMED_WAITING Yggdrasil Key Fetcher: [java.base@21.0.4/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.4/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.4/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758), java.base@21.0.4/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@21.0.4/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 50; []
	Active Data Packs: vanilla, file/bukkit, paper (incompatible)
	Available Data Packs: bundle, file/bukkit, paper (incompatible), trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -679767915825103681
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Machine-Maker** [comment]
Yep, use discord
