### ISSUE TITLE
How to fix it?

### ISSUE THREAD

**Issue by KINURUH** [PaperSpigot/Paper#11335]
### Stack trace

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2024-08-28 11:17:02
Description: Exception in server tick loop

org.spongepowered.configurate.loader.ParsingException: []: Unknown error occurred while loading
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:165)
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63)
	at org.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56)
	at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:171)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:227)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: mapping values are not allowed here
 in 'reader', line 354, column 9:
      sensor:
            ^

	at org.spongepowered.configurate.yaml.internal.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:905)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:394)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:241)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:637)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.composer.Composer.composeNode(Composer.java:205)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.composer.Composer.composeNode(Composer.java:209)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.composer.Composer.getNode(Composer.java:131)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
	at org.spongepowered.configurate.yaml.internal.snakeyaml.Yaml.load(Yaml.java:446)
	at org.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:183)
	at org.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:47)
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:155)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.1.0-22-amd64
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1041914880 bytes (993 MiB) / 2147483648 bytes (2048 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 1
	Processor Vendor: AuthenticAMD
	Processor Name: DO-Premium-AMD
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 20354.36
	Virtual memory used (MiB): 9549.75
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 2663.46
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 99.98, total: 100.00
	Space in storage for workdir (MiB): available: 119048.39, total: 161097.88
	JVM Flags: 13 total; -Xms2G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication
	CraftBukkit Information: 
   BrandInfo: Paper (papermc:paper) version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z)
   Running: Paper version 1.21.1-52-e08e667 (MC: 1.21.1) (Implementing API version 1.21.1-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Signal Dispatcher: [], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.3/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.3/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.3/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.3/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.3/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.3/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Yggdrasil Key Fetcher: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758), java.base@21.0.3/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@21.0.3/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.3/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.3/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.3/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)], RUNNABLE Notification Thread: [], WAITING Paper Common Worker #0: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], WAITING RegionFile I/O Thread #0: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221), ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:97)], WAITING Worker-Main-1: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371), java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519), java.base@21.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780), java.base@21.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725), java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707), java.base@21.0.3/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING Common-Cleaner: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847), java.base@21.0.3/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71), java.base@21.0.3/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143), java.base@21.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218), java.base@21.0.3/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.3/java.lang.Thread.run(Thread.java:1583), java.base@21.0.3/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)], WAITING Finalizer: [java.base@21.0.3/java.lang.Object.wait0(Native Method), java.base@21.0.3/java.lang.Object.wait(Object.java:366), java.base@21.0.3/java.lang.Object.wait(Object.java:339), java.base@21.0.3/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48), java.base@21.0.3/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158), java.base@21.0.3/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89), java.base@21.0.3/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371), java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519), java.base@21.0.3/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780), java.base@21.0.3/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725), java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707), java.base@21.0.3/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:81), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:73)], RUNNABLE Reference Handler: [java.base@21.0.3/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@21.0.3/java.lang.ref.Reference.processPendingReferences(Reference.java:246), java.base@21.0.3/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Timer hack thread: [java.base@21.0.3/java.lang.Thread.sleep0(Native Method), java.base@21.0.3/java.lang.Thread.sleep(Thread.java:509), net.minecraft.Util$7.run(Util.java:785)], RUNNABLE Server thread: [java.base@21.0.3/java.lang.Thread.dumpThreads(Native Method), java.base@21.0.3/java.lang.Thread.getAllStackTraces(Thread.java:2521), org.bukkit.craftbukkit.CraftCrashReport.get(CraftCrashReport.java:35), org.bukkit.craftbukkit.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.setDetail(SystemReport.java:71), net.minecraft.CrashReport.<init>(CrashReport.java:40), net.minecraft.server.MinecraftServer.constructOrExtractCrashReport(MinecraftServer.java:1421), net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1338), net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330), net.minecraft.server.MinecraftServer$$Lambda/0x00007f0378c58fc8.run(Unknown Source), java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)], TIMED_WAITING JNA Cleaner: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269), java.base@21.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847), java.base@21.0.3/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71), java.base@21.0.3/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143), java.base@21.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218), com.sun.jna.internal.Cleaner$CleanerThread.run(Cleaner.java:154)], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@21.0.3/jdk.internal.misc.Unsafe.park(Native Method), java.base@21.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410), java.base@21.0.3/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452), java.base@21.0.3/java.util.concurrent.SynchronousQueue$Transferer.xferLifo(SynchronousQueue.java:194), java.base@21.0.3/java.util.concurrent.SynchronousQueue.xfer(SynchronousQueue.java:233), java.base@21.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:336), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.base@21.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642), java.base@21.0.3/java.lang.Thread.runWith(Thread.java:1596), java.base@21.0.3/java.lang.Thread.run(Thread.java:1583)],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 20; []
	Active Data Packs: vanilla, file/bukkit, paper (incompatible)
	Available Data Packs: bundle, file/bukkit, paper (incompatible), trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -7830709225161731362
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

### Plugin and Datapack List

[12:08:21 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[12:08:21 INFO]: There are no more data packs available
[12:09:04 INFO]: Server Plugins (2):
[12:09:04 INFO]: Bukkit Plugins:
[12:09:04 INFO]:  - floodgate, Geyser-Spigot

### Paper version

[12:07:50 INFO]: This server is running Paper version 1.21.1-52-master@e08e667 (2024-08-26T18:02:06Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
your world defaults config file is invalid, please use the discord/forums for support
