### ISSUE TITLE
 [ModernPluginLoadingStrategy] Could not load plugin 'team-1.jar' in folder 'plugins'java.lang.ClassNotFoundException: com.(myname).clan.TeamPlugin

### ISSUE THREAD

**Issue by juwonjun** [PaperSpigot/Paper#11402]
### Profile link

https://github.com/juwonjun

### Description of issue

it's saying like so 

12:59:40 | [ModernPluginLoadingStrategy] Could not load plugin 'team-1.jar' in folder 'plugins'java.lang.ClassNotFoundException: com.jungj.clan.TeamPlugin
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.lang.Class.forName(Class.java:508) ~[?:?]
	at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:51) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:29) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:169) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:139) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:510) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]

### Plugin and Datapack List

    package ServerPlugins.team;

    import org.bukkit.Bukkit;
    import org.bukkit.command.Command;
    import org.bukkit.command.CommandExecutor;
    import org.bukkit.command.CommandSender;
    import org.bukkit.entity.Player;
    import org.bukkit.plugin.java.JavaPlugin;

    import java.util.HashMap;
    import java.util.Map;
    import java.util.Objects;
    import java.util.UUID;

    class TeamPlugin extends JavaPlugin {

        private final Map<String, UUID> clanLeaders = new HashMap<>();
        private final Map<UUID, String> joinRequests = new HashMap<>();

        @Override
        public void onEnable() {
            Objects.requireNonNull(getCommand("createclan")).setExecutor(new CreateClanCommand());
            Objects.requireNonNull(getCommand("joinclan")).setExecutor(new JoinClanCommand());
            Objects.requireNonNull(getCommand("acceptclanjoin")).setExecutor(new AcceptClanJoinCommand());
        }

        @Override
        public void onDisable() {
            // Plugin shutdown logic
        }

        public class CreateClanCommand implements CommandExecutor {
            @Override
            public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
                if (sender instanceof Player) {
                    Player player = (Player) sender;
                    if (args.length == 1) {
                        String clanName = args[0];
                        if (clanLeaders.containsKey(clanName)) {
                            player.sendMessage("이미 존재하는 클랜입니다.");
                        } else {
                            clanLeaders.put(clanName, player.getUniqueId());
                            player.sendMessage("클랜 '" + clanName + "'을(를) 생성했습니다.");
                        }
                    } else {
                        player.sendMessage("클랜 이름을 입력하세요.");
                    }
                } else {
                    sender.sendMessage("이 명령어는 플레이어만 사용할 수 있습니다.");
                }
                return true;
            }
        }

        public class JoinClanCommand implements CommandExecutor {
            @Override
            public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
                if (sender instanceof Player) {
                    Player player = (Player) sender;
                    if (args.length == 1) {
                        String clanName = args[0];
                        if (clanLeaders.containsKey(clanName)) {
                            UUID leaderUUID = clanLeaders.get(clanName);
                            joinRequests.put(player.getUniqueId(), clanName);
                            Player leader = Bukkit.getPlayer(leaderUUID);
                            if (leader != null) {
                                leader.sendMessage(player.getName() + "이(가) 클랜 '" + clanName + "'에 가입하고 싶어합니다.");
                            }
                            player.sendMessage("클랜 '" + clanName + "'에 가입 요청을 보냈습니다.");
                        } else {
                            player.sendMessage("존재하지 않는 클랜입니다.");
                        }
                    } else {
                        player.sendMessage("클랜 이름을 입력하세요.");
                    }
                } else {
                    sender.sendMessage("이 명령어는 플레이어만 사용할 수 있습니다.");
                }
                return true;
            }
        }

        public class AcceptClanJoinCommand implements CommandExecutor {
            @Override
            public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
                if (sender instanceof Player) {
                    Player player = (Player) sender;
                    if (args.length == 1) {
                        String playerName = args[0];
                        Player requestingPlayer = Bukkit.getPlayer(playerName);
                        if (requestingPlayer != null) {
                            UUID requestingPlayerUUID = requestingPlayer.getUniqueId();
                            String clanName = joinRequests.get(requestingPlayerUUID);
                            if (clanName != null && clanLeaders.get(clanName).equals(player.getUniqueId())) {
                                joinRequests.remove(requestingPlayerUUID);
                                // Add player to the clan (you can implement your own clan management logic here)
                                requestingPlayer.sendMessage("클랜 '" + clanName + "'에 가입되었습니다.");
                                player.sendMessage(requestingPlayer.getName() + "이(가) 클랜 '" + clanName + "'에 가입했습니다.");
                            } else {
                                player.sendMessage("가입 요청이 없거나 권한이 없습니다.");
                            }
                        } else {
                            player.sendMessage("존재하지 않는 플레이어입니다.");
                        }
                    } else {
                        player.sendMessage("플레이어 이름을 입력하세요.");
                    }
                } else {
                    sender.sendMessage("이 명령어는 플레이어만 사용할 수 있습니다.");
                }
                return true;
            }
        }
    }

### Server config files

```
Paste configs or paste.gg link here!
```

### Paper version

12:59:38 | Starting minecraft server version 1.20.1

**Comment by lynxplay** [comment]
Please don't use our github issue tracker for basic plugin development support.
Checkout `paper-dev` on our [discord ](https://discord.com/invite/papermc) instead.
