### ISSUE TITLE
Error loading plugin: Directory 'plugins\team-1.jar' failed to load!java.lang.RuntimeException: Directory 'plugins\team-1.jar' failed to load!

### ISSUE THREAD

**Issue by juwonjun** [PaperSpigot/Paper#11401]
### Profile link

https://github.com/juwonjun

### Description of issue

it's syaing 

12:50:07 | [DirectoryProviderSource] Error loading plugin: Directory 'plugins\team-1.jar' failed to load!java.lang.RuntimeException: Directory 'plugins\team-1.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[paper-1.20.1.jar:git-Paper-196]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.Main.main(Main.java:137) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.Main.main(Main.java:324) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: org.spongepowered.configurate.serialize.SerializationException: [api-version] of type java.lang.String: Provided plugin's version (1.2) is not supported on this version.
	at io.papermc.paper.plugin.provider.configuration.serializer.constraints.PluginConfigConstraints$PluginVersion$Factory.lambda$make$0(PluginConfigConstraints.java:80) ~[paper-1.20.1.jar:git-Paper-196]
	at org.spongepowered.configurate.objectmapping.FieldData.validate(FieldData.java:131) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:65) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
	at io.papermc.paper.plugin.provider.configuration.PaperPluginMeta.create(PaperPluginMeta.java:97) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.create(PaperPluginProviderFactory.java:52) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.create(PaperPluginProviderFactory.java:23) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.provider.type.PluginFileType.getConfig(PluginFileType.java:77) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:70) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[paper-1.20.1.jar:git-Paper-196]
	... 20 more

### Plugin and Datapack List

package ServerPlugins.team;

import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

class TeamPlugin extends JavaPlugin {

    private final Map<String, UUID> clanLeaders = new HashMap<>();
    private final Map<UUID, String> joinRequests = new HashMap<>();

    @Override
    public void onEnable() {
        Objects.requireNonNull(getCommand("createclan")).setExecutor(new CreateClanCommand());
        Objects.requireNonNull(getCommand("joinclan")).setExecutor(new JoinClanCommand());
        Objects.requireNonNull(getCommand("acceptclanjoin")).setExecutor(new AcceptClanJoinCommand());
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }

    public class CreateClanCommand implements CommandExecutor {
        @Override
        public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
            if (sender instanceof Player) {
                Player player = (Player) sender;
                if (args.length == 1) {
                    String clanName = args[0];
                    if (clanLeaders.containsKey(clanName)) {
                        player.sendMessage("이미 존재하는 클랜입니다.");
                    } else {
                        clanLeaders.put(clanName, player.getUniqueId());
                        player.sendMessage("클랜 '" + clanName + "'을(를) 생성했습니다.");
                    }
                } else {
                    player.sendMessage("클랜 이름을 입력하세요.");
                }
            } else {
                sender.sendMessage("이 명령어는 플레이어만 사용할 수 있습니다.");
            }
            return true;
        }
    }

    public class JoinClanCommand implements CommandExecutor {
        @Override
        public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
            if (sender instanceof Player) {
                Player player = (Player) sender;
                if (args.length == 1) {
                    String clanName = args[0];
                    if (clanLeaders.containsKey(clanName)) {
                        UUID leaderUUID = clanLeaders.get(clanName);
                        joinRequests.put(player.getUniqueId(), clanName);
                        Player leader = Bukkit.getPlayer(leaderUUID);
                        if (leader != null) {
                            leader.sendMessage(player.getName() + "이(가) 클랜 '" + clanName + "'에 가입하고 싶어합니다.");
                        }
                        player.sendMessage("클랜 '" + clanName + "'에 가입 요청을 보냈습니다.");
                    } else {
                        player.sendMessage("존재하지 않는 클랜입니다.");
                    }
                } else {
                    player.sendMessage("클랜 이름을 입력하세요.");
                }
            } else {
                sender.sendMessage("이 명령어는 플레이어만 사용할 수 있습니다.");
            }
            return true;
        }
    }

    public class AcceptClanJoinCommand implements CommandExecutor {
        @Override
        public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
            if (sender instanceof Player) {
                Player player = (Player) sender;
                if (args.length == 1) {
                    String playerName = args[0];
                    Player requestingPlayer = Bukkit.getPlayer(playerName);
                    if (requestingPlayer != null) {
                        UUID requestingPlayerUUID = requestingPlayer.getUniqueId();
                        String clanName = joinRequests.get(requestingPlayerUUID);
                        if (clanName != null && clanLeaders.get(clanName).equals(player.getUniqueId())) {
                            joinRequests.remove(requestingPlayerUUID);
                            // Add player to the clan (you can implement your own clan management logic here)
                            requestingPlayer.sendMessage("클랜 '" + clanName + "'에 가입되었습니다.");
                            player.sendMessage(requestingPlayer.getName() + "이(가) 클랜 '" + clanName + "'에 가입했습니다.");
                        } else {
                            player.sendMessage("가입 요청이 없거나 권한이 없습니다.");
                        }
                    } else {
                        player.sendMessage("존재하지 않는 플레이어입니다.");
                    }
                } else {
                    player.sendMessage("플레이어 이름을 입력하세요.");
                }
            } else {
                sender.sendMessage("이 명령어는 플레이어만 사용할 수 있습니다.");
            }
            return true;
        }
    }
}
(this is korean)

### Server config files

```
Paste configs or paste.gg link here!
```https://paste.gg/p/anonymous/e9464d2189a14e7f9a63f355d6aebd59

### Paper version

12:50:11 | You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.12:50:11 | Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'12:50:13 | Loaded 7 recipes12:50:13 | Starting minecraft server version 1.20.112:50:13 | Loading properties12:50:13 | This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)12:50:14 | Server Ping Player Sample Count: 1212:50:14 | Using 4 threads for Netty based IO

### Other

no

**Comment by lynxplay** [comment]
1.20.1 is no longer supported. Additionally, when defining the api-version in your plugin.yml, make sure to quote it.
`api-version: "1.20"`

**Comment by juwonjun** [comment]
omg... your god
