### ISSUE TITLE
ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder

### ISSUE THREAD

**Issue by servicomcr** [PaperSpigot/Paper#11517]
### Expected behavior

experiencing the same error too.  (https://github.com/PaperMC/Paper/issues/11136)

No errors in console.

[05:27:15 INFO]: Checking version, please wait...
[05:27:15 INFO]: Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*

You are running the latest version

### Observed/Actual behavior

n/A

### Steps/models to reproduce

[05:22:53 ERROR]: [ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder] Failed to save entity data (10,-995) in world 'survival'
net.minecraft.ReportedException: Saving entity NBT
at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2594) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:2407) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.world.entity.Entity.saveAsPassenger(Entity.java:2393) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.world.entity.Entity.save(Entity.java:2423) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.saveEntityChunk0(ChunkEntitySlices.java:116) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.saveEntityChunk(ChunkEntitySlices.java:94) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.save(ChunkEntitySlices.java:146) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.saveEntities(NewChunkHolder.java:1843) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.save(NewChunkHolder.java:1714) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.autoSave(ChunkHolderManager.java:245) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:413) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:401) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:415) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1843) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Value must be within range [1;99]: 108
at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar:?]
at net.minecraft.world.item.ItemStack.save(ItemStack.java:624) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.world.entity.item.ItemEntity.addAdditionalSaveData(ItemEntity.java:435) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.world.entity.Entity.addAdditionalSaveData(Entity.java:2764) ~[purpur-1.21.jar:1.21-2284-4e55e26]
at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2537) ~[purpur-1.21.jar:1.21-2284-4e55e26]
... 19 more

### Plugin and Datapack List

N/a

### Paper version

[05:27:15 INFO]: Checking version, please wait...
[05:27:15 INFO]: Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*

**Comment by lynxplay** [comment]
As with the other issue, there is nothing we can do here beyond instructing you to find out what plugin/datapack emitted an oversized itemstack.
