### ISSUE TITLE
java.lang.IllegalStateException: Failed to bind to port 1.21.3 error

### ISSUE THREAD

**Issue by Sonic3Modder** [PaperSpigot/Paper#11643]
### Stack trace

`[16:07:37] [ServerMain/INFO]: [bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS; Azul Systems, Inc. Zulu21.34+19-CA) on Linux 6.6.31+rpt-rpi-2712 (aarch64)

[16:07:37] [ServerMain/INFO]: [bootstrap] Loading Paper 1.21.3-46-master@f8e2a67 (2024-11-21T17:43:15Z) for Minecraft 1.21.3

[16:07:37] [ServerMain/INFO]: [PluginInitializerManager] Initializing plugins...

[16:07:38] [ServerMain/INFO]: [PluginInitializerManager] Initialized 2 plugins

[16:07:38] [ServerMain/INFO]: [PluginInitializerManager] Bukkit plugins (2):

 - FeatherMorph (1.4.0.alpha2), ModObserverPlugin (2.0.0)

[16:07:45] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]

[16:07:51] [ServerMain/INFO]: Loaded 1337 recipes

[16:07:51] [ServerMain/INFO]: Loaded 1448 advancements

[16:07:52] [Server thread/INFO]: Starting minecraft server version 1.21.3

[16:07:52] [Server thread/INFO]: Loading properties

[16:07:52] [Server thread/INFO]: This server is running Paper version 1.21.3-46-master@f8e2a67 (2024-11-21T17:43:15Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

[16:07:53] [Server thread/INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling

[16:07:53] [Server thread/INFO]: Server P[16:07:59] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]

[16:08:03] [ServerMain/INFO]: Loaded 1337 recipes

[16:08:03] [ServerMain/INFO]: Loaded 1448 advancements

[16:08:03] [Server thread/INFO]: Starting minecraft server version 1.21.3

[16:08:03] [Server thread/INFO]: Loading properties

[16:08:03] [Server thread/INFO]: This server is running Paper version 1.21.3-46-master@f8e2a67 (2024-11-21T17:43:15Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

[16:08:04] [Server thread/INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling

[16:08:04] [Server thread/INFO]: Server Ping Player Sample Count: 12

[16:08:04] [Server thread/INFO]: Using 4 threads for Netty based IO

[16:08:05] [Server thread/INFO]: [MoonriseCommon] Paper is using 1 worker threads, 1 I/O threads

[16:08:05] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using population gen parallelism: true

[16:08:06] [Server thread/INFO]: Default game type: CREATIVE

[16:08:06] [Server thread/INFO]: Generating keypair

[16:08:06] [Server thread/INFO]: Starting Minecraft server on 192.168.40.40:25565

[16:08:06] [Server thread/INFO]: Using epoll channel type

[16:08:06] [Server thread/INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.

[16:08:06] [Server thread/INFO]: Paper: Using OpenSSL 3.x.x (Linux aarch64) cipher from Velocity.

[16:08:06] [Server thread/WARN]: **** FAILED TO BIND TO PORT!

[16:08:06] [Server thread/WARN]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Cannot assign requested address

[16:08:06] [Server thread/WARN]: Perhaps a server is already running on that port?

[16:08:06] [Server thread/ERROR]: Encountered an unexpected exception

java.lang.IllegalStateException: Failed to bind to port

	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:283) ~[paper-1.21.3.jar:1.21.3-46-f8e2a67]

	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-46-f8e2a67]

	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-46-f8e2a67]

	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Cannot assign requested address

[16:08:06] [Server thread/ERROR]: This crash report has been saved to: /opt/minecraft/myserver/crash-reports/crash-2024-11-21_16.08.06-server.txt

[16:08:06] [Server thread/INFO]: Stopping server

[16:08:06] [Server thread/INFO]: Saving players

[16:08:06] [Server thread/INFO]: Saving worlds

[16:08:06] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

[16:08:06] [Server thread/INFO]: Waiting for I/O tasks to complete...

[16:08:06] [Server thread/INFO]: All I/O tasks to complete

[16:08:06] [Server thread/INFO]: [MoonriseCommon] Awaiting termination of worker pool for up to 60s...

[16:08:06] [Server thread/INFO]: [MoonriseCommon] Awaiting termination of I/O pool for up to 60s...`

what does this mean, also im using paper for 1.21.3

### Plugin and Datapack List

feathermorph
modobserver

### Paper version

1.21.3

**Comment by lynxplay** [comment]
Or the ip defined in the server.properties is no longer valid (it usually is just empty anyway).
But as said, seek help on the discord for this.

**Comment by Sonic3Modder** [comment]
yeah i make sure that the port is always 25565, and idk if this is a issue but i ssh into a pi 5 for this, and i'm using a minecraft server launcher of my design

**Comment by lynxplay** [comment]
Yea, please check your `server-ip` setting in the server.properties.
Generally you want this empty unless you have a specific ip you want to bind to.
