### ISSUE TITLE
Crash after updating to 1.21.3 from 1.21.1

### ISSUE THREAD

**Issue by esin** [PaperSpigot/Paper#11665]
### Stack trace

Hey

```
[14:07:58 INFO]: esin0 joined the game
[14:07:58 ERROR]: Couldn't place player in world
java.lang.ArrayIndexOutOfBoundsException: Index 35 out of bounds for length 35
        at ca.spottedleaf.moonrise.patches.chunk_system.util.ParallelSearchRadiusIteration.getSearchIteration(ParallelSearchRadiusIteration.java:26) ~[paper-1.21.3.jar:1.21.3-
60-cf956ac]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.update(RegionizedPlayerChunkLoader.java:982) ~[paper-1.21.3.ja
r:1.21.3-60-cf956ac]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.add(RegionizedPlayerChunkLoader.java:891) ~[paper-1.21.3.jar:1
.21.3-60-cf956ac]
        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.addPlayer(RegionizedPlayerChunkLoader.java:196) ~[paper-1.21.3.jar:1.21.3-60-cf956ac
]
        at ca.spottedleaf.moonrise.common.util.ChunkSystem.addPlayerToDistanceMaps(ChunkSystem.java:166) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.level.ChunkMap.updatePlayerStatus(ChunkMap.java:816) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:925) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:396) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.3.jar:1.
21.3-60-cf956ac]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.3.jar:1.21.3-60-
cf956ac]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.3.jar:1.21.3-60-
cf956ac]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1577) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1554) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1547) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1498) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1508) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1344) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-60-cf956ac]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Plugin and Datapack List

Removed all plugins before update

### Actions to reproduce (if known)

Just downloaded server-1.21.3-build60 from https://papermc.io/downloads/paper
Stop server, then run server with new jar

### Paper version

1.21.3-60-cf956ac (MC: 1.21.3)

**Comment by electronicboy** [comment]
from what I've seen of this error thus far, and a quick scan of the code, your servers view distance is improperly configured

**Comment by electronicboy** [comment]
Yes, vanilla limit is 21

**Comment by esin** [comment]
Thank you!

BTW, after setting params:
```
simulation-distance=32
view-distance=32
```
server runs perfectly
