### ISSUE TITLE
Bad ABI Compatible crash my plugin

### ISSUE THREAD

**Issue by MrXiaoM** [PaperSpigot/Paper#11726]
### Stack trace

```
[23:05:49 ERROR]: Error occurred while enabling MMOi18n v1.0.0 (Is it up to date?)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    top/mrxiaom/mmoi18n/placeholder/providers/ShieldPatternDataProvider.list(Lnet/Indyuce/mmoitems/stat/data/ShieldPatternData;)Ljava/lang/String; @47: invokestatic
  Reason:
    Type 'org/bukkit/block/banner/PatternType' (current frame, stack[2]) is not assignable to 'java/lang/Enum'
  Current Frame:
    bci: @47
    flags: { }
    locals: { 'top/mrxiaom/mmoi18n/placeholder/providers/ShieldPatternDataProvider', 'net/Indyuce/mmoitems/stat/data/ShieldPatternData', 'java/util/List', 'java/util/Iterator', 'org/bukkit/block/banner/Pattern' }
    stack: { 'java/util/List', 'org/bukkit/ChatColor', 'org/bukkit/block/banner/PatternType' }
  Bytecode:
    0000000: bb00 3659 b700 374d 2bb6 003d b900 4301
    0000010: 004e 2db9 0049 0100 9900 332d b900 4d01
    0000020: 00c0 004f 3a04 2cb2 0055 1904 b600 59b8
    0000030: 005f b200 5519 04b6 0063 b800 5fba 006f
    0000040: 0000 b900 7202 0057 a7ff ca12 742c b800
    0000050: 7ab0
  Stackmap Table:
    append_frame(@18,Object[#63],Object[#69])
    chop_frame(@75,1)

        at MMOi18n-1.0.0.jar/top.mrxiaom.mmoi18n.placeholder.IProvider.createAllProviders(IProvider.java:34) ~[MMOi18n-1.0.0.jar:?]
        at MMOi18n-1.0.0.jar/top.mrxiaom.mmoi18n.Translation.init(Translation.java:101) ~[MMOi18n-1.0.0.jar:?]
        at MMOi18n-1.0.0.jar/top.mrxiaom.mmoi18n.PluginMain.onEnable(PluginMain.java:43) ~[MMOi18n-1.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Plugin and Datapack List

https://github.com/MrXiaoM/MMOi18n

### Actions to reproduce (if known)

Directly reason:
| paper-api | spigot-api |
| --- | --- |
| `interface PatternType` | `enum PatternType` |

You guys have made a *good* job :)

### Paper version

```
[23:21:50 INFO]: This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-130-b1b5d4c (MC: 1.21)
```

**Comment by electronicboy** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/46b6d445c363be17953869fe9fada59655b778a4#src%2Fmain%2Fjava%2Forg%2Fbukkit%2Fblock%2Fbanner%2FPatternType.java

The enum > interface change was done by spigot in their 1.21 API builds as part of their experimental changes, in which they've been warning against treating this stuff as an Enum for the past few releases now, I'm not sure if there is any paper specific issues here, did we disable one of their stupidly expensive mitigations by default? I know that there was an enum rewrite which was so expensive that even spigot put that one behind a configuration option
