### ISSUE TITLE
[1.21.4] Brigadier Argument of a STRUCTURE resource sends invalid packets

### ISSUE THREAD

**Issue by Strokkur424** [PaperSpigot/Paper#11766]
### Expected behavior

When creating a Brigadier command tree using Paper's Command API, when declaring a `ArgumentTypes.resource(RegistryKey.STRUCTURE)` argument, it should not kick a player on join because of a missing registry.

### Observed/Actual behavior

The client gets kicked off the server. It seems to not be a server-sided kick, but instead a client-sided kick. The client gets a `Connection Lost` screen with a `Network Protocol Error` exception. The client's console also throws the following stacktrace:
```ruby
[13:24:21] [Render thread/ERROR]: Failed to handle packet ace@9ecff4a, disconnecting
java.lang.IllegalStateException: Registry minecraft:worldgen/structure not found
	at jt$a.g(SourceFile:116) ~[minecraft-1.21.4-client.jar:?]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at jt$a.d(SourceFile:116) ~[minecraft-1.21.4-client.jar:?]
	at fw.<init>(SourceFile:49) ~[minecraft-1.21.4-client.jar:?]
	at fw$a$a.a(SourceFile:127) ~[minecraft-1.21.4-client.jar:?]
	at fw$a$a.b(SourceFile:118) ~[minecraft-1.21.4-client.jar:?]
	at ace$a.a(SourceFile:170) ~[minecraft-1.21.4-client.jar:?]
	at ace$d.a(SourceFile:336) ~[minecraft-1.21.4-client.jar:?]
	at ace$d.a(SourceFile:348) ~[minecraft-1.21.4-client.jar:?]
	at ace$d.a(SourceFile:348) ~[minecraft-1.21.4-client.jar:?]
	at ace.a(SourceFile:266) ~[minecraft-1.21.4-client.jar:?]
	at ggb.a(SourceFile:1534) ~[minecraft-1.21.4-client.jar:?]
	at ace.a(SourceFile:262) ~[minecraft-1.21.4-client.jar:?]
	at ace.a(SourceFile:39) ~[minecraft-1.21.4-client.jar:?]
	at yz.a(SourceFile:27) ~[minecraft-1.21.4-client.jar:?]
	at bra.d(SourceFile:164) [minecraft-1.21.4-client.jar:?]
	at bre.d(SourceFile:23) [minecraft-1.21.4-client.jar:?]
	at bra.B(SourceFile:138) [minecraft-1.21.4-client.jar:?]
	at bra.bA(SourceFile:123) [minecraft-1.21.4-client.jar:?]
	at flk.c(SourceFile:1296) [minecraft-1.21.4-client.jar:?]
	at flk.f(SourceFile:922) [minecraft-1.21.4-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:267) [minecraft-1.21.4-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[13:24:21] [Render thread/WARN]: Client disconnected with reason: Network Protocol Error
```

### Steps/models to reproduce

Create a fresh plugin, and add the following code to your main class file:
```java
package your.package.name;

import com.mojang.brigadier.tree.LiteralCommandNode;
import io.papermc.paper.command.brigadier.CommandSourceStack;
import io.papermc.paper.command.brigadier.Commands;
import io.papermc.paper.command.brigadier.argument.ArgumentTypes;
import io.papermc.paper.plugin.lifecycle.event.types.LifecycleEvents;
import io.papermc.paper.registry.RegistryKey;
import org.bukkit.plugin.java.JavaPlugin;

@SuppressWarnings("UnstableApiUsage")
public final class PluginMain extends JavaPlugin {

    @Override
    public void onEnable() {
        this.getLifecycleManager().registerEventHandler(LifecycleEvents.COMMANDS, event -> {
            final LiteralCommandNode<CommandSourceStack> node = Commands.literal("teststructures")
                .then(Commands.argument("value", ArgumentTypes.resource(RegistryKey.STRUCTURE)))
                .build();

            event.registrar().register(node);
        });
    }
}
```

When starting the server, there is no issues and the command seems to be registered correctly, though no players are able of joining, due to the mentioned missing client-side registry.

### Plugin and Datapack List

```ruby
pl
[13:31:06 INFO]: Server Plugins (1):
[13:31:06 INFO]: Paper Plugins:
[13:31:06 INFO]:  - DocsTest
```

(DocsTest is the plugin I've discovered this issue on).

There are no additional data packs. This is a fresh server.
```ruby
datapack list
[13:32:07 INFO]: There are 3 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [paper (built-in)]
[13:32:07 INFO]: There are no more data packs available
```

### Paper version

```ruby
version
[13:32:47 INFO]: Checking version, please wait...
[13:32:47 INFO]: This server is running Paper version 1.21.4-15-master@bb76819 (2024-12-15T09:48:21Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
```

### Other

This issue does not happen if you replace `ArgumentTypes.resource(...)` with `Argumenttypes.resourceKey(...)`

In fact, the tab completions work flawlessly in that case:
![Image](https://github.com/user-attachments/assets/b414318c-53de-4f4c-92f1-fb283660c688)

The client console also display nothing out of the ordinary when doing that.

**Comment by Strokkur424** [comment]
This does not happen with any other `ArgumentTypes.resource(...)` or `ArgumentTypes.resourceKey(...)` argument. I have them all tested. Only `RegistryKey.STRUCTURE` in combination with`ArgumentTypes.resource(...)` has this issue.

Again, since the error is actually thrown on the client, I am not 100% certain this is a Paper issue, but it might still be worthwhile to look into it, mainly as the `resourceKey(...)` variant, which should visually have the same tab completion, does not behave this way.

**Comment by Machine-Maker** [comment]
Yeah, this is a vanilla issue. I think it's been reported before, maybe here or on discord. The cause is that the structure registry isn't synced with the client. The client then only has access to the static layer of registries (the builtins like Item, Block, etc) and the synced registries. So the `resource` argument type will only work with those registries. We can add a check on the server side that throws if you try to create one that will fail on the client.

**Comment by Strokkur424** [comment]
Yeah, I think that would be good. I am definitely noting that in the docs, but it would be worthwhile to also make some JavaDocs and maybe some exception if you try to ignore it regardless
