### ISSUE TITLE
The paperspigot jar is not compiling

### ISSUE THREAD

**Issue by imBuzz** [PaperSpigot/Paper#6608]
### Expected behavior

Hi! Why i'm getting this error when i try to compile paper 1.8.8 ?

$ ./build.sh
Downloading unmapped vanilla jar...
Applying class mappings...
Exception in thread "main" java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:436)
        at net.md_5.ss.repo.RuntimeRepo.getClass0(RuntimeRepo.java:25)
        at net.md_5.ss.repo.ClassRepo.getClass(ClassRepo.java:22)
        at net.md_5.ss.repo.AggregateRepo.getClass0(AggregateRepo.java:30)
        at net.md_5.ss.repo.ClassRepo.getClass(ClassRepo.java:22)
        at net.md_5.ss.model.ClassInfo$1.apply(ClassInfo.java:97)
        at net.md_5.ss.model.ClassInfo$1.apply(ClassInfo.java:92)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at net.md_5.ss.remapper.EnhancedRemapper.findFieldDeclarer(EnhancedRemapper.java:45)
        at net.md_5.ss.remapper.EnhancedRemapper.mapFieldName(EnhancedRemapper.java:107)
        at net.md_5.ss.remapper.ClassRemapper.visitField(ClassRemapper.java:71)
        at org.objectweb.asm.ClassReader.readField(ClassReader.java:768)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:689)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
        at net.md_5.ss.model.ClassInfo.remap(ClassInfo.java:120)
        at net.md_5.ss.SpecialSource.map(SpecialSource.java:96)
        at net.md_5.ss.SpecialSource.main(SpecialSource.java:44)
Failed to apply class mappings.

### Observed/Actual behavior

---

### Steps/models to reproduce

Try to execute ./build.sh from the bash on IntellJ

### Plugin list

---

### Paper version

Version: GitHub cloned repo 1.8.8

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by electronicboy** [comment]
1.8.8 hasn't been supported in years, probs wrong java version.
