### ISSUE TITLE
updating 1.12.2 region creates endless loop / fills up HD with .backup files

### ISSUE THREAD

**Issue by terbin** [PaperSpigot/Paper#6718]
### Stack trace

```
[World upgrader thread for world world_the_end #4/WARN]: Backing up regionfile "xxx\world_the_end\DIM1\region\r.-3.-1.mca" to xxx\world_the_end\DIM1\region\r.-3.-1.mca.4295739377041195202.backup
[World upgrader thread for world world_the_end #4/WARN]: Backed up the regionfile to xxx\world_the_end\DIM1\region\r.-3.-1.mca.4295739377041195202.backup
[Server thread/INFO]: [io.papermc.paper.world.ThreadedWorldUpgrader] 98,98% completed (92237 / 93184 chunks)...
[World upgrader thread for world world_the_end #4/INFO]: Starting summary of changes for regionfile xxx\world_the_end\DIM1\region\r.-3.-1.mca
[World upgrader thread for world world_the_end #4/INFO]: End of change summary for regionfile xxx\world_the_end\DIM1\region\r.-3.-1.mca
[World upgrader thread for world world_the_end #4/INFO]: Successfully wrote new header to disk for regionfile xxx\world_the_end\DIM1\region\r.-3.-1.mca
[World upgrader thread for world world_the_end #4/ERROR]: Attempting to read chunk data at [-83, -30] but got chunk data for [45, 34] instead! Attempting regionfile recalculation for regionfile xxx\world_the_end\DIM1\region\r.-3.-1.mca
[World upgrader thread for world world_the_end #4/WARN]: Corrupt regionfile header detected! Attempting to re-calculate header offsets for regionfile xxx\world_the_end\DIM1\region\r.-3.-1.mca
java.lang.Throwable: null
	at net.minecraft.world.level.chunk.storage.RegionFile.recalculateHeader(RegionFile.java:137) ~[patched_1.17.1.jar:git-Paper-302]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:219) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:221) ~[app:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:192) ~[app:?]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.read(ChunkStorage.java:116) ~[app:?]
	at io.papermc.paper.world.ThreadedWorldUpgrader$ConvertTask.run(ThreadedWorldUpgrader.java:169) ~[patched_1.17.1.jar:git-Paper-302]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### Plugin and Datapack List

no plugins or datapacks

### Actions to reproduce (if known)

1. put the attached End region file in world_the_end/DIM1/region
2. start paper 1.17.1 with the --forceUpgrade parameter

Info: this region loads in Paper 1.12.2 Build 1618 and can be visited with a client

[r.-3.-1.mca.zip](https://github.com/PaperMC/Paper/files/7281141/r.-3.-1.mca.zip)

### Paper version

Paper 1.17.1 Build 302

### Other

While it might not be feasible to write a fix for this problem with the region file, it seems dangerous to have the harddrive fill up with .backup files until there is no space left.

**Comment by Prof-Bloodstone** [comment]
Every chunk in this region file seems corrupted, confirmed with Amulet:
```
>>> {k: v for (k, v) in amulet.level.formats.anvil_world.region.AnvilRegion("r.-3.-1.mca").get_chunk_data(-83+32*3, -30+32)['Level'].items() if k in {'zPos', 'xPos'}}
{'zPos': 34, 'xPos': 45}
```

This is an issue in Paper's world upgrade system (CC: @Spottedleaf). Spigot spams a lot of warnings, but _seems_ to upgrade the chunks:
```
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -11] has invalid position [32, 53]
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -11] has invalid position [32, 53]
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -11] has invalid position [32, 53]
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -10] has invalid position [32, 54]
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -10] has invalid position [32, 54]
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -10] has invalid position [32, 54]
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -9] has invalid position [32, 55]
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -9] has invalid position [32, 55]
[23:32:21] [pool-4-thread-3/WARN]: Chunk [-96, -9] has invalid position [32, 55]
```

**Comment by Spottedleaf** [comment]
I never thought I'd see the day where a chunk's raw data had been copied from one regionfile to another. There's a lot of problems doing it that way. 

One of them being that it's impossible for the recalculator to tell if the chunk is intended to be there or not. It's a pretty big deal actually - the recalculator was designed to directly fix chunk relocation issues. After I made regionfiles reliable to write to around 1.13, and after Mojang did the same later, the kinds of regionfile corruption _changed_. The new writing order made it far far more likely that issues arose as chunk relocations (I would say it's the _most likely corruption_)

The other problem is the game stores absolute positions for basically everything in the chunk (entity, tile entity, other misc data). Some things are exempt, but most aren't. The old code in 1.12 to migrate this doesn't exist anymore, and wouldn't cover everything anyways. So, directly copying data is going to cause the positions to be wrong - which will result in missing tile entity data, incorrect next tick data...

So I'm going to update it to simply delete the data if it is found to locate outside of the regionfile. If you want to avoid that, use 1.12 to load and write the whole regionfile, or edit the corrupt chunks so that their positions match. As always, the backup it creates will still have the data as it was in the original (corrupt or not).

**Comment by terbin** [comment]
This has happened a few times because of region file renaming.
Thank you for your time and for the quick answer Spottedleaf. Much appreciated.
