### ISSUE TITLE
Don't know if this is important

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6740]
### Stack trace

```
[2021-10-07 09:29:19 | Profile Lookup Executor #0] Couldn't look up profile properties for com.mojang.authlib.GameProfile@fcbcf24[id=3d187d82-f441-3d03-88d0-bb01d017a829,name=koter_1,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:124) ~[server.jar:git-Paper-279]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:98) ~[server.jar:git-Paper-279]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:193) ~[server.jar:git-Paper-279]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[server.jar:git-Paper-279]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[server.jar:git-Paper-279]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[server.jar:git-Paper-279]
	at net.minecraft.world.level.block.entity.TileEntitySkull.lambda$updateGameprofile$2(TileEntitySkull.java:157) ~[server.jar:git-Paper-279]
	at net.minecraft.SystemUtils.a(SystemUtils.java:391) ~[server.jar:git-Paper-279]
	at net.minecraft.world.level.block.entity.TileEntitySkull.lambda$updateGameprofile$5(TileEntitySkull.java:154) ~[server.jar:git-Paper-279]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:976) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1454) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1060) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:788) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:723) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1676) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:140) ~[server.jar:git-Paper-279]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:103) ~[server.jar:git-Paper-279]
	... 11 more

```

### Plugin and Datapack List

dynmap, Essentials, EssentialsSpawn, LuckPerms, Orebfuscator, ProtocolLib, SkinsRestorer, Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known)

This happened unexpectedly, only once and there's nothing before or after this stacktrace (e.g. no ping, no player connection, etc..)

### Paper version

This server is running Paper version git-Paper-279 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6de48db)
You are 34 version(s) behind
Previous version: git-Paper-276 (MC: 1.17.1)

**Comment by electronicboy** [comment]
your network connection to mojangs servers timed out, not a paper issue

**Comment by molor** [comment]
But server is in offline mode, why it is trying to authenticaticate player?

**Comment by electronicboy** [comment]
It's not.

**Comment by MiniDigger** [comment]
(it tried to load a player texture for a skull)

**Comment by molor** [comment]
Maybe we can reduce this stacktrace by catching this exception to 1-2 red error/yellow warning lines please?
Today 5-15 players played on my server fine while other 3-5 was trying to connect and server log file gets flooded with 400+ lines of this :/

**Comment by electronicboy** [comment]
No
