### ISSUE TITLE
calls to Container#getInventory() throws error when obtained from nested container from BlockStateMeta

### ISSUE THREAD

**Issue by TauCu** [PaperSpigot/Paper#6745]
### Expected behavior

calls to Container#getInventory to return the inventory of the container, within the container

### Observed/Actual behavior

calling Container#getInventory throws an error:
`[21:27:21 ERROR]: Could not pass event PlayerInteractEvent to CreativeBugFixes v0.0.7
java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getHandle()" because "this.world" is null
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getWorldHandle(CraftBlockState.java:61) ~[patched_1.17.1.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_17_R1.block.CraftChest.getInventory(CraftChest.java:41) ~[patched_1.17.1.jar:git-Paper-318]
        at me.taucu.minevictus.creativebugfixes.modules.nbtcontrol.NBTControl.doContainerLogic(NBTControl.java:221) ~[CreativeBugFixes-0.0.7.jar:?]
        at me.taucu.minevictus.creativebugfixes.modules.nbtcontrol.NBTControl.doContainerLogic(NBTControl.java:229) ~[CreativeBugFixes-0.0.7.jar:?]
        at me.taucu.minevictus.creativebugfixes.modules.nbtcontrol.NBTControl.onPlayerInteract(NBTControl.java:353) ~[CreativeBugFixes-0.0.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor315.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-318]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-318]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[patched_1.17.1.jar:git-Paper-318]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1810) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1367) ~[patched_1.17.1.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1278) ~[patched_1.17.1.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]`

### Steps/models to reproduce

1. Create the nested container
    Place a shulker box and put a chest in the shulker that has an item in it.
2. Attempt to get a reference to the inventory of the nested container.

the following is the code producing this error:
```
    public boolean doContainerLogic(Player player, ItemStack stack) {
        if (stack != null) {
            ItemMeta meta = stack.getItemMeta();
            if (meta instanceof BlockStateMeta) {
                BlockStateMeta bsm = (BlockStateMeta) meta;
                BlockState state = bsm.getBlockState();
                if (state instanceof Container) {
                    inventoryActionLimiter.actionAndPenalty(player, interactActionMult / 16);
                    Container container = (Container) state;
/* 221 */           Inventory inv = container.getInventory();
                    ItemStack[] stacks = inv.getContents();
                    boolean modify = false;
                    for (int i = 0; i < stacks.length; i++) {
                        if (doItemLogic(player, stacks[i])) {
                            stacks[i].setAmount(0);
                            modify = true;
                        }
                        if (doContainerLogic(player, stacks[i])) { // nested logic for subcontainers
                            modify = true;
                        }
                    }
                    if (modify) {
                        state.update();
                        bsm.setBlockState(container);
                        stack.setItemMeta(bsm);
                        player.updateInventory();
                    }
                    return modify;
                }
            }
        }
        return false;
    }
```

### Plugin and Datapack List

My plugin.

Vanilla (built-in)
file/bukkit (world)

### Paper version

[21:33:43 INFO]: Checking version, please wait...
[21:33:44 INFO]: This server is running Paper version git-Paper-318 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 0d1e187)
You are running the latest version

**Comment by electronicboy** [comment]
Use getSnapshotInventory, I'd imagine, the chest is not in the world, thus has no real inventory attached to it as such

**Comment by Machine-Maker** [comment]
I think this is still a valid issue, the javadocs say getInventory should return the snapshot inventory if its not placed, not error out.
