### ISSUE TITLE
Server crashing randomly, fastutils

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#6758]
### Stack trace

```
[08:24:12] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1638) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper.jar:git-Paper-"4a0d935"]
    at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
    at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:668) ~[paper.jar:git-Paper-"4a0d935"]
    at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:950) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:2047) ~[app:?]
    at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:2070) ~[app:?]
    at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1082) ~[app:?]
    at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:934) ~[app:?]
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:731) ~[app:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[paper.jar:git-Paper-"4a0d935"]
    ... 5 more
[08:24:12] [Server thread/ERROR]:     Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
    at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:668) ~[paper.jar:git-Paper-"4a0d935"]
    at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:950) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:2047) ~[app:?]
    at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:2070) ~[app:?]
    at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1082) ~[app:?]
    at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:934) ~[app:?]
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:731) ~[app:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[paper.jar:git-Paper-"4a0d935"]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper.jar:git-Paper-"4a0d935"]
    at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### Plugin and Datapack List

LuckPerms v5.3.47 me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin [Luck], 
WorldEdit v7.2.6+4b2d1e7 com.sk89q.worldedit.bukkit.WorldEditPlugin [], 
OpenInv v4.1.8 com.lishid.openinv.OpenInv [lishid, Jikoo, ShadowRanger], 
PlaceholderAPI v2.10.9 me.clip.placeholderapi.PlaceholderAPIPlugin [HelpChat], 
PlugMan v2.1.6 com.rylinaux.plugman.PlugMan [rylinaux], 
spark v1.6.0 me.lucko.spark.bukkit.BukkitSparkPlugin [Luck], 
BuycraftX v12.0.7 net.buycraft.plugin.bukkit.BuycraftPlugin [Buycraft], 
FarmLimiter v1.3.1 com.gmail.filoghost.farmlimiter.FarmLimiter [filoghost], 
Votifier v2.7.1 com.vexsoftware.votifier.NuVotifierBukkit [Ichbinjoe, blakeman8192, Kramer, tuxed],
ProtocolLib v4.7.1-SNAPSHOT-b530 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], 
BungeeGuard v1.0-SNAPSHOT me.lucko.bungeeguard.backend.BungeeGuardBackendPlugin [], 
NoteBlockAPI v1.6.2-SNAPSHOT com.xxmicloxx.NoteBlockAPI.NoteBlockAPI [xxmicloxx, michidk, koca2000, Luck], 
SuperVanish v6.1.8 de.myzelyam.supervanish.SuperVanish [MyzelYam], 
CalendarEvents v2.3.0 me.nikl.calendarevents.CalendarEvents [Nikl], 
PlayerParticles v7.20 dev.esophose.playerparticles.PlayerParticles [Esophose],
BungeeTabListPlus v3.4.3 codecrafter47.bungeetablistplus.BukkitPlugin [CodeCrafter47], 
LiteBans v2.7.5 litebans.BukkitPlugin [Ruan]

No datapacks

### Actions to reproduce (if known)

Occurs seemingly at random, about once a week. The server is an SMP with a bungee cord and about 15 players.

### Paper version

 This server is running Paper version git-Paper-"4a0d935" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 4a0d935)
You are running the latest version

**Comment by Chew** [comment]
Possibly related to #6438?

**Comment by electronicboy** [comment]
Closing, every instance of this has been traced down to plugins messing with internals; This is pretty much FastUtils equivalent of a ConcurrentModificationException, the collection impacted here is only ever mutated on the main thread behind async catchers, so, I don't see how this could be Paper
