### ISSUE TITLE
Maybe BlockPlaceEvent doesn't cancelled completely

### ISSUE THREAD

**Issue by molor** [PaperSpigot/Paper#6778]
### Expected behavior

I'm still connected to the server and can play

### Observed/Actual behavior

I'm getting kicked because of `Packet processing error`

### Steps/models to reproduce

1. First, in CREATIVE mode, place a sign in the world, write something and CTRL+MIDDLE_MOUSE on it to grab block with NBT data
2. Run server with BlockPlaceEvent handler like this:
```java
public class TestEvent implements Listener {
	private int t;

	public TestEvent() {
		t = 0;
	}

	@EventHandler (priority = EventPriority.NORMAL)
	public void blockPlaceEvent(BlockPlaceEvent event) {
		if (event.isCancelled()) {
			return;
		}

		if (++ t < 3) {
			event.setCancelled(true);
		}
	}
}
```
3. Now, switch to SURVIVAL, try to place the sign with NBT on any block (and remember this block), then try place it to any other block
4. Switch to CREATIVE and place this sign again on FIRST remembered block
5. Get the `Packet processing error`
```
[2021-10-15 13:06:47 | Server thread] Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseItem@76e5d9f7 for DevelopmentPreview[/127.0.0.1:64888]
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.entity.TileEntitySign.a(java.util.UUID)" because "sign" is null
	at net.minecraft.server.level.EntityPlayer.openSign(EntityPlayer.java:1446) ~[server.jar:git-Paper-296]
	at net.minecraft.world.item.ItemStack.placeItem(ItemStack.java:445) ~[server.jar:git-Paper-296]
	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:601) ~[server.jar:git-Paper-296]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1810) ~[server.jar:git-Paper-296]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[server.jar:git-Paper-296]
	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9) ~[server.jar:git-Paper-296]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[server.jar:git-Paper-296]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server.jar:git-Paper-296]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[server.jar:git-Paper-296]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[server.jar:git-Paper-296]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[server.jar:git-Paper-296]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[server.jar:git-Paper-296]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[server.jar:git-Paper-296]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[server.jar:git-Paper-296]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[server.jar:git-Paper-296]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[server.jar:git-Paper-296]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367) ~[server.jar:git-Paper-296]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278) ~[server.jar:git-Paper-296]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[server.jar:git-Paper-296]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Plugin and Datapack List

Plugins (1): TestPlugin
There are 2 data packs enabled: [vanilla (built-in)], [file/Bukkit (world)]

### Paper version

This server is running Paper version git-Paper-296 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 45c4f90)
You are 31 version(s) behind

**Comment by electronicboy** [comment]
Confirmed that this is a bug on the latest version, please actually read the acknowledgements in the future and provide a report from the *latest* server build

**Comment by lynxplay** [comment]
Can also confirm that this issue can be reproduced on `3259-Spigot-dc75aca-11c9299` (tho the player connection is not closed, an exception is thrown nonetheless).
