### ISSUE TITLE
ERROR: Could not load 'plugins\PexTabCompleter.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by RealSting** [PaperSpigot/Paper#6849]
### Expected behavior

no errors expected

### Observed/Actual behavior

C:\Users\user\Documents\buildtools>java -Xms2G -Xmx2G -jar paper-1.17.1-353.jar --nogui
System Info: Java 16 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[21:11:33 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:11:33 INFO]: Reloading ResourceManager: Default, bukkit
[21:11:34 INFO]: Loaded 7 recipes
[21:11:36 INFO]: Starting minecraft server version 1.17.1
[21:11:36 INFO]: Loading properties
[21:11:36 INFO]: This server is running Paper version git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)
[21:11:36 INFO]: Server Ping Player Sample Count: 12
[21:11:36 INFO]: Using 4 threads for Netty based IO
[21:11:36 INFO]: Default game type: SURVIVAL
[21:11:36 INFO]: Generating keypair
[21:11:36 INFO]: Starting Minecraft server on *:25565
[21:11:36 INFO]: Using default channel type
[21:11:36 INFO]: Paper: Using Java 11 compression from Velocity.
[21:11:36 INFO]: Paper: Using Java cipher from Velocity.

[21:11:36 ERROR]: **Could not load 'plugins\PexTabCompleter.jar' in folder 'plugins'**

org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [PermissionsEx]. Please download and install these plugins to run 'PexTabCompleter'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:290) ~[patched_1.17.1.jar:git-Paper-353]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[patched_1.17.1.jar:git-Paper-353]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-353]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[21:11:37 INFO]: [Vault] Loading Vault v1.7.3-b131
[21:11:37 INFO]: [ProtocolLib] Loading ProtocolLib v4.7.0
[21:11:38 INFO]: [Essentials] Loading Essentials v2.19.0
[21:11:38 INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.19.0
[21:11:38 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:11:38 INFO]: [Vault] Enabling Vault v1.7.3-b131
[21:11:38 WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.19.0 which is not a depend, softdepend or loadbefore of this plugin.
[21:11:38 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[21:11:38 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[21:11:38 INFO]: [Vault] Enabled Version 1.7.3-b131
[21:11:38 INFO]: [ProtocolLib] Enabling ProtocolLib v4.7.0
[21:11:38 INFO]: [ProtocolLib] Started structure compiler thread.
[21:11:38 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[21:11:38 WARN]: The server will make no attempt to authenticate usernames. Beware.
[21:11:38 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[21:11:38 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[21:11:38 INFO]: Preparing level "world"
[21:11:39 INFO]: Preparing start region for dimension minecraft:overworld
[21:11:39 INFO]: Time elapsed: 326 ms
[21:11:39 INFO]: Preparing start region for dimension minecraft:the_nether
[21:11:39 INFO]: Time elapsed: 117 ms
[21:11:39 INFO]: Preparing start region for dimension minecraft:the_end
[21:11:39 INFO]: Time elapsed: 101 ms
[21:11:39 INFO]: [Essentials] Enabling Essentials v2.19.0
[21:11:40 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[21:11:40 INFO]: [Essentials] No kits found to migrate.
[21:11:40 INFO]: [Essentials] Starting Essentials ban format conversion
[21:11:40 INFO]: [Essentials] Starting usermap repair
[21:11:40 WARN]: [Essentials] Missing userdata folder, aborting
[21:11:40 INFO]: [Essentials] Attempting to migrate ignore list to UUIDs
[21:11:40 INFO]: [Essentials] Attempting to migrate legacy userdata keys to Configurate
[21:11:40 INFO]: [Essentials] Loaded 36837 items from items.json.
[21:11:40 INFO]: [Essentials] Using locale it_IT
[21:11:40 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[21:11:40 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[21:11:40 INFO]: [Vault] [Economy] Essentials Economy hooked.
[21:11:40 INFO]: [Essentials] Using superperms-based permissions.
[21:11:40 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.19.0
[21:11:40 INFO]: [EssentialsSpawn] Starting Metrics. Opt-out using the global bStats config.
[21:11:40 INFO]: Running delayed init tasks
[21:11:40 INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[21:11:40 INFO]: [Essentials] Caricamento delle informazione sulla versione...
[21:11:40 INFO]: Done (4.647s)! For help, type "help"
[21:11:40 INFO]: Timings Reset
[21:11:40 INFO]: [Vault] Checking for Updates ...
[21:11:41 INFO]: [Vault] No new version available

### Steps/models to reproduce

java -Xms2G -Xmx2G -jar paper-1.17.1-353.jar --nogui

### Plugin and Datapack List

EssentialsX v2.19.0
EssentialsXSpawn v2.19.0 
Loading Vault v1.7.3-b131
ProtocolLib v4.7.0
Essentials v2.19.0
EssentialsSpawn v2.19.0

### Paper version

paper-1.17.1-353.jar

**Comment by NoahvdAa** [comment]
"PexTabCompleter" requires PermissionsEX to work properly.

**Comment by e-im** [comment]
> Unknown/missing dependency plugins: [PermissionsEx]. Please download and install these plugins to run 'PexTabCompleter'.

You need to install PEX. Please come to our [discord](https://discord.gg/papermc) #paper-help channel before making future issues.

**Comment by RealSting** [comment]
> PermissionsEX

Tnx! But this ULR https://www.spigotmc.org/resources/permissionsex-tab-completer-1-7-1-17-includes-permissionsex.69539/ says: "PermissionsEx Tab Completer | [1.7 - 1.17] | **Includes** PermissionsEx 1.3.1"

**Comment by e-im** [comment]
Please read the README.txt file in the zip download for installation instructions, they package pex in the zip you download. If you need more help, contact the plugin author's support.

**Comment by RealSting** [comment]
> > Unknown/missing dependency plugins: [PermissionsEx]. Please download and install these plugins to run 'PexTabCompleter'.
> 
> You need to install PEX. Please come to our [discord](https://discord.gg/papermc) #paper-help channel before making future issues.

thanks so much! Solved!
