### ISSUE TITLE
IndexOutOfBoundsException entering the nether

### ISSUE THREAD

**Issue by Sneakometer** [PaperSpigot/Paper#6932]
### Stack trace

```
[01:43:06 WARN]: Region file ./world_nether/DIM-1/entities/r.0.-3.mca has an invalid sector at index: 608; sector 45 is out of bounds
[01:43:06 FATAL]: Detected invalid header for regionfile /home/th/McHardcore2/./world_nether/DIM-1/entities/r.0.-3.mca! Cannot recalculate, removing local chunk (1,360) from header
[01:43:06 WARN]: Backing up regionfile "/home/th/McHardcore2/./world_nether/DIM-1/entities/r.0.-3.mca" to /home/th/McHardcore2/./world_nether/DIM-1/entities/r.0.-3.mca.-889393948994273398.backup
[01:43:06 WARN]: Backed up the regionfile to /home/th/McHardcore2/./world_nether/DIM-1/entities/r.0.-3.mca.-889393948994273398.backup
[01:43:06 WARN]: Failed to read chunk [11, -91]
java.lang.IndexOutOfBoundsException: null
        at java.nio.Buffer.checkIndex(Buffer.java:742) ~[?:?]
        at java.nio.DirectIntBufferS.put(DirectIntBufferS.java:406) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:521) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:436) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.getFile(RegionFileStorage.java:103) ~[app:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:187) ~[app:?]
        at net.minecraft.world.level.chunk.storage.IOWorker.lambda$loadAsync$2(IOWorker.java:99) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.world.level.chunk.storage.IOWorker.lambda$submitTask$10(IOWorker.java:129) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:90) ~[app:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[01:43:06 ERROR]: Failed to read chunk [11, -91]
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158) ~[?:?]
        at com.mojang.datafixers.util.Either$Right.ifRight(Either.java:109) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.ProcessorHandle.lambda$askEither$0(ProcessorHandle.java:29) ~[app:?]
        at net.minecraft.util.thread.ProcessorHandle$1.tell(ProcessorHandle.java:44) ~[app:?]
        at net.minecraft.world.level.chunk.storage.IOWorker.lambda$submitTask$10(IOWorker.java:129) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:90) ~[app:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkIndex(Buffer.java:742) ~[?:?]
        at java.nio.DirectIntBufferS.put(DirectIntBufferS.java:406) ~[?:?]
        at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:521) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:436) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.getFile(RegionFileStorage.java:103) ~[app:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:187) ~[app:?]
        at net.minecraft.world.level.chunk.storage.IOWorker.lambda$loadAsync$2(IOWorker.java:99) ~[patched_1.17.1.jar:git-Paper-388]
        ... 8 more
```

### Plugin and Datapack List

None

### Actions to reproduce (if known)

Download my world and enter the nether portal at (10 65 -10046)

### Paper version

git-Paper-388 (MC: 1.17.1)

### Other

World Download: https://workupload.com/file/3aW4ghaQE8Y

**Comment by electronicboy** [comment]
you have corrupted region files (or, well, that's an entity)

**Comment by Sneakometer** [comment]
Well they open fine in vanilla server

**Comment by electronicboy** [comment]
paper, being an extension of craftbukkit, moves the world folder for the nether/end, so vanilla won't be loading those files

**Comment by Sneakometer** [comment]
Just drop the DIM from world_nether to world and it works perfectly
