### ISSUE TITLE
[1.18-rc3] Internal server error on join

### ISSUE THREAD

**Issue by NEZNAMY** [PaperSpigot/Paper#6940]
### Stack trace

```
[19:21:55] [Server thread/INFO]: _NEZNAMY_[/127.0.0.1:59685] logged in with entity id 24 at ([world]-704.6787220820817, 66.0, 702.141767320753)
[19:21:56] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:59685
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:751) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:315) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1634) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1469) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1263) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Chunk not there when requested: Unloaded [-42, 43] Unloaded [-33, 48] Unloaded ticket level [-41, 40]
	at net.minecraft.server.level.ServerChunkCache.lambda$getChunk$13(ServerChunkCache.java:681) ~[?:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[paper-1.18-rc3.jar:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:677) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:530) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:863) ~[?:?]
	at net.minecraft.world.level.BlockCollisions.computeNext(BlockCollisions.java:89) ~[?:?]
	at net.minecraft.world.level.BlockCollisions.computeNext(BlockCollisions.java:18) ~[?:?]
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.world.level.CollisionGetter.noCollision(CollisionGetter.java:48) ~[?:?]
	at net.minecraft.world.level.Level.a(Level.java:983) ~[?:?]
	at net.minecraft.world.entity.Entity.canEnterPose(Entity.java:2453) ~[paper-1.18-rc3.jar:git-Paper-"4def84f"]
	at net.minecraft.world.entity.player.Player.updatePlayerPose(Player.java:391) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:313) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:669) ~[?:?]
	... 9 more
[19:21:57] [Server thread/INFO]: _NEZNAMY_ lost connection: Internal server error
[19:21:57] [Server thread/INFO]: _NEZNAMY_ left the game
```

### Plugin and Datapack List

Providing because requested, but none of them have anything to do with this.
[19:29:02] [Server thread/INFO]: Plugins (9): EazyNick, PlaceholderAPI, PlugMan*, TAB, TAB-Bridge, TAB-Placeholders, ViaBackwards, ViaRewind, ViaVersion

### Actions to reproduce (if known)

I created a world with 1.17.1 (purpur, hopefully saying this won't instalock the issue), upgraded to 1.18-rc3 paper, then switched to the mojang mapped jar to see how totally it breaks my plugin (the answer is totally), then switched back to the "reobf" jar and joined the server.

### Paper version

The one from your discord.
[19:32:32] [Server thread/INFO]: Checking version, please wait...
[19:32:33] [Thread-16/INFO]: This server is running Paper version git-Paper-"4def84f" (MC: 1.18 Release Candidate 3) (Implementing API version 1.18-rc3-R0.1-SNAPSHOT) (Git: 4def84f on dev/1.18)
Error obtaining version information
Previous version: git-Purpur-1406 (MC: 1.17.1)

### Other

When I joined again everything was fine.

**Comment by luketeam5** [comment]
This happens just for the first connection to the server, then the error stops occurring.

**Comment by aurorasmiles** [comment]
Does this still happen with the latest build?

**Comment by MiniDigger** [comment]
pls reopen a new issue if this still occurs on the latest build
