### ISSUE TITLE
Attempting to sleep kicks the player

### ISSUE THREAD

**Issue by JustCat80** [PaperSpigot/Paper#6999]
### Expected behavior

The player should be able to sleep

### Observed/Actual behavior

The player gets kicked with "connection lost" before even laying down

### Steps/models to reproduce

Join the server, attempt to sleep

### Plugin and Datapack List

None

### Paper version

Checking version, please wait...
[19:05:41 INFO]: This server is running Paper version git-Paper-22 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 956124f)
You are running the latest version

### Other

If i install the geyser plugin, for some reason bedrock players can sleep. im not sure if this is helpful but yea

**Comment by electronicboy** [comment]
Logs? client logs? etc

**Comment by JustCat80** [comment]
Heres the logs
[latest.txt](https://github.com/PaperMC/Paper/files/7644485/latest.txt)

And heres a video of what happens
https://imgur.com/N4CFM21

**Comment by lynxplay** [comment]
Can you post your client logs for this ? As the server does not seem to have any issue.

**Comment by JustCat80** [comment]
oop, I'm sorry I didn't think about it being the client because it was working before I swapped over to paper, ig its just fabric or one of my mods, vanilla works fine I'm sorry

Heres the error message anyway, 

```
Unexpectedly disconnected from server!
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_10582(String, String)" because "this.field_12039" is null
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_10582(String, String)" because "this.field_12039" is null
	at net.minecraft.class_2622.handler$baj000$onRead(class_2622.java:532) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2622.<init>(class_2622.java:38) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2539$class_4532.method_22310(class_2539.java:417) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2539.method_10783(class_2539.java:469) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2543.decode(class_2543.java:36) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at net.earthcomputer.multiconnect.impl.DebugUtils$DebugDecoderHandler.decode(DebugUtils.java:301) ~[multiconnect-1.5.1.jar:?]
	at net.minecraft.class_2543.callDecode(class_2543.java) ~[intermediary-fabric-loader-0.12.8-1.18.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	... 35 more
```

**Comment by JustCat80** [comment]
Yep, removed mods and its just a mod issue

**Comment by lynxplay** [comment]
Okay :+1: Thanks for the report anyway, now other users that experience the same issues can check if they match your issue :+1:  Could maybe try to find out which mod exactly is causing the issue and report it to their issue tracker.
