### ISSUE TITLE
[1.18] Feature placement server crash (async entity add)

### ISSUE THREAD

**Issue by Puremin0rez** [PaperSpigot/Paper#7001]
### Stack trace

```
[14:43:32] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.minecraft.ReportedException: Feature placement
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1262) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1243) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 8 more
Caused by: java.lang.IllegalStateException: Asynchronous entity add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1370) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1316) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1311) ~[?:?]
	at net.minecraft.world.level.block.Block.popResource(Block.java:402) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.block.Block.popResource(Block.java:368) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.block.Block.lambda$dropResources$4(Block.java:353) ~[paper-1.18.jar:git-Paper-23]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.world.level.block.Block.dropResources(Block.java:352) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.server.level.WorldGenRegion.destroyBlock(WorldGenRegion.java:226) ~[?:?]
	at net.minecraft.world.level.LevelWriter.destroyBlock(LevelWriter.java:23) ~[?:?]
	at net.minecraft.world.level.LevelWriter.destroyBlock(LevelWriter.java:19) ~[?:?]
	at net.minecraft.world.level.block.PointedDripstoneBlock.scheduleStalactiteFallTicks(PointedDripstoneBlock.java:325) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.block.PointedDripstoneBlock.updateShape(PointedDripstoneBlock.java:110) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.updateShape(BlockBehaviour.java:994) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$updateShapeAtEdge$4(StructureTemplate.java:403) ~[?:?]
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.forAllAxisFaces(DiscreteVoxelShape.java:225) ~[?:?]
	at net.minecraft.world.phys.shapes.DiscreteVoxelShape.forAllFaces(DiscreteVoxelShape.java:203) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.updateShapeAtEdge(StructureTemplate.java:392) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.placeInWorld(StructureTemplate.java:351) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.TemplateStructurePiece.postProcess(TemplateStructurePiece.java:83) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.RuinedPortalPiece.postProcess(RuinedPortalPiece.java:177) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.StructureStart.placeInChunk(StructureStart.java:62) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.chunk.ChunkGenerator.lambda$addVanillaDecorations$5(ChunkGenerator.java:306) ~[paper-1.18.jar:git-Paper-23]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.addVanillaDecorations(ChunkGenerator.java:305) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:396) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:391) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:148) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273) ~[paper-1.18.jar:git-Paper-23]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1245) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1243) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 8 more
```

### Plugin and Datapack List

No plugins or datapacks - an entirely fresh instance of Paper.

### Actions to reproduce (if known)

Create a world using the following seed: `-36682981`
Teleport to the following location: `/tp -1158 101 -1262`
Wait for the chunks around you to generate, the server will crash.

### Paper version

[14:57:38 INFO]: Checking version, please wait...
[14:57:38 INFO]: This server is running Paper version git-Paper-23 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 057adb0)
You are running the latest version

### Other

This reproducible issue (due to seed and coordinates) was discovered and reported by a user in the Chunky support channel.

**Comment by lynxplay** [comment]
Replicable on latest using the straight forward steps laid out :)
