### ISSUE TITLE
Paper 1.18 Experimental Crash due to net.minecraft.world.level.block.CaveVinesBlock.getGrowIntoState(CaveVinesBlock.java:56)

### ISSUE THREAD

**Issue by ilektron** [PaperSpigot/Paper#7062]
### Stack trace

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 12/7/21, 11:48 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: 'float java.util.Random.nextFloat(float)'
	at net.minecraft.world.level.block.CaveVinesBlock.getGrowIntoState(CaveVinesBlock.java:56)
	at net.minecraft.world.level.block.GrowingPlantHeadBlock.randomTick(GrowingPlantHeadBlock.java:61)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:962)
	at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:831)
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1049)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:923)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:622)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.level.block.CaveVinesBlock.getGrowIntoState(CaveVinesBlock.java:56)
	at net.minecraft.world.level.block.GrowingPlantHeadBlock.randomTick(GrowingPlantHeadBlock.java:61)
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:962)
	at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:831)
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1049)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:923)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:622)

-- Affected level --
Details:
	All players: 1 total; [EntityPlayer['ilektron'/180, uuid='9448853e-6fb6-4f59-af0b-e4700538972c', l='ServerLevel[world]', x=109.27, y=75.00, z=-290.03, cpos=[6, -19], tl=1189, v=true](ilektron at 109.26994583391414,75.0,-290.0333673390538)]
	Chunk stats: 2532
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,64,-208), Section: (at 0,0,0 in 7,4,-13; chunk contains blocks 112,-64,-208 to 127,319,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 9087 game time, 9087 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 126470 (now: false), thunder time: 155998 (now: false)
	Known server brands: Paper
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:831)

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Linux (amd64) version 5.4.78-2-pve
	Java Version: 17-ea, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1915138408 bytes (1826 MiB) / 3221225472 bytes (3072 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 1700 Eight-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 64847.90
	Virtual memory used (MB): 35446.89
	Swap memory total (MB): 32693.00
	Swap memory used (MB): 1754.25
	JVM Flags: 20 total; -Xms3G -Xmx3G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	CraftBukkit Information: 
   Running: Paper version git-Paper-58 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING Worker-Main-3: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3454), java.base@17-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3425), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17-ea/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], WAITING Worker-Main-6: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3454), java.base@17-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3425), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17-ea/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], WAITING Paper Async Chunk Task Thread #0: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], RUNNABLE DestroyJavaVM: [], WAITING Paper Async Chunk Task Thread #2: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Paper RegionFile IO Thread: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], RUNNABLE Signal Dispatcher: [], RUNNABLE Server thread: [java.base@17-ea/java.lang.Thread.dumpThreads(Native Method), java.base@17-ea/java.lang.Thread.getAllStackTraces(Thread.java:1647), org.bukkit.craftbukkit.v1_18_R1.CraftCrashReport.get(CraftCrashReport.java:33), org.bukkit.craftbukkit.v1_18_R1.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.a(SystemReport.java:65), net.minecraft.CrashReport.<init>(CrashReport.java:36), net.minecraft.CrashReport.a(CrashReport.java:242), net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1618), net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480), net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470), net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264), net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317), net.minecraft.server.MinecraftServer$$Lambda$3948/0x00000008014326e0.run(Unknown Source), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], TIMED_WAITING Paper Async Task Handler Thread - 0: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17-ea/java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:460), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1060), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], TIMED_WAITING Timer hack thread: [java.base@17-ea/java.lang.Thread.sleep(Native Method), net.minecraft.SystemUtils$5.run(SystemUtils.java:651)], TIMED_WAITING pool-4-thread-1: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@17-ea/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@17-ea/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], RUNNABLE Netty Epoll Server IO #1: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:192), io.netty.channel.epoll.Native.epollWait(Native.java:185), io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], WAITING Paper Async Chunk Task Thread #3: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Worker-Main-1: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3454), java.base@17-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3425), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17-ea/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], WAITING Worker-Main-2: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3454), java.base@17-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3425), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17-ea/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], WAITING Worker-Main-5: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3454), java.base@17-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3425), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17-ea/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], TIMED_WAITING Paper Watchdog Thread: [java.base@17-ea/java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:243)], WAITING Paper Async Chunk Urgent Task Thread: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], TIMED_WAITING Common-Cleaner: [java.base@17-ea/java.lang.Object.wait(Native Method), java.base@17-ea/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17-ea/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17-ea/java.lang.Thread.run(Thread.java:831), java.base@17-ea/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:161)], WAITING Worker-Main-4: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3454), java.base@17-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3425), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17-ea/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], RUNNABLE Notification Thread: [], WAITING Craft Async Scheduler Management Thread: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3454), java.base@17-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3425), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17-ea/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], TIMED_WAITING User Authenticator #1: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17-ea/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17-ea/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1060), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], TIMED_WAITING IO-Worker-5: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17-ea/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17-ea/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1060), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], RUNNABLE Server console handler: [java.base@17-ea/java.io.FileInputStream.readBytes(Native Method), java.base@17-ea/java.io.FileInputStream.read(FileInputStream.java:271), java.base@17-ea/java.io.BufferedInputStream.read1(BufferedInputStream.java:282), java.base@17-ea/java.io.BufferedInputStream.read(BufferedInputStream.java:343), java.base@17-ea/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270), java.base@17-ea/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313), java.base@17-ea/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188), java.base@17-ea/java.io.InputStreamReader.read(InputStreamReader.java:169), java.base@17-ea/java.io.BufferedReader.fill(BufferedReader.java:162), java.base@17-ea/java.io.BufferedReader.readLine(BufferedReader.java:329), java.base@17-ea/java.io.BufferedReader.readLine(BufferedReader.java:396), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:111)], TIMED_WAITING IO-Worker-2: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17-ea/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17-ea/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1060), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], RUNNABLE Reference Handler: [java.base@17-ea/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17-ea/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@17-ea/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], TIMED_WAITING IO-Worker-3: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17-ea/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17-ea/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1060), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1121), java.base@17-ea/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17-ea/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3454), java.base@17-ea/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3425), java.base@17-ea/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17-ea/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:71), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:192), io.netty.channel.epoll.Native.epollWait(Native.java:185), io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17-ea/java.lang.Thread.run(Thread.java:831)], WAITING Paper Async Chunk Task Thread #1: [java.base@17-ea/jdk.internal.misc.Unsafe.park(Native Method), java.base@17-ea/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:84)], WAITING Finalizer: [java.base@17-ea/java.lang.Object.wait(Native Method), java.base@17-ea/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17-ea/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@17-ea/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)],}
   
   Force Loaded Chunks: { world: {}, world_nether: {}, world_the_end: {},}
	Server Running: true
	Player Count: 1 / 20; [EntityPlayer['ilektron'/180, uuid='9448853e-6fb6-4f59-af0b-e4700538972c', l='ServerLevel[world]', x=109.27, y=75.00, z=-290.03, cpos=[6, -19], tl=1189, v=true](ilektron at 109.26994583391414,75.0,-290.0333673390538)]
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

### Plugin and Datapack List

[00:57:47 INFO]: Plugins (0): 
[00:58:11 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[00:58:11 INFO]: There are no more data packs available

### Actions to reproduce (if known)

Running Docker version 20.10.1, build 831ebea on Debian

Docker container generated from https://github.com/ilektron/Docker-Minecraft-PaperMC-Server

1. Created blank folder `/opt/minecraft/some-folder/`
2. Copied automatically generated default server.properties over from another folder to `/opt/minecraft/some-folder/`
3. Changed the seed to be `level-seed=-3657743899679432705`
4. Run the docker container with the following ENV, with a bind from /opt/minecraft/some-folder/ to /data in the container, port forward for access
```
"Env": [
                "PATH=/opt/openjdk-17/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/opt/openjdk-17",
                "JAVA_VERSION=17-ea+14",
                "MEMORYSIZE=3G",
                "JAVAFLAGS=-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=mcflags.emc.gs -Dcom.mojang.eula.agree=true"
            ],
```
5. Launch minecraft client 1.18, connect to server
6. Immediately head towards village which is visible from spawn
7. Within a couple of minutes walking around the village or so, server crashes as outlined. Any time reentering server, same crash

### Paper version

[00:56:55 INFO]: This server is running Paper version git-Paper-58 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 772e880)

**Comment by jpenilla** [comment]
Does this happen on a release version of JDK 17?

**Comment by jpenilla** [comment]
Yeah, this is due to an outdated JDK. This method was added in JDK 17 and is included in the release, but not in the EA you are running.

**Comment by mtoensing** [comment]
What is the recommended base image for Java 17?  @jpenilla

**Comment by e-im** [comment]
you can either use the "official" openjdk non-alpine version, just `openjdk:17`. Some other options that are at times better maintained include eclipse's temurin, amazon's corretto, or azul's zulu

Paper does not have an official recommendation, but all of these listed will suffice.

**Comment by josxha** [comment]
@mtoensing @sulu5890 I opened a pr.
