### ISSUE TITLE
Exception loading structure piece with id minecraft:jigsaw

### ISSUE THREAD

**Issue by PhantumOne** [PaperSpigot/Paper#7063]
When ever I TP or use Spawn I get this message in the Console:

Paper Version: paper-1.18.jar:git-Paper-60

[15:06:24] [Paper Async Chunk Task Thread PaperMC/papermc.io#1/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.NullPointerException: Cannot read field "nextInKToVBucket" because "bucketEntry" is null
	at com.google.common.collect.HashBiMap.delete(HashBiMap.java:155) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:316) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:290) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.core.MappedRegistry.registerMapping(MappedRegistry.java:81) ~[?:?]
	at net.minecraft.core.MappedRegistry.registerOrOverride(MappedRegistry.java:115) ~[?:?]
	at net.minecraft.resources.RegistryReadOps.readAndRegisterElement(RegistryReadOps.java:124) ~[paper-1.18.jar:git-Paper-60]
	at net.minecraft.resources.RegistryReadOps.lambda$decodeElement$3(RegistryReadOps.java:80) ~[paper-1.18.jar:git-Paper-60]
	at net.minecraft.resources.RegistryFileCodec.decode(RegistryFileCodec.java:50) ~[paper-1.18.jar:git-Paper-60]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:324) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.18.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.jar:git-Paper-60]
	at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.jar:git-Paper-60]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:790) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:363) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:106) ~[paper-1.18.jar:git-Paper-60]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.jar:git-Paper-60]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.jar:git-Paper-60]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.jar:git-Paper-60]

**Comment by Tsoccerguy3** [comment]
[latest.log](https://github.com/PaperMC/Paper/files/7697874/latest.log)

I'm getting a similar error on start up when Paper 1.18.1 build 68 loads the world spawn

**Comment by Lisible** [comment]
I'm getting that error on a 1.16~1.17 map with Paper 1.18.1 build 71.

**Comment by electronicboy** [comment]
Not a paper issue, this is down to vanilla not cleaning up after themselves

**Comment by electronicboy** [comment]
dismiss my last comment, I misread

**Comment by MrApik** [comment]
I'm getting similar exception (but with WorldGenFeaturePillagerOutpostPoolPiece) - with Paper 1.18.1 build 73. Exception occures when players are teleporting.

**Comment by Creeper36** [comment]
I am getting: 
ERROR: Exception loading structure piece with id minecraft:jigsaw
java.long.IllegalStateException: Invalid pool element found

on 1.18.1 build 81 but its a really old map and just updated from build 52 lol

**Comment by Sirraide** [comment]
Yeah, I'm also having that problem

**Comment by electronicboy** [comment]
Missing pool elements are irrelevant to this issue, this is about an actual exception in the server

Vanilla is mutating a collection concurrently

**Comment by MayaValentia** [comment]
Reproduced this exception on a world converted from Paper 1.17.1.
Server is on Paper version git-Paper-129 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: d0b8b1e)

```
[15:13:12] [Paper Async Chunk Task Thread #0/ERROR]: No key placement in MapLike[{config:{blacklist:[],block_placer:{type:"minecraft:simple_block_placer"},can_replace:0b,need_water:0b,project:1b,state_provider:{type:"minecraft:plain_flower_provider"},tries:64,whitelist:[],xspread:7,yspread:3,zspread:7},type:"minecraft:flower"}]; No key feature in MapLike[{config:{blacklist:[],block_placer:{type:"minecraft:simple_block_placer"},can_replace:0b,need_water:0b,project:1b,state_provider:{type:"minecraft:plain_flower_provider"},tries:64,whitelist:[],xspread:7,yspread:3,zspread:7},type:"minecraft:flower"}]
[15:13:12] [Paper Async Chunk Task Thread #0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:54) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-129]
        at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-129]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-129]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-129]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-129]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-129]
```

**Comment by it-rec** [comment]
Got the same execption today after upgrading to 1.18.1:

![grafik](https://user-images.githubusercontent.com/19797875/148433998-cefcf4fb-6e5f-454f-b4d1-dcb1d6e1f633.png)

The Jigsaw is still there, but it's not animating.

**Comment by No767** [comment]
> Got the same execption today after upgrading to 1.18.1:
> 
> ![grafik](https://user-images.githubusercontent.com/19797875/148433998-cefcf4fb-6e5f-454f-b4d1-dcb1d6e1f633.png)
> 
> The Jigsaw is still there, but it's not animating.

I'm also getting the same exact issue when upgrading

**Comment by jacobvdl** [comment]
I'm getting the same issue but the server is playable. Is there anything I should worry about or should I change back to 1.17?

**Comment by No767** [comment]
> I'm getting the same issue but the server is playable. Is there anything I should worry about or should I change back to 1.17?

Apparently this is a issue on vanilla itself. [MC-227945](https://bugs.mojang.com/browse/MC-227945) has been around since 1.17 and Paper had patched it at one point during 1.17. for now, just ignore it unless a fix is brought in

**Comment by electronicboy** [comment]
That issue and this issue are different

**Comment by Machine-Maker** [comment]
The original issue has been mitigated. In older versions (like 1.18) there was the opportunity for stuff to be added to registries from the resources during runtime. That doesn't happen anymore. Regsitries are frozen before the server even starts after loading everything from datapacks/vanilla.
