### ISSUE TITLE
Show log4j error message while starting

### ISSUE THREAD

**Issue by Gaojianli** [PaperSpigot/Paper#7117]
### Expected behavior

No error message

### Observed/Actual behavior

```
2021-12-14 14:23:32,569 ServerMain ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:234)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1107)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1032)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1024)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:643)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:243)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:289)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:626)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
        at net.minecraft.SystemUtils.<clinit>(SystemUtils.java:72)
        at net.minecraft.server.Main.<clinit>(Main.java:341)
        at org.bukkit.craftbukkit.Main.main(Main.java:293)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)

2021-12-14 14:23:32,584 ServerMain ERROR Null object returned for RollingRandomAccessFile in Appenders.
2021-12-14 14:23:32,592 ServerMain ERROR Appender File cannot be located. Reference ignored
```

### Steps/models to reproduce

1. Instal package from archlinuxcn `pacman -S papermc` [actual package url](https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/x86_64/papermc-1.18.1%2Bb74-1-any.pkg.tar.zst)
2. Run `papermc start`
3. Get this error message from console

### Plugin and Datapack List

- ChestSort v12.1.3
- SkinsRestorer v14.1.10
- TreeAssist v7.2.43

### Paper version

```
> version
[14:26:20 INFO]: Checking version, please wait...
[14:26:21 INFO]: This server is running Paper version git-Paper-74 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 7f31095)
You are running the latest version
Previous version: git-Paper-71 (MC: 1.18.1)
```

**Comment by electronicboy** [comment]
This is pretty much always down to bad file perms, etc, preventing the logs folder from being accessed

**Comment by Gaojianli** [comment]
> 

oh! That's it! It seems that the package manager created the logs folder with root. After chown, it disappeared, thanks
