### ISSUE TITLE
1.18.1 server crash

### ISSUE THREAD

**Issue by tydaytygx** [PaperSpigot/Paper#7136]
### Stack trace

```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/18/21, 10:23 PM
Description: Exception in server tick loop

java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:311)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:281)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1401)
	at java.desktop/sun.awt.AppContext$2.run(AppContext.java:273)
	at java.desktop/sun.awt.AppContext$2.run(AppContext.java:262)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.awt.AppContext.initMainAppContext(AppContext.java:262)
	at java.desktop/sun.awt.AppContext$3.run(AppContext.java:315)
	at java.desktop/sun.awt.AppContext$3.run(AppContext.java:298)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.awt.AppContext.getAppContext(AppContext.java:297)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:129)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadServerIcon0(CraftServer.java:2246)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadIcon(CraftServer.java:1059)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.<init>(CraftServer.java:379)
	at net.minecraft.server.players.PlayerList.<init>(PlayerList.java:160)
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:15)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:212)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.4.0-91-generic
	Java Version: 17.0.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 121777672 bytes (116 MiB) / 406847488 bytes (388 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7K62 48-Core Processor
	Identifier: AuthenticAMD Family 23 Model 49 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: GD 5446
	Graphics card #0 vendor: Cirrus Logic (0x1013)
	Graphics card #0 VRAM (MB): 32.00
	Graphics card #0 deviceId: 0x00b8
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 1967.77
	Virtual memory used (MB): 973.41
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xmx3072m -Xms256m
	CraftBukkit Information: 
   Running: Paper version git-Paper-81 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException: Cannot read field "reloadCount" because "net.minecraft.server.MinecraftServer.getServer().server" is null
	at org.bukkit.craftbukkit.v1_18_R1.CraftCrashReport.get(CraftCrashReport.java:31)
	at org.bukkit.craftbukkit.v1_18_R1.CraftCrashReport.get(CraftCrashReport.java:17)
	at net.minecraft.SystemReport.a(SystemReport.java:65)
	at net.minecraft.CrashReport.<init>(CrashReport.java:36)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1296)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:833)

	Server Running: true
	Data Packs: vanilla, file/bukkit
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

### Plugin and Datapack List

I set up a pure paper server without plugins, everything is fine until this crash
only two folders in /plugins

> bStats
> PluginMetrics

I have no plugins.

Since I start my server crash after I hit it to run, I have no way to run a command, 
so
 ```
 datapack list
```
could not be shown.

### Actions to reproduce (if known)

run
```sh 
java -Xmx3072m -Xms256m -jar /home/mcserver/spigotmc_1.18/paper-1.18.1-81.jar nogui
```

### Paper version

paper-1.18.1-81

**Comment by electronicboy** [comment]
This is an issue with your java install, you need the non headless JRE install

**Comment by cedral** [comment]
This didn't used to be required. Does this mean the nogui option is no longer working? That requires installing 103 additional packages totaling 600 MBs on my linux server which was already running 1.17 successfully.

**Comment by electronicboy** [comment]
nogui works fine, that doesn't change the fact that certain things try to load up certain system libraries; explicitly enabling headless mode with the AWT system property, or whatever it was, can mitigate some stuff, other stuff which requires on those libraries need those libraries.

outside of that, please don't bump old tickets with 0 info, for support, if using a supported version, please use the discord.

**Comment by e-im** [comment]
That specifically has always been required for the server icon. the nogui option is functional as always.

**Comment by cedral** [comment]
What server icon?
The command he ran to reproduce this issue was
java paper-1.18.1-81.jar nogui

I can tell you it was not required at 1.17 because I stopped a running server, Installed 1.19 in the same folder, changed the start.sh to reference 1.19 and got the error:

Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so

Though I would guess I am in the wrong place because that looks like craftbukkit, not y'all. But do you have any thoughts as to why craftbukkit is trying to load an icon running with nogui?

**Comment by e-im** [comment]
it is the `server-icon.png` that is displayed in the server list screen on the client

**Comment by cedral** [comment]
But is that something new? Why was 1.17 not having that problem?

**Comment by electronicboy** [comment]
that's literally been the case for years, nothing has changed here
