### ISSUE TITLE
PacketPlayInCustomPayload serialization Kicking

### ISSUE THREAD

**Issue by funkemunky** [PaperSpigot/Paper#7149]
### Stack trace

```

[20:45:25 ERROR]: Couldn't dispatch custom payload
java.lang.IndexOutOfBoundsException: null
        at io.netty.buffer.EmptyByteBuf.readByte(EmptyByteBuf.java:523) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at net.minecraft.network.FriendlyByteBuf.readByte(FriendlyByteBuf.java:980) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.readVarInt(FriendlyByteBuf.java:386) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.readUtf(FriendlyByteBuf.java:551) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3159) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:38) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:7) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-82]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-82]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:45:25 INFO]: funkemunky lost connection: Invalid custom payload!

```

### Plugin and Datapack List

Plugins (2): Atlas (1.11.0), Kauri

### Actions to reproduce (if known)

- Join the server
- Get kicked

This is generally caused by serializing the PacketPlayInCustomPayload packet at all.

### Paper version

 [Server thread/INFO]: This server is running CraftBukkit version 3368-Spigot-8965a50-2a2caa7 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
[20:58:56] [Server thread/INFO]: Checking version, please wait...
[20:58:56] [Thread-10/INFO]: You are running the latest version

### Other

This does not occur with regular spigot on 1.18.1, and is a Paper only bug. I am unsure what is the actual cause as I have not been able to look into it. The better I could find was this forum post https://forums.minecraftforge.net/topic/89266-solved1161-getting-entity-from-packetbuffer/

**Comment by electronicboy** [comment]
empty payload? o.O

**Comment by funkemunky** [comment]
Closing the issue. Im an idiot. I was actually making the payload empty by reading its bytes so once I copied it before doing so, it was fine. for some reason regular spigot doesn't have this kind of check.
