### ISSUE TITLE
Failed to parse resource pack prompt 'A resource pack is required to connect to this server.'

### ISSUE THREAD

**Issue by PatiTati** [PaperSpigot/Paper#7200]
### Expected behavior

Normal startup

### Observed/Actual behavior

[13:05:45] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:05:45] [ServerMain/INFO]: Reloading ResourceManager: Default, bukkit, armor statues v2.8.3.zip, fast leaf decay v2.0.5.zip, framey-e2420.zip, track raw statistics v1.5.2.zip
[13:05:46] [Worker-Main-1/INFO]: Loaded 7 recipes
[13:05:47] [ServerMain/WARN]: Failed to parse resource pack prompt 'A resource pack is required to connect to this server.'
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65) ~[gson-2.8.8.jar:?]
	at net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:503) ~[?:?]
	at net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:527) ~[?:?]
	at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:432) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.parseResourcePackPrompt(DedicatedServer.java:847) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:99) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.Main.lambda$main$0(Main.java:243) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.spin(MinecraftServer.java:327) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.Main.main(Main.java:242) ~[paper-1.18.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.Main.main(Main.java:293) ~[paper-1.18.1.jar:git-Paper-101]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.8.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:592) ~[gson-2.8.8.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.8.jar:?]
	at com.google.gson.internal.Streams.parse(Streams.java:46) ~[gson-2.8.8.jar:?]
	... 12 more
[13:05:47] [Server thread/INFO]: Starting minecraft server version 1.18.1
[13:05:47] [Server thread/INFO]: Loading properties
[13:05:48] [Server thread/INFO]: This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)
[13:05:48] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:05:48] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:05:48] [Server thread/INFO]: Default game type: SURVIVAL

### Steps/models to reproduce

Startup the server and look at the Logs.

### Plugin and Datapack List

[13:12:04] [Server thread/INFO]: Plugins (19): AngelChest, AutoComposter, Chunky, CoreProtect, DoorsReloaded, Harbor, HeadDatabase, InventoryRollbackPlus, InvSeePlusPlus, JukeBoxPlus, LiveKit, LuckPerms, MiniMOTD, PlaceholderAPI, TAB, UltimateAutoRestartPro, Vault, WorldEdit, WorldGuard
[13:16:10] [Server thread/INFO]: There are 6 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/armor statues v2.8.3.zip (world)], [file/fast leaf decay v2.0.5.zip (world)], [file/framey-e2420.zip (world)], [file/track raw statistics v1.5.2.zip (world)]
[13:16:10] [Server thread/INFO]: There are no more data packs available

### Paper version

[13:11:19] [Server thread/INFO]: Checking version, please wait...
[13:11:19] [Thread-27/INFO]: This server is running Paper version git-Paper-101 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 464b171)
You are running the latest version
Previous version: git-Paper-100 (MC: 1.18.1)

### Other

Try without Datapacks, same Error.

_No response_

**Comment by Machine-Maker** [comment]
I think that the error is pretty self explanatory. You need to put json in the [resource pack prompt](https://minecraft.fandom.com/wiki/Server.properties ) setting in server.properties.

**Comment by NoahvdAa** [comment]
`resource-pack-prompt` must be a [chat component](https://minecraft.fandom.com/wiki/Raw_JSON_text_format), try wrapping it in quotes

EDIT: Ninja'd by MM

**Comment by PatiTati** [comment]
> I think that the error is pretty self explanatory. You need to put json in the [resource pack prompt](https://minecraft.fandom.com/wiki/Server.properties) setting in server.properties.

You're right. My server management software AMP does not write the text in the serverconfig with ". I think it is a bug of the server software AMP. Now the error is no longer present.
