### ISSUE TITLE
ConcurrentModificationException when calling ChunkData.setBlock

### ISSUE THREAD

**Issue by ShaneParslow** [PaperSpigot/Paper#7253]
### Expected behavior

Blocks written by ChunkData.setBlock, and no exception.

### Observed/Actual behavior

A server crash, with the following stack trace:
```
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.createBlockData(CraftServer.java:2518) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.createBlockData(CraftServer.java:2493) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1925) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.Material.createBlockData(Material.java:4101) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CraftChunkData.setBlock(CraftChunkData.java:69) ~[paper-1.18.1.jar:git-Paper-124]
	at com.Logaaan.AetherGen.AetherGen.generateNoise(AetherGen.java:57) ~[AetherGen-1.0-SNAPSHOT.jar:?] <------ My plugin, at ChunkData.setBlock
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.lambda$fillFromNoise$0(CustomChunkGenerator.java:253) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.lambda$fillFromNoise$1(CustomChunkGenerator.java:258) ~[paper-1.18.1.jar:git-Paper-124]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768) ~[?:?]
	... 4 more
Cause of unexpected exception was
java.util.ConcurrentModificationException: null
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R1.block.data.CraftBlockData.newData(CraftBlockData.java:525) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.createBlockData(CraftServer.java:2518) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.createBlockData(CraftServer.java:2493) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.Bukkit.createBlockData(Bukkit.java:1925) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.Material.createBlockData(Material.java:4101) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CraftChunkData.setBlock(CraftChunkData.java:69) ~[paper-1.18.1.jar:git-Paper-124]
	at com.Logaaan.AetherGen.AetherGen.generateNoise(AetherGen.java:57) ~[AetherGen-1.0-SNAPSHOT.jar:?] <------ My plugin, at ChunkData.setBlock
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.lambda$fillFromNoise$0(CustomChunkGenerator.java:253) ~[paper-1.18.1.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_18_R1.generator.CustomChunkGenerator.lambda$fillFromNoise$1(CustomChunkGenerator.java:258) ~[paper-1.18.1.jar:git-Paper-124]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

This occurred while running the plugin I'm working on, which adds a custom world generator. I'm new to the Bukkit API, but as far as I can tell this is the intended way to implement a chunk generator. It also seems implied that ChunkData.setBlock should be thread safe.
The full source of the plugin can be found [here](https://github.com/ShaneParslow/AetherGen), but the relevant chunk generation method is listed here.

```java
public void generateNoise(@NotNull WorldInfo worldInfo, @NotNull Random random, int chunkX, int chunkZ, @NotNull ChunkGenerator.ChunkData chunkData) {
    SimplexOctaveGenerator gen = new SimplexOctaveGenerator(new Random(worldInfo.getSeed()), Config.aether_octaves);
    SimplexOctaveGenerator lower_gen = new SimplexOctaveGenerator(new Random(worldInfo.getSeed() + 1), Config.aether_octaves);
    gen.setScale(0.005);
    lower_gen.setScale(0.005);

    int worldBaseX = chunkX * 16;
    int worldBaseZ = chunkZ * 16;

    for (int X = 0; X < 16; X++) {
        for (int Z = 0; Z < 16; Z++) {
            int worldX = worldBaseX + X;
            int worldZ = worldBaseZ + Z;

            double noise = gen.noise(worldX, worldZ, Config.aether_frequency, Config.aether_amplitude);
            int currentHeight = (int) (noise * 7D + Config.aether_height);
            double offset_noise = lower_gen.noise(worldX, worldZ, Config.aether_frequency, Config.aether_amplitude);
            int lower_offset = (int) (offset_noise * 7D);
            int lower_y = (int) (Config.aether_height - (noise * 7D - 13D) + lower_offset);

            for (int Y = currentHeight; Y > lower_y; Y--) {
                Biome biome = chunkData.getBiome(X, Y, Z);
                if (noise > Config.aether_spawn_rate) {

                    /***** Exception occurs the following setBlocks *****/

                    if (Y == currentHeight) {
                        if (biome.equals(Biome.DESERT)) {
                            chunkData.setBlock(X, Y, Z, Material.SAND);
                        } else {
                            chunkData.setBlock(X, Y, Z, Material.GRASS_BLOCK);
                        }
                    // On second to top block
                    } else if (Y == currentHeight - 1) {
                        chunkData.setBlock(X, Y, Z, Material.DIRT);
                    // On some other block, for loop ensures within sane y limits
                    } else {
                        chunkData.setBlock(X, Y, Z, Material.STONE);
                    }

                    /***** End exception area *****/

                }
            }
        }
    }
}
```

To reproduce, simply generate new chunks. The exception occurs somewhat randomly, but seems more common near server start.

I could not reproduce this on CraftBukkit or Spigot.

### Plugin and Datapack List

AetherGen (my plugin) and Multiverse-Core

### Paper version

This server is running Paper version git-Paper-124 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: cee7e0d)
You are running the latest version
Previous version: git-Paper-101 (MC: 1.18.1)

### Other

The call to HashMap.computeIfAbsent is at line 62 in [0502-Cache-block-data-strings.patch](https://github.com/PaperMC/Paper/blob/cee7e0df017d9f52c4af4a6975222dc59c7bcac9/patches/server/0502-Cache-block-data-strings.patch#L62):
`CraftBlockData cached = stringDataCache.computeIfAbsent(data, s -> createNewData(null, s));`

The issue seems to be that ChunkData.setBlock is not thread safe because of CraftBlockData.newData and it's HashMap cache. I don't see any API documentation outright saying that ChunkData.setBlock should be thread safe, but it appears to be in CraftBukkit and Spigot. I'm not sure how you would do chunk generation if it wasn't.

I suspect that the reason the exception is more common near server start is because the cache is being populated.

**Comment by ShaneParslow** [comment]
Simply changing HashMap to ConcurrentHashMap fixes it for me. If that is a suitable fix I can open a PR.

**Comment by SirYwell** [comment]
There is an open PR for that https://github.com/PaperMC/Paper/pull/6876

**Comment by ShaneParslow** [comment]
Looks good, I'll close this then since it seems like it's being taken care of. Thanks!
