### ISSUE TITLE
the provided org.yaml:snakeyaml dependency (version 1.30) cannot load in custom classes with the Yaml#loadAs(..., Class<T> type)

### ISSUE THREAD

**Issue by bananasmoothii** [PaperSpigot/Paper#7262]
### Expected behavior

The configuration being successfully loaded, and the Config class being found by SnakeYaml

### Observed/Actual behavior

```
[00:52:29] [Server thread/INFO]: [BananabubblePlugin] Enabling BananabubblePlugin v1.0
[00:52:29] [Server thread/ERROR]: Error occurred while enabling BananabubblePlugin v1.0 (Is it up to date?)
org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:fr.bananasmoothii.bananabubbleplugin.Config; exception=Class not found: fr.bananasmoothii.bananabubbleplugin.Config
 in 'reader', line 1, column 1:
    bananacoinRewardMsg: '§aYou won ... 
    ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:336) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:220) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:174) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:158) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:442) ~[snakeyaml-1.30.jar:?]
	at fr.bananasmoothii.bananabubbleplugin.BananabubblePlugin.onEnable(BananabubblePlugin.java:39) ~[BananabubblePlugin-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-"6852c65"]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-"6852c65"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-"6852c65"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-"6852c65"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-"6852c65"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-"6852c65"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-"6852c65"]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: org.yaml.snakeyaml.error.YAMLException: Class not found: fr.bananasmoothii.bananabubbleplugin.Config
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:669) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:323) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:332) ~[snakeyaml-1.30.jar:?]
	... 18 more
[00:52:29] [Server thread/INFO]: [BananabubblePlugin] Disabling BananabubblePlugin v1.0
```

**Note:** I was able to work around this by setting SnakeYaml's scope as `compile`:
```xml
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.30</version>
            <scope>compile</scope>
        </dependency>
```
and by relocating SnakeYaml like this:
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <!-- This version is needed in order to be able to compile with Java 17 -->
                <version>3.3.1-SNAPSHOT</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <relocations>
                                <relocation>
                                    <pattern>org.yaml</pattern>
                                    <shadedPattern>fr.bananasmoothii.bananabubbleplugin.org.yaml</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
And adding this to be able to use version `3.3.1-SNAPSHOT` as decribed [here](https://stackoverflow.com/a/68245055/11720290):
```xml
    <pluginRepositories>
        <pluginRepository>
            <id>maven-snapshots</id>
            <url>https://repository.apache.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```
**Note 2:** it also works when using Junit tests (that's why I added them to the dependencies below)

### Steps/models to reproduce

Make a new plugin

Use these Maven dependencies:
```xml
    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.18.1-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.30</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
```

Make a `Config` class, mine is
```java
// don't convert to record or else SnakeYaml won't work at all
public final class Config {
    private String bananacoinRewardMsg;

    public Config(String bananacoinRewardMsg) {
        this.bananacoinRewardMsg = bananacoinRewardMsg;
    }

    private Config() {
        this("");
    }

    public String getBananacoinRewardMsg() {
        return bananacoinRewardMsg;
    }
}
```

Make the corresponding `config.yml` file
```yaml
bananacoinRewardMsg: '§aYou won a Bananacoin !'
```

Load configuration via `Yaml#loadAs()`:
```java
    @Override
    public void onEnable() {
        final File configFile = new File("./plugins/BananabubblePlugin/config.yml");
        if (!configFile.exists()) saveDefaultConfig();
        final Yaml yaml = new Yaml();
        yaml.setBeanAccess(BeanAccess.FIELD);
        try {
            config = yaml.loadAs(new FileReader(configFile), Config.class); // this line will cause the error
        } catch (FileNotFoundException e) {
            // should not happen
            throw new RuntimeException(e);
        }
    }
```

### Plugin and Datapack List

None except that plugin I just made

### Paper version

This server is running Paper version git-Paper-"79dd62a" (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 79dd62a)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-"3c5284d" (MC: 1.18.1)

**Comment by zml2008** [comment]
Quick guess is that this is a classloader hierarchy thing -- the provided snakeyaml is on the base classloader, which doesn't know about your plugin's classes in the `PluginClassloader`. See the body of `getClassForNode` here:

```java
    protected Class<?> getClassForName(String name) throws ClassNotFoundException {
        try {
            return Class.forName(name, true, Thread.currentThread().getContextClassLoader());
        } catch (ClassNotFoundException e) {
            return Class.forName(name);
        }
    }
```

This can of course be worked around or it may it may be possible to configure SnakeYAML to avoid calling that method altogether, but that goes into the realm of a snakeyaml support query, rather than a Paper issue.

**Comment by bananasmoothii** [comment]
Yeah, but SnakeYaml probably won't fix that, maybe Paper can throw in some little patches ?

**Comment by zml2008** [comment]
[wow i wonder what this is](https://bitbucket.org/snakeyaml/snakeyaml/src/master/src/main/java/org/yaml/snakeyaml/constructor/CustomClassLoaderConstructor.java)

and again, not something paper has any reason to get involved witth

**Comment by bananasmoothii** [comment]
Sorry, I don't understand what this is and how to use it

**Comment by electronicboy** [comment]
We have pretty much 0 control over this (and aren't going to maintain patches over 3rd party libraries outside of necessity), the thing uses the current context classloader, as zml pulled out; 

There are 2 trivial options here:
1) set the current context classloader before calling load so that your plugins classloader is where it looks (make sure to restore it)
2) implement a custom Constructor for this, you can easily extend the built in one and implement the `getClassForName(String)` and other potentially relevant methods to explicitly use your own classloader (pardon scatter brain, zml linked a class which has already done this for you!) - You just need to pass it into the Yaml instance you create

This issue seems far too easily solvable on your side without us needing to maintain patches over random libraries (to solve an issue which would be massively nuanced and likely creates it's own set of issues anyways)

**Comment by bananasmoothii** [comment]
Ok, it works this way:
```java
        final Yaml yaml = new Yaml(new Constructor() {
            @Override
            protected Class<?> getClassForName(String name) throws ClassNotFoundException {
                if (name.equals(Config.class.getName())) return Config.class;
                return super.getClassForName(name);
            }
        });
```
Thanks !
