### ISSUE TITLE
The water are floating!

### ISSUE THREAD

**Issue by LittleSheep2Code** [PaperSpigot/Paper#7272]
### Expected behavior

When I put water on the wall, the water should falling

### Observed/Actual behavior

When I put water on the wall, the water are floating like the block does't update

### Steps/models to reproduce

Just put water on the wall

### Plugin and Datapack List

Plugins (24): AdvancedNMotd, AdvancedTeleport, ChestShop, Chunky, CMILib, CoreProtect, Essentials, EssentialsChat, EssentialsDiscord, EssentialsProtect, EssentialsSpawn, GUIShop, LuckPerms, LWC, Multiverse-Core, PlaceholderAPI, PlayerTitle, ProtocolLib, Residence, Scoreboard-revision*, TradePlus, Vault, WorldEdit, WorldGuard
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Paper version

```
[21:58:10 INFO]: Checking version, please wait...
[21:58:10 WARN]: java.net.UnknownHostException: papermc.io
[21:58:10 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
[21:58:10 WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:58:10 WARN]: 	at java.base/java.net.Socket.connect(Socket.java:633)
[21:58:10 WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
[21:58:10 WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[21:58:10 WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[21:58:10 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[21:58:10 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[21:58:10 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[21:58:10 WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[21:58:10 WARN]: 	at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[21:58:10 WARN]: 	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:474)
[21:58:10 WARN]: 	at com.google.common.io.CharSource.openBufferedStream(CharSource.java:126)
[21:58:10 WARN]: 	at com.destroystokyo.paper.PaperVersionFetcher.fetchDistanceFromSiteApi(PaperVersionFetcher.java:90)
[21:58:10 WARN]: 	at com.destroystokyo.paper.PaperVersionFetcher.getUpdateStatusMessage(PaperVersionFetcher.java:61)
[21:58:10 WARN]: 	at com.destroystokyo.paper.PaperVersionFetcher.getVersionMessage(PaperVersionFetcher.java:35)
[21:58:10 WARN]: 	at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:205)
[21:58:10 WARN]: 	at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:189)
[21:58:10 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:58:10 INFO]: This server is running Paper version git-Paper-124 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: cee7e0d)
Error obtaining version information
Previous version: git-Paper-402 (MC: 1.17.1)
```
(My network is bad)

### Other

I used a my develop plugin: [PanelCraft](https://github.com/LittleSheep2010/PanelCraft-Core)
I have tried remove it and it does't work too

**Comment by e-im** [comment]
replicate without plugins, ensure `simulation-distance` in spigot.yml/server.properties is at some sane value (non-negative). This isn't a paper issue.

**Comment by LittleSheep2Code** [comment]
That's very helpful, thank you!

**Comment by LittleSheep2Code** [comment]
I found the issue because 1.18 residence don't allow place water at high than floor 63
