### ISSUE TITLE
Saving a Class<?>.getCanonicalName() causes ClassCastException in org.bukkit.configuration.file.YamlConfiguration

### ISSUE THREAD

**Issue by deadbeef-enc0de** [PaperSpigot/Paper#7283]
### Expected behavior

Loading the yaml file without issue

### Observed/Actual behavior

When trying to load the following YAML file
```
plugins/YamlSaver/RPG/net.mctitan.rpg.data.Entity/df389f5b-bf48-4270-aecb-60e9d2c8b4ba.yml
modifiers: !!set
  ? type: net.mctitan.rpg.modifier.base.BaseCritChanceModifier
    critchance: 0.025
    rank: 1
  : null
  ? type: net.mctitan.rpg.modifier.magic.IncreasedHealthModifier
    value: 0.0
    rank: 1
  : null
  ? type: net.mctitan.rpg.modifier.base.BaseAttackSpeedModifier
    value: 1.0
    rank: 1
  : null
  ? type: net.mctitan.rpg.modifier.base.BasePhysicalDamageModifier
    minimum: 1.0
    maximum: 3.0
    rank: 1
  : null
  ? type: net.mctitan.rpg.modifier.other.AdjustedExperienceGivenModifier
    amount: 0.1
    rank: 1
  : null
experience:
  level: 1
  exp: 0
name: Panda
health: -1.0
statusmanager:
  timed: !!set {}
nametagmanager:
  tags:
  - Level 1
uuid: df389f5b-bf48-4270-aecb-60e9d2c8b4ba
```

Causes the following stack trace within snakeyml
```
[15:33:01 INFO]: [RPG] [STDOUT] Loading: df389f5b-bf48-4270-aecb-60e9d2c8b4ba
[15:33:01 ERROR]: Could not pass event EntitiesLoadEvent to RPG v0.5.1
java.lang.ClassCastException: class org.yaml.snakeyaml.nodes.MappingNode cannot be cast to class org.yaml.snakeyaml.nodes.ScalarNode (org.yaml.snakeyaml.nodes.MappingNode and org.yaml.snakeyaml.nodes.ScalarNode are in unnamed module of loader java.net.URLClassLoader @6a4f787b)
	at org.bukkit.configuration.file.YamlConfiguration.hasSerializedTypeKey(YamlConfiguration.java:170) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:153) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:114) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.mctitan.data.PluginData.load(PluginData.java:106) ~[YamlSaver-1.3.0.jar:?]
	at net.mctitan.data.PluginData.load(PluginData.java:82) ~[YamlSaver-1.3.0.jar:?]
	at net.mctitan.data.PluginData.load(PluginData.java:76) ~[YamlSaver-1.3.0.jar:?]
	at net.mctitan.rpg.data.DataManager.entity(DataManager.java:86) ~[RPG-0.5.1.jar:?]
	at net.mctitan.rpg.handlers.LivingEntity.onEntitiesLoad(LivingEntity.java:150) ~[RPG-0.5.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-132]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:1870) ~[paper-1.18.1.jar:git-Paper-132]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.processPendingLoads(PersistentEntitySectionManager.java:384) ~[paper-1.18.1.jar:git-Paper-132]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.tick(PersistentEntitySectionManager.java:392) ~[paper-1.18.1.jar:git-Paper-132]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:683) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-132]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-132]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-132]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

1. Start a server with the plugins
2. Stop the server
3. Start the server

This will cause the reproduction

### Plugin and Datapack List

[RPG](http://archiva.mctitan.net/repository/public/net/mctitan/rpg/RPG/0.5.1b83/RPG-0.5.1b83.jar)
[YamlSaver](http://archiva.mctitan.net/repository/public/net/mctitan/data/YamlSaver/1.3.0b4/YamlSaver-1.3.0b4.jar)
[EasyCommands](http://archiva.mctitan.net/repository/public/net/mctitan/commands/EasyCommands/1.3.0/EasyCommands-1.3.0.jar)
ProtocolLib

### Paper version

Paper version git-Paper-132 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 5e30e19)

### Other

This is not happening on:  
Paper version git-Paper-110 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 6852c65)

Removing the modifiers removes the issue as well (for testing)

**Comment by Machine-Maker** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-6886 might be related. Either way, its def an upstream issue. 

(Which isn't to say paper can't fix it, but that's the root cause)

**Comment by e-im** [comment]
[resolved upstream](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/8c956b8de36c4b9aa1c72084c973db74195f96f3#src/test/java/org/bukkit/configuration/file/YamlConfigurationTest.java)
