### ISSUE TITLE
[1.18.1] Crash server with Exception in server tick loop

### ISSUE THREAD

**Issue by Diablolend** [PaperSpigot/Paper#7302]
### Stack trace

[crash-2022-01-08_14.54.43-server.txt](https://github.com/OhTheDungeon/OhTheDungeon/files/7833005/crash-2022-01-08_14.54.43-server.txt)
```
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58)
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91)
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146)
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1241)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1222)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 8 more
Caused by: java.lang.IllegalStateException: Entity EntityLargeFireball['Fireball'/1137, uuid='b773e00e-e0d4-4002-958c-af2726d337fe', l='ServerLevel[world]', x=1861.24, y=356.71, z=-160.47, cpos=[116, -11], tl=0, v=false] is not in the region
	at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
	at org.bukkit.craftbukkit.v1_18_R1.generator.CraftLimitedRegion.saveEntities(CraftLimitedRegion.java:97)
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:410)
	at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:391)
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:148)
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:273)
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$35(ChunkTracker.java:1224)
	... 11 more
```

### Plugin and Datapack List

Plugins:
AuthMe, BlueMap, Citizens, CleanroomGenerator, CoreProtect, DiscordSRV, elyby-skinsystem*, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), Geyser-Spigot, Graves, GSit, Harbor, HeadDatabase, HeadsPlus, ImageMaps, ImageOnMap, JukeBox, LuckPerms, mcMMO, mcMMOAction, Minepacks, Multiverse-Core, NoteBlockAPI, OpenInv, PCGF_PluginLib, PlaceholderAPI, ProtocolLib, Quests, Sentinel, ServerRestart, ServerRestorer, SkinsRestorer, SkQuery, Skript, skript-yaml, TAB, Vault, ViaBackwards, ViaVersion, VoidGen, VRolePlay*, WorldBorder, WorldGuard.

Datapacks:
[vanilla (built-in)], [file/bukkit (world)], [file/Zombie_Leather_1.1 (world)], [file/CraftSound_for_1.17 (world)], [file/armor_statues_v2.9.2 (world)], [file/BlazeandCaves Advancements Pack 1.13.1 (world)], [file/DoubleDoors1.17 (world)], [file/armored elytra v1.0.5 (world)], [file/fast leaf decay v2.0.5 (world)], [file/larger phantoms v1.2.3 (world)], [file/track raw statistics v1.5.2 (world)], [file/track statistics v1.1.3 (world)]

### Actions to reproduce (if known)

I assume this crash is caused by the boundary between new and old chunks. It is caused by the generation of a certain fireball.
The trigger of this crash is the Oh The Dungeon plugin. But as the author of this plugin claims:
![image](https://user-images.githubusercontent.com/11898488/148659287-9119dd07-dffe-45f7-a0b0-fc057eceb855.png)

### Paper version

This server is running Paper version git-Paper-140 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: d9fb602)

**Comment by electronicboy** [comment]
This issue was fixed upstream
