### ISSUE TITLE
FATAL Uncaught exception in thread Profile Lookup Executor

### ISSUE THREAD

**Issue by PappoYT** [PaperSpigot/Paper#7434]
### Stack trace

```
[14:25:43] [Profile Lookup Executor #0/FATAL]: Uncaught exception in thread Profile Lookup Executor #0
java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[patched_1.17.1.jar:git-Paper-408]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:199) ~[patched_1.17.1.jar:git-Paper-408]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[patched_1.17.1.jar:git-Paper-408]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[patched_1.17.1.jar:git-Paper-408]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[patched_1.17.1.jar:git-Paper-408]
	at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$2(SkullBlockEntity.java:157) ~[app:?]
	at net.minecraft.Util.ifElse(Util.java:391) ~[app:?]
	at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$5(SkullBlockEntity.java:154) ~[app:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

02.02 15:41:31 [Server] INFO Plugins (83): AnimatedScoreboard, AutomaticBroadcast, BentoBox, BetterSleeping4, Citizens, CoreProtect, CustomCommands, CustomEnchantments, DBAPI*, DiscordSRV, DisplayShops, dtlTradersPlus, EliteMobs, ExcellentCrates, ExecutableItems, Factions, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, GrapplingHook, GriefPrevention, GriefPreventionFlags, GSit, GUIPlus, HolographicDisplays, HoloPlots, HPWP, InteractiveBooks, InventoryRollbackPlus, InvSeePlusPlus, KayTeamAPI, KitPvP, KumandrasEconomy, LeaderHeadsRevamped, LibsDisguises, LootChest, LuckPerms, MBedwars, MiniMOTD, Multiverse-Core, Multiverse-Inventories, MurderMystery, MyCommand, MythicMobs, NametagEdit, NBTAPI, NexEngine, Oh_the_dungeons_youll_go, Ollivanders2, Parkour, PetMaster, PL-Hide, PlaceholderAPI, Plan, PlayerKits, PlotSquared, ProtocolLib, PvPManager, Quests, Randomtp, RPGLoot, SCore, Seasons, SecondThreadAPI*, Sentinel, SetHome*, SheepQuest, SimpleHomes, SkinsRestorer, Spleef*, TangledMazePlus, TheFloorIsLava, TheNewEconomy, TNTRun_reloaded, TNTRunTimedRewards, TradeSystem, Vault, ViaVersion, VoidGen, WarpSystem, WebSender*, WorldBorderAPI, WorldGuard

### Actions to reproduce (if known)

Startup the server.
After startup is completed, this message appear in console every 2-3 seconds.

### Paper version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-407 (MC: 1.17.1)

### Other

before today I never see this errors.
I didnt install any plugin just before errors appear.

**Comment by electronicboy** [comment]
Duplicate of #6682

**Comment by electronicboy** [comment]
Actually, I misread that one, not a duplicate, you have a skull in the world which has invalid profile data on it

**Comment by Machine-Maker** [comment]
*not really*

**Comment by protected22** [comment]
> Actually, I misread that one, not a duplicate, you have a skull in the world which has invalid profile data on it

Hi. I have the exact same problem. How can we know which skull causes this?

**Comment by TaakoOfficial** [comment]
Same issue here how can we just remove all skulls from the world

**Comment by Starflight-code** [comment]
I see you have Citizens in your plugin folder. This could be caused by making edits to the `Citizens/saves.yml` folder. I had this issue as well and solved this by using `/npc rem all`. Try it and see if it solves your issue as well.

**Comment by e-im** [comment]
As this appears to be coming up in search: On recent versions of Paper you can add `-DPaper.debugInvalidSkullProfiles=true` to your startup command, before `-jar`, to print more information here. It will be able to tell you if the bad skull comes from a plugin, or if not, where in the world the skull block is.
