### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by masterhacka** [PaperSpigot/Paper#7447]
### Expected behavior

Clean console

### Observed/Actual behavior

Console spam: [11:12:23 FATAL]: Uncaught exception in thread Profile Lookup Executor #131031
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.2.38.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.2.38.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.18.1.jar:git-Paper-186]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.2.38.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$3(SkullBlockEntity.java:155) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:438) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$6(SkullBlockEntity.java:152) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

### Steps/models to reproduce

Just start the server

### Plugin and Datapack List

Plugins (59): AdvancedBan, AltDetector, BedrockPlayerManager, BungeeGuard, BungeeServerSigns*, BungeeTabListPlus, BuycraftX, ChatControlRed, Citizens, CityBuildV2*, CMI, CMILib, ConditionalEvents, CrazyCrates, DBVerifierLinker*, DeluxeMenus, DiscordSRV, EasySetSpawn*, EazyNick, FastAsyncWorldEdit (WorldEdit), floodgate, GadgetsMenu, GeyserSkinManager, GMusic, goBrush, HolographicDisplays, ImageMaps, ItemJoin, JumpPads, LeaderHeadsRevamped, LibsDisguises, LuckPerms, Matrix, MyCommand, MysqlEconomyBank, NametagEdit, OldCombatMechanics, OptimalBungeePortals, Orebfuscator, PlaceholderAPI, Plan, PlugMan, PremiumVanish, ProtocolLib, SuperbVote, TigerReports, TigerReportsSupports*, TitleManager, Vault, ViaBackwards, ViaRewind, ViaVersion, ViaVersionStatus, VIPJoinSlots*, Votifier, WarpSystem, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

### Paper version

This server is running Paper version git-Paper-186 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 6df4641)

**Comment by electronicboy** [comment]
more than likely, update floodgate

**Comment by masterhacka** [comment]
I have installed the newest version of floodgate. On my other servers in the network it is running fine

**Comment by electronicboy** [comment]
skulls which where created in the period of time between you updating that plugin and mojang changing their API are likely broken, you'll need to go find them and fix them or something

**Comment by masterhacka** [comment]
any idea how to do so? fortunately the map is only 200*200

**Comment by masterhacka** [comment]
I delete the whole maps and still same error

**Comment by e-im** [comment]
Please come by our [discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io) for future support with this issue. You've likely got a slightly different issue, as exactly what you've posted here is definitely from an invalid skull. or I guess a plugin.

**Comment by masterhacka** [comment]
Yeah I already stated my issue on discord but no one answers
