### ISSUE TITLE
Crash when exploring map

### ISSUE THREAD

**Issue by FunixG** [PaperSpigot/Paper#7473]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Invalid bounding box data, inverted bounds for: StructureBoundingBox{minX=2147483647, minY=2147483647, minZ=2147483647, maxX=-2147483648, maxY=-2147483648, maxZ=-2147483648}
[19:21:07 ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid call to EmtyPoolElement.getBoundingBox, filter me!
at net.minecraft.world.level.levelgen.feature.structures.EmptyPoolElement.getBoundingBox(EmptyPoolElement.java:39) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.(PoolElementStructurePiece.java:57) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:74) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.levelgen.feature.StructureFeature.loadStaticStart(StructureFeature.java:129) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:796) ~[?:?]
at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:369) ~[?:?]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.18.1.jar:git-Paper-187]
at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.18.1.jar:git-Paper-187]
[19:21:07 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1626) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'float java.util.Random.nextFloat(float)'
at net.minecraft.world.level.block.CaveVinesBlock.getGrowIntoState(CaveVinesBlock.java:56) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.block.GrowingPlantHeadBlock.randomTick(GrowingPlantHeadBlock.java:61) ~[?:?]
at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:962) ~[?:?]
at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:834) ~[?:?]
at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1045) ~[?:?]
at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:923) ~[?:?]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:625) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-187]
... 5 more
[19:21:07 ERROR]: Cause of unexpected exception was
java.lang.NoSuchMethodError: 'float java.util.Random.nextFloat(float)'
at net.minecraft.world.level.block.CaveVinesBlock.getGrowIntoState(CaveVinesBlock.java:56) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.world.level.block.GrowingPlantHeadBlock.randomTick(GrowingPlantHeadBlock.java:61) ~[?:?]
at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.randomTick(BlockBehaviour.java:962) ~[?:?]
at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:834) ~[?:?]
at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1045) ~[?:?]
at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:923) ~[?:?]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:625) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-187]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
[19:21:07 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-02-12_19.21.07-server.txt

### Plugin and Datapack List

[19:44:37 INFO]: Plugins (13): CMILib, CoreProtect, Essentials, EssentialsSpawn, GriefPrevention, Jobs, PacifistaBox, PacifistaMain, PacifistaShop, PacifistaSurvie, Vault, WorldEdit, WorldGuard

### Actions to reproduce (if known)

Teleport to coordinates higher than 1 million

### Paper version

[19:45:05 INFO]: This server is running Paper version git-Paper-194 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9567753)

**Comment by electronicboy** [comment]
likely bad java version, update; do note some of the docker images where shipping pre-release builds

**Comment by HexF** [comment]
This appears to be a bug within a paper-mc applied patch, namely this line:
https://github.com/PaperMC/Paper/blob/0bf7c95c8d8144c4f9ee1ec7b70f00ea7b9c5bf9/patches/server/0804-Fix-kelp-modifier-changing-growth-for-other-crops.patch#L28

Java docs for Java 17 dont declare `float java.util.Random.nextFloat(float)`
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Random.html#nextFloat()

**Comment by e-im** [comment]
[not a bug](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/random/RandomGenerator.html#nextFloat(float)) - this does not exist in ea versions of java 17. paper does not support early access versions of java 17.

Should this not exist it also wouldn't compile.
