### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7506]
### Observed/Actual behavior
Description: Exception in server tick loop

java.lang.IllegalArgumentException: 0
	at io.papermc.paper.chunk.PlayerChunkLoader.setTickDistance(PlayerChunkLoader.java:223)
	at io.papermc.paper.chunk.PlayerChunkLoader.setTargetTickViewDistance(PlayerChunkLoader.java:172)
	at net.minecraft.server.level.DistanceManager.updateSimulationDistance(DistanceManager.java:553)
	at net.minecraft.server.level.ServerChunkCache.<init>(ServerChunkCache.java:416)
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:517)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:833)

When I update from 'paper-1.18.1-197' to 'paper-1.18.1-214', the above crash error occurs. (Settings, etc. are not changed at all)
The tested server is a lobby server, so there is nothing special about the world map.
Therefore, it is currently unable to update and stays at version 197.
Please let me know how I can solve this.

### Steps/models to reproduce

.

### Plugin and Datapack List

Viaversion, ViaBackward, ViaRewind only 3
(I uninstalled all the plugins and tried running version 214, but the same crash occurred)

### Paper version

[05:34:50] [Thread-12/INFO]: This server is running Paper version git-Paper-197 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: a8f2d67)
You are 17 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-214 (MC: 1.18.1)

**Comment by derklaro** [comment]
Maybe I am blind but which "above crash error"

**Comment by ghost** [comment]
> Maybe I am blind but which "above crash error"

Description: Exception in server tick loop

java.lang.IllegalArgumentException: 0
	at io.papermc.paper.chunk.PlayerChunkLoader.setTickDistance(PlayerChunkLoader.java:223)
	at io.papermc.paper.chunk.PlayerChunkLoader.setTargetTickViewDistance(PlayerChunkLoader.java:172)
	at net.minecraft.server.level.DistanceManager.updateSimulationDistance(DistanceManager.java:553)
	at net.minecraft.server.level.ServerChunkCache.<init>(ServerChunkCache.java:416)
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:517)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by e-im** [comment]
Your simulation distance can't be 0. Set it to 2 or above.

**Comment by ghost** [comment]
> Your simulation distance can't be 0. Set it to 2 or above.

thank you! If I change it to 2, it works normally.
