### ISSUE TITLE
CraftBlockTag#getValues throws an exception if the underlying tag does not exist

### ISSUE THREAD

**Issue by Geolykt** [PaperSpigot/Paper#7545]
### Expected behavior

Either the tag cannot be obtained at all via Bukkit#getTag (i. e. it returns null) or the method returns an empty collection

### Observed/Actual behavior

The method throws a `java.util.NoSuchElementException: No value present`
Full stacktrace in one of my plugins:
```
java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Optional.java:143) ~[?:?]
    at org.bukkit.craftbukkit.v1_18_R2.tag.CraftTag.getHandle(CraftTag.java:25) ~[paper-1.18.2.jar:git-Paper-225]
    at org.bukkit.craftbukkit.v1_18_R2.tag.CraftBlockTag.getValues(CraftBlockTag.java:32) ~[paper-1.18.2.jar:git-Paper-225]
    at de.geolykt.presence.PresenceBukkit.onEnable(PresenceBukkit.java:749) ~[presence-1.1.0.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-225]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-225]
    at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-225]
    at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-225]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-225]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-225]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-225]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

Run code like
```java
        for (String s : bukkitCfg.getStringList("harvestable-crops")) {
                String var10001 = s.substring(1);
                if (var10001 == null) {
                    throw new NullPointerException(s);
                }
                NamespacedKey key = NamespacedKey.fromString(var10001);
                if (key == null) {
                    throw new IllegalStateException("Invalid namespaced key \"" + s + "\" is the harvestable-crops list.");
                }
                Tag<@NotNull Material> tag = Bukkit.getTag(Tag.REGISTRY_BLOCKS, key, Material.class);
                if (tag == null) {
                    // Try it again with the item registry
                    tag = Bukkit.getTag(Tag.REGISTRY_ITEMS, key, Material.class);
                }
                if (tag == null) {
                    getSLF4JLogger().error("The tag \"{}\" in the harvestable-crops list does not exist.", var10001);
                } else {
                    harvestableCrops.addAll(tag.getValues());
                }
        }
```
with
```yml
harvestable-crops:
  - "#beetroots"
  - "#carrots"
  - "#potatoes"
  - "wheat"
  - "melon"
  - "pumpkin"
```
as the input

### Plugin and Datapack List

[12:47:18 INFO]: Plugins (20): AdvancedTeleport, BetterSleeping4, Enchantments_plus, FastLeafDecay, LuckPerms, mcMMO, MineableSpawners, PlayerCurrency, PlayerShop, Presence, PresenceSquaremap, ServerUtils, spark, squaremap, StarterKit, TabList, Treasury, Vault, WorldEdit, WorldGuard

[12:47:18 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[12:47:18 INFO]: There are no more data packs available

### Paper version

[12:47:18 INFO]: This server is running Paper version git-Paper-225 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1d7a6a0)
You are running the latest version
Previous version: git-Paper-214 (MC: 1.18.1)

**Comment by HexedHero** [comment]
Likely will need to be reported and fixed upstream if it's present there.

**Comment by Doc94** [comment]
> Likely will need to be reported and fixed upstream if it's present there.

tested same code and happen in upstream..

i try change the line in CraftTag for `getHandle` when handle its null (not sure why)
`handle = registry.getTag(tag).get(); //a Optional` to `handle = registry.getOrCreateTag(tag);`  and not throw the error but returns a empty list in `getValues` then not sure if its the correct fix for a PR... because i dont use Tags...

**Comment by electronicboy** [comment]
getOrCreateTag imho would probably be the expected behaviour here given that the logic always returns a tag, either that or it woul need some form of getTagIfExists type method/bool on CraftServer, that way you can do a lookup without creating one

**Comment by Doc94** [comment]
> getOrCreateTag imho would probably be the expected behaviour here given that the logic always returns a tag, either that or it woul need some form of getTagIfExists type method/bool on CraftServer, that way you can do a lookup without creating one

yeah.. not sure if the tag exists based in the report... then not sure if in first place the getTag need return null for this case

PD: Not sure how works this in previous versions but maybe https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/05a38da190704cb8df90401c45fc39d087cdc031#src/main/java/org/bukkit/craftbukkit/tag/CraftTag.java

**Comment by Geolykt** [comment]
The tags in my case do not exist

**Comment by kennytv** [comment]
If you want to retain previous behavior, you have to return an empty set for non-existing tags, but Server.getTag not just returning null in the first place makes little sense regarding the nullability annotation and docs

**Comment by Doc94** [comment]
Created PR in upstream for make this cases where the tag not exists return null.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/1023/overview
