### ISSUE TITLE
Can't open custom inventory from PlayerRecipeBookClickEvent

### ISSUE THREAD

**Issue by DevLGuilherme** [PaperSpigot/Paper#7550]
### Expected behavior

Expected to open a custom inventory when the player clicks on a specific recipe from the recipe book.

### Observed/Actual behavior

The player who click is kicked from the server and the message "Packet Processing Error" shows up.
This behavior only happens with the **PlayerRecipeBookClickEvent**. Other Events, like **PlayerToggleSneakEvent** and **InventoryCloseEvent**, the same custom inventory opens and works as expected.

![image](https://user-images.githubusercontent.com/57814418/156904570-bc1080fd-2aec-41d5-9266-54e03be52608.png)

And this error is logged in the console:

```
[21:59:52 ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInAutoRecipe@67420ef for iLGx[/127.0.0.1:50630]
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_18_R2.inventory.CraftContainer cannot be cast to class net.minecraft.world.inventory.ContainerRecipeBook (org.bukkit.craftbukkit.v1_18_R2.inventory.CraftContainer and net.minecraft.world.inventory.ContainerRecipeBook are in unnamed module of loader java.net.URLClassLoader @7960847b)
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handlePlaceRecipe$18(ServerGamePacketListenerImpl.java:2957) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlaceRecipe(ServerGamePacketListenerImpl.java:2956) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlaceRecipePacket.handle(ServerboundPlaceRecipePacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlaceRecipePacket.handle(ServerboundPlaceRecipePacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1387) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1364) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1357) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1335) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-228]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

The simple plugin below can help to reconstruct the issue.

Using only the paper-api:1.18.2-R0.1-SNAPSHOT as dependency.

```java
public final class SimpleInventory extends JavaPlugin implements Listener {

    @Override
    public void onEnable() {
        Bukkit.getServer().getLogger().info("SimpleInventory ENABLED");
        createOpenInventoryRecipe();
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @Override
    public void onDisable() {
        Bukkit.getServer().getLogger().info("SimpleInventory DISABLED");
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event){
        if(event.getPlayer().hasDiscoveredRecipe(NamespacedKey.minecraft("open_inventory"))) return;
        event.getPlayer().discoverRecipe(NamespacedKey.minecraft("open_inventory"));
    }

    @EventHandler
    public void onRecipeBookClick(PlayerRecipeBookClickEvent event) {
        if(event.getRecipe().getKey().equals("open_inventory")){
            var inventory = Bukkit.createInventory(event.getPlayer().getInventory().getHolder(), 9 );
            event.getPlayer().openInventory(inventory);
        }
    }

    public static void createOpenInventoryRecipe() {
        Bukkit.getServer().getLogger().info("CREATING RECIPE");
        var playerHead = new ItemStack(Material.PLAYER_HEAD, 1);
        var itemMeta = (SkullMeta) playerHead.getItemMeta();
        assert itemMeta != null;
        itemMeta.displayName(Component.text(ChatColor.YELLOW + "" + ChatColor.BOLD + "Open Inventory"));
        itemMeta.lore(List.of(Component.text("Click to open Inventory")));
        playerHead.setItemMeta(itemMeta);
        //ShapedRecipe
        var recipe = new ShapedRecipe(NamespacedKey.minecraft("open_inventory"), playerHead);
        recipe.shape("  ","  ");
        Bukkit.getServer().addRecipe(recipe);
        Bukkit.getServer().getLogger().info("RECIPE ADDED");
    }
}
```

### Plugin and Datapack List

Using only the plugin mentioned in the **Steps/models to reproduce** field, and **no datapacks**.

### Paper version

This server is running Paper version git-Paper-228 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 6564f70)
You are running the latest version
Previous version: git-Paper-224 (MC: 1.18.2)

**Comment by Machine-Maker** [comment]
Ok, I see where the issue is, you open the inventory, and then since the player's menu has changed, it tries to place the recipe in that inventory, and fails.
