### ISSUE TITLE
Chunk Loading Crash

### ISSUE THREAD

**Issue by TastaMax** [PaperSpigot/Paper#7589]
### Stack trace

Time: 3/13/22, 10:52 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.a()" because "value" is null
	at net.minecraft.core.Registry$1.getId(Registry.java:522)
	at net.minecraft.core.Registry$1.a(Registry.java:519)
	at net.minecraft.world.level.chunk.LinearPalette.getSerializedSize(LinearPalette.java:99)
	at net.minecraft.world.level.chunk.PalettedContainer$Data.getSerializedSize(PalettedContainer.java:381)
	at net.minecraft.world.level.chunk.PalettedContainer.getSerializedSize(PalettedContainer.java:324)
	at net.minecraft.world.level.chunk.LevelChunkSection.getSerializedSize(LevelChunkSection.java:292)
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.calculateChunkSize(ClientboundLevelChunkPacketData.java:103)
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:48)
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:36)
	at net.minecraft.server.level.ChunkTracker.lambda$playerLoadedChunk$66(ChunkTracker.java:2137)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at net.minecraft.server.level.ChunkTracker.playerLoadedChunk(ChunkTracker.java:2136)
	at net.minecraft.server.level.ChunkTracker.updateChunkTracking(ChunkTracker.java:1617)
	at io.papermc.paper.chunk.PlayerChunkLoader$PlayerLoaderData.sendChunk(PlayerChunkLoader.java:855)
	at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:578)
	at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:728)
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1259)
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:828)
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1387)
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369)
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Plugin and Datapack List

Datapacks
iris, armoredelytra, armorstatues
Plugins
AsyncWorldEdit, Citizens, CoreProtect, DiscordSRV, dtlTraders, Dynmap, Dynmap-Worldguard, Essentials, EssentialsChat, EssentialsSpawn, floodgate, geyser-spigot, GSit, Guilds, Harbor, HeadsPlus, InventoryRollbackPlus, Iris, LuckPerms, LWC, Minecord, MoneyFromMobs, Multiverse-Core, PlaceholderAPI, Plan, ProtocolLib, Quests, SurvivalInvisiframes, Tablist, Vault, Worldedit, Worldguard

### Paper version

[10:14:20] [Server thread/INFO]: This server is running Paper version git-Paper-247 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1358d1e)

**Comment by electronicboy** [comment]
corrupted world

**Comment by aurorasmiles** [comment]
As @electronicboy already said, you have an issue with corruption in your world. This means that your world or a part of it contains some errors that are crashing your server. This can happen when the server isn't shut down properly or be caused by a bad plugin. We recommend restoring a backup from your world, but you might also have success with just deleting and regenerating the corrupted area/data.
If you need more help I'd recommend asking on our Discord at [discord.gg/papermc
](discord.gg/papermc)
