### ISSUE TITLE
I don't know what that error means.

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#7641]
### Expected behavior

Sometimes the following error is output to the console. What is the error?

[09:11:51] [Profile Lookup Executor #0/ERROR]: Uncaught exception in thread Profile Lookup Executor #0
java.lang.RuntimeException: Original profile: 'com.mojang.authlib.GameProfile@77e76791[id=74c5d7d2-bc58-46e3-aa88-af55aaa1c425,name=platoonf,properties={},legacy=false]' Run with -DPaper.debugInvalidSkullProfiles=true for further debug information.
	at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:192) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at com.google.common.collect.LinkedHashMultimap$ValueSet$1.checkForComodification(LinkedHashMultimap.java:420) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.LinkedHashMultimap$ValueSet$1.hasNext(LinkedHashMultimap.java:426) ~[guava-31.0.1-jre.jar:?]
	at java.util.AbstractSet.hashCode(AbstractSet.java:121) ~[?:?]
	at java.util.Objects.hashCode(Objects.java:103) ~[?:?]
	at java.util.HashMap$Node.hashCode(HashMap.java:299) ~[?:?]
	at java.util.AbstractMap.hashCode(AbstractMap.java:526) ~[?:?]
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap.hashCode(AbstractMapBasedMultimap.java:1408) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.AbstractMultimap.hashCode(AbstractMultimap.java:255) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.LinkedHashMultimap.hashCode(LinkedHashMultimap.java:86) ~[guava-31.0.1-jre.jar:?]
	at com.google.common.collect.ForwardingMultimap.hashCode(ForwardingMultimap.java:154) ~[guava-31.0.1-jre.jar:?]
	at java.util.WeakHashMap.hash(WeakHashMap.java:303) ~[?:?]
	at java.util.WeakHashMap.getEntry(WeakHashMap.java:432) ~[?:?]
	at java.util.WeakHashMap.containsKey(WeakHashMap.java:423) ~[?:?]
	at org.apache.commons.lang3.builder.ToStringStyle.isRegistered(ToStringStyle.java:207) ~[commons-lang3-3.12.0.jar:3.12.0]
	at org.apache.commons.lang3.builder.ToStringStyle.appendInternal(ToStringStyle.java:492) ~[commons-lang3-3.12.0.jar:3.12.0]
	at org.apache.commons.lang3.builder.ToStringStyle.append(ToStringStyle.java:466) ~[commons-lang3-3.12.0.jar:3.12.0]
	at org.apache.commons.lang3.builder.ToStringBuilder.append(ToStringBuilder.java:845) ~[commons-lang3-3.12.0.jar:3.12.0]
	at com.mojang.authlib.GameProfile.toString(GameProfile.java:108) ~[authlib-3.3.39.jar:?]
	at java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453) ~[?:?]
	at java.lang.StringConcatHelper.simpleConcat(StringConcatHelper.java:408) ~[?:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:203) ~[authlib-3.3.39.jar:?]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.18.2.jar:git-Paper-265]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.3.39.jar:?]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.18.2.jar:git-Paper-265]
	at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$4(SkullBlockEntity.java:170) ~[?:?]
	at net.minecraft.Util.ifElse(Util.java:427) ~[?:?]
	at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:167) ~[?:?]
	... 3 more

### Observed/Actual behavior

.

### Steps/models to reproduce

.

### Plugin and Datapack List

.

### Paper version

[09:15:30] [Server thread/INFO]: This server is running Paper version git-Paper-265 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 993f828)
You are running the latest version
Previous version: git-Paper-260 (MC: 1.18.2)

**Comment by MiniDigger** [comment]
do you really have no plugins installed?

**Comment by Lmaxplay** [comment]
Can you give the log file?

**Comment by aurorasmiles** [comment]
No response for a couple months, we sadly can't help without additional information.
