### ISSUE TITLE
I can't build server.jar

### ISSUE THREAD

**Issue by LIMPIX31** [PaperSpigot/Paper#7705]
### Expected behavior

The server will work

### Observed/Actual behavior

I have accomplished:
1. The file weighs twice as much as expected.
2. The script crashes on startup with an error:
```
[21:15:25 ERROR]: Failed to load properties from file: server.properties
[21:15:25 INFO]: [STDERR]: java.lang.IncompatibleClassChangeError: Expecting non-static method 'java.lang.String net.minecraft.server.dedicated.DedicatedServerProperties.c(java.lang.String)'
[21:15:25 INFO]: [STDERR]:      at net.minecraft.server.dedicated.DedicatedServerProperties.<init>(DedicatedServerProperties.java:130)
[21:15:25 INFO]: [STDERR]:      at net.minecraft.server.dedicated.DedicatedServerProperties.fromFile(DedicatedServerProperties.java:137)
[21:15:25 INFO]: [STDERR]:      at net.minecraft.server.dedicated.DedicatedServerSettings.<init>(DedicatedServerSettings.java:19)
[21:15:25 INFO]: [STDERR]:      at net.minecraft.server.Main.main(Main.java:110)
[21:15:25 INFO]: [STDERR]:      at org.bukkit.craftbukkit.Main.main(Main.java:289)
[21:15:25 INFO]: [STDERR]:      at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
[21:15:25 INFO]: [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps/models to reproduce

```bash
gradlew applyPatches
# Create my patches (successfully)
gradlew rebuildPatches
gradlew applyPatches
gradlew createReobfBundlerJar
```

### Plugin and Datapack List

No

### Paper version

1.18.2 Commit: 62dcff3

### Other

I've been spending many hours trying to build a server jar file.

**Comment by Machine-Maker** [comment]
Don't build on Windows. Use WSL (Windows Subsystem for Linux) if you don't have another operating system available. See https://github.com/FabricMC/tiny-remapper/issues/87
