### ISSUE TITLE
quando avvio il server mi da questo errore 

### ISSUE THREAD

**Issue by BrianILMangiaNteLLa** [PaperSpigot/Paper#7720]
### Stack trace

Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads ***
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.2+8-Ubuntu-118.04) Host: Linux 4.15.0-175-generic (amd64)
Loading libraries, please wait...
[15:34:17 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:34:17 FATAL]: Failed to start the minecraft server
net.minecraft.util.SessionLock$ExceptionWorldConflict: /root/Lobby/./world/session.lock: already locked (possibly by other Minecraft instance?)
        at net.minecraft.util.DirectoryLock$LockException.alreadyLocked(DirectoryLock.java:98) ~[?:?]
        at net.minecraft.util.DirectoryLock.create(DirectoryLock.java:44) ~[?:?]
        at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.<init>(LevelStorageSource.java:312) ~[?:?]
        at net.minecraft.world.level.storage.LevelStorageSource.createAccess(LevelStorageSource.java:282) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:156) ~[paper-1.18.jar:git-Paper-66]
        at org.bukkit.craftbukkit.Main.main(Main.java:295) ~[paper-1.18.jar:git-Paper-66]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
root@mc:~/Lobby# ^C

### Plugin and Datapack List

DeluxeHub 3.5.1
GWarp
LuckPerms 5.4.9
MultiverseCore 4.3.1
PlaceholderAPI 2.11.1
SkinsRestorer
TAB 3.1.1
TitleManager 2.3.6
ViaVersion 4.2.1
WorldEdit 7.2.8
WorldGuard 7.0.6
znpc

### Paper version

root@mc:~/Lobby# /version
-bash: /version: No such file or directory

### Other

utilizzo paper 1.18

**Comment by electronicboy** [comment]
There is something already running which is accessing the world folder

**Comment by Machine-Maker** [comment]
Please use English (or a translator) in the future. Just by looking at the stack trace, it looks like either another server is already using that world, or the lock file wasn't cleared last shutdown. If its not the former, delete the session.lock files in the world folders

**Comment by BrianILMangiaNteLLa** [comment]
> Si prega di utilizzare l'inglese (o un traduttore) in futuro. Solo guardando la traccia dello stack, sembra che un altro server stia già utilizzando quel mondo o che il file di blocco non sia stato cancellato l'ultimo arresto. Se non è il primo, elimina i file session.lock nelle cartelle del mondo

ok thanks

**Comment by BrianILMangiaNteLLa** [comment]
> Si prega di utilizzare l'inglese (o un traduttore) in futuro. Solo guardando la traccia dello stack, sembra che un altro server stia già utilizzando quel mondo o che il file blocco non sia stato cancellato l'ultimo arresto. Se non è il primo, elimina i file session.lock nelle cartelle del mondo

I created the worlds except the KitPvP one
