### ISSUE TITLE
Server won

### ISSUE THREAD

**Issue by Dunuin** [PaperSpigot/Paper#7768]
### Stack trace

```
[14:54:36] [ServerMain/ERROR]: Failed to start the minecraft server
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonNull
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:869) ~[gson-2.8.9.jar:?]
	at net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:417) ~[?:?]
	at net.minecraft.util.GsonHelper.parse(GsonHelper.java:469) ~[?:?]
	at net.minecraft.util.GsonHelper.parse(GsonHelper.java:465) ~[?:?]
	at net.minecraft.util.GsonHelper.parse(GsonHelper.java:473) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServerProperties.lambda$new$2(DedicatedServerProperties.java:125) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.dedicated.Settings.get(Settings.java:184) ~[?:?]
	at net.minecraft.server.dedicated.Settings.get(Settings.java:207) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServerProperties.<init>(DedicatedServerProperties.java:124) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.dedicated.DedicatedServerProperties.fromFile(DedicatedServerProperties.java:137) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.dedicated.DedicatedServerSettings.<init>(DedicatedServerSettings.java:19) ~[paper-1.18.2.jar:git-Paper-312]
	at net.minecraft.server.Main.main(Main.java:110) ~[paper-1.18.2.jar:git-Paper-312]
	at org.bukkit.craftbukkit.Main.main(Main.java:289) ~[paper-1.18.2.jar:git-Paper-312]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

### Plugin and Datapack List

Plugins:
worldguard-bukkit-7.0.7-dist.jar
worldedit-bukkit-7.2.10.jar
WorldBorder.jar (2.1.5)
LuckPerms-Bukkit-5.4.21.jar
Hibernate-2.0.0.jar
EssentialsXGeoIP-2.19.4.jar
EssentialsXChat-2.19.4.jar
EssentialsX-2.19.4.jar
Dynmap-3.4-beta-3-spigot.jar
AsyncWorldEdit-3.9.4.jar
AncientGates.jar (2.5.1)

### Actions to reproduce (if known)

Server won't start at all after upgrading from 1.16.5 to 1.18.2 and always fails with the error above.

### Paper version

Paper 1.18.2-312

### Other

I'm running a Debian VM with MineOS, Waterfall and 6 Paper Servers. Al Paper MC servers use the same Paper version and 5 of them use the same plugins and 4 of these are starting fine. Just one of the 5 is failing to start. I just replaced the Paper jar and plugin jars like with all the other servers that are working.

**Comment by lynxplay** [comment]
Your `server.properties` `generator-settings` are most likely malformed. This is most certainly not an issue with the server, rather with your configuration. For further help, please see our [discord](https://discord.gg/papermc).

**Comment by Dunuin** [comment]
Thanks, your are right. :)
The server that wasn't working got "generator-settings=null" and not "generator-settings={}" like the other servers. Changed it to "generator-settings={}" too and with that its working.
