### ISSUE TITLE
Null head crashes

### ISSUE THREAD

**Issue by sequoiadotdev** [PaperSpigot/Paper#7786]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:754) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:314) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: []
        at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at net.minecraft.nbt.NbtUtils.readGameProfile(NbtUtils.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:47) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:307) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:283) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.asBukkitCopy(CraftItemStack.java:62) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.world.entity.LivingEntity.collectEquipmentChanges(LivingEntity.java:3038) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.detectEquipmentUpdates(LivingEntity.java:3000) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2907) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:269) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:668) ~[?:?]
        ... 9 more
[20:22:48 INFO]: cnamew lost connection: Internal server error
[20:22:48 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:754) ~[?:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:620) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:602) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2009) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1989) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:753) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: []
        at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at net.minecraft.nbt.NbtUtils.readGameProfile(NbtUtils.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:47) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:307) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:283) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.asBukkitCopy(CraftItemStack.java:62) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.world.entity.LivingEntity.collectEquipmentChanges(LivingEntity.java:3038) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.detectEquipmentUpdates(LivingEntity.java:3000) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2907) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:269) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:668) ~[?:?]
        ... 12 more
[20:22:48 ERROR]:       Cause of unexpected exception was
java.lang.IllegalArgumentException: Invalid UUID string: []
        at java.util.UUID.fromString1(UUID.java:280) ~[?:?]
        at java.util.UUID.fromString(UUID.java:258) ~[?:?]
        at net.minecraft.nbt.NbtUtils.readGameProfile(NbtUtils.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.<init>(CraftMetaSkull.java:47) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:307) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:283) ~[paper-1.18.2.jar:git-Paper-317]
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.asBukkitCopy(CraftItemStack.java:62) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.world.entity.LivingEntity.collectEquipmentChanges(LivingEntity.java:3038) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.detectEquipmentUpdates(LivingEntity.java:3000) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2907) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:269) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:668) ~[?:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:620) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:602) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2009) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1989) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:753) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:22:49 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-05-03_20.22.49-server.txt
[20:22:49 INFO]: Stopping server
[20:22:49 INFO]: Saving players
[20:22:49 INFO]: Saving worlds
[20:22:49 ERROR]: Exception stopping the server
java.lang.IllegalStateException: null
        at io.papermc.paper.chunk.PlayerChunkLoader.trySendChunks(PlayerChunkLoader.java:574) ~[paper-1.18.2.jar:git-Paper-317]
        at io.papermc.paper.chunk.PlayerChunkLoader.tickMidTick(PlayerChunkLoader.java:741) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1251) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:820) ~[?:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1018) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[paper-1.18.2.jar:git-Paper-317]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-317]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin and Datapack List

none

### Actions to reproduce (if known)

hold or equip a null head

### Paper version

1.18.2 latest

### Other

if you hold or equip a null head it crashes the server

**Comment by Doc94** [comment]
How can you get a "null head"?

**Comment by e-im** [comment]
This sounds very much like a creative thing. If you're not able to do this in survival, it'll be a wontfix. There are practically an infinite number of similar/related issues.

Creative servers should use a plugin to filter what is possible with creative mode. such issues are not generally fixed by paper.

**Comment by electronicboy** [comment]
CraftMeta should probably try to be sane, but, that's the general extent of what we care about in regards to malicously crafted data, illegal data either should be captured using a creative protection plugin, or, not created by users, vanilla does somewhat good by just not caring about the data, but, there's generally 0 care that stuff won't

**Comment by sequoiadotdev** [comment]
huh interesting, it only crashes paper, not spigot or etc
