### ISSUE TITLE
Paper 1.18.2-348 breaks Multiverse-Core

### ISSUE THREAD

**Issue by SlimeDog** [PaperSpigot/Paper#7850]
### Expected behavior

Worlds load correctly

### Observed/Actual behavior

world, world_nether and world_the_end fail to load.

```
[07:45:52] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot create a world with key minecraft:world_the_end and name world_the_end one (or both) already match a world that exists
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.createWorld(CraftServer.java:1152)
[07:45:52] [Server thread/WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:767)
[07:45:52] [Server thread/WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:461)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[07:45:52] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] The world 'world_the_end' could NOT be loaded because it contains errors and is probably corrupt!
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'world_the_end'
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[07:45:52] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot create a world with key minecraft:world and name world one (or both) already match a world that exists
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.createWorld(CraftServer.java:1152)
[07:45:52] [Server thread/WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:767)
[07:45:52] [Server thread/WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:461)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[07:45:52] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] The world 'world' could NOT be loaded because it contains errors and is probably corrupt!
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'world'
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
[07:45:52] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot create a world with key minecraft:world_nether and name world_nether one (or both) already match a world that exists
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.createWorld(CraftServer.java:1152)
[07:45:52] [Server thread/WARN]:        at org.bukkit.Bukkit.createWorld(Bukkit.java:767)
[07:45:52] [Server thread/WARN]:        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:461)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[07:45:52] [Server thread/WARN]:        at Multiverse-Core-4.3.2-b870.jar//com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[07:45:52] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[07:45:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[07:45:52] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[07:45:52] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] The world 'world_nether' could NOT be loaded because it contains errors and is probably corrupt!
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] Try using Minecraft Region Fixer to repair your world! 'world_nether'
[07:45:52] [Server thread/ERROR]: [Multiverse-Core] https://github.com/Fenixin/Minecraft-Region-Fixer
```

Reference: https://github.com/Multiverse/Multiverse-Core/issues/2773

### Steps/models to reproduce

- Update Paper from 345 to 348 or 349. No other changes from previous execution.
- Start server.
- Read log.

Revert to Paper 345 removes issue.

### Plugin and Datapack List

```
[07:41:02 INFO]: Multiverse-Core               4.3.2-SNAPSHOT-b870
[07:41:02 INFO]: Multiverse-Inventories        4.2.4-SNAPSHOT-b524
[07:41:02 INFO]: Multiverse-NetherPortals      4.2.3-SNAPSHOT-b808
[07:41:02 INFO]: Multiverse-Portals            4.2.2-SNAPSHOT-b852
[07:41:02 INFO]: ProtocolLib                   5.0.0-SNAPSHOT-b556
```

### Paper version

```
> version
[07:41:58 INFO]: This server is running Paper version git-Paper-349 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: b6a6544)
You are running the latest version
Previous version: git-Paper-345 (MC: 1.18.2)
```

**Comment by SlimeDog** [comment]
Confirmed fixed in Paper 1.18.2-350. Thanks.
