### ISSUE TITLE
player.openBook -> IllegalStateException: PlayerAdvancementCriterionGrantEvent

### ISSUE THREAD

**Issue by Catzy44** [PaperSpigot/Paper#7856]
### Stack trace

```
java.lang.IllegalStateException: PlayerAdvancementCriterionGrantEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:657) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.PlayerAdvancements.award(PlayerAdvancements.java:284) ~[?:?]
        at net.minecraft.advancements.CriterionTrigger$Listener.run(CriterionTrigger.java:35) ~[?:?]
        at net.minecraft.advancements.critereon.SimpleCriterionTrigger.trigger(SimpleCriterionTrigger.java:73) ~[?:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.lambda$trigger$0(InventoryChangeTrigger.java:57) ~[?:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(InventoryChangeTrigger.java:53) ~[?:?]
        at net.minecraft.server.level.ServerPlayer$2.slotChanged(ServerPlayer.java:307) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:305) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:242) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.openItemGui(ServerPlayer.java:1560) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.openBook(CraftPlayer.java:2443) ~[paper-1.18.2.jar:git-Paper-341]
        at me.catzy.utils.CustomBook.open(CustomBook.java:45) ~[EndiManager.jar:?]
        at me.catzy.players.RPlayer.showBook(RPlayer.java:128) ~[EndiManager.jar:?]
        at me.catzy.players.RPlayer$1.run(RPlayer.java:108) ~[EndiManager.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-341]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-341]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-341]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

Plugins (44): AuthMe, AutoMessage*, Brewery, ChestTerminal, Citizens, DyedBackpacks, DynaTech, EcoPower, EndiManager, Essentials, EssentialsSpawn, ExoticGarden, ExtraTools, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, FluffyMachines, FunnyGuilds, GUIShop, ImageMaps, komunikaty*, LiteXpansion, LuckPerms, MiniMOTD, MobCapturer, MoreTools, Paracopter, PlaceholderAPI, PlayerProfiles, PlayerStatistics, PlugMan, PrivateStorage, ProtocolLib, RandomTP, SensibleToolbox, SFCalc, SkinsRestorer, Slimefun, SlimefunOreChunks, SlimyTreeTaps, SoundMuffler, StatusQuery, Vault, WorldGuard, WorldGuardExtraFlags

Datapacks (5): amplified-nether, chjoicetheorem, immersive-struct, incendium, Terralith

### Actions to reproduce (if known)

Sometimes when calling player.openBook im getting an exception in the server console (the book is opening as it should)

### Paper version

This server is running Paper version git-Paper-341 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc1752f)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-277 (MC: 1.18.2)

### Other

Line 45 of CustomBook class:

p.openBook(this.book);

**Comment by kennytv** [comment]
Don't call the method asynchronously
