### ISSUE TITLE
Opening a maliciously crafted book can crash the server

### ISSUE THREAD

**Issue by plooshi** [PaperSpigot/Paper#7866]
### Expected behavior

It should open the book

### Observed/Actual behavior

The server slowly runs out of memory, then just crashes.
```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.util.Arrays.copyOf(Arrays.java:3536)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:228)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:582)
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:308)
	at java.base/java.io.StringWriter.write(StringWriter.java:106)
	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:586)
	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:418)
	at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:707)
	at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:721)
	at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:713)
	at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:721)
	at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:721)
	at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:721)
	at com.google.gson.internal.bind.TypeAdapters$27.write(TypeAdapters.java:655)
	at com.google.gson.internal.Streams.write(Streams.java:72)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:82)
	at com.google.gson.Gson.toJson(Gson.java:735)
	at com.google.gson.Gson.toJson(Gson.java:714)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:649)
	at net.minecraft.network.chat.Component$Serializer.toJson(Component.java:423)
	at net.minecraft.world.item.WrittenBookItem.resolvePage(WrittenBookItem.java:151)
	at net.minecraft.world.item.WrittenBookItem.resolveBookComponents(WrittenBookItem.java:124)
	at net.minecraft.server.level.ServerPlayer.openItemGui(ServerPlayer.java:1597)
	at net.minecraft.world.item.WrittenBookItem.use(WrittenBookItem.java:109)
	at net.minecraft.world.item.ItemStack.use(ItemStack.java:487)
	at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:514)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2004)
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:28)
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8)
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51)
	at net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$7216/0x000000080208d3c8.run(Unknown Source)
```

### Plugin and Datapack List

Plugins (0):

### Paper version

git-Paper-b1ac25f (MC: 1.18.2)

### Other

It even crashes on my server with 16gb ram and a ryzen 5800x

**Comment by kennytv** [comment]
These kinds of issues are better reported on our Discord, tho this one is already known. Generally, most creative mode item sanitizer plugins should already handle this as well.

**Comment by infectedw** [comment]
Tested this, crashes my server to.

I found solution on Pufferfish by disableing books in pufferfish.yml.


Waiting PaperMC to patch this.

Edit: Option to disable books is called simply by disable-books: true
