### ISSUE TITLE
[Server crash] Failed to schedule load callback for chunk [127, 1393] java.util.concurrent.CompletionException: net.minecraft.ReportedException: Feature placement

### ISSUE THREAD

**Issue by Ghost-chu** [PaperSpigot/Paper#7871]
### Stack trace

```
https://paste.gg/p/anonymous/cdee94bad1af43fd92fe8b07fa9e0f42
```

### Plugin and Datapack List

```
> plugins
[21:51:54 INFO]: Plugins (0):
> datapack list
[21:52:11 INFO]: There are 17 data packs enabled: [vanilla (built-in)], [file/BlazeandCaves Advancements Pack 1.13.8 (world)], [file/HopoBetterUnderwaterRuins 1.0.5 (world)], [file/New-Desert-Temple (world)], [file/New-End-Cities (world)], [file/New-Igloo (world)], [file/New-Pillagers (world)], [file/New-Ruined-Portals (world)], [file/New-Shipwrecks (world)], [file/Terralith_v2.2.1a_Seed_6494544002992276580 (world)], [file/bukkit (world)], [file/choicetheorem-overhaul-village-1-18-2-2-8 (world)], [file/fokastudio-s-ender-expansion-v1-4a-e840 (world)], [file/nova (world)], [file/towns-and-towers-structure-overhaul-terralith-1-6 (world)], [file/HopoBetterMineshaft-1.18.2-1.1.3 (world)], [file/amplified-nether-1-18 (world)]
[21:52:11 INFO]: There are no more data packs available
>
```

### Actions to reproduce (if known)

Use command `/minecraft:tp @s 1912.1145676884657  -15.564724891612029  22460.074272494647` and fly around this position, then server will crashed.

### Paper version

```
> version
[21:52:46 INFO]: Checking version, please wait...
[21:53:24 WARN]: java.net.ConnectException: Connection timed out: connect
[21:53:24 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[21:53:24 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:579)
[21:53:24 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:568)
[21:53:24 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[21:53:24 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:53:24 WARN]:        at java.base/java.net.Socket.connect(Socket.java:633)
[21:53:24 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
[21:53:24 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[21:53:24 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[21:53:24 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[21:53:24 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[21:53:24 WARN]:        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:896)
[21:53:24 WARN]:        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
[21:53:24 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
[21:53:24 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[21:53:24 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[21:53:24 WARN]:        at java.base/java.net.URL.openStream(URL.java:1161)
[21:53:24 WARN]:        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:72)
[21:53:24 WARN]:        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:474)
[21:53:24 WARN]:        at com.google.common.io.CharSource.openBufferedStream(CharSource.java:126)
[21:53:24 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.fetchDistanceFromSiteApi(PaperVersionFetcher.java:90)
[21:53:24 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.getUpdateStatusMessage(PaperVersionFetcher.java:61)
[21:53:24 WARN]:        at com.destroystokyo.paper.PaperVersionFetcher.getVersionMessage(PaperVersionFetcher.java:35)
[21:53:24 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:205)
[21:53:24 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:189)
[21:53:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:53:24 INFO]: This server is running Paper version git-Paper-372 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: bed5cb2)
Error obtaining version information
>
```

Sorry for my bad internet connection :(.

### Other

Crash report: https://paste.gg/p/anonymous/70313650016a4a43b10a3f907e73179b

The server can be download here (edit this issue to check markdown comments):

[//]: https://drive.google.com/file/d/1H6t7A4XRNJ8eltZrXPPBph6J84j0hucE/view?usp=sharing

**Comment by Ghost-chu** [comment]
Update: I have tried Purpur and seems also crashed.

**Comment by Ghost-chu** [comment]
Update 2: Also tried with Spigot (`3493-Spigot-b081915-9d46b56`) and it prevent player login.
But there no exception or crash, just player stucking on login process for LONG time both server and client.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/30802565/172006022-7d05f29c-083e-4ae3-af3b-e0028023e9b8.png">

**Comment by Ghost-chu** [comment]
Update 3: On Vanilla jar it also doesn't working, player left in void for infinite time and in loop that waiting for chunk from server.

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/30802565/172006305-62343d0f-2236-440d-b0b9-0c244dcde46c.png">

**Comment by electronicboy** [comment]
Was just about to say to test on vanilla, this really looks like a bad datapack which is tryna do what it's complaining about, and trying to cause a structure to go into a chunk which is out of range, best guess would be to isolate which pack it is and speak to the author of it

**Comment by Ghost-chu** [comment]
> Was just about to say to test on vanilla, this really looks like a bad datapack which is tryna do what it's complaining about, and trying to cause a structure to go into a chunk which is out of range, best guess would be to isolate which pack it is and speak to the author of it

This failure seems to be persistent.
It still doesn't working even after all datapacks deleted and launch server with `--safeMode`.

The only way to recover it is delete `level.dat`.

**Comment by Ghost-chu** [comment]
~~Update 4: After delete `level.dat/WorldGenSettings` compound tag, the world seems recovered.~~

~~But this way looks will break world generating, not a good idea.~~

Doesn't work if move to new chunks

**Comment by electronicboy** [comment]
well, the gen settings are defined from the datapacks iirc, there's nothing here really for us to go off, all we can see is that something potentially modified the settings and caused a structure to try to generate in a unexpected place or something

**Comment by Ghost-chu** [comment]
> well, the gen settings are defined from the datapacks iirc, there's nothing here really for us to go off, all we can see is that something potentially modified the settings and caused a structure to try to generate in a unexpected place or something

I find there have over 1k biomes tags in level.dat, looks like impossible to find something wrong one by one.
Trying with other ways.

**Comment by Ghost-chu** [comment]
Thanks for Noah's awesome support!
I have created a custom Paper fork and print out the infomations about generator.
Now I located this issue was caused by `New-Shipwrecks`, after use command `/datapack disable file/New-Shipwrecks` to disabled it, the world recovered and server now working normal.
