### ISSUE TITLE
[1.19] Crash on startup, config related

### ISSUE THREAD

**Issue by octylFractal** [PaperSpigot/Paper#7911]
### Expected behavior

Old configurations are migrated without issue.

### Observed/Actual behavior

```
[16:15:36 ERROR]: Failed to start the minecraft server
java.lang.NullPointerException: element in path [null, null, PacketPlayInAutoRecipe]
        at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?]
        at org.spongepowered.configurate.AbstractConfigurationNode.node(AbstractConfigurationNode.java:360) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.AbstractConfigurationNode.node(AbstractConfigurationNode.java:43) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.transformation.SingleConfigurationTransformation.applySingleAction(SingleConfigurationTransformation.java:126) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.transformation.SingleConfigurationTransformation.applySingleAction(SingleConfigurationTransformation.java:97) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.transformation.SingleConfigurationTransformation.apply(SingleConfigurationTransformation.java:58) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.transformation.VersionedTransformation.apply(VersionedTransformation.java:51) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.transformation.ChainedConfigurationTransformation.apply(ChainedConfigurationTransformation.java:41) ~[configurate-core-4.1.2.jar:?]
        at io.papermc.paper.configuration.PaperConfigurations.convert(PaperConfigurations.java:328) ~[paper-1.19.jar:git-Paper-"0a21166"]
        at io.papermc.paper.configuration.PaperConfigurations.setup(PaperConfigurations.java:294) ~[paper-1.19.jar:git-Paper-"0a21166"]
        at net.minecraft.server.Services.create(Services.java:30) ~[paper-1.19.jar:git-Paper-"0a21166"]
        at net.minecraft.server.Main.main(Main.java:152) ~[paper-1.19.jar:git-Paper-"0a21166"]
        at org.bukkit.craftbukkit.Main.main(Main.java:289) ~[paper-1.19.jar:git-Paper-"0a21166"]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

My old config file: https://gist.github.com/octylFractal/37cd1f80fb3b33cbb4f120a67cfbacca

Should just happen on startup.

### Plugin and Datapack List

N/A, didn't even start loading.

### Paper version

`paper-1.19.jar:git-Paper-"0a21166"`, I guess?

**Comment by Blzd87** [comment]
Can confirm this issue

https://img.justblzd.com/e4814f.png

**Comment by e-im** [comment]
that is an unrelated (but also known) issue Blzd87.

the original issue report is with packet limiter migration and is only present on reobf (normal, non-development) jars

**Comment by kennytv** [comment]
Fixed by https://github.com/PaperMC/Paper/commit/5ac29fcb93a7d3b9fcae744d878d7303cf986953 (if you move back your old paper.yml and delete the config directory)
