### ISSUE TITLE
[1.19] Configuration Migration Issues

### ISSUE THREAD

**Issue by e-im** [PaperSpigot/Paper#7913]
Please put all 1.19 configuration migration related issues as comments on this thread. Known issues will be added here.

## Known issues:
- ~~packet limiter overrides are not correctly accounted for on a reobf server (https://github.com/PaperMC/Paper/issues/7911)~~ https://github.com/PaperMC/Paper/commit/5ac29fcb93a7d3b9fcae744d878d7303cf986953
- ~~`async-chunks.threads` was set away from the auto value of `-1`~~ https://github.com/PaperMC/Paper/commit/02b5ec4c7880c5a22f4add590ef559dae4d768db
- ~~`alt-item-despawn-rate` was migrated incorrectly or not at all~~ https://github.com/PaperMC/Paper/commit/02b5ec4c7880c5a22f4add590ef559dae4d768db
- ~~Missing entity type entries in `despawn-ranges` causes a crash on world load.~~ https://github.com/PaperMC/Paper/commit/76f81aec25f04056c1f681482cf31071a75ea748

**Comment by AnthyUwU** [comment]
Loads of what it seems to be de-serialization errors over here.

It was a 2 day old 1.18.2 server with some datapacks from Vanilla Tweaks (Don't know if it's important but mentioning anyway) and the "SkinRestorer" plugin.
I just changed the old server jar for the new one and tried running it.
[latest.log](https://github.com/PaperMC/Paper/files/8874588/latest.log)

**Comment by electronicboy** [comment]
That's completely irrelevant to this issue

**Comment by e-im** [comment]
Thanks for the report! This is unrelated to configuration and has been fixed in experimental build 2

**Comment by AnthyUwU** [comment]
> Thanks for the report! This is unrelated and has been fixed in experimental build 2

Oof, sorry! Thought any errors while migrating were related not specifically the migration ones. Glad to know it was fixed though!

**Comment by Blzd87** [comment]
unsure if this is right spot sorry if is... but downloaded build 2 and it doesnt even load without crash

https://img.justblzd.com/ed306f.png

**Comment by e-im** [comment]
That is my mistake; not sure what happened there at all. It will be fixed in a moment.

**Comment by Folas1337** [comment]
Since I seem to have had some errors, just for completion here's my paper.yml I had before: https://paste.gg/p/anonymous/ac947dd04450483f886cbafbd9c1ecea

Several settings weren't copied including the velocity-support section, anti-xray, entity-per-chunk-save-limit, max-auto-save-chunks-per-tick and a lot more that I didn't check yet.

I still have to verify it with experimental build 2 once it's working :)

**Comment by Machine-Maker** [comment]
@Folas1337 please post any stacktraces that may have appeared in the logs. I just ran your config through the migration and I see the velocity section (it moved, search for `velocity`), I see anti-xray (in `paper-world-defaults.yml`). Please make sure the settings you are talking about are acutally missing, and not just renamed. TONS of settings were renamed, put in different places etc. I see `entity-per-chunk-save-limit` in `paper-world-defaults.yml` for example.

**Comment by Folas1337** [comment]
settings.async-chunks.threads: -1
got translated to
asyncchunks.threads: 4
(which might be the expected outcome)

world-settings.default.auto-save-interval: -1
got translated to
chunks.auto-save-interval: default
(which might be the expected outcome)

world-settings.default.alt-item-despawn-rate.enabled: true
got translated to
entities.spawning.alt-item-despawn-rate.enabled: false
(certainly not expected outcome)
Neither did any of the items I had set up get translated.

I haven't gotten any errors or stacktraces while the server was running.
I was aware that some settings were renamed but now in experimental version 3 it seems to have been fixed.

The three mentioned above are still present though.

Edit 1: Also any world specific settings were not migrated, which are mostly just anti-xray and feature-seeds.

**Comment by Machine-Maker** [comment]
@Folas1337 are you sure? look inside the world folders. I specifically checked for that too. Like I saw the antixray settings for world_survival_nether and world_survival_the_end

**Comment by Folas1337** [comment]
Ah alright, I take that one back, totally missed they're in the world folders. Thanks for clarifying, the other 3 are still valid though.
I am sure about those :)

**Comment by Machine-Maker** [comment]
Ok, async-chunks.threads being set away from -1 is a bug, and the alt-item-despawn-rate enabled being flipped is too. the 2nd one tho is supposed to happen. `-1` was the `default` before.

EDIT: @Folas1337 both of those issues should be resolved when the next build is posted.

**Comment by Blzd87** [comment]
Build 4 crashes using my SMP backup.

https://gist.github.com/45639ba51372133cb44dce4dc2575186

**Comment by aurorasmiles** [comment]
> Build 4 crashes using my SMP backup.
> 
> https://gist.github.com/45639ba51372133cb44dce4dc2575186

don't think this has anything to do with the config migration, please open a seperate issue for that

**Comment by SirKillian** [comment]
After trying experimental 4, one out of my six worlds did not convert properly.

My backup file `paper.yml.old` shows:
```
world-settings:
  Spawn:
    keep-spawn-loaded-range: 6
    keep-spawn-loaded: true
```
But my `paper-world.yml` in my `Spawn` directory shows:
```
# This is a world configuration file for Paper.
# This file may start empty but can be filled with settings to override ones in the config/world-defaults.yml

_version: 28
```

No console errors so I'm not sure if this report is helpful in the first place.

**Comment by nopjar** [comment]
With using experimental 4 I get this error: https://pastebin.pl/view/831db527

First time trying to update a 1.17 server to 1.19.

**Comment by Strahilchu** [comment]
> With using experimental 4 I get this error: https://pastebin.pl/view/831db527
> 
> First time trying to update a 1.17 server to 1.19.

I don't think you can jump from 1.17 to 1.19

**Comment by Blzd87** [comment]
build 5 still crashes on start 
https://gist.github.com/d76ddba314f7abc3939030463fb7fed6

**Comment by Machine-Maker** [comment]
That log doesn't help at all. Please provide the latest.log instead of the crash report.

**Comment by entity** [comment]
Got this error the first time I swapped from Spigot 1.19 to Paper 1.19, weirdly on second boot I got no errors, but still wanted to report it.
https://gist.github.com/heychazza/4058e6fbde6563aa13582b4514590cf3

**Comment by Machine-Maker** [comment]
Use the latest experimental build, build 5 @heychazza

**Comment by Folas1337** [comment]
I've verified with build 5 and can't find any errors anymore.
What I haven't verified though is that there wasn't any configuration missed entirely, I only looked in the new file and checked if all the settings that are present there had the same values as in the old config.

If any configs were missing in the new file entirely I wouldn't have noticed. Might check that later... maybe someone else does before me, then feel free to report :)

**Comment by entity** [comment]
> Use the latest experimental build, build 5 @heychazza

Just tried again with a fresh copy from a backup, worked fine this time. Thank you lots!

**Comment by Folas1337** [comment]
> > Use the latest experimental build, build 5 @heychazza
> 
> Just tried again with a fresh copy from a backup, worked fine this time. Thank you lots!

Also please stop discussing this any further, it has nothing to do with this thread!

**Comment by Machine-Maker** [comment]
@SirKillian can you post your full paper.yml? There should've been a backup made of it. I can't seem to replicate your issue. Setting server.properties level-name=Spawn and adding those 2 lines to a default 1.18.2 config works fine. They show up in the Spawn folder's config file in the right place.

**Comment by SirKillian** [comment]
> @SirKillian can you post your full paper.yml? 

@Machine-Maker https://paste.helpch.at/ixucigoyiv.yml

**Comment by nopjar** [comment]
Still getting the server crash on startup with experimental v5. Log: https://pastebin.pl/view/574f1a77

**Comment by nopjar** [comment]
> Still getting the server crash on startup with experimental v5. Log: https://pastebin.pl/view/574f1a77

Just to give you an update: This issue is not caused by paper! There existed a file in the directory which was called `config`.

**Comment by e-im** [comment]
Missing entity types under `despawn-ranges` causes the server to crash after world load (#7935)
```kt
[22:30:49 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1570) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.papermc.paper.configuration.WorldConfiguration$Entities$Spawning$DespawnRange.hard()" because the return value of "java.util.Map.get(Object)" is null
	at net.minecraft.world.entity.Mob.checkDespawn(Mob.java:806) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:678) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	... 5 more
```

I'm not sure if the best way to handle this is just to 1. check this and exit earlier for invalid config, 2. add missing entries on load, or 3. provide a default value for missing entries but do not write to the config file.

**Comment by Blzd87** [comment]
> That log doesn't help at all. Please provide the latest.log instead of the crash report.

https://gist.github.com/94ddff9e1c49f4d8d45dd7ee191258ac

**Comment by Machine-Maker** [comment]
> Missing entity types under `despawn-ranges` causes the server to crash after world load (#7935)
> 
> ```kotlin
> [22:30:49 ERROR]: Encountered an unexpected exception
> net.minecraft.ReportedException: Exception ticking world
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1570) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
> 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.NullPointerException: Cannot invoke "io.papermc.paper.configuration.WorldConfiguration$Entities$Spawning$DespawnRange.hard()" because the return value of "java.util.Map.get(Object)" is null
> 	at net.minecraft.world.entity.Mob.checkDespawn(Mob.java:806) ~[?:?]
> 	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:678) ~[?:?]
> 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
> 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
> 	... 5 more
> ```

Resolved in 76f81aec25f04056c1f681482cf31071a75ea748

**Comment by IntroCDC** [comment]
Loading world in dimension nether or the end with mca files generated in overworld causes a large error flood in console (this log a lot of times), the world load correctly but causes this flood

`[07:11:25 WARN]: Failed to load light data for chunk [-21, 11] in world 'TheNether', light will be regenerated
java.lang.IllegalArgumentException: Data cannot be null and have state be initialised
	at ca.spottedleaf.starlight.common.light.SWMRNibbleArray.(SWMRNibbleArray.java:80) ~[paper-1.19.jar:git-Paper-"55201f0"]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:262) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:117) ~[paper-1.19.jar:git-Paper-"55201f0"]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:42) ~[paper-1.19.jar:git-Paper-"55201f0"]
	at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.19.jar:git-Paper-"55201f0"]
	at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:62) ~[paper-1.19.jar:git-Paper-"55201f0"]`

**Comment by sovtec** [comment]
Dont know why so many is having issues with the experimental versions. I updated and merged a 1.18 server with 20 plugins without a single issue O.o

**Comment by Owen1212055** [comment]
@IntroCDC Was this world created/used at any point during older experimental builds?

**Comment by Codzsters** [comment]
Hi there - Aurora told me to post a comment here.

Basically - I'm having issues when upgrading from 1.18.2 to the Paper 1.19-3 experimental build. When I do, it creates a bunch of folders. I have attached a screenshot of some of the folders and my old paper.yml config from my 1.18.2 server.

Cheers
Codzsters
![Screen Shot 2022-06-12 at 10 10 17 PM](https://user-images.githubusercontent.com/106864431/173229221-82de662e-eca0-415c-83aa-cc9fb9873cab.png)

Paper.yml File (sorry I had to save it as a txt file as it wouldn't let me upload .yml files here)
[paper.txt](https://github.com/PaperMC/Paper/files/8885662/paper.txt)

**Comment by kennytv** [comment]
Your old Paper config is invalid/broken, everything you have under `world-settings` (except the two world overrides at the bottom) should be under `world-settings.default`

**Comment by Codzsters** [comment]
> 

I'm a bit confused. So I should remove everything under `world-settings` and leave the `default:` section? Sorry to be a hassle!

**Comment by kennytv** [comment]
Just remove everything between `world-settings:` and `default:` if you didn't touch the things between those. If you did, replace everything under `default:` until the two worlds at the end with that

**Comment by alezhshede** [comment]
I was told to post my old config here. as it prevented my server from starting when upgrading to papermc 1.19 expiremental.
I dont know the issue.

https://paste.gg/p/Pencil/79a94922f40a426caade0f8c646fd6d9

after deleting both the config and the old one. it worked

**Comment by kennytv** [comment]
> I was told to post my old config here. as it prevented my server from starting when upgrading to papermc 1.19 expiremental. I dont know the issue.
> 
> https://paste.gg/p/Pencil/79a94922f40a426caade0f8c646fd6d9
> 
> after deleting both the config and the old one. it worked

`velocity-support.enabled` is a boolean, so it has to be `true` or `false`

**Comment by alezhshede** [comment]
> > I was told to post my old config here. as it prevented my server from starting when upgrading to papermc 1.19 expiremental. I dont know the issue.
> > https://paste.gg/p/Pencil/79a94922f40a426caade0f8c646fd6d9
> > after deleting both the config and the old one. it worked
> 
> `velocity-support.enabled` is a boolean, so it has to be `true` or `false`

Alright. well i've never touched that setting but after changing it, it works

**Comment by surfrock66** [comment]
Certain fields which were configured previously as maps (and were working) are causing my server to not start, as it is looking for lists.  Per the discussion on the paper forums, the 1.18.2 config was likely "invalid" but as it worked there and did not work in 1.19 after the config conversion, the experience was confusing.  Maybe it can be a case where "lists" defined as "maps" could be converted as part of the conversion?

The issue is resolved by changing "{}" to "[]" in the config files.

Server error log: 
```
[20:46:20 ERROR]: Encountered an unexpected exception
org.spongepowered.configurate.serialize.SerializationException: [anticheat, anti-xray, hidden-blocks] of type java.lang.String: Value must be provided as a scalar!
    at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:101) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:69) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
    at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
    at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:139) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:221) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
    Suppressed: org.spongepowered.configurate.serialize.SerializationException: [anticheat, anti-xray, replacement-blocks] of type java.lang.String: Value must be provided as a scalar!
        at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:101) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:69) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
        at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:139) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:221) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:46:20 WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null
    at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$15(MinecraftServer.java:1692) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at net.minecraft.SystemReport.setDetail(SystemReport.java:61) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1691) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"d1b1c6f"]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Full log file: https://paste.gg/p/anonymous/9dc3dabf6fc748e9836b194662f22e68/files/ab36129599384284b5a87cf30258f7a6/raw

Relevant section of 1.19 paper-world-defaults.yml:
```
anticheat:
  anti-xray:
    chunk-edge-mode: 3
    enabled: false
    engine-mode: 1
    hidden-blocks: {}
    lava-obscures: false
    max-block-height: 64
    max-chunk-section-index: 3
    replacement-blocks: {}
    update-radius: 2
    use-permission: false
```

1.18.2 paper.yml: https://paste.gg/p/anonymous/d54b1f2a0acb482cbfd4a9405795b670/files/e073226ec0d744fd8311c53b3903f11e/raw

I made a thread about this in the forum if the additional info is helpful:  https://forums.papermc.io/threads/server-wont-start-compiled-from-the-latest-git-commit-currently-d1b1c6f.359/

**Comment by comonier** [comment]
```java
[14:23:00 INFO]: Loading properties
[14:23:00 INFO]: This server is running Paper version git-Paper-29 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 9797f08)
[14:23:01 INFO]: Using 4 threads for Netty based IO
[14:23:01 INFO]: Server Ping Player Sample Count: 12
[14:23:01 INFO]: Default game type: SURVIVAL
[14:23:01 INFO]: Generating keypair
[14:23:01 INFO]: Starting Minecraft server on 0.0.0.0:25734
[14:23:01 INFO]: Using epoll channel type
[14:23:02 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[14:23:02 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[14:23:02 WARN]: **** FAILED TO BIND TO PORT!
[14:23:02 WARN]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
[14:23:02 WARN]: Perhaps a server is already running on that port?
[14:23:02 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-29]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:23:02 WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null
        at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$15(MinecraftServer.java:1692) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.SystemReport.setDetail(SystemReport.java:61) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1691) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[paper-1.19.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-29]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:23:02 ERROR]: This crash report has been saved to: /root/cracked/./crash-reports/crash-2022-06-19_14.23.02-server.txt
[14:23:02 INFO]: Stopping server
```
help ? ( everthing was working ) after i try use plugman load chestshop.jar by console server crash and it happens,
already tried rename world folder to .bkp and let server generate a new one but the problem still in loop. not corrupted world folder so...., already try rename config folder, but still on the same, already try change paper version still same problem

**Comment by electronicboy** [comment]
Nothing to do with this issue, you already have something running on that port

**Comment by comonier** [comment]
> Nothing to do with this issue, you already have something running on that port

solution:
![image](https://user-images.githubusercontent.com/19571541/174494638-bb4c6b49-4c75-44bc-a755-a71ba7f634a4.png)

**Comment by aurorasmiles** [comment]
Please go to our Discord for support. Your issue has nothing to do with what we are talking here

**Comment by aurorasmiles** [comment]
Since we didn't receive any other reports for over a month now, and all the known issues have been fixed, I'm closing this. If anyone else finds a config migration issue please open a new issue.
