### ISSUE TITLE
Papermc load chunk error in console

### ISSUE THREAD

**Issue by sebberj** [PaperSpigot/Paper#7915]
### Expected behavior

Hi my console keeps spamming this error after updating to paper 1.19. There are nothing wrong ingame, and i also tried to teleport to the coordinates ingame, nothing wrong.. 

Errror: 

https://pastebin.com/EMCSkUuD

My issue is that it is spamming my console every second...

### Observed/Actual behavior

java.lang.IllegalArgumentException: Data cannot be null and have state be initialised
        at ca.spottedleaf.starlight.common.light.SWMRNibbleArray.<init>(SWMRNibbleArray.java:80) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:257) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:117) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:42) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.19.jar:git-Paper-"4a51a54"]
[00:33:22 ERROR]: [com.destroystokyo.paper.io.chunk.ChunkLoadTask] Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (206,74), hashcode:2086616201, priority: -1
java.lang.IllegalArgumentException: Data cannot be null and have state be initialised
        at ca.spottedleaf.starlight.common.light.SWMRNibbleArray.<init>(SWMRNibbleArray.java:80) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:257) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:117) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:42) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.19.jar:git-Paper-"4a51a54"]
[00:33:22 ERROR]: [com.destroystokyo.paper.io.chunk.ChunkLoadTask] Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (206,75), hashcode:817982118, priority: -1

### Steps/models to reproduce

It starts when i start the server

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/22130787/172967869-9d44e4b5-fadd-47cb-ae6a-1041d5723295.png)

### Paper version

paper-1.19-experimental-3-mojang-mapped

**Comment by Owen1212055** [comment]
Can confirm, looking into this *again*.

**Comment by matipoirierg** [comment]
similar issue for me while pregenerating with chunky. https://pastebin.com/nHDESQ2S

**Comment by Impactic48** [comment]
I'm also getting the same issue: https://mclo.gs/CeBHmSu (Fresh v3 world with no plugins)

**Comment by velnias75** [comment]
Confirm, too.

**Comment by electronicboy** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/83e2a3582bbeea78b54b7430ebe0c336e97e5575
