### ISSUE TITLE
Error while trying to fill chunks

### ISSUE THREAD

**Issue by BenTheLlama** [PaperSpigot/Paper#7916]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
[00:56:03 ERROR]: [com.destroystokyo.paper.io.chunk.ChunkLoadTask] Could not de-serialize chunk data for task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world', (-23,-4), hashcode:1088258695, priority: -1
java.lang.IllegalArgumentException: Data cannot be null and have state be initialised
        at ca.spottedleaf.starlight.common.light.SWMRNibbleArray.<init>(SWMRNibbleArray.java:80) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:257) ~[?:?]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:117) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:42) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:118) ~[paper-1.19.jar:git-Paper-"4a51a54"]
        at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:51) ~[paper-1.19.jar:git-Paper-"4a51a54"]

### Plugin and Datapack List

dynmap, LuckPerms, mcMMO, WorldBorder

### Actions to reproduce (if known)

was filling chunks when error appeared, threw lots of these errors, even after stopping the fill and rebooting

### Paper version

[00:58:33 INFO]: Checking version, please wait...
[00:58:34 INFO]: This server is running Paper version git-Paper-"4a51a54" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 4a51a54 on dev/1.19)
Error obtaining version information

### Other

Issue started after trying to fill chunks, persisted after stopping fill and rebooting

**Comment by Owen1212055** [comment]
Dupe of https://github.com/PaperMC/Paper/issues/7915

**Comment by e-im** [comment]
Duplicate of #7915
