### ISSUE TITLE
Failed to start paper-1.19-experimental-4

### ISSUE THREAD

**Issue by schneidermr** [PaperSpigot/Paper#7922]
### Stack trace

```log
2022-06-10 12:23:26 | net.minecraft.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:COBBLESTONE
-- | --
  |   | 2022-06-10 12:23:26 | at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[?:?]
  |   | 2022-06-10 12:23:26 | at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[?:?]
  |   | 2022-06-10 12:23:26 | at io.papermc.paper.configuration.transformation.world.LegacyPaperWorldConfig.lambda$notVersioned$9(LegacyPaperWorldConfig.java:139) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
  |   | 2022-06-10 12:23:26 | at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
  |   | 2022-06-10 12:23:26 | at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553) ~[?:?]
  |   | 2022-06-10 12:23:26 | at io.papermc.paper.configuration.transformation.world.LegacyPaperWorldConfig.lambda$notVersioned$10(LegacyPaperWorldConfig.java:137) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
  |   | 2022-06-10 12:23:26 | at org.spongepowered.configurate.transformation.SingleConfigurationTransformation.applySingleAction(SingleConfigurationTransformation.java:124) ~[configurate-core-4.1.2.jar:?]
  |   | 2022-06-10 12:23:26 | at org.spongepowered.configurate.transformation.SingleConfigurationTransformation.apply(SingleConfigurationTransformation.java:58) ~[configurate-core-4.1.2.jar:?]
  |   | 2022-06-10 12:23:26 | at org.spongepowered.configurate.transformation.ChainedConfigurationTransformation.apply(ChainedConfigurationTransformation.java:41) ~[configurate-core-4.1.2.jar:?]
  |   | 2022-06-10 12:23:26 | at io.papermc.paper.configuration.PaperConfigurations.convert(PaperConfigurations.java:335) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
  |   | 2022-06-10 12:23:26 | at io.papermc.paper.configuration.PaperConfigurations.setup(PaperConfigurations.java:294) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
  |   | 2022-06-10 12:23:26 | at net.minecraft.server.Services.create(Services.java:30) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
  |   | 2022-06-10 12:23:26 | at net.minecraft.server.Main.main(Main.java:152) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
  |   | 2022-06-10 12:23:26 | at org.bukkit.craftbukkit.Main.main(Main.java:289) ~[paper-1.19.jar:git-Paper-"02b5ec4"]
  |   | 2022-06-10 12:23:26 | at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
  |   | 2022-06-10 12:23:26 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

EssentialsX-2.19.4.jar
EssentialsXChat-2.19.4.jar
EssentialsXGeoIP-2.19.4.jar
EssentialsXProtect-2.19.4.jar
LuckPerms-Bukkit-5.4.26.jar
Multiverse-Core-4.3.1.jar
Vault.jar
spark-1.9.11-bukkit.jar
worldedit-bukkit-7.2.10.jar
worldguard-bukkit-7.0.7-dist.jar

### Paper version

paper-1.19-experimental-4

**Comment by kennytv** [comment]
Fixed by https://github.com/PaperMC/Paper/commit/dd6a8e939435807606c72bdff78bdb1e192ba3b0
