### ISSUE TITLE
Custom Entity Taglists can't be referenced in datapack functions

### ISSUE THREAD

**Issue by Window0** [PaperSpigot/Paper#7928]
### Expected behavior

I made a test datapack with this entity taglist:

{
  "replace": false,
  "values": [
    "#minecraft:arrows",
    "minecraft:snowball",
    "minecraft:egg",
    "minecraft:fireball",
    "minecraft:small_fireball",
    "minecraft:dragon_fireball",
    "minecraft:trident",
    "minecraft:wither_skull",
    "minecraft:shulker_bullet",
    "minecraft:llama_spit"
  ]
}

and this command (in a function):

execute if entity @e[type=#custom:reflectable_projectiles] run say hi

### Observed/Actual behavior

When loading the datapack, the server gave me this error:

[18:05:54] [ServerMain/ERROR]: Failed to load function custom:test
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Could not parse command: Cannot read field "commands" because the return value of "io.papermc.paper.configuration.GlobalConfiguration.get()" is null at position 57: ...rojectiles<--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Could not parse command: Cannot read field "commands" because the return value of "io.papermc.paper.configuration.GlobalConfiguration.get()" is null at position 57: ...rojectiles<--[HERE]
	at net.minecraft.commands.CommandFunction.fromLines(CommandFunction.java:68) ~[?:?]
	at net.minecraft.server.ServerFunctionLibrary.lambda$reload$3(ServerFunctionLibrary.java:84) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more

### Steps/models to reproduce

-set up a paper server without any plugins
-install my test datapack
-try to run test.mcfunction
-the taglist doesn't work in functions, but it still works if you run the same command in chat

### Plugin and Datapack List

Here's the datapack I used to test this issue. No plugins or other datapacks were used.

[testpack taglists.zip](https://github.com/PaperMC/Paper/files/8880477/testpack.taglists.zip)

### Paper version

[18:21:02 INFO]: This server is running Paper version git-Paper-"9b6fb2f" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 9b6fb2f on dev/1.19)

### Other

I tried setting `fix-target-selector-tag-completion` to false, but it had no effect.

**Comment by Machine-Maker** [comment]
Fixed in https://github.com/PaperMC/Paper/commit/99aa5f2fa57ccc17f936d51097d2b01504aa72dd
