### ISSUE TITLE
Server Crash due to unexpected exception regarding entities in world

### ISSUE THREAD

**Issue by nopjar** [PaperSpigot/Paper#7935]
### Stack trace

```
[22:52:16] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1570) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.papermc.paper.configuration.WorldConfiguration$Entities$Spawning$DespawnRange.hard()" because the return value of "java.util.Map.get(Object)" is null
	at net.minecraft.world.entity.Mob.checkDespawn(Mob.java:806) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:678) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	... 5 more
[22:52:16] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "io.papermc.paper.configuration.WorldConfiguration$Entities$Spawning$DespawnRange.hard()" because the return value of "java.util.Map.get(Object)" is null
	at net.minecraft.world.entity.Mob.checkDespawn(Mob.java:806) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:678) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-"9b6fb2f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

I'm not able to share this information. But there are no datapacks.

### Paper version

Paper 1.19 - Experimental Build 5

**Comment by e-im** [comment]
what do you have your spawn ranges set to in paper-world-default.yml? Ideally please upload your paper-world-default.yml, or at least that section of it here.

**Comment by nopjar** [comment]
```yml
entities.spawning:
    all-chunks-are-slime-chunks: false
    alt-item-despawn-rate:
      enabled: false
      items:
        cobblestone: 300
    count-all-mobs-for-spawning: false
    creative-arrow-despawn-rate: default
    despawn-ranges:
      ambient:
        hard: 128
        soft: 32
      creature:
        hard: 128
        soft: 32
      misc:
        hard: 128
        soft: 32
      monster:
        hard: 128
        soft: 32
      underground_water_creature:
        hard: 128
        soft: 32
      water_ambient:
        hard: 64
        soft: 32
      water_creature:
        hard: 128
        soft: 32
    disable-mob-spawner-spawn-egg-transformation: false
    duplicate-uuid:
      mode: SAFE_REGEN
      safe-regen-delete-range: 32
    filter-nbt-data-from-spawn-eggs-and-related: true
    iron-golems-can-spawn-in-air: false
    monster-spawn-max-light-level: -1
    non-player-arrow-despawn-rate: default
    per-player-mob-spawns: true
    scan-for-legacy-ender-dragon: true
    skeleton-horse-thunder-spawn-chance: default
    slime-spawn-height:
      slime-chunk:
        maximum: 40.0
      surface-biome:
        maximum: 70.0
        minimum: 50.0
    spawn-limits:
      ambient: -1
      creature: -1
      monster: -1
      underground_water_creature: -1
      water_ambient: -1
      water_creature: -1
    wandering-trader:
      spawn-chance-failure-increment: 25
      spawn-chance-max: 75
      spawn-chance-min: 25
      spawn-day-length: 24000
      spawn-minute-length: 1200
    wateranimal-spawn-height:
      maximum: default
      minimum: default
```

**Comment by e-im** [comment]
Add `axolotls` to `despawn-ranges` as a temp fix on your end. However, this is still an issue as that shouldn't happen. I'll move this under #7913. Thank you for your report.
