### ISSUE TITLE
Symlinked world directory not working

### ISSUE THREAD

**Issue by mbledkowski** [PaperSpigot/Paper#7969]
### Expected behavior

Server should start with symlinked "world" directory.

### Observed/Actual behavior

Server does not start with symlinked "world" directory:
[17:38:35 ERROR]:       Cause of unexpected exception was
java.nio.file.FileAlreadyExistsException: ./world
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
        at java.nio.file.Files.createDirectories(Files.java:753) ~[?:?]
        at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:184) ~[paper-1.19.jar:git-Paper-9]
        at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:173) ~[paper-1.19.jar:git-Paper-9]
        at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:262) ~[paper-1.19.jar:git-Paper-9]
        at net.minecraft.server.level.ServerLevel.lambda$new$2(ServerLevel.java:491) ~[?:?]
        at net.minecraft.world.level.Level.<init>(Level.java:277) ~[?:?]
        at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:491) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:583) ~[paper-1.19.jar:git-Paper-9]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-9]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-9]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-9]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[

### Steps/models to reproduce

- symlink world, world_nether and world_the_end to folder with Minecraft server files
- start the server using /bin/sh -c \"cd ./bin; java -Xms2G -Xmx8G -jar server.jar --nogui\"

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-9 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e4f5e1c)

**Comment by Cyberyisus2g** [comment]
Same here

**Comment by bigpresh** [comment]
Same issue here - `world` is a symlink to the world held elsewhere.  This setup worked fine pre-1.19, but I now get the same error as the OP:

```
[22:35:46 ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Could not create world config for world
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:264) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.level.ServerLevel.lambda$new$2(ServerLevel.java:491) ~[?:?]
	at net.minecraft.world.level.Level.<init>(Level.java:277) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:491) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:583) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-18]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.file.FileAlreadyExistsException: ./world
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:753) ~[?:?]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:184) ~[paper-1.19.jar:git-Paper-18]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:173) ~[paper-1.19.jar:git-Paper-18]
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:262) ~[paper-1.19.jar:git-Paper-18]
	... 9 more
[22:35:46 ERROR]: 	Cause of unexpected exception was
java.nio.file.FileAlreadyExistsException: ./world
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:398) ~[?:?]
	at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]
	at java.nio.file.Files.createDirectories(Files.java:753) ~[?:?]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:184) ~[paper-1.19.jar:git-Paper-18]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:173) ~[paper-1.19.jar:git-Paper-18]
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:262) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.level.ServerLevel.lambda$new$2(ServerLevel.java:491) ~[?:?]
	at net.minecraft.world.level.Level.<init>(Level.java:277) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:491) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:583) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-18]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by Owen1212055** [comment]
Can reproduce, working on a fix!

**Comment by wangzhizhou** [comment]
I have the same problem on my paper server,

**Comment by nijave** [comment]
Depending on the permissions and setup of your server, you might be able to bind mount as a workaround 

https://unix.stackexchange.com/a/198591
