### ISSUE TITLE
Clicking self-destructive signs kicks the player with a packet processing error

### ISSUE THREAD

**Issue by GoldenDelicios** [PaperSpigot/Paper#7970]
### Expected behavior

A sign containing a command that destroys itself, such as `setblock ~ ~ ~ minecraft:air` should do so without kicking the player.

### Observed/Actual behavior

Clicking such a sign will cause a packet processing error.

### Steps/models to reproduce

1. Make sure your character is in creative mode.
2. Run `/give @s minecraft:oak_sign{BlockEntityTag: {id: "minecraft:sign", Text1: '{"text":"","clickEvent":{"action":"run_command","value":"setblock ~ ~ ~ minecraft:air"}}'}}`
3. Place the sign and right click it.

### Plugin and Datapack List

None

### Paper version

This server is running Paper version git-Paper-10 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: bd097b4)
You are running the latest version
Previous version: git-Paper-8 (MC: 1.19)

**Comment by electronicboy** [comment]
logs? anything? have you tested on vanilla?

**Comment by Chew** [comment]
Vanilla (singleplayer) works fine.

Paper logs:
```
[13:07:26 INFO]: ChewLeKitten issued server command: /setblock ~ ~ ~ minecraft:air
[13:07:26 ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseItem@69bb643f for ChewLeKitten[/127.0.0.1:59827]
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState cannot be cast to class org.bukkit.block.Sign (org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState and org.bukkit.block.Sign are in unnamed module of loader java.net.URLClassLoader @1de0aca6)
	at net.minecraft.world.level.block.entity.SignBlockEntity.executeClickCommands(SignBlockEntity.java:234) ~[?:?]
	at net.minecraft.world.level.block.SignBlock.use(SignBlock.java:111) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1052) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:571) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1872) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-10]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:07:26 INFO]: ChewLeKitten lost connection: Packet processing error
[13:07:26 INFO]: ChewLeKitten left the game
```

**Comment by GoldenDelicios** [comment]
Tested on a vanilla 1.19 server and this does not happen.

Server logs:
```
[17:48:17 ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInUseItem@674bd2bb for GoldenDelicios[/xxx.xxx.xxx.xxx:xxxxx]
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState cannot be cast to class org.bukkit.block.Sign (org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockState and org.bukkit.block.Sign are in unnamed module of loader java.net.URLClassLoader @2957fcb0)
        at net.minecraft.world.level.block.entity.SignBlockEntity.executeClickCommands(SignBlockEntity.java:234) ~[?:?]
        at net.minecraft.world.level.block.SignBlock.use(SignBlock.java:111) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1052) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:571) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1872) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-10]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-10]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:48:17 INFO]: GoldenDelicios lost connection: Packet processing error
[17:48:17 INFO]: GoldenDelicios left the game
```
