### ISSUE TITLE
Problem with CMIs Holograms with floating Items

### ISSUE THREAD

**Issue by CloudeLecaw** [PaperSpigot/Paper#7981]
### Expected behavior

Well the items should float over the hologram.

### Observed/Actual behavior

a big issue in the console

```
Craft Scheduler Thread - 430 - CMI: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:87)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:77)
	at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
	at net.minecraft.world.level.levelgen.BitRandomSource.j(BitRandomSource.java:54)
	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:67)
	at CMI_9.2.0.0.jar//com.Zrips.CMI.NBT.v1_19_R1.makeFloatingIcon(v1_19_R1.java:927)
	at CMI_9.2.0.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1400)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:83)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.BitRandomSource.j(BitRandomSource.java:54)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:67)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at CMI_9.2.0.0.jar//com.Zrips.CMI.NBT.v1_19_R1.makeFloatingIcon(v1_19_R1.java:927)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at CMI_9.2.0.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1400)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:79)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:45)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.BitRandomSource.nextDouble(BitRandomSource.java:54)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.entity.item.ItemEntity.<init>(ItemEntity.java:67)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	... 8 more
[22:37:44] [Craft Scheduler Thread - 471 - CMI/ERROR]: Thread dumps: 
Craft Scheduler Thread - 471 - CMI: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:87)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:77)
	at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
	at net.minecraft.world.level.levelgen.BitRandomSource.j(BitRandomSource.java:54)
	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:67)
	at CMI_9.2.0.0.jar//com.Zrips.CMI.NBT.v1_19_R1.makeFloatingIcon(v1_19_R1.java:927)
	at CMI_9.2.0.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1400)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:83)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.BitRandomSource.j(BitRandomSource.java:54)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:67)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at CMI_9.2.0.0.jar//com.Zrips.CMI.NBT.v1_19_R1.makeFloatingIcon(v1_19_R1.java:927)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at CMI_9.2.0.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1400)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:79)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:45)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.BitRandomSource.nextDouble(BitRandomSource.java:54)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.entity.item.ItemEntity.<init>(ItemEntity.java:67)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	... 8 more
```

### Steps/models to reproduce

Create some holograms with CMI and let it have floaring items..
after some holograms an error in console is coming. Thats new in 1.19...

### Plugin and Datapack List

CMI, CMILib, Vault. CMIInjector

### Paper version

Paper 1.19-10

### Other

I posted this first on CMI Github

https://github.com/Zrips/CMI/issues/6970

The Dev Zrips told me there it normaly would be part of paper to fix this issue...

So i came here..

**Comment by kennytv** [comment]
That's a CMI issue
