### ISSUE TITLE
{world}.dropItemNaturally(...) causes exception: Cannot drop air

### ISSUE THREAD

**Issue by ScotcherDev** [PaperSpigot/Paper#7993]
### Expected behavior

Normally, the item should drop without giving an error in the console.

### Observed/Actual behavior

``I have programmed a plugin that makes it possible for me to right-click on a fully grown crop and thereby harvest and replant it.
To do this, I generate a droptable by method, which then run through a for loop using an iterator. Each pass of the loop should drop one of the items.

If I drop the item using the dropItemNaturally(...) method, an error message is generated in the console. If I drop the item with the dropItem(...) method, no error is generated anymore.

The error looks like this:
```
[19:45:06] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to PaperUtilities v1.4
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.world.entity.item.ItemEntity.setItem(ItemEntity.java:512) ~[?:?]
	at net.minecraft.world.entity.item.ItemEntity.<init>(ItemEntity.java:74) ~[?:?]
	at net.minecraft.world.entity.item.ItemEntity.<init>(ItemEntity.java:67) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.dropItem(CraftWorld.java:692) ~[paper-1.19.jar:git-Paper-8]
	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.dropItemNaturally(CraftWorld.java:715) ~[paper-1.19.jar:git-Paper-8]
	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.dropItemNaturally(CraftWorld.java:703) ~[paper-1.19.jar:git-Paper-8]
	at de.scotcher.event.PlayerInteractListener.onPlayerClickCrops(PlayerInteractListener.java:54) ~[PaperUtilities.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor122.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:527) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1872) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-8]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

I have already tried to check via logger if the item to be dropped really does not correspond to `Material.AIR`. Not once was the AIR item included.

### Steps/models to reproduce

When I use this class, it works perfectly:

```
package de.scotcher.event;

import java.util.Collection;
import java.util.Iterator;
import java.util.Random;

import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.data.Ageable;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.PlayerInventory;
import org.bukkit.inventory.meta.Damageable;
import org.bukkit.inventory.meta.ItemMeta;

import de.scotcher.main.PaperUtilities;

public class PlayerInteractListener implements Listener {

	@SuppressWarnings("unused")
	private PaperUtilities plugin;
	public PlayerInteractListener(PaperUtilities plugin) {
		this.plugin = plugin;
	}
	
	@EventHandler
	public void onPlayerClickCrops(PlayerInteractEvent e) {
		Player p = e.getPlayer();
		Action action = e.getAction();
		Block block = e.getClickedBlock();
		
		if (action != Action.RIGHT_CLICK_BLOCK) {
			return;
		}
		
		if (!isCrop(block)) {
			return;
		}
		
		for (Iterator<ItemStack> iterator = generatedDrops(p, block).iterator(); iterator.hasNext();) {
			ItemStack item = (ItemStack) iterator.next();
			
			if (item == null || item.getType() == null || item.getType() == Material.AIR) {
				continue;
			}
			
			System.out.println("Item: " + item.getType().name() + " - Block: " + block.getType());
			
			p.getWorld().dropItem(block.getLocation().add(0.5, 0.2, 0.5), new ItemStack(item.getType()));
		}
		
		Ageable crop = (Ageable) block.getBlockData();
		crop.setAge(0);
		
		block.setBlockData(crop, true);
	}
	
	private boolean isCrop(Block block) {
		if (!(block.getBlockData() instanceof Ageable)) {
			return false;
		}
		
		Ageable crop = (Ageable) block.getBlockData();
		return (crop.getMaximumAge() == crop.getAge());
	}
	
	private Collection<ItemStack> generatedDrops(Player p, Block block) {
		Material mat = block.getType();
		Random random = new Random();
		int fortuneLvl = 0;
		
		PlayerInventory inv = p.getInventory();
		ItemStack mainHand = inv.getItemInMainHand();
		
		if (mainHand.containsEnchantment(Enchantment.LOOT_BONUS_BLOCKS)) {
			fortuneLvl = mainHand.getEnchantmentLevel(Enchantment.LOOT_BONUS_BLOCKS);
		}
		
		Collection<ItemStack> drops = block.getDrops();
		drops.clear();	
		
		
		if (mat == Material.WHEAT) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(3) : (fortuneLvl == 2 ? random.nextInt(4): (fortuneLvl == 3 ? random.nextInt(5) : random.nextInt(2)));
			
			drops.add(new ItemStack(Material.WHEAT, 1));
			if (maxRandomDropQuantitiy > 0) drops.add(new ItemStack(Material.WHEAT_SEEDS, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.BEETROOTS) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(4) : (fortuneLvl == 2 ? random.nextInt(5): (fortuneLvl == 3 ? random.nextInt(6) : random.nextInt(3)));
			
			drops.add(new ItemStack(Material.BEETROOT, 1));
			if (maxRandomDropQuantitiy > 0) drops.add(new ItemStack(Material.BEETROOT_SEEDS, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.CARROTS) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(4) : (fortuneLvl == 2 ? random.nextInt(5): (fortuneLvl == 3 ? random.nextInt(6) : random.nextInt(3))) + 1;
			
			drops.add(new ItemStack(Material.CARROT, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.POTATOES) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(5) : (fortuneLvl == 2 ? random.nextInt(6): (fortuneLvl == 3 ? random.nextInt(7) : random.nextInt(4))) + 1;
			int maxRandomDropQuantitiyPoisonousPotato = (int) Math.ceil(Math.random() - 0.8D);
			
			drops.add(new ItemStack(Material.POTATO, maxRandomDropQuantitiy));
			if (maxRandomDropQuantitiyPoisonousPotato > 0) drops.add(new ItemStack(Material.POISONOUS_POTATO, maxRandomDropQuantitiyPoisonousPotato));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.NETHER_WART) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(3) : (fortuneLvl == 2 ? random.nextInt(4): (fortuneLvl == 3 ? random.nextInt(5) : random.nextInt(2))) + 1;
			
			drops.add(new ItemStack(Material.NETHER_WART, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.COCOA) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(2) : (fortuneLvl == 2 ? random.nextInt(3): (fortuneLvl == 3 ? random.nextInt(4) : random.nextInt(1))) + 1;
			
			drops.add(new ItemStack(Material.COCOA_BEANS, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		return drops;
	}
	
	@SuppressWarnings("unused")
	private void damageItem(ItemStack itemInHand) {
		ItemMeta itemInHandMeta = itemInHand.getItemMeta();
		
		if (itemInHand == null) {
			return;
		}
		
		if (itemInHand.getType() == Material.AIR) {
			return;
		}
		
		if (!itemInHandMeta.isUnbreakable() && itemInHand.containsEnchantment(Enchantment.LOOT_BONUS_BLOCKS)) {
			Damageable itemInHandDamageable = (Damageable) itemInHandMeta;
			int damage = itemInHandDamageable.getDamage();
			int maxDamage = itemInHand.getType().getMaxDurability();
			
			if (damage + 1 <= maxDamage) {
				itemInHandDamageable.setDamage(damage + 1);
				itemInHand.setItemMeta(itemInHandDamageable);
				return;
			}
			
			itemInHand.setAmount(0);
		}
	}
}

```

In this class I replaced the line containing `p.getWorld().dropItem(block.getLocation().add(0.5, 0.2, 0.5), new ItemStack(item.getType()));` with `p.getWorld().dropItemNaturally(block.getLocation(), item);`:

```
package de.scotcher.event;

import java.util.Collection;
import java.util.Iterator;
import java.util.Random;

import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.data.Ageable;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.Action;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.PlayerInventory;
import org.bukkit.inventory.meta.Damageable;
import org.bukkit.inventory.meta.ItemMeta;

import de.scotcher.main.PaperUtilities;

public class PlayerInteractListener implements Listener {

	@SuppressWarnings("unused")
	private PaperUtilities plugin;
	public PlayerInteractListener(PaperUtilities plugin) {
		this.plugin = plugin;
	}
	
	@EventHandler
	public void onPlayerClickCrops(PlayerInteractEvent e) {
		Player p = e.getPlayer();
		Action action = e.getAction();
		Block block = e.getClickedBlock();
		
		if (action != Action.RIGHT_CLICK_BLOCK) {
			return;
		}
		
		if (!isCrop(block)) {
			return;
		}
		
		for (Iterator<ItemStack> iterator = generatedDrops(p, block).iterator(); iterator.hasNext();) {
			ItemStack item = (ItemStack) iterator.next();
			
			if (item == null || item.getType() == null || item.getType() == Material.AIR) {
				continue;
			}
			
			System.out.println("Item: " + item.getType().name() + " - Block: " + block.getType());
			
			block.getWorld().dropItemNaturally(block.getLocation(), item);
		}
		
		Ageable crop = (Ageable) block.getBlockData();
		crop.setAge(0);
		
		block.setBlockData(crop, true);
	}
	
	private boolean isCrop(Block block) {
		if (!(block.getBlockData() instanceof Ageable)) {
			return false;
		}
		
		Ageable crop = (Ageable) block.getBlockData();
		return (crop.getMaximumAge() == crop.getAge());
	}
	
	private Collection<ItemStack> generatedDrops(Player p, Block block) {
		Material mat = block.getType();
		Random random = new Random();
		int fortuneLvl = 0;
		
		PlayerInventory inv = p.getInventory();
		ItemStack mainHand = inv.getItemInMainHand();
		
		if (mainHand.containsEnchantment(Enchantment.LOOT_BONUS_BLOCKS)) {
			fortuneLvl = mainHand.getEnchantmentLevel(Enchantment.LOOT_BONUS_BLOCKS);
		}
		
		Collection<ItemStack> drops = block.getDrops();
		drops.clear();	
		
		
		if (mat == Material.WHEAT) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(3) : (fortuneLvl == 2 ? random.nextInt(4): (fortuneLvl == 3 ? random.nextInt(5) : random.nextInt(2)));
			
			drops.add(new ItemStack(Material.WHEAT, 1));
			if (maxRandomDropQuantitiy > 0) drops.add(new ItemStack(Material.WHEAT_SEEDS, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.BEETROOTS) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(4) : (fortuneLvl == 2 ? random.nextInt(5): (fortuneLvl == 3 ? random.nextInt(6) : random.nextInt(3)));
			
			drops.add(new ItemStack(Material.BEETROOT, 1));
			if (maxRandomDropQuantitiy > 0) drops.add(new ItemStack(Material.BEETROOT_SEEDS, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.CARROTS) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(4) : (fortuneLvl == 2 ? random.nextInt(5): (fortuneLvl == 3 ? random.nextInt(6) : random.nextInt(3))) + 1;
			
			drops.add(new ItemStack(Material.CARROT, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.POTATOES) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(5) : (fortuneLvl == 2 ? random.nextInt(6): (fortuneLvl == 3 ? random.nextInt(7) : random.nextInt(4))) + 1;
			int maxRandomDropQuantitiyPoisonousPotato = (int) Math.ceil(Math.random() - 0.8D);
			
			drops.add(new ItemStack(Material.POTATO, maxRandomDropQuantitiy));
			if (maxRandomDropQuantitiyPoisonousPotato > 0) drops.add(new ItemStack(Material.POISONOUS_POTATO, maxRandomDropQuantitiyPoisonousPotato));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.NETHER_WART) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(3) : (fortuneLvl == 2 ? random.nextInt(4): (fortuneLvl == 3 ? random.nextInt(5) : random.nextInt(2))) + 1;
			
			drops.add(new ItemStack(Material.NETHER_WART, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		if (mat == Material.COCOA) {
			int maxRandomDropQuantitiy = fortuneLvl == 1 ? random.nextInt(2) : (fortuneLvl == 2 ? random.nextInt(3): (fortuneLvl == 3 ? random.nextInt(4) : random.nextInt(1))) + 1;
			
			drops.add(new ItemStack(Material.COCOA_BEANS, maxRandomDropQuantitiy));
			damageItem(mainHand);
			return drops;
		}
		
		return drops;
	}
	
	@SuppressWarnings("unused")
	private void damageItem(ItemStack itemInHand) {
		ItemMeta itemInHandMeta = itemInHand.getItemMeta();
		
		if (itemInHand == null) {
			return;
		}
		
		if (itemInHand.getType() == Material.AIR) {
			return;
		}
		
		if (!itemInHandMeta.isUnbreakable() && itemInHand.containsEnchantment(Enchantment.LOOT_BONUS_BLOCKS)) {
			Damageable itemInHandDamageable = (Damageable) itemInHandMeta;
			int damage = itemInHandDamageable.getDamage();
			int maxDamage = itemInHand.getType().getMaxDurability();
			
			if (damage + 1 <= maxDamage) {
				itemInHandDamageable.setDamage(damage + 1);
				itemInHand.setItemMeta(itemInHandDamageable);
				return;
			}
			
			itemInHand.setAmount(0);
		}
	}
}

```

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/15203329/173921341-b9cd1775-7a81-49a6-82ab-3d31c0881319.png)

### Paper version

This server is running Paper version git-Paper-8 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: e4f5e1c)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads

**Comment by Doc94** [comment]
Related to #6889 ?

But im a little confuse.. the method dropItemNaturally only add the random loc variations and use the dropItem then if pass null/AIR item in the two methods you get the error for try to use AIR or NULL.
