### ISSUE TITLE
Crash during boot on 1.19, after updating worlds from 1.18.2.

### ISSUE THREAD

**Issue by BigScary** [PaperSpigot/Paper#8012]
### Stack trace

java.lang.RuntimeException: Could not create world config for world
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:264) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.level.ServerLevel.lambda$new$2(ServerLevel.java:491) ~[?:?]
	at net.minecraft.world.level.Level.<init>(Level.java:277) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:491) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:583) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-27]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.spongepowered.configurate.serialize.SerializationException: [entities, spawning, skeleton-horse-thunder-spawn-chance] of type io.papermc.paper.configuration.type.DoubleOrDefault: 0 is of an unexpected type class io.papermc.paper.configuration.type.DoubleOrDefault
	at io.papermc.paper.configuration.type.DoubleOrDefault$Serializer.deserialize(DoubleOrDefault.java:51) ~[paper-1.19.jar:git-Paper-27]
	at io.papermc.paper.configuration.type.DoubleOrDefault$Serializer.deserialize(DoubleOrDefault.java:34) ~[paper-1.19.jar:git-Paper-27]
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
	at io.papermc.paper.configuration.Configurations.lambda$creator$0(Configurations.java:79) ~[paper-1.19.jar:git-Paper-27]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:201) ~[paper-1.19.jar:git-Paper-27]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:173) ~[paper-1.19.jar:git-Paper-27]
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:262) ~[paper-1.19.jar:git-Paper-27]
	... 9 more
[17:52:25] [Server thread/ERROR]: 	Cause of unexpected exception was
org.spongepowered.configurate.serialize.SerializationException: [entities, spawning, skeleton-horse-thunder-spawn-chance] of type io.papermc.paper.configuration.type.DoubleOrDefault: 0 is of an unexpected type class io.papermc.paper.configuration.type.DoubleOrDefault
	at io.papermc.paper.configuration.type.DoubleOrDefault$Serializer.deserialize(DoubleOrDefault.java:51) ~[paper-1.19.jar:git-Paper-27]
	at io.papermc.paper.configuration.type.DoubleOrDefault$Serializer.deserialize(DoubleOrDefault.java:34) ~[paper-1.19.jar:git-Paper-27]
	at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
	at io.papermc.paper.configuration.Configurations.lambda$creator$0(Configurations.java:79) ~[paper-1.19.jar:git-Paper-27]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:201) ~[paper-1.19.jar:git-Paper-27]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:173) ~[paper-1.19.jar:git-Paper-27]
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:262) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.level.ServerLevel.lambda$new$2(ServerLevel.java:491) ~[?:?]
	at net.minecraft.world.level.Level.<init>(Level.java:277) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:491) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:583) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-27]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-27]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:52:25] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/multicraft/servers/server1/./crash-reports/crash-2022-06-17_17.52.25-server.txt

### Plugin and Datapack List

I can't run these commands because it won't boot, but you can see the plugins trying to load in the pasted log below. Our only data pack is some custom achievements.

https://paste.gg/p/anonymous/d56ff079a86b4ed891a05b1c8e2b4872

### Actions to reproduce (if known)

Just boot? I assume it has something to do with the upgrade but I didn't try setting up an entirely new server.

### Paper version

paper-1.19.jar:git-Paper-27

### Other

I did try removing the plugins which were complaining ahead of the crash, but it didn't change the outcome - still crashing.

**Comment by electronicboy** [comment]
need a copy of the config file(s) and the old config file from pre migration

**Comment by BigScary** [comment]
Attaching config zip file



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by BigScary** [comment]
[config.zip](https://github.com/PaperMC/Paper/files/8929627/config.zip)

**Comment by Machine-Maker** [comment]
Yeah, I see the issue, it was checking if you had put a double, and 0 is an int. It should accept integer values here as well.
