### ISSUE TITLE
java.lang.NullPointerException: Cannot read the array length because "storage" is null

### ISSUE THREAD

**Issue by ootwclyhe** [PaperSpigot/Paper#8014]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
[17:57:33 ERROR]: Entity threw exception at world:1538.5,13.0,5354.5
java.lang.NullPointerException: Cannot read the array length because "storage" is null
        at io.papermc.paper.world.ChunkEntitySlices$EntityCollectionBySection.getEntitiesWithEnderDragonParts(ChunkEntitySlices.java:378) ~[paper-1.19.jar:git-Paper-27]
        at io.papermc.paper.world.ChunkEntitySlices.getEntities(ChunkEntitySlices.java:138) ~[paper-1.19.jar:git-Paper-27]
        at io.papermc.paper.world.EntitySliceManager.getEntities(EntitySliceManager.java:149) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.world.level.Level.getEntities(Level.java:1055) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.pushEntities(LivingEntity.java:3447) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3377) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:634) ~[?:?]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2949) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
        at net.minecraft.world.entity.monster.Creeper.tick(Creeper.java:167) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1155) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:898) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-27]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin and Datapack List

AuctionHouse, CMI, CMILib, LuckPerms, MiniMOTD, Multiverse-Core, PlaceholderAPI, Residence, Vault, XConomy

### Paper version

paper1.19#27

### Other

the position when i reach found nothing but just a cave without light(may be something were cleared after server restart)

**Comment by electronicboy** [comment]
looking at the code, I literally have no idea how you'd induce this, that field is never null, can you reproduce this? without plugins? logs?

**Comment by ootwclyhe** [comment]
> looking at the code, I literally have no idea how you'd induce this, that field is never null, can you reproduce this? without plugins? logs?

already tried to reproduce without plugins but failed, it may a probability crash,i has updated the lastest version,submit this crashreport just for paper developers to aware the potential bug.

**Comment by e-im** [comment]
This has to be caused by a plugin. It doesn't really make any sense. Thanks for the report, regardless.

**Comment by ootwclyhe** [comment]
邮件收到了哦

**Comment by ootwclyhe** [comment]
邮件收到了哦
