### ISSUE TITLE
Jigsaw block kicking user

### ISSUE THREAD

**Issue by BoxWithoutATop** [PaperSpigot/Paper#8102]
### Expected behavior

When in the menu of the jigsaw block pressing generate should close the menu, and if everything is input properly, it should generate a structure.

### Observed/Actual behavior

Pressing "generate" within the jigsaw block causes the user to be removed from the server with the message "packet processing error."

### Steps/models to reproduce

Use '/op @p'. Then use '/gamemode creative' and '/give @p jigsaw'. a jigsaw block should now be in your inventory. place it down and right click it, then click generate.

### Plugin and Datapack List

FastAsyncWorldEdit-Bukkit-2.4.1-SNAPSHOT-241

### Paper version

This server is running Paper version git-Paper-50 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: c879064)
You are running the latest version
Previous version: git-Purpur-1699 (MC: 1.19)

### Other

This issue only happens with player generated jigsaw blocks. Jigsaws generated with structure blocks do not have problems. I assume the issue has something to do with nbt data.

**Comment by lynxplay** [comment]
I can only replicate this with the empty defaults. While I am unsure if this is expected behavior (even for the minecraft:empty target pool) inputting any proper target pool properly generates the jigsaw structure.

Can you provide the exact target pool/block configuration you are failing with ? Or is this purely an issue with minecraft:empty.

**Comment by BoxWithoutATop** [comment]
I believe it is an issue with minecraft:empty, but with proper function filling that data with empty (which has it's own utility) or filling it incorrectly still should not remove the user.

**Comment by orblazer** [comment]
Hello,
I think i have exact same issue, but with that version :
git-Paper-66 (MC: 1.19) (Implementing API Version 1.19-R0.1-SNAPSHOT) (Git: b7faa65)

## First error
```
[12:51:01 ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInJigsawGenerate@6cf6dbf8 for orblazer[/90.2.49.214:54916]
java.lang.IllegalArgumentException: Bound must be positive
        at net.minecraft.world.level.levelgen.BitRandomSource.nextInt(BitRandomSource.java:19) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.world.level.levelgen.structure.pools.StructureTemplatePool.getRandomTemplate(StructureTemplatePool.java:92) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement.addPieces(JigsawPlacement.java:55) ~[?:?]
        at net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement.generateJigsaw(JigsawPlacement.java:136) ~[?:?]
        at net.minecraft.world.level.block.entity.JigsawBlockEntity.generate(JigsawBlockEntity.java:112) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleJigsawGenerate(ServerGamePacketListenerImpl.java:1122) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundJigsawGeneratePacket.handle(ServerboundJigsawGeneratePacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundJigsawGeneratePacket.a(ServerboundJigsawGeneratePacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-66]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

With this jigsaw configuration
![Screenshot_20220721_145631](https://user-images.githubusercontent.com/1344792/180219113-e55b4f5b-55fc-49e7-8ebb-93f2b279b244.png)


## Second error
```
[12:56:46 ERROR]: Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInJigsawGenerate@4f633b07 for orblazer[/90.2.49.214:42130]
java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / minecraft:worldgen/template_pool]: ResourceKey[minecraft:worldgen/template_pool / minefight:dungeons/jail/lanes]
        at net.minecraft.core.Registry.lambda$getHolderOrThrow$70(Registry.java:598) ~[paper-1.19.jar:git-Paper-66]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.core.Registry.lambda$getHolderOrThrow$70(Registry.java:598) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.world.level.block.entity.JigsawBlockEntity.generate(JigsawBlockEntity.java:111) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleJigsawGenerate(ServerGamePacketListenerImpl.java:1122) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundJigsawGeneratePacket.handle(ServerboundJigsawGeneratePacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundJigsawGeneratePacket.a(ServerboundJigsawGeneratePacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-66]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-66]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

With this jigsaw configuration
![Screenshot_20220721_145807](https://user-images.githubusercontent.com/1344792/180220197-750a5284-f942-4848-a1e5-abcf97ef1a21.png)


## Step to reproduce

1) Save structures with an jigsaw inside
2) Load one of structures created
3) try different configurations with jigsaw, then click to "generate"

## Theory

I think the jigsaw can't found the structure but that is exist for load in structure

**Comment by lynxplay** [comment]
I agree that this should not kick players completely. A change on the paper side of things to prevent this is definitely something we could do.

However, I marked this as a low priority for us, as generally proper usage of these blocks should not lead to a kick.
