### ISSUE TITLE
NPE after setting Bee flower pos to null

### ISSUE THREAD

**Issue by nopjar** [PaperSpigot/Paper#8105]
### Stack trace

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BaseBlockPosition.u()" because "vec" is null
        at net.minecraft.world.phys.Vec3.atBottomCenterOf(Vec3.java:42) ~[?:?]
        at net.minecraft.world.entity.animal.Bee$BeePollinateGoal.tick(Bee.java:806) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:151) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:860) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3307) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:634) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:60) ~[?:?]
        at net.minecraft.world.entity.animal.Bee.aiStep(Bee.java:488) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2949) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
        at net.minecraft.world.entity.animal.Bee.tick(Bee.java:275) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1155) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:898) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-48]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-48]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-48]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-48]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-48]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-48]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

I'm afraid I'm not able to share the plugin-list.
Datapacks: `There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]`

### Actions to reproduce (if known)

This issue came up, when I called a Bee with our own Pets-Plugin, and it flew around for some time. But I can ensure, this Plugin does not infer with NMS-Code.

### Paper version

This server is running Paper version git-Paper-48 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 385f313)

**Comment by electronicboy** [comment]
This looks like something induced an illegal state, the entity entered a state in which it's brain set it could do, but, it couldn't; and all of the other logic around here generally on a quick scan looks fine

i.e. bee thought it could enter a polination state, yet, the targeted flower which it needs to enter and stay in this state, was not set

**Comment by nopjar** [comment]
What we do is set `org.bukkit.entity.Bee#setFlower(@Nullable Location)` to null every tick to ensure desired behavior. But the API allows setting it to null. (Same applies to `org.bukkit.entity.Bee#setHive(@Nullable Location)`).

**Comment by electronicboy** [comment]
annnd that would do it... where exactly are you doing that call from? the scheduler?

**Comment by nopjar** [comment]
Jap, we use the BukkitScheduler

**Comment by nopjar** [comment]
Correcting myself, we don't run it every tick. "Just" every ten ticks.
