### ISSUE TITLE
/world/data folder created before 1.19 cause memory run out in 1.19

### ISSUE THREAD

**Issue by Ticozheng** [PaperSpigot/Paper#8114]
### Stack trace

[18:31:30] [Server thread/INFO]: 运行时间：4 分钟 31 秒
[18:31:30] [Server thread/INFO]: 当前服务器TPS=14.17
[18:31:30] [Server thread/INFO]: 最大内存：7,168MB。
[18:31:30] [Server thread/INFO]: 已分配内存：7,168MB。
[18:31:30] [Server thread/INFO]: 空闲内存：31MB。
[18:31:38] [Server thread/INFO]: World“world”：6,259区块，4,422实体，20,351方块实体。
[18:31:38] [Server thread/INFO]: Nether“world_nether”：898区块，605实体，926方块实体。
[18:31:38] [Server thread/INFO]: The End“world_the_end”：560区块，243实体，762方块实体。
[18:31:38] [Server thread/INFO]: Nether“zy2”：585区块，171实体，13方块实体。
[18:31:38] [Server thread/INFO]: World“zy1”：3,970区块，2,003实体，9,064方块实体。
[18:31:38] [Server thread/INFO]: The End“zy3”：267区块，127实体，76方块实体。
[18:31:41] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-52 (MC: 1.19) ---
[18:31:41] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[18:31:41] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:31:41] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[18:31:41] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:31:41] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[18:31:41] [Paper Watchdog Thread/ERROR]: 	PID: 26 | Suspended: false | Native: false | State: RUNNABLE
[18:31:41] [Paper Watchdog Thread/ERROR]: 	Stack:
[18:31:42] [Paper Watchdog Thread/ERROR]: 		com.google.gson.stream.JsonReader.<init>(JsonReader.java:282)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:423)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:449)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:499)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.block.entity.SignBlockEntity.deserializeTextSafe(SignBlockEntity.java:135)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.block.entity.SignBlockEntity.loadLine(SignBlockEntity.java:120)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.block.entity.SignBlockEntity.load(SignBlockEntity.java:103)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.block.entity.BlockEntity.lambda$loadStatic$1(BlockEntity.java:151)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.block.entity.TileEntity$$Lambda$7191/0x00000008021b6f18.apply(Unknown Source)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.Optional.map(Optional.java:260)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.block.entity.BlockEntity.loadStatic(BlockEntity.java:149)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:54)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:27)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftSign.<init>(CraftSign.java:22)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$$Lambda$7471/0x000000080220a4a8.apply(Unknown Source)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:104)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:96)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:78)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:278)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:236)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.getState(CraftBlock.java:335)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.CraftChunk.getTileEntities(CraftChunk.java:160)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.CraftChunk.getTileEntities(CraftChunk.java:139)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		EssentialsX-2.19.5-dev+26-2bba577.jar//com.earth2me.essentials.commands.Commandgc.run(Commandgc.java:56)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		EssentialsX-2.19.5-dev+26-2bba577.jar//com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		EssentialsX-2.19.5-dev+26-2bba577.jar//com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:809)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		EssentialsX-2.19.5-dev+26-2bba577.jar//com.earth2me.essentials.Essentials.onCommand(Essentials.java:714)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:872)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:473)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$4341/0x00000008014d7000.run(Unknown Source)
[18:31:42] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.lang.Thread.run(Thread.java:833)
[18:31:42] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:31:42] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[18:31:42] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:31:43] [Server thread/INFO]: World“shopn”：441区块，2,009实体，8,054方块实体。
[18:32:06] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-52 (MC: 1.19) ---
[18:32:06] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[18:32:06] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:06] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[18:32:06] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:06] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[18:32:06] [Paper Watchdog Thread/ERROR]: 	PID: 26 | Suspended: false | Native: false | State: RUNNABLE
[18:32:06] [Paper Watchdog Thread/ERROR]: 	Stack:
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.Arrays.copyOf(Arrays.java:3481)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.ArrayList.grow(ArrayList.java:237)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.ArrayList.grow(ArrayList.java:244)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.ArrayList.add(ArrayList.java:454)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.ArrayList.add(ArrayList.java:467)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ChunkMap.lambda$getChunkRangeFuture$12(ChunkMap.java:793)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.PlayerChunkMap$$Lambda$6658/0x0000000801ff6a20.apply(Unknown Source)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:1248)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1261)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:821)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:2688)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.executeMidTickTasks(MinecraftServer.java:2711)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.tickBlockEntities(Level.java:882)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:701)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$4341/0x00000008014d7000.run(Unknown Source)
[18:32:06] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.lang.Thread.run(Thread.java:833)
[18:32:06] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:06] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[18:32:06] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:18] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-52 (MC: 1.19) ---
[18:32:19] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[18:32:19] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:19] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[18:32:19] [Paper Watchdog Thread/ERROR]: Ticking entity: minecraft:minecart, entity class: net.minecraft.world.entity.vehicle.EntityMinecartRideable
[18:32:19] [Paper Watchdog Thread/ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[18:32:19] [Paper Watchdog Thread/ERROR]: Entity UUID: ed838f41-a7cf-4c39-a36c-484a52a0d610
[18:32:19] [Paper Watchdog Thread/ERROR]: Position: world: 'world' at location (-1078.4900000095367, 71.0, 26203.490000009537)
[18:32:19] [Paper Watchdog Thread/ERROR]: Velocity: (0.0, -0.0, 0.0) (in blocks per tick)
[18:32:19] [Paper Watchdog Thread/ERROR]: Entity AABB: AABB[-1078.9800000190735, 71.0, 26203.0] -> [-1078.0, 71.69999998807907, 26203.980000019073]
[18:32:19] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:19] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[18:32:19] [Paper Watchdog Thread/ERROR]: 	PID: 26 | Suspended: false | Native: false | State: RUNNABLE
[18:32:19] [Paper Watchdog Thread/ERROR]: 	Stack:
[18:32:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.world.level.Level.tickBlockEntities(Level.java:862)
[18:32:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:701)
[18:32:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551)
[18:32:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
[18:32:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414)
[18:32:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187)
[18:32:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[18:32:19] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda$4341/0x00000008014d7000.run(Unknown Source)
[18:32:19] [Paper Watchdog Thread/ERROR]: 		java.base@17.0.3.1/java.lang.Thread.run(Thread.java:833)
[18:32:19] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:19] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[18:32:19] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:40] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-52 (MC: 1.19) ---
[18:32:41] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[18:32:45] [Paper Watchdog Thread/ERROR]: ------------------------------
[18:32:45] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[18:32:54] [Thread-0/INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[18:32:54] [Server thread/ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:942) ~[?:?]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:913) ~[paper-1.19.jar:git-Paper-52]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:781) ~[paper-1.19.jar:git-Paper-52]
	at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:885) ~[paper-1.19.jar:git-Paper-52]
	at org.bukkit.craftbukkit.v1_19_R1.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[paper-1.19.jar:git-Paper-52]
[18:32:54] [Thread-0/INFO]: Stopping server

### Plugin and Datapack List

Plugins (46): AdvancedBan, AntiAttack*, AntiXRay, AuthMe, BungeeTabListPlus, ChestSort, ClearLag, ClickRingBell, CMILib, CoreProtect, CreativeManager, CreeperConfetti, DeadChest, DeluxeMenus, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FarmProtect*, GSit, HanNotice*, HiveChecker, ImageOnMap, InventoryRollback-Continued, LuckPerms, Matrix, MentionNotify, Multiverse-Core, MyCommand, NBTAPI, OpenInv, PlaceholderAPI, PlayerHeads, PlayerTitle, ProtocolLib, QuickShop, Residence, SafeNetherDoor*, SkinsRestorer, UltimateChat, Vault, ViaBackwards, ViaVersion, VillagerInfo, VoidGen

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Actions to reproduce (if known)

I upgrade my server from 1.18.2 half month ago, and before I upgrade，no frequent crash, and after the upgrade, the server crash several times per day, I have try lots of methods to solve it, and finally find the where the problem is, although I dont know what exactaly happen.

I remove the folder /world/data coincidentally(also remove /data form world_nether and world_the_end), and everything become normal, no JavaOutofMemory no server not responded and no crash. When I restore this folder, the server crash happen again, I provided my data as attachment for analytics if you need
[data.zip](https://github.com/PaperMC/Paper/files/9074019/data.zip)

### Paper version

This server is running Paper version git-Paper-52 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 6ea73e7)
You are 4 version(s) behind

### Other

I hava the plugin ImageOnMap, and dont know whether its image maps caused the problem, but just remove this plugin won't solve ths crash

Maybe something wrong when the 1.19 server processing the folder or the files broken down in upgrade?

**Comment by Owen1212055** [comment]
Your issue is because your ``chunks.dat`` file is trying to forceload 606 chunks.
This causes a large amount of chunks to be loaded, causing your server to crash eventually from running out of memory.
![image](https://user-images.githubusercontent.com/23108066/183555771-9f86a409-c9b7-4cf1-8a69-66d267defdeb.png)

**Comment by Ticozheng** [comment]
> Your issue is because your `chunks.dat` file is trying to forceload 606 chunks. This causes a large amount of chunks to be loaded, causing your server to crash eventually from running out of memory. ![image](https://user-images.githubusercontent.com/23108066/183555771-9f86a409-c9b7-4cf1-8a69-66d267defdeb.png)

@Owen1212055 Thanks for help! But I didn't know which program generate it, I didn't find any info about this file in wiki and noticed that this file seems used for BE, I hava install geyser on my server, is it cause this problem? If not, could you tell me whick problem may cause this? My server still crash one or two times per day now! Sincere thanks！！

**Comment by Owen1212055** [comment]
Please provide logs, additionally you’re more than welcome to ask for help in https://discord.gg/papermc .

**Comment by Ticozheng** [comment]
> Please provide logs, additionally you’re more than welcome to ask for help in https://discord.gg/papermc .

@Owen1212055 I had check for latest.log by myself, but didn't find anythink associate to this problem
(by the way, I had ask for help one month ago on discord but didn't get useful help, even the problem of the folder was found by myself [sad face])

[latest.log](https://github.com/PaperMC/Paper/files/9289689/latest.log)
