### ISSUE TITLE
/paper fixlight throws exception error

### ISSUE THREAD

**Issue by mrfloris** [PaperSpigot/Paper#8115]
### Stack trace

```
[19:03:54 INFO]: mrfloris issued server command: /paper fixlight 2500
[19:03:55 ERROR]: Caught exception in thread Thread[Worker-Main-1,4,main]
java.lang.IllegalStateException: null
        at ca.spottedleaf.starlight.common.light.StarLightEngine.relightChunks(StarLightEngine.java:944) ~[paper-1.19.jar:git-Paper-56]
        at ca.spottedleaf.starlight.common.light.StarLightInterface.relightChunks(StarLightInterface.java:450) ~[paper-1.19.jar:git-Paper-56]
        at net.minecraft.server.level.ThreadedLevelLightEngine.lambda$relight$2(ThreadedLevelLightEngine.java:226) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

n/a

### Actions to reproduce (if known)

Normally, and yesterday, I used /paper fixlight 2500, and now when i use it in a world i get this error. Never happened before.

### Paper version

```
> ver
[19:08:41 INFO]: Checking version, please wait...
[19:08:42 INFO]: This server is running Paper version git-Paper-56 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 41238a4)
You are running the latest version
Previous version: git-Paper-52 (MC: 1.19)
>
```

**Comment by jpenilla** [comment]
Can reproduce, not consistently though

**Comment by mrfloris** [comment]
Thank you for fixing this, I appreciate it.
