### ISSUE TITLE
Cannot invoke "net.minecraft.network.chat.PlayerChatMessage.f()" because "message" is null

### ISSUE THREAD

**Issue by RanMinecraft** [PaperSpigot/Paper#8197]
### Observed/Actual behavior

java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.PlayerChatMessage.f()" because "message" is null
        at net.minecraft.network.chat.OutgoingPlayerChatMessage.create(OutgoingPlayerChatMessage.java:20) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2357) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.chat(CraftPlayer.java:676) ~[paper-1.19.1.jar:git-Paper-85]
        at cn.ranmc.Ranmc.onPlayerSwapHandItemsEvent(Ranmc.java:464) ~[Ranmc.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor953.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-85]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1816) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.19.1.jar:git-Paper-85]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-85]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps/models to reproduce

player.chat("/say hi");

### Paper version

This server is running Paper version git-Paper-85 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 71544ab)
You are running the latest version
Previous version: git-Paper-58 (MC: 1.19)

**Comment by Machine-Maker** [comment]
Fixed in https://github.com/PaperMC/Paper/pull/8131
