### ISSUE TITLE
Exception in server tick loop / Failed to get system info for world generation 

### ISSUE THREAD

**Issue by TreyyTreyy** [PaperSpigot/Paper#8239]
### Stack trace

```
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.3+7-Ubuntu-0ubuntu0.20.04.1) Host: Linux 5.15.0-43-generic (amd64)
Loading libraries, please wait...
[08:59:48 INFO]: Building unoptimized datafixer
[08:59:50 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08:59:50 INFO]: Found new data pack file/bukkit, loading it automatically
[08:59:52 INFO]: Loaded 7 recipes
[08:59:53 INFO]: Starting minecraft server version 1.19.1
[08:59:53 INFO]: Loading properties
[08:59:53 INFO]: This server is running Paper version git-Paper-109 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 69950d5)
[08:59:53 ERROR]: Encountered an unexpected exception
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
        at java.lang.System.load(System.java:1953) ~[?:?]
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
        at jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398) ~[?:?]
        at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
        at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
        at java.awt.Toolkit$2.run(Toolkit.java:1392) ~[?:?]
        at java.awt.Toolkit$2.run(Toolkit.java:1390) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1389) ~[?:?]
        at java.awt.Toolkit.initStatic(Toolkit.java:1427) ~[?:?]
        at java.awt.Toolkit.<clinit>(Toolkit.java:1401) ~[?:?]
        at java.awt.Color.<clinit>(Color.java:277) ~[?:?]
        at org.bukkit.map.MapPalette.c(MapPalette.java:28) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.map.MapPalette.<clinit>(MapPalette.java:44) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.<init>(CraftServer.java:370) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.server.players.PlayerList.<init>(PlayerList.java:163) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:15) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:208) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-109]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:59:53 WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null
        at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$15(MinecraftServer.java:1693) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.SystemReport.setDetail(SystemReport.java:62) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1692) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[paper-1.19.1.jar:git-Paper-109]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-109]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:59:53 ERROR]: This crash report has been saved to: /home/treytrey/Desktop/Minecraft Server/./crash-reports/crash-2022-08-04_08.59.53-server.txt
[08:59:53 INFO]: Stopping server
[08:59:53 INFO]: Saving worlds
[08:59:53 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[08:59:53 INFO]: Flushing Chunk IO
[08:59:53 INFO]: Closing Thread Pool
2022-08-04 08:59:53,751 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment

```

### Plugin and Datapack List

no plugins completely fresh installation 

### Actions to reproduce (if known)

create a server under a Linux Ubuntu virtual machine (under virtualbox) and change the jar file from (paper-1.19.1-109.jar) to (paper.jar) 

### Paper version

paper-1.19.1-109.jar

### Other

Ive tried setting up the server about 5-7ish times and its always been the same error, I also tried going back to a earlier installation of paper mc but it still didn't work

The Link to the crash report should be in this paste bin right here >https://paste.gg/p/anonymous/fd5a419cd2ee43debaedd9ef6ddd266b

Any help will be appreciated tyvm :)

**Comment by electronicboy** [comment]
Missing libraries, install the non-headless version of the JRE

**Comment by TreyyTreyy** [comment]
should I uninstall JDK 17 then?

**Comment by electronicboy** [comment]
You can either install the jdk package which doesn't have "headless" in the name (it still installs the "headless" jdk package, it just also depends on other packages, so that stuff like jwt loads properly, there was a flag to potentially fix the issue you're seeing, but, you still need those libraries for other stuff, like the server-icon, IIRC), or follow https://docs.papermc.io/misc/java-install

**Comment by TreyyTreyy** [comment]
oh wow the documents made it very easy to go through thanks alot preciate it
