### ISSUE TITLE
Paper 1.19.1 breaks Multiverse-Core (Same as Issue #7850)

### ISSUE THREAD

**Issue by Nutmegan** [PaperSpigot/Paper#8241]
### Expected behavior

Multiverse should be able to recognize and load world keys and files

### Observed/Actual behavior

Fails to load worlds because of duplicate keys existing

Console Error:

[18:04:27 WARN]: java.lang.IllegalArgumentException: Cannot create a world with key minecraft:briar_briarcraft_nether and name briar_briarcraft_nether one (or both) already match a world that exists
[18:04:27 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.createWorld(CraftServer.java:1155)
[18:04:27 WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:767)
[18:04:27 WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:474)
[18:04:27 WARN]: 	at Multiverse-Core-4.3.2-SNAPSHOT-870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:486)
[18:04:27 WARN]: 	at Multiverse-Core-4.3.2-SNAPSHOT-870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:467)
[18:04:27 WARN]: 	at Multiverse-Core-4.3.2-SNAPSHOT-870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:442)
[18:04:27 WARN]: 	at Multiverse-Core-4.3.2-SNAPSHOT-870.jar//com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:770)
[18:04:27 WARN]: 	at Multiverse-Core-4.3.2-SNAPSHOT-870.jar//com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:313)
[18:04:27 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:04:27 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:04:27 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[18:04:27 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
[18:04:27 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
[18:04:27 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[18:04:27 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[18:04:27 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[18:04:27 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1124)
[18:04:27 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[18:04:27 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

### Steps/models to reproduce

Add Multiverse to a server with existing root world containing a datapack and preloaded linked dimensions to the root.

### Plugin and Datapack List

Paper 1.19.1#109
Multiverse-Core-4.3.2-SNAPSHOT-87
[briarcraft.zip](https://github.com/PaperMC/Paper/files/9264274/briarcraft.zip)
0

### Paper version

[18:27:50 INFO]: Checking version, please wait...
[18:27:51 INFO]: This server is running Paper version git-Paper-109 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 69950d5)
You are running the latest version
Previous version: git-Paper-94 (MC: 1.19.1)

### Other

The issue and error seem to exactly match a 1.18.2 issue that was patched and has possibly resurfaced.

See Issues:
#7850 and #7851

**Comment by lynxplay** [comment]
Indeed replicable, just generally quite a pain to deal with without breaking other stuff from my first looks into it.
Might not be as fast of a solution as the other issues, so you may have to be patient here.

**Comment by Nutmegan** [comment]
I can understand, if it's anything like trying to relearn the constant datapack changes. I have ways to get around Multiverse for now.

**Comment by CKY-** [comment]
Having the same issues as this. can post a log but it's the same. so this is not localized to Nutmegan's setup.

**Comment by RillSoji** [comment]
If you'd like my log I can send it too but it's pretty identical.
