### ISSUE TITLE
Unable to Post Timings Report After Issuing `/timings paste`: 404 Not Found

### ISSUE THREAD

**Issue by GalvinGao** [PaperSpigot/Paper#8260]
### Expected behavior

Should be outputting a timings report URL.

### Observed/Actual behavior

I got these log records:

```
[16:55:01] [Server thread/INFO]: GalvinGao issued server command: /timings paste
[16:55:01] [Server thread/INFO]: Preparing Timings Report...
[16:55:02] [Timings paste thread/INFO]: Error uploading timings, check your logs for more information
[16:55:02] [Timings paste thread/WARN]: Not Found
java.io.FileNotFoundException: https://timings.aikar.co/post
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at co.aikar.timings.TimingsExport.getResponse(TimingsExport.java:369) ~[paper-1.19.1.jar:git-Paper-109]
        at co.aikar.timings.TimingsExport.run(TimingsExport.java:338) ~[paper-1.19.1.jar:git-Paper-109]
[16:55:02] [Timings paste thread/INFO]: Upload Error: 404: Not Found
[16:55:02] [Timings paste thread/INFO]: Check your logs for more information
```

### Steps/models to reproduce

Enter the following commands accordingly:
1. `/timings on`
2. Wait > 1min
3. `/timings paste`

### Plugin and Datapack List

Plugins:
```
> plugins
[16:58:00 INFO]: Plugins (1): mcMMO
```

Datapacks:
```
> datapack list
[16:58:16 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[16:58:16 INFO]: There are no more data packs available
```

### Paper version

```
> version
[16:58:49 INFO]: This server is running Paper version git-Paper-109 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 69950d5)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
```

**Comment by lynxplay** [comment]
The aikar timings service is currently down. This is known.

**Comment by Astralchroma** [comment]
Timings is down right now, this is a known issue please be paitient.

**Comment by Astralchroma** [comment]
> The aikar timings service is currently down. This is known.

Damn it you beat me to it.

**Comment by Chew** [comment]
For anyone following, the timings.aikar.co service is now back up.
