### ISSUE TITLE
New Y values seem to not be functioning correctly

### ISSUE THREAD

**Issue by olijeffers0n** [PaperSpigot/Paper#8265]
### Stack trace

```
java.lang.IllegalArgumentException: y out of range (expected 0-256, got 300)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftChunk.validateChunkCoordinates(CraftChunk.java:363) ~[paper-1.19.2.jar:git-Paper-116]
        at org.bukkit.craftbukkit.v1_19_R1.CraftChunk.getBlock(CraftChunk.java:117) ~[paper-1.19.2.jar:git-Paper-116]
        at xyz.ollieee.cloud.listeners.ChunkLoadListener.onChunkLoad(ChunkLoadListener.java:21) ~[AngelCloud.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-116]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:862) ~[?:?]
        at net.minecraft.server.level.ChunkHolder.lambda$updateFutures$19(ChunkHolder.java:767) ~[?:?]
        at net.minecraft.server.level.ChunkMap$CallbackExecutor.run(ChunkMap.java:201) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1265) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1347) ~[paper-1.19.2.jar:git-Paper-116]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.2.jar:git-Paper-116]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.2.jar:git-Paper-116]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.19.2.jar:git-Paper-116]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-116]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

Only plugin is mine with this code:

```java
    @EventHandler
    public void onChunkLoad(ChunkLoadEvent event) {
        event.getChunk().getBlock(7, 300, 7).setType(Material.DIAMOND_BLOCK);
    }
```

### Actions to reproduce (if known)

Just use a test plugin with the above block getter and the preconditions check should throw the Exception

### Paper version

This server is running Paper version git-Paper-116 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: a47301e)
You are running the latest version
Previous version: git-Paper-31 (MC: 1.19)

### Other

It might have something todo with me doing it on chunk load, but i'm not sure

**Comment by electronicboy** [comment]
you probably wanna look at the actual world in the chunk load event, only the overworld has the extended height afaik

**Comment by olijeffers0n** [comment]
Ah! makes sense. Forgot about the other worlds...
