### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by leofleeo** [PaperSpigot/Paper#8288]
### Stack trace

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-08-13 12:22:11
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.18.16-arch1-1
	Java Version: 18.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6066939520 bytes (5785 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: Navi 23 [Radeon RX 6600/6600 XT/6600M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 20106.74
	Virtual memory used (MB): 13382.14
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xmx6144M -Xms6144M
	CraftBukkit Information: 
   Running: Paper version git-Paper-125 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING pool-6-thread-1: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672), java.base@18.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@18.0.2/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], WAITING Paper Async Chunk Task Thread #0: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], RUNNABLE Server console handler: [java.base@18.0.2/java.io.FileInputStream.read0(Native Method), java.base@18.0.2/java.io.FileInputStream.read(FileInputStream.java:228), org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468), net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158), net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:107)], WAITING Paper Async Chunk Task Thread #1: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], WAITING Paper Async Chunk Task Thread #3: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], RUNNABLE Reference Handler: [java.base@18.0.2/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@18.0.2/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@18.0.2/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], TIMED_WAITING Timer hack thread: [java.base@18.0.2/java.lang.Thread.sleep(Native Method), net.minecraft.SystemUtils$7.run(SystemUtils.java:713)], WAITING Worker-Main-5: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@18.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464), java.base@18.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@18.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 3: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@18.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@18.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], WAITING Finalizer: [java.base@18.0.2/java.lang.Object.wait(Native Method), java.base@18.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@18.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@18.0.2/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:183)], WAITING Paper Async Chunk Urgent Task Thread: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], WAITING Worker-Main-3: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@18.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464), java.base@18.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@18.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-Async: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@18.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464), java.base@18.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@18.0.2/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:71), org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)], RUNNABLE Notification Thread: [], TIMED_WAITING Craft Scheduler Thread - 0: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@18.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@18.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 1: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@18.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@18.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Paper Watchdog Thread: [java.base@18.0.2/java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:242)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:209), io.netty.channel.epoll.Native.epollWait(Native.java:202), io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:294), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], RUNNABLE Signal Dispatcher: [], WAITING Worker-Main-2: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@18.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464), java.base@18.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@18.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], WAITING Worker-Main-4: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@18.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464), java.base@18.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@18.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], WAITING Paper Async Chunk Task Thread #2: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211), com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:97)], WAITING Worker-Main-6: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@18.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464), java.base@18.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@18.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Common-Cleaner: [java.base@18.0.2/java.lang.Object.wait(Native Method), java.base@18.0.2/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@18.0.2/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@18.0.2/java.lang.Thread.run(Thread.java:833), java.base@18.0.2/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING process reaper: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@18.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@18.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], RUNNABLE Server thread: [java.base@18.0.2/java.lang.Thread.dumpThreads(Native Method), java.base@18.0.2/java.lang.Thread.getAllStackTraces(Thread.java:1662), org.bukkit.craftbukkit.v1_19_R1.CraftCrashReport.get(CraftCrashReport.java:33), org.bukkit.craftbukkit.v1_19_R1.CraftCrashReport.get(CraftCrashReport.java:17), net.minecraft.SystemReport.a(SystemReport.java:62), net.minecraft.CrashReport.<init>(CrashReport.java:38), net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1272), net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1216), net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305), net.minecraft.server.MinecraftServer$$Lambda$4391/0x0000000800957c90.run(Unknown Source), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], WAITING Worker-Main-1: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@18.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3464), java.base@18.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3435), java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@18.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Craft Scheduler Thread - 2: [java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method), java.base@18.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@18.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@18.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@18.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@18.0.2/java.lang.Thread.run(Thread.java:833)],}
   
   Force Loaded Chunks: {}
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, file/bukkit (incompatible)
	World Generation: ERR
	Is Modded: Definitely; Server brand changed to 'Paper'
	Type: Dedicated Server (map_server.txt)
```

### Plugin and Datapack List

None

### Actions to reproduce (if known)

Start fresh new server with latest paper build on a linux system (I use arch linux) running openjdk 18

### Paper version

It instantly crashes so I cannot run that. It is the latest build at the time of writing from papermc.io

### Other

Here is the latest.log
```
[12:22:09] [ServerMain/INFO]: Building unoptimized datafixer
[12:22:09] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:22:10] [ServerMain/INFO]: Found new data pack file/bukkit, loading it automatically
[12:22:10] [ServerMain/INFO]: Loaded 7 recipes
[12:22:11] [Server thread/INFO]: Starting minecraft server version 1.19.2
[12:22:11] [Server thread/INFO]: Loading properties
[12:22:11] [Server thread/INFO]: This server is running Paper version git-Paper-125 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3f0415b)
[12:22:11] [Server thread/INFO]: Server Ping Player Sample Count: 12
[12:22:11] [Server thread/INFO]: Using 4 threads for Netty based IO
[12:22:11] [Server thread/INFO]: Default game type: SURVIVAL
[12:22:11] [Server thread/INFO]: Generating keypair
[12:22:11] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:22:11] [Server thread/INFO]: Using epoll channel type
[12:22:11] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[12:22:11] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[12:22:11] [Server thread/WARN]: **** FAILED TO BIND TO PORT!
[12:22:11] [Server thread/WARN]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
[12:22:11] [Server thread/WARN]: Perhaps a server is already running on that port?
[12:22:11] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-125]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:22:11] [Server thread/WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null
	at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$15(MinecraftServer.java:1694) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.SystemReport.setDetail(SystemReport.java:62) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1693) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[paper-1.19.2.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-125]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:22:11] [Server thread/ERROR]: This crash report has been saved to: /home/cloudy/Desktop/Server2/./crash-reports/crash-2022-08-13_12.22.11-server.txt
[12:22:11] [Server thread/INFO]: Stopping server
[12:22:11] [Server thread/INFO]: Saving players
[12:22:12] [Server thread/INFO]: Saving worlds
[12:22:12] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:22:12] [Server thread/INFO]: Flushing Chunk IO
[12:22:12] [Server thread/INFO]: Closing Thread Pool
[12:22:12] [Server thread/INFO]: Closing Server
```

**Comment by MWHunter** [comment]
**** FAILED TO BIND TO PORT!

You have another server running

**Comment by e-im** [comment]
Please come by our [Discord](https://discord.gg/papermc) (`#paper-help` channel), [forums](https://forums.papermc.io), or [IRC](https://webchat.esper.net/?channels=paper-help) for support.

**Comment by leofleeo** [comment]
That's odd. There are no servers running. I even killed java.

**Comment by leofleeo** [comment]
There is no way to kill java. It never dies. That's really odd. I'm going to try restarting my system

**Comment by leofleeo** [comment]
Restarting my system fixed the issue
