### ISSUE TITLE
Crash when paper-global.yml and settings directory are read-only

### ISSUE THREAD

**Issue by karthanistyr** [PaperSpigot/Paper#8301]
### Stack trace

```
[18:01:07 ERROR]: Encountered an unexpected exception
org.spongepowered.configurate.ConfigurateException: []: java.nio.file.AccessDeniedException: /mcconfig/.22351533673970431302813050paper-global.yml.tmp
        at org.spongepowered.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:205) ~[configurate-core-4.1.2.jar:?]
        at io.papermc.paper.configuration.Configurations.initializeGlobalConfiguration(Configurations.java:114) ~[paper-1.19.2.jar:git-Paper-130]
        at io.papermc.paper.configuration.Configurations.initializeGlobalConfiguration(Configurations.java:97) ~[paper-1.19.2.jar:git-Paper-130]
        at io.papermc.paper.configuration.PaperConfigurations.initializeGlobalConfiguration(PaperConfigurations.java:180) ~[paper-1.19.2.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:214) ~[paper-1.19.2.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1125) ~[paper-1.19.2.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.nio.file.AccessDeniedException: /mcconfig/.22351533673970431302813050paper-global.yml.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:246) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258) ~[?:?]
        at java.nio.file.Files.copy(Files.java:1305) ~[?:?]
        at org.spongepowered.configurate.loader.AtomicFiles.atomicBufferedWriter(AtomicFiles.java:85) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.loader.AtomicFiles.lambda$atomicWriterFactory$0(AtomicFiles.java:58) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:188) ~[configurate-core-4.1.2.jar:?]
        ... 7 more
[18:01:07 ERROR]:       Cause of unexpected exception was
java.nio.file.AccessDeniedException: /mcconfig/.22351533673970431302813050paper-global.yml.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:246) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258) ~[?:?]
        at java.nio.file.Files.copy(Files.java:1305) ~[?:?]
        at org.spongepowered.configurate.loader.AtomicFiles.atomicBufferedWriter(AtomicFiles.java:85) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.loader.AtomicFiles.lambda$atomicWriterFactory$0(AtomicFiles.java:58) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:188) ~[configurate-core-4.1.2.jar:?]
        at io.papermc.paper.configuration.Configurations.initializeGlobalConfiguration(Configurations.java:114) ~[paper-1.19.2.jar:git-Paper-130]
        at io.papermc.paper.configuration.Configurations.initializeGlobalConfiguration(Configurations.java:97) ~[paper-1.19.2.jar:git-Paper-130]
        at io.papermc.paper.configuration.PaperConfigurations.initializeGlobalConfiguration(PaperConfigurations.java:180) ~[paper-1.19.2.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:214) ~[paper-1.19.2.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1125) ~[paper-1.19.2.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

N/A

### Actions to reproduce (if known)

1. Populate a directory (eg `my_configs/`) with a preset `paper-global.yml` and `paper-world-defaults.yml` files
2. Set directory and files as read-only (or change ownership to some other user and remove the writable flag)
3. Start paper with argument `--paper-settings-directory my_configs`

### Paper version

[18:01:07 INFO]: This server is running Paper version git-Paper-130 (MC: 1.19.2)

### Other

The use case is to have versioned configuration files that are immutable once applied to the server. Paper should not crash if the configuration files are present and correct, but simply read-only, unless there is a misconfiguration inside or a necessary migration.

IMO this is a regression as Paper did not crash in this situation (but definitely complained) prior to migrating the configuration handling to Configurate.

**Comment by Machine-Maker** [comment]
Do we want to support having a read only configuration? In order for new settings to be added to the file, the server has to write to it, otherwise new settings wouldn't appear in the files

**Comment by molor** [comment]
But why update/write the configuration files in case if there are no new settings?.. It's just a waste of SSD writes in most of times :c

**Comment by Machine-Maker** [comment]
Well it doesn't *know* that there aren't new settings. It loads in the settings you've got, then writes them all back out with the defaults for any new settings.

**Comment by Astralchroma** [comment]
> Do we want to support having a read only configuration? In order for new settings to be added to the file, the server has to write to it, otherwise new settings wouldn't appear in the files

There are cases where a read-only configuration is wanted, I can try to PR a fix later if it is wanted.

**Comment by karthanistyr** [comment]
IMO an admin should be able to make sure by themself that the server is correctly configured. It's confusing when things like config files change in the background tbh.

> In order for new settings to be added to the file, the server has to write to it, otherwise new settings wouldn't appear in the files

I disagree: it's also the admin's job. Btw you folks did an awesome documentation job here https://docs.papermc.io/paper/reference/global-configuration, and it's clear that the vast majority of settings have a default and therefore should not even need to be in the file to begin with.

While I do think there's value in Paper holding the admin's hand in some scenarios, I think it should fail safe in case the admin has taken over that responsibility and no mandatory key is missing.

**Comment by MiniDigger** [comment]
we can just not write when we dont have write perms and log a warning instead. changing the status quo here of automatically adding new keys is not really something we should do, its the best way to improve discoverability of new settings, else people would have no real way to see whats new (other than manually going thru the docs, which is just painful)

**Comment by karthanistyr** [comment]
If we can avoid the hard crash for lack of write privileges and leave it to the admin to fix whatever is wrong with the config file, i think that should be enough for this specific issue; and I don't expect it to be a problem, if paper just wants to write default values in the file for discoverability, the in-memory config should already be able to work with these defaults anyway.
