### ISSUE TITLE
Nullpointer Exception on serverload cause rotation is "null"

### ISSUE THREAD

**Issue by CarinaSchoppe** [PaperSpigot/Paper#8320]
### Expected behavior

Clean load of the server

### Observed/Actual behavior

[14:30:32 ERROR]: Error executing task on Chunk source main thread executor for minecraft:the_end
net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$36(ChunkMap.java:1303) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:1248) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1261) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:821) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1347) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1407) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.EnumDirection.ordinal()" because "rotation" is null
	at net.minecraft.core.FrontAndTop.lookupKey(FrontAndTop.java:33) ~[?:?]
	at net.minecraft.core.FrontAndTop.fromFrontAndTop(FrontAndTop.java:48) ~[?:?]
	at com.mojang.math.OctahedralGroup.rotate(OctahedralGroup.java:174) ~[?:?]
	at net.minecraft.world.level.block.JigsawBlock.rotate(JigsawBlock.java:36) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.rotate(BlockBehaviour.java:842) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.filterBlocks(StructureTemplate.java:217) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.getShuffledJigsawBlocks(SinglePoolElement.java:100) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement.getRandomNamedJigsaw(JigsawPlacement.java:103) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement.addPieces(JigsawPlacement.java:62) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.structures.JigsawStructure.findGenerationPoint(JigsawStructure.java:94) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.world.level.levelgen.structure.Structure.generate(Structure.java:83) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkGenerator.tryGenerateStructure(ChunkGenerator.java:829) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkGenerator.lambda$createStructures$19(ChunkGenerator.java:773) ~[paper-1.19.jar:git-Paper-81]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.EnumDirection.ordinal()" because "rotation" is null

	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.createStructures(ChunkGenerator.java:756) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$2(ChunkStatus.java:51) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:275) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$37(ChunkTracker.java:1288) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[paper-1.19.jar:?]
	at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$39(ChunkTracker.java:1286) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:51) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[?:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more

### Steps/models to reproduce

Just started the server

### Plugin and Datapack List

None

### Paper version

Paper 1.19.2 build #132

**Comment by mbax** [comment]
Just wanted to say your issue says build 132 but your log says `git-Paper-81`, which is a difference of 51 builds

**Comment by lynxplay** [comment]
can you provide the world this is happening in ?
Replicating this seems pretty horrible :sweat:

**Comment by CarinaSchoppe** [comment]
> Just wanted to say your issue says build 132 but your log says `git-Paper-81`, which is a difference of 51 builds

Well I thought Ive used the latest build.

**Comment by CarinaSchoppe** [comment]
> 

whats the best way of providing the world as a download?

**Comment by lynxplay** [comment]
If you can, just throw your world folder into a zip/tar.gz and upload it here.
if it is too large for github, maybe test if this is a specific issue based on the seed (e.g. if you create a new fresh paper server with the same seed, does this error also occur ?)

Last option would be some file share like google driver.

**Comment by CarinaSchoppe** [comment]
[world_nether.zip](https://github.com/PaperMC/Paper/files/9396279/world_nether.zip)

**Comment by lynxplay** [comment]
I fail to replicate this on my local setup using the latest paper. Can you attempt to test this with your local setup on the proper latest paper version, 1.19.2 build #132 ? 

I don't recall anything touching this area, however having a shared ground for testing would be useful.

The general issue seems borderline impossible to run into, at least from my first look at the code that is erroring if you are not running any plugins and not-modified paper.

**Comment by Owen1212055** [comment]
Seeing as though we haven’t had similar reports to this, I’ll be closing this.

If you are still able to reproduce the issue even with taking the above comment into consideration please feel free to comment and this issue can be reopened. Thank you 😄
