### ISSUE TITLE
PlayerArmorChangeEvent doesn't work correctly

### ISSUE THREAD

**Issue by pawelkuwa** [PaperSpigot/Paper#8336]
### Expected behavior

I want to execute when player wear specified.

### Observed/Actual behavior

In console plugin spam this error
```
[01:10:12 ERROR]: Could not pass event PlayerArmorChangeEvent to DropSMP v1.5.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.hasDisplayName()" because the return value of "org.bukkit.inventory.ItemStack.getItemMeta()" is null
        at me.wisnia.dropsmp.MagicItems.tribalChest.onArmorChange(tribalChest.java:15) ~[DropSMP-1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor566.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.collectEquipmentChanges(LivingEntity.java:3039) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.detectEquipmentUpdates(LivingEntity.java:3000) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2907) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:269) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:668) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:314) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1623) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

```package me.wisnia.dropsmp.MagicItems;

import com.destroystokyo.paper.event.player.PlayerArmorChangeEvent;
import me.wisnia.dropsmp.DropSMP;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

public class tribalChest implements Listener {

    @EventHandler
    public void onArmorChange(PlayerArmorChangeEvent e) {
        if (e.getNewItem().getItemMeta().getDisplayName() == null) return;
        String new_item_name = e.getNewItem().getItemMeta().getDisplayName();
        e.getPlayer().sendMessage(new_item_name);
        if (e.getNewItem().getItemMeta().getDisplayName().equals(DropSMP.getPlugin().getConfig().getString("magic-items.tribal-chest.name"))) {
            e.getPlayer().sendMessage("Założyłeś plemienną zbroję");
        }
    }

}
```

### Plugin and Datapack List

```
[01:13:30 INFO]: Plugins (5): DecentHolograms, DropSMP, PlaceholderAPI, PlugManX (PlugMan), TAB
```

### Paper version

This server is running Paper version git-Paper-386 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 072f54c on ver/1.18.2)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads

**Comment by lynxplay** [comment]
Your code is simply not valid. Items do not have to have an item meta. You need to ensure that the result of the getItemMeta call is not null before calling methods on it. For future help with development please use our discord (https://discord.gg/papermc).
