### ISSUE TITLE
ReaderException when starting the server

### ISSUE THREAD

**Issue by CarinaSchoppe** [PaperSpigot/Paper#8337]
### Expected behavior

Clean startup

### Observed/Actual behavior

```
System Info: Java 18 (Java HotSpot(TM) 64-Bit Server VM 18.0.2.1+1-1) Host: Windows 11 10.0 (amd64)
Loading libraries, please wait...
2022-08-31 13:50:09,938 ServerMain WARN Advanced terminal features are not available in this environment
[13:50:12 INFO]: Building unoptimized datafixer
[13:50:13 ERROR]: Failed to start the minecraft server
java.lang.Exception: Failed to load configuration file: bukkit.yml
	at io.papermc.paper.configuration.PaperConfigurations.loadLegacyConfigFile(PaperConfigurations.java:411) ~[paper-1.19.2.jar:git-Paper-135]
	at net.minecraft.server.Main.main(Main.java:115) ~[paper-1.19.2.jar:git-Paper-135]
	at org.bukkit.craftbukkit.Main.main(Main.java:300) ~[paper-1.19.2.jar:git-Paper-135]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.configuration.InvalidConfigurationException: unacceptable code point ' ' (0x0) special characters are not allowed
in "'reader'", position 0
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
Caused by: org.bukkit.configuration.InvalidConfigurationException: unacceptable code point ' ' (0x0) special characters are not allowed

	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.configuration.PaperConfigurations.loadLegacyConfigFile(PaperConfigurations.java:409) ~[paper-1.19.2.jar:git-Paper-135]
	... 4 more
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:211) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1218) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:329) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:251) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:214) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:156) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:141) ~[snakeyaml-1.30.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-1.30.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:102) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.configuration.PaperConfigurations.loadLegacyConfigFile(PaperConfigurations.java:409) ~[paper-1.19.2.jar:git-Paper-135]
	... 4 more
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed

w: Detected multiple Kotlin daemon sessions at build\kotlin\sessions
```

Caused by: org.bukkit.configuration.InvalidConfigurationException: unacceptable code point ' ' (0x0) special characters are not allowed
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed

### Steps/models to reproduce

Just started the server

### Plugin and Datapack List

own but that has not been loaded so far

### Paper version

Paper 1.19.2 build 135

**Comment by electronicboy** [comment]
You have a malformed (legacy) config file

**Comment by CarinaSchoppe** [comment]
> You have a malformed (legacy) config file

but how. Ive just setup that server like 10 min ago.

**Comment by electronicboy** [comment]
I can't comment on a file I can't see, I can however say that snakeyaml blew up when reading your files; error at position 0 often screams a truncated file, or something improperly added towards the beginning of the file

**Comment by electronicboy** [comment]
O, I mean, apparently bukkit.yml, not the "legacy" paper config, misread that bit

> java.lang.Exception: Failed to load configuration file: bukkit.yml

**Comment by CarinaSchoppe** [comment]
> O, I mean, apparently bukkit.yml, not the "legacy" paper config, misread that bit
> 
> > java.lang.Exception: Failed to load configuration file: bukkit.yml

yeah sure.
Its full of yeah "erros" or lets just say non ASCII characters.
But  how can this happen when using a clean installed server.

**Comment by electronicboy** [comment]
I can't tell you how the file ended up malformed, if it's just a fresh server probably just delete it and move on, if you keep reproducing it you'd need to start digging deeper, but, that probably wouldn't be for the issue tracker

**Comment by CarinaSchoppe** [comment]
> I can't tell you how the file ended up malformed, if it's just a fresh server probably just delete it and move on, if you keep reproducing it you'd need to start digging deeper, but, that probably wouldn't be for the issue tracker

yeah okay.
Ill move on
