### ISSUE TITLE
NPE when tab completing "/schedule clear" in console 

### ISSUE THREAD

**Issue by Varauk** [PaperSpigot/Paper#8345]
### Stack trace

```
[06:08:28 INFO]: [org.jline] Error while finding completion candidates
java.lang.NullPointerException: Cannot read field "N" because the return value of "net.minecraft.commands.CommandListenerWrapper.f()" is null
        at net.minecraft.server.commands.ScheduleCommand.lambda$static$1(ScheduleCommand.java:34) ~[?:?]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Paper-138]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:601) ~[paper-1.19.2.jar:?]
        at io.papermc.paper.console.BrigadierCommandCompleter.complete(BrigadierCommandCompleter.java:41) ~[paper-1.19.2.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_19_R1.command.ConsoleCommandCompleter.addCompletions(ConsoleCommandCompleter.java:150) ~[paper-1.19.2.jar:git-Paper-138]
        at org.bukkit.craftbukkit.v1_19_R1.command.ConsoleCommandCompleter.complete(ConsoleCommandCompleter.java:119) ~[paper-1.19.2.jar:git-Paper-138]
        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4381) ~[jline-reader-3.20.0.jar:?]
        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4347) ~[jline-reader-3.20.0.jar:?]
        at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4286) ~[jline-reader-3.20.0.jar:?]
        at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3778) ~[jline-reader-3.20.0.jar:?]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:679) ~[jline-reader-3.20.0.jar:?]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468) ~[jline-reader-3.20.0.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[terminalconsoleappender-1.3.0.jar:?]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[terminalconsoleappender-1.3.0.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:107) ~[paper-1.19.2.jar:git-Paper-138]
```

### Plugin and Datapack List

None

### Actions to reproduce (if known)

1. Boot fresh server
2. Type `schedule clear ` in server console
3. Press tab

Using tab completion ingame works fine.

Sidenote: The NPE also gets thrown when there are functions scheduled (but since it also occurs without any datapacks loaded I didnt upload a test datapack here).

### Paper version

> version
[06:09:54 INFO]: Checking version, please wait...
[06:09:54 INFO]: This server is running Paper version git-Paper-138 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 09904fd)
You are running the latest version
Previous version: git-Paper-135 (MC: 1.19.2)

**Comment by Varauk** [comment]
ah forgot to mention: tested it on spigot 1.19.2, worked fine there.

**Comment by Machine-Maker** [comment]
This is because the CommandSourceStack used in the brigadier console completer is created (when the terminal reader is started) before any world information has been loaded.

There are probably 2 potential fixes. Either the logic in the schedule command should fallback to the server (even though the level should always be non null for suggestions), or the CommandSourceStack in the completer should be lazily loaded.
