### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by LautjeDS** [PaperSpigot/Paper#8353]
### Stack trace

[06:56:42 ERROR]: Encountered an unexpected exception
java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:340) ~[?:?]
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282) ~[?:?]
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:321) ~[?:?]
        at java.util.jar.JarVerifier.update(JarVerifier.java:234) ~[?:?]
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:762) ~[?:?]
        at java.util.jar.JarFile.getInputStream(JarFile.java:845) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:181) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:56:42 WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.p" is null
        at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$15(MinecraftServer.java:1734) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.SystemReport.setDetail(SystemReport.java:61) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1733) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1255) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin and Datapack List

Fast Async World Edit
Fast Async Voxel Sniper
Gholo
LuckPerms
Custom Plugin from Me
Multiverse Core
PlaceholderAPI
PlugMan
PowerCamera
SkinsRestorer
Spark
Vault

### Actions to reproduce (if known)

Start the server (That simple)

### Paper version

As the server doesn't start, I have provided the startup version message
[06:56:41 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)

### Other

I tried updating to 1.19 but the error still appears.

**Comment by LautjeDS** [comment]
The issue was my custom plugin and it not being signed properly.
