### ISSUE TITLE
Console errors if write in chat

### ISSUE THREAD

**Issue by onovozhenov** [PaperSpigot/Paper#8359]
### Expected behavior

Must be no errors in console when somebody writes in chat

### Observed/Actual behavior

When anybody writes anything in chat - errors in console, core paper

[18:01:14 INFO]: [Not Secure] <bleazzz> a
[18:01:14 ERROR]: Chain link failed, continuing to next one
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
	at net.minecraft.server.network.ServerGamePacketListenerImpl.detectRateSpam(ServerGamePacketListenerImpl.java:2620) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2590) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2228) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps/models to reproduce

1. Join server
2. Write anything in chat
3. Get errors in console

No plugins or datapacks, latest build Velocity+Paper just configured default configs

### Plugin and Datapack List

No plugins, no datapacks

### Paper version

 This server is running Paper version git-Paper-142 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ef0e5a6)
You are running the latest version

**Comment by lynxplay** [comment]
Can you please share your `spigot.yml` configuration in addition to this.

**Comment by onovozhenov** [comment]
Moved to pastebin

**Comment by lynxplay** [comment]
Please upload it to a pastebin like https://paste.gg/, make sure you keep indentation correct.

**Comment by onovozhenov** [comment]
https://paste.gg/p/anonymous/e373b167e50a4fe3aba68326e9a91a3a

**Comment by onovozhenov** [comment]
Do you need server.properties, bukkit or paper configs?

**Comment by lynxplay** [comment]
Your `commands.spam-exclusions`, `commands.replace-commands` and `advancements.disabled` are all wrongly defined.
```yml
spam-exclusion:
 - []
```
in yaml means that spam exclusion holds a list of list, while it should hold a list of strings. You should change them to:
```yml
spam-exclusion: []
```
(and all other occurrences I listed above) as this properly defines it to be an empty list instead of a list with a single empty list inside.

**Comment by onovozhenov** [comment]
Thanks a lot! Useful info, I will change configs immediately.
