### ISSUE TITLE
java.lang.Throwable: null

### ISSUE THREAD

**Issue by rinnaninn** [PaperSpigot/Paper#8392]
### Expected behavior

Clean server boot after 'Timings Reset'  & armour stands plugin dialog

### Observed/Actual behavior

java.lang.Throwable: null
	at io.papermc.paper.chunk.system.entity.EntityLookup.addEntity(EntityLookup.java:369) ~[paper-1.19.2.jar:git-Paper-174]
	at io.papermc.paper.chunk.system.entity.EntityLookup.addEntityChunkEntities(EntityLookup.java:315) ~[paper-1.19.2.jar:git-Paper-174]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.loadInEntityChunk(NewChunkHolder.java:116) ~[paper-1.19.2.jar:git-Paper-174]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.getOrCreateEntityChunk(ChunkHolderManager.java:670) ~[paper-1.19.2.jar:git-Paper-174]
	at io.papermc.paper.chunk.system.scheduling.ChunkFullTask.run(ChunkFullTask.java:57) ~[paper-1.19.2.jar:git-Paper-174]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.19.2.jar:git-Paper-174]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.19.2.jar:git-Paper-174]
	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.executeMainThreadTask(ChunkTaskScheduler.java:250) ~[paper-1.19.2.jar:git-Paper-174]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1003) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:578) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.19.2.jar:git-Paper-174]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-174]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-174]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-174]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-174]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[latest.log](https://github.com/PaperMC/Paper/files/9646713/latest.log)

### Steps/models to reproduce

Updated from build 171 to 174. Initialised server. Stop/start will reproduce.

### Plugin and Datapack List

1 plugin enabled: Coreprotect
13 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/Shulker Preview Data Pack (1.19).zip (world)], [file/afk display v1.1.3.zip (world)], [file/anti enderman grief v1.1.3.zip (world)], [file/armor statues v2.8.4.zip (world)], [file/armored elytra v1.0.6.zip (world)], [file/confetti creepers v2.2.3.zip (world)], [file/custom nether portals v2.3.6.zip (world)], [file/double shulker shells v1.3.3.zip (world)], [file/dragon drops v1.3.3.zip (world)], [file/more mob heads v2.10.1.zip (world)], [file/player head drops v1.1.3.zip (world)]

### Paper version

This server is running Paper version git-Paper-174 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 01a1387)
You are running the latest version
Previous version: git-Paper-171 (MC: 1.19.2)

**Comment by tvig74** [comment]
Hi rinnaninn
I had the same problem and compared datapacks with your setup. I found that the datapack: **armored elytra v1.0.6.zip** caused the problem. Removing the datapack fixed the issue.

**Comment by rinnaninn** [comment]
> Hi rinnaninn I had the same problem and compared datapacks with your setup. I found that the datapack: **armored elytra v1.0.6.zip** caused the problem. Removing the datapack fixed the issue.

Cheers, tvig. We're not noticing any performance issues, but perhaps someone a little more familiar with this can address if there is concern to be had here or not.

**Comment by lynxplay** [comment]
I don't see how this is related to performance ? the data pack appears to be spawning an armorstand with a uuid that already exists in the worl.

Can you elaborate ?

**Comment by electronicboy** [comment]
Not a perf issue directly, but, spewing errors can lead to it;

So, that DP forceloads a chunk far out, and spawns an armor stand there; I'd imagine something induced a behavioral change somewhere in regards to force loaded chunks, maybe?

**Comment by tvig74** [comment]
Sorry for indicating this relation. I just observed that removing the armored elytra v1.0.6.zip datapack made the error go away. The issue appeares in version 174 and forward.

**Comment by rinnaninn** [comment]
> I don't see how this is related to performance ? the data pack appears to be spawning an armorstand with a uuid that already exists in the worl.
> 
> Can you elaborate ?

The datapack dialog is normal, & expected on subsequent loads. 
What is new are the error strings posted above. 
My comment about performance is simply me saying, I haven't noticed any consequence to this new string of errors, for what casual gameplay observation is worth.

**Comment by rinnaninn** [comment]
Updated to ver. 196 & Terminal no longer logs these nulls :)
