### ISSUE TITLE
paper build#174 is not working & making errors with some plugins 

### ISSUE THREAD

**Issue by adalmo** [PaperSpigot/Paper#8395]
### Expected behavior

it need to be no error with thoes plugins UltimateStacker & Panilla it was working on build#173 without thoes errors

### Observed/Actual behavior

[12:32:50 WARN]: [UltimateStacker] Plugin UltimateStacker v2.3.0 generated an exception while executing task 832
java.lang.NoSuchFieldError: P
        at com.songoda.ultimatestacker.core.nms.v1_19_R1v2.world.SWorldImpl.getLivingEntities(SWorldImpl.java:26) ~[UltimateStacker-2.3.0.jar:?]
        at com.songoda.ultimatestacker.core.world.SWorld.getLivingEntities(SWorld.java:35) ~[UltimateStacker-2.3.0.jar:?]
        at com.songoda.ultimatestacker.tasks.StackingTask.run(StackingTask.java:86) ~[UltimateStacker-2.3.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-176]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Steps/models to reproduce

put UltimateStacker & Panilla on plugin folder and got thoes errors 

### Plugin and Datapack List

UltimateStacker
Panilla 

### Paper version

build#176

**Comment by electronicboy** [comment]
Plugins messing with server internals will need to update, idk if there is a concession to provide a level of compatibility for this stuff

**Comment by MillionthOdin16** [comment]
This is a pretty significant issue. Many plugins have issues and I can't update because of this

**Comment by Owen1212055** [comment]
Well it’s their responsibility to update. This is because they are using unsupported parts of the server.

**Comment by Owen1212055** [comment]
Closing as this is generally an issue with plugins using NMS, and paper is not responsible for upkeep the use of NMS.
It is recommended that you stick to api calls inorder to prevent breakages between updates, or understand the fact that you will need to update the plugin manually due to these changes.
