### ISSUE TITLE
Spamming of error: onTrackingStart called during navigation iteration

### ISSUE THREAD

**Issue by bergerkiller** [PaperSpigot/Paper#8396]
### Expected behavior

This error not showing up spamming in the server log

### Observed/Actual behavior

This error shows up a huge amount of times:

```
[14:20:19 ERROR]: onTrackingStart called during navigation iteration
java.lang.IllegalStateException: onTrackingStart called during navigation iteration
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2558) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2517) ~[?:?]
	at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:265) ~[paper-1.19.2.jar:git-Paper-176]
	at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194) ~[paper-1.19.2.jar:?]
	at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304) ~[paper-1.19.2.jar:git-Paper-176]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1240) ~[paper-1.19.2.jar:git-Paper-176]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1309) ~[paper-1.19.2.jar:git-Paper-176]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1036) ~[paper-1.19.2.jar:git-Paper-176]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1020) ~[paper-1.19.2.jar:git-Paper-176]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:905) ~[paper-1.19.2.jar:git-Paper-176]
	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.scheduleTickingState(ChunkTaskScheduler.java:293) ~[paper-1.19.2.jar:git-Paper-176]
	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.scheduleChunkLoad(ChunkTaskScheduler.java:399) ~[paper-1.19.2.jar:git-Paper-176]
	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:533) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:440) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:502) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:780) ~[?:?]
	at net.minecraft.world.entity.ai.navigation.GroundPathNavigation.createPath(GroundPathNavigation.java:43) ~[?:?]
	at net.minecraft.world.entity.ai.navigation.PathNavigation.createPath(PathNavigation.java:112) ~[?:?]
	at net.minecraft.world.entity.ai.navigation.PathNavigation.recomputePath(PathNavigation.java:84) ~[?:?]
	at net.minecraft.server.level.ServerLevel.sendBlockUpdated(ServerLevel.java:1708) ~[?:?]
	at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:628) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:604) ~[?:?]
	at net.minecraft.world.level.Level.setBlock(Level.java:513) ~[?:?]
	at net.minecraft.world.level.block.DoorBlock.setOpen(DoorBlock.java:187) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.InteractWithDoor.start(InteractWithDoor.java:101) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.Behavior.tryStart(Behavior.java:60) ~[paper-1.19.2.jar:git-Paper-176]
	at net.minecraft.world.entity.ai.Brain.startEachNonRunningBehavior(Brain.java:417) ~[?:?]
	at net.minecraft.world.entity.ai.Brain.tick(Brain.java:374) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:250) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:247) ~[?:?]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:881) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3310) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:640) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2972) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.tick(Villager.java:292) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1190) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:728) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-176]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:708) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-176]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-176]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-176]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

Unsure as this is on someone else's server, but it has started happening since the new Chunk System changes. I assume an Entity is trying to navigate and loading a chunk (sync). Since entities now load in sync as well, it instantly trips that "tracking during navigation" tripwire.

### Plugin and Datapack List

BKCommonLib and MyWorlds. BKCL ruled out by disabling some code which might touch it.

### Paper version

This server is running Paper version git-Paper-175 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: b58c0cf)

### Other

Navigation -> Sync Chunk Load -> Chunk System -> LevelCallback -> ServerLevel::onTrackingStart -> OH NO

**Comment by bergerkiller** [comment]
Any update on this? An update is on hold until this is fixed. If it's going to take a little while that's fine, but I'd like to know, then I'll update a little sooner and deal with any incompatibilities later.

**Comment by lynxplay** [comment]
This in general is only a debug message.
```java
if (entity instanceof Mob) {
    Mob entityinsentient = (Mob) entity;

    if (ServerLevel.this.isUpdatingNavigations) {
        String s = "onTrackingStart called during navigation iteration";

        Util.logAndPauseIfInIde("onTrackingStart called during navigation iteration", new IllegalStateException("onTrackingStart called during navigation iteration"));
    }

    ServerLevel.this.navigatingMobs.add(entityinsentient);
}
```

we are most likely going to hide it by default behind some form of flag, but we are still discussing what flag exactly.

**Comment by BillyGalbreath** [comment]
Better question is why is `Util.logAndPauseIfInIde` throwing in production and not IDE as the name suggests?

**Comment by lynxplay** [comment]
the pause is the only thing that relates to the `IfInIde` suffix :sweat_smile:
