### ISSUE TITLE
Illegal Entity Teleport

### ISSUE THREAD

**Issue by MelonCraftDE** [PaperSpigot/Paper#8504]
### Expected behavior

no error like it was before updating
while riding an entity and teleport with them

### Observed/Actual behavior

an error and the entity isnt following

[16:59:34 WARN]: Illegal Entity Teleport EntityChicken['Chicken'/1011389, uuid='7b0f3b01-9fb1-47cc-a2f1-76f87bc756c3', l='ServerLevel[Farm]', x=228.50, y=89.20, z=1376.03, cpos=[14, 86], tl=11704, v=false] to ServerLevel[Towny]:net.minecraft.core.Position@7c05350e
java.lang.Throwable: null
        at net.minecraft.world.entity.Entity.teleportTo(Entity.java:3335) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:577) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:546) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:651) ~[paper-1.19.2.jar:git-Paper-235]
        at com.Zrips.CMI.AllListeners.PlayerListeners$4.run(PlayerListeners.java:1036) ~[CMI-9.2.4.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-235]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps/models to reproduce

Type "/cmi ride" while looing at an entity and warp/teleport to another world

### Plugin and Datapack List

 Plugins (49): AdvancedCrates, AdvancedEnchantments, AnimatedScoreboard, AsyncWorldEdit, BattlePass, Chunky, Citizens, CMI, CMILib, CommandPanels, ConsoleSpamFix, Denizen, DiscordSRV, dtlTraders, DungeonParties, dynmap, eco, EcoPets, ExecutableBlocks, ExecutableItems, HeadDatabase, Interactions, Iris, ItemsAdder, ItemsAdder-WorldEdit, Lands, LibsDisguises, LoneLibs, LuckPerms, Markets, mcMMO, ModelEngine, Multiverse-Core, MythicDungeons, MythicMobs, PlaceholderAPI, ProtocolLib, RealisticSeasons, SCore, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, Vulcan, WildStacker, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Paper version

> version
[17:33:24 INFO]: Checking version, please wait...
[17:33:25 INFO]: This server is running Paper version git-Paper-235 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 1c1aeb2)

**Comment by electronicboy** [comment]
We can't diagnose stuff around premium/closed source plugins, and CMI apparently straight up tried to teleport an entity which is no longer valid
