### ISSUE TITLE
watchdog crash

### ISSUE THREAD

**Issue by eki-github** [PaperSpigot/Paper#8550]
### Stack trace

```
[22:08:51 INFO]: [Matrix] Scanning outdated log files....
[22:08:51 INFO]: [Matrix] Deleted 0 outdated log files!
[22:08:51 INFO]: [Matrix] Hooked with PlaceholderAPI
[22:08:51 INFO]: [Matrix] Welcome to Matrix!
[22:08:51 INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[22:08:51 ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Thread.java:939) ~[?:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1041) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:817) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:1013) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[patched_1.17.1.jar:git-Paper-408]
[22:08:51 INFO]: Stopping server
[22:08:51 INFO]: [Matrix] Disabled Matrix AntiCheat.
[22:08:51 INFO]: [GSit] The Plugin was successfully disabled.
[22:08:51 INFO]: [PlotSquared/BukkitPlatform] (UUID) PlotSquared will fetch UUIDs in groups of 200
[22:08:51 INFO]: [PlotSquared/BukkitPlatform] (UUID) PlotSquared has cached 100.0% of UUIDs
[22:08:51 INFO]: [PlotSquared/BukkitPlatform] (UUID) PlotSquared has cached all UUIDs
[22:08:51 INFO]: [TAB] Disabled in 2ms
[22:08:52 INFO]: [PlotSquared/SQLManager] All DB transactions during this session are being validated (This may take a while if corrections need to be made)
[22:08:52 ERROR]: [PlotSquared/SQLManager] CRITICAL ERROR IN VALIDATION TASK!
[22:08:52 ERROR]: [PlotSquared/SQLManager] PLOT AREA CANNOT BE NULL! SKIPPING PLOT!
[22:08:52 INFO]: [PlayerKits] Has been disabled! Version: 2.22.2
[22:08:52 INFO]: Doszla smutna informacja, wylaczono kSwear
[22:08:52 INFO]: [hsqldb.db.HSQLDB80D2EF74D5.ENGINE] Database closed
[22:08:52 INFO]:

[]=====[Disabling AdvancedBan]=====[]
| Information:
|   Name: AdvancedBan
|   Developer: Leoko
|   Version: 2.3.0
|   Storage: HSQLDB (local)
| Support:
|   Github: https://github.com/DevLeoko/AdvancedBan/issues
|   Discord: https://discord.gg/ycDG6rS
| Twitter: @LeokoGar
[]================================[]

[22:08:52 INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[22:08:52 INFO]: Saving players
[22:08:52 INFO]: Saving worlds
[22:08:52 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[22:08:53 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:08:53 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[22:08:53 INFO]: Saving usercache.json
[22:08:53 INFO]: Flushing Chunk IO
[22:08:53 INFO]: Closing Thread Pool
[22:08:53 INFO]: Closing Server

```

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/65031661/200942443-afd6731c-bc5d-466c-ad44-1a1130446e8e.png)

### Paper version

1.17.1-408

### Other

pls help

**Comment by electronicboy** [comment]
1.17.1 is unsupported, nor is this the place for support with understanding logs
