### ISSUE TITLE
When a player is damaged by an arrow shot by a dispenser, PaperMC throws an exception

### ISSUE THREAD

**Issue by Ogikusa** [PaperSpigot/Paper#8552]
### Stack trace

```
[17:24:05 ERROR]: Could not pass event EntityDamageByEntityEvent to HealthBar v1.8.1
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_19_R1.projectiles.CraftBlockProjectileSource cannot be cas
t to class org.bukkit.entity.Entity (org.bukkit.craftbukkit.v1_19_R1.projectiles.CraftBlockProjectileSource and org.bukk
it.entity.Entity are in unnamed module of loader java.net.URLClassLoader @3eb07fd3)
        at com.rocknatalino.plugin.Mobs.onKillEvent(Mobs.java:134) ~[HealthBar.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?
]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:
git-Paper-265]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.j
ar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHO
T.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:249) ~[paper-1.19.2.
jar:git-Paper-265]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1153) ~[
paper-1.19.2.jar:git-Paper-265]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1012)
~[paper-1.19.2.jar:git-Paper-265]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:964) ~[paper-1.19.2.jar:git-Paper-265]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1187) ~[paper-1.19.2.jar:git-Paper-265]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2122) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1075) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1369) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:982) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1044) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:412) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:181) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:306) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:242) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1192) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:897) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:730) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.2.jar:git-Paper-265]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.2.jar:git-Paper-265]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-265]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-265]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-265]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-265]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

dynmap, EditableSign, floodgate, Geyser-Spigot, Hat, HealthBar, Images, LuckPerms, SimpleSit*

### Actions to reproduce (if known)

When a player is damaged by an arrow shot by a dispenser, PaperMC throws an exception.
Also this exception doesn't happend if a player damged by an arrow shot by other player.

Original Text:
ディスペンサーから放たれた矢によってプレイヤーがダメージを受けた場合、PaperMCは例外を投げます
この例外はプレイヤーが放った矢では起こりません(おそらくスケルトンでも)

### Paper version

[17:32:44 INFO]: This server is running Paper version git-Paper-265 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 117579c)
You are running the latest version
Previous version: git-Paper-237 (MC: 1.19.2)

**Comment by kennytv** [comment]
That's a problem inside of the plugin HealthBar, not with Paper
