### ISSUE TITLE
Chunk could not Deserialize

### ISSUE THREAD

**Issue by TheNetherPug** [PaperSpigot/Paper#8614]
### Expected behavior

Normal world loading
![2022-08-17_15 26 54](https://user-images.githubusercontent.com/91162221/206046969-73800a96-9b4c-418a-8338-166ee05ab774.png)

### Observed/Actual behavior

`	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:236) ~[?:?]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:107) ~[paper-1.18.2.jar:git-Paper-372]
	at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.2.jar:git-Paper-372]
	at com.destroystokyo.paper.io.chunk.ChunkTaskManager.pollNextChunkTask(ChunkTaskManager.java:231) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:1250) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:820) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1387) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-372]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1447) ~[paper-1.18.2.jar:git-Paper-372]
`

^ Sample of a very VERY long error.

![image](https://user-images.githubusercontent.com/91162221/206047057-2fbbbf4d-a6d4-445b-a6c4-517c64bc1e34.png)

### Steps/models to reproduce

Steps to reproduce:

- Delete the "World" folder.
- Restart server

### Paper version

git-Paper-411 running Minecraft 1.18.2.

This server is hosted on Minehut.

### Other

I am aware there is a similar issue to this posted on this github, however, I have searched everywhere and could not find a solution to this issue. If anyone can assist, It will be greatly appreciated.

**Comment by electronicboy** [comment]
excerpt of the error is useless, nor is 1.18 supported anymore
