### ISSUE TITLE
Errors appeared in my console upon starting the server.

### ISSUE THREAD

**Issue by Boomer-1** [PaperSpigot/Paper#8649]
### Timings or Profile link

there's no timings to run as the server wasn't even loaded.

### Description of issue

I'm not versed in java, i'm just reporting this error that appeared the first time I started paper 322 in a 1.19.3 world, before any plugins even were loaded.

### Plugin and Datapack List

none were loaded when this appeared.

### Server config files

```
Paste configs or paste.gg link here!
```
spigot.yml - https://pastebin.com/jDHpiLYD
server properties.yml https://pastebin.com/pSPufNQK
paper-world.yml  https://pastebin.com/by2EaJBQ
bukkit.yml. https://pastebin.com/LXwKkJvV
paper-global.yml  https://pastebin.com/VrnXUyZm

### Paper version

[16:02:19 INFO]: foChecking version, please wait...
[16:02:20 INFO]: fThis server is running Paper version git-Paper-322 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: eeeb8d5)r
aYou are running the latest version

### Other

sorry i have nothing else to give you other than what's in the log. Here's the errors

[15:50:13 ERROR]: Failed to read console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:276) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:282) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:329) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:396) ~[?:?]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:180) ~[terminalconsoleappender-1.3.0.jar:?]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[terminalconsoleappender-1.3.0.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:102) ~[paper-1.19.3.jar:git-Paper-322]
	Suppressed: java.io.IOException: The handle is invalid
		at java.io.FileDescriptor.close0(Native Method) ~[?:?]
		at java.io.FileDescriptor.close(FileDescriptor.java:297) ~[?:?]
		at java.io.FileInputStream$1.close(FileInputStream.java:459) ~[?:?]
		at java.io.FileDescriptor.closeAll(FileDescriptor.java:355) ~[?:?]
		at java.io.FileInputStream.close(FileInputStream.java:457) ~[?:?]
		at java.io.BufferedInputStream.close(BufferedInputStream.java:481) ~[?:?]
		at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:366) ~[?:?]
		at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:204) ~[?:?]
		at java.io.InputStreamReader.close(InputStreamReader.java:192) ~[?:?]
		at java.io.BufferedReader.close(BufferedReader.java:525) ~[?:?]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:183) ~[terminalconsoleappender-1.3.0.jar:?]
		at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) ~[terminalconsoleappender-1.3.0.jar:?]
		at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:102) ~[paper-1.19.3.jar:git-Paper-322]

**Comment by electronicboy** [comment]
This is pretty much always down to running in environments that don't provide a proper terminal, given that detecting this is not something that's ultra viable, and it has no effect on the app or how it performs, etc; this won't be touched
