### ISSUE TITLE
Server (that used to work) crash on startup

### ISSUE THREAD

**Issue by Amitb01FUB** [PaperSpigot/Paper#8702]
### Stack trace

This server has been running for the past 3 weeks without a problem. 
Last night the server crashed/restarted with no log file for the crash, at the time of the crash two players were connected AFK at farms.
Since the crash the server won't start.

log file:

```
[15:37:57] [ServerMain/INFO]: Building unoptimized datafixer
[15:37:58] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:37:59] [ServerMain/INFO]: Loaded 7 recipes
[15:38:00] [Server thread/INFO]: Starting minecraft server version 1.19.2
[15:38:00] [Server thread/INFO]: Loading properties
[15:38:01] [Server thread/INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
[15:38:01] [Server thread/INFO]: Server Ping Player Sample Count: 12
[15:38:01] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:38:01] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[15:38:01] [Server thread/INFO]: Default game type: SURVIVAL
[15:38:01] [Server thread/INFO]: Generating keypair
[15:38:01] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:38:01] [Server thread/INFO]: Using default channel type
[15:38:01] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[15:38:01] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[15:38:02] [Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_19_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[15:38:05] [Server thread/WARN]: Legacy plugin OnePlayerSleep v1.3 does not specify an api-version.
[15:38:05] [Server thread/INFO]: [ServerBackup] Loading ServerBackup v2.8.3
[15:38:05] [Server thread/INFO]: [SkinsRestorer] Loading SkinsRestorer v14.2.3
[15:38:05] [Server thread/INFO]: [OnePlayerSleep] Loading OnePlayerSleep v1.3
[15:38:05] [Server thread/INFO]: [SmoothTimber] Loading SmoothTimber v1.22.4
[15:38:05] [Server thread/INFO]: [UserLogin] Loading UserLogin v2.13.1
[15:38:05] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:38:05] [Server thread/INFO]: Preparing level "world"
[15:38:05] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Could not create world config for world
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:275) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.level.ServerLevel.lambda$new$2(ServerLevel.java:529) ~[?:?]
	at net.minecraft.world.level.Level.<init>(Level.java:276) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:529) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:586) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.spongepowered.configurate.loader.ParsingException: []: Unknown error occurred while loading
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:165) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56) ~[configurate-core-4.1.2.jar:?]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:208) ~[paper-1.19.2.jar:git-Paper-307]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:187) ~[paper-1.19.2.jar:git-Paper-307]
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:273) ~[paper-1.19.2.jar:git-Paper-307]
	... 9 more
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateScanner.scanToNextToken(ConfigurateScanner.java:1206) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateScanner.fetchMoreTokens(ConfigurateScanner.java:316) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateScanner.checkToken(ConfigurateScanner.java:256) ~[configurate-yaml-4.1.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184) ~[snakeyaml-1.33.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateYaml.loadConfigurate(ConfigurateYaml.java:39) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:158) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:42) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:155) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56) ~[configurate-core-4.1.2.jar:?]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:208) ~[paper-1.19.2.jar:git-Paper-307]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:187) ~[paper-1.19.2.jar:git-Paper-307]
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:273) ~[paper-1.19.2.jar:git-Paper-307]
	... 9 more
[15:38:05] [Server thread/ERROR]: 	Cause of unexpected exception was
org.spongepowered.configurate.loader.ParsingException: []: Unknown error occurred while loading
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:165) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56) ~[configurate-core-4.1.2.jar:?]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:208) ~[paper-1.19.2.jar:git-Paper-307]
	at io.papermc.paper.configuration.Configurations.createWorldConfig(Configurations.java:187) ~[paper-1.19.2.jar:git-Paper-307]
	at io.papermc.paper.configuration.PaperConfigurations.createWorldConfig(PaperConfigurations.java:273) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.level.ServerLevel.lambda$new$2(ServerLevel.java:529) ~[?:?]
	at net.minecraft.world.level.Level.<init>(Level.java:276) ~[?:?]
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:529) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:586) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateScanner.scanToNextToken(ConfigurateScanner.java:1206) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateScanner.fetchMoreTokens(ConfigurateScanner.java:316) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateScanner.checkToken(ConfigurateScanner.java:256) ~[configurate-yaml-4.1.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:184) ~[snakeyaml-1.33.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateYaml.loadConfigurate(ConfigurateYaml.java:39) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:158) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:42) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:155) ~[configurate-core-4.1.2.jar:?]
	... 14 more
[15:38:05] [Server thread/ERROR]: This crash report has been saved to: G:\minecraft server DN\Server with rebbeca\.\crash-reports\crash-2022-12-20_15.38.05-server.txt
[15:38:05] [Server thread/INFO]: Stopping server
[15:38:05] [Server thread/INFO]: Saving players
[15:38:05] [Server thread/INFO]: Saving worlds
[15:38:05] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[15:38:05] [Server thread/INFO]: Flushing Chunk IO
[15:38:05] [Server thread/INFO]: Closing Thread Pool
[15:38:05] [Server thread/INFO]: Closing Server

```

### Plugin and Datapack List

ServerBackup
SkinsRestorer
OnePlayerSleep
SmoothTimber
UserLogin

### Actions to reproduce (if known)

Running the server, with and without plugins, also tried using the newest Paper version (without success)
The world does work on Vanilla and Single-player, but this is not a solution since users lose their inventory, and a lot of players had a lot of good stuff on them.

### Paper version

(from log file)

[15:38:01] [Server thread/INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

**Comment by lynxplay** [comment]
You have an invalid configuration file that includes special characters.
Either delete the world config file and recreate it or find the invalid character.

Generally tho, this is nothing for the issuer tracker, please head to our [discord](https://discord.gg/papermc) if you have more issues with this.
This is expected behaviour of paper :+1:
