### ISSUE TITLE
shulker boxes broken

### ISSUE THREAD

**Issue by NBS-Paste** [PaperSpigot/Paper#8708]
### Expected behavior

 shulker box drops when mined with a pickaxe

### Observed/Actual behavior

shulker box doesnt drop when mined with a pickaxe

### Steps/models to reproduce

break shulker box with a pickaxe

### Plugin and Datapack List

Plugins (15): ChunkLoader, Chunky, DeadChest, DynDeath, dynmap, floodgate, Geyser-Spigot, HeadsPlus, HiddenArmor, Mapify, ProtocolLib, SilkSpawners_v2, VeinMiner, WorldEdit, WorldGuard

There are 13 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/explosiondropsall (world)], [file/anti ghast grief v1.1.3 (world)], [file/anti enderman grief v1.1.3 (world)], [file/custom nether portals v2.3.6 (world)], [file/durability ping v1.1.3 (world)], [file/nether portal coords v1.1.3 (world)], [file/back to blocks (world)], [file/more trapdoors data pack (world)], [file/spawning spheres v1.1.3 (world)], [file/merge-xp (world)], [file/anti enderman grief v1.1.3.zip (world)]

### Paper version

Previous version: git-Paper-340 (MC: 1.19.3)

**Comment by Machine-Maker** [comment]
Can you replicate this with no plugins or datapacks?

**Comment by NBS-Paste** [comment]
havent tried it but i dont want to delete them all then reinstall them

**Comment by Machine-Maker** [comment]
See, the problem is, that if it is an issue with one of those plugins, how am I supposed to know that? If it’s an issue with one of the plugins or datapacks, it’s not a paper issue. I suspect this is the case, cause if no one could break shulkers, we’d be inundated with issues about it. I could try and replicate what you have exactly, but that is an insane amount of work, and I don’t know how you have each of your plugins configured. I don’t know where you got each of your plugins or datapacks, maybe you modified them slightly yourself… I could go on and on with reasons that testing without plugins or datapacks is important to issue triage. Because I can break shulkers on a test server with no plugins or datapacks.

**Comment by NBS-Paste** [comment]
if i coppied all of the server files would it make a replica server for me to test it?

**Comment by NBS-Paste** [comment]
ok

**Comment by NBS-Paste** [comment]
ill try it in a bit and get back to you

**Comment by NBS-Paste** [comment]
i just tried and i coppied the server and it wouldnt work when i tried to run it. i tried changing the port to 25566 so it would let me connect to it and not my normal server 

[14:45:26] [ServerMain/INFO]: Building unoptimized datafixer
[14:45:27] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:45:27] [ServerMain/WARN]: Missing data pack file/explosiondropsall
[14:45:27] [ServerMain/WARN]: Missing data pack file/anti ghast grief v1.1.3
[14:45:27] [ServerMain/WARN]: Missing data pack file/anti enderman grief v1.1.3
[14:45:27] [ServerMain/WARN]: Missing data pack file/custom nether portals v2.3.6
[14:45:27] [ServerMain/WARN]: Missing data pack file/durability ping v1.1.3
[14:45:27] [ServerMain/WARN]: Missing data pack file/nether portal coords v1.1.3
[14:45:27] [ServerMain/WARN]: Missing data pack file/back to blocks
[14:45:27] [ServerMain/WARN]: Missing data pack file/more trapdoors data pack
[14:45:27] [ServerMain/WARN]: Missing data pack file/spawning spheres v1.1.3
[14:45:27] [ServerMain/WARN]: Missing data pack file/merge-xp
[14:45:27] [ServerMain/WARN]: Missing data pack file/anti enderman grief v1.1.3.zip
[14:45:28] [ServerMain/INFO]: Loaded 7 recipes
[14:45:29] [Server thread/INFO]: Starting minecraft server version 1.19.3
[14:45:29] [Server thread/INFO]: Loading properties
[14:45:29] [Server thread/INFO]: This server is running Paper version git-Paper-349 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 7b52db5)
[14:45:29] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:45:29] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:45:29] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[14:45:29] [Server thread/INFO]: Default game type: SURVIVAL
[14:45:29] [Server thread/INFO]: Generating keypair
[14:45:29] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:45:29] [Server thread/INFO]: Using default channel type
[14:45:29] [Server thread/INFO]: Paper: Using Java compression from Velocity.
[14:45:29] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[14:45:29] [Server thread/WARN]: **** FAILED TO BIND TO PORT!
[14:45:29] [Server thread/WARN]: The exception was: java.net.BindException: Address already in use: bind
[14:45:29] [Server thread/WARN]: Perhaps a server is already running on that port?
[14:45:29] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[paper-1.19.3.jar:git-Paper-349]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-349]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[14:45:29] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Jack\Dropbox\PC\Desktop\test minecraft server\.\crash-reports\crash-2022-12-22_14.45.29-server.txt
[14:45:29] [Server thread/INFO]: Stopping server
[14:45:29] [Server thread/INFO]: Saving players
[14:45:29] [Server thread/INFO]: Saving worlds
[14:45:29] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[14:45:29] [Server thread/INFO]: Flushing Chunk IO
[14:45:29] [Server thread/INFO]: Closing Thread Pool
[14:45:29] [Server thread/INFO]: Closing Server

**Comment by lynxplay** [comment]
Judging by your log, you did not successfully change the port.
`[14:45:29] [Server thread/INFO]: Starting Minecraft server on *:25565`
make sure to save the server.properties file after you edited it. If you need more help, I'd suggest joining our discord, github issues are not meant for support.

**Comment by NBS-Paste** [comment]
well it wasn't paper's problem
it is one of the plugins or data packs
