### ISSUE TITLE
"Illegal Entity Teleport" when async teleporting non-players between worlds.

### ISSUE THREAD

**Issue by BigScary** [PaperSpigot/Paper#8732]
### Expected behavior

Entity teleports across worlds without error. This has been working on my server for years, but stopped working (i estimate) a few weeks ago. It's kind of a big deal for us because players want to take their favorite non-player entities, especially leveled-up villagers, from our temporary "resource gathering" world to our permanent "building" world.

### Observed/Actual behavior

Entity does not teleport. Error in logs:

Illegal Entity Teleport EntityPig['Pig'/843237, uuid='26ebfdbe-6475-460a-bceb-730f23c52a8e', l='ServerLevel[sampleWorld]', x=-5631.79, y=65.00, z=-11811.22, cpos=[-352, -739], tl=118475, v=false] to ServerLevel[world]:net.minecraft.core.Position@77cce2e2
java.lang.Throwable: null
	at net.minecraft.world.entity.Entity.teleportTo(Entity.java:3365) ~[paper-1.19.3.jar:git-Paper-360]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftEntity.teleport(CraftEntity.java:585) ~[paper-1.19.3.jar:git-Paper-360]
	at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftEntity.teleport(CraftEntity.java:554) ~[paper-1.19.3.jar:git-Paper-360]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:651) ~[paper-1.19.3.jar:git-Paper-360]
	at org.bukkit.craftbukkit.v1_19_R2.entity.CraftEntity.lambda$teleportAsync$0(CraftEntity.java:1273) ~[paper-1.19.3.jar:git-Paper-360]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-360]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-360]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-360]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-360]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-360]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.3.jar:git-Paper-360]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-360]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-360]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps/models to reproduce

Attempt to teleport an animal entity from one "normal" world to another "normal" world. By normal I mean not nether or end.

I am using the entity.TeleportAsync(location) method, and I am calling this method as a followup from another teleportasync() call with a player entity.

So the strategy is "teleport this player async, and when that's done, teleport all these non-player entities asynchronously to the same location".

### Plugin and Datapack List

Plugins (34): aArmorStandEditorf, aAutomaticInventoryf, aBetterMsgPlusf, aBetterShulkerBoxesf, aBreweryf, aBuycraftXf, aCelestef, aDiscordChat*f, aDiscordSRVf, aExcellentEnchantsf, aFastLeafDecayf, aGraviTreef, aGriefPreventionf, aGriefPreventionFlagsf, aGSitf, aHatf, aHeadDatabasef, aIslandsf, aIslandsWorldGenf, amcMMOf, aMeteoritesProf, aMoreMobHeadsf, aMyPetf, aNexEnginef, aPermissionsBukkit*f, aPhantomAdminf, aPlanf, aPopulationDensityf, aShopkeepersf, aSystemChatf, aVeinMinerf, aViaVersionf, aWorldEditf, aWuufusWaygates

### Paper version

This server is running Paper version git-Paper-362 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: https://github.com/PaperMC/Paper/commit/52718dba10c028a57a7a00993ed490a503ca9ecd)
You are running the latest version
Previous version: git-Paper-360 (MC: 1.19.3)

### Other

You guys are amazing, thank you for making high performance servers possible, so we can have big Minecraft communities. <3

**Comment by Owen1212055** [comment]
The interesting thing is according to the log this entity is "invalid", but it isn't removed from the world. Does this happen to be in unloaded chunks? :thinking:

**Comment by Owen1212055** [comment]
Seeing as though this has not occurred again, I will be closing this.

Feel free to leave a comment and we can reopen the issue if needed.
