### ISSUE TITLE
Problem with HealthScale causing server crash

### ISSUE THREAD

**Issue by BuchNieZyje** [PaperSpigot/Paper#8808]
### Stack trace

```
[12:12:21 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1412) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.MinecraftServer$$Lambda$4614/0x00000000ca5f1018.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket.<init>(ClientboundUpdateAttributesPacket.java:22) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:382) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:203) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:1267) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:1278) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:822) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:653) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:701) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        ... 6 more
[12:12:21 ERROR]:       Cause of unexpected exception was
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:?]
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundUpdateAttributesPacket.<init>(ClientboundUpdateAttributesPacket.java:22) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendDirtyEntityData(ServerEntity.java:382) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:203) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.processTrackQueue(ChunkTracker.java:1267) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:1278) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:822) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:653) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:701) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1412) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[slimeworldmanager-1.19.3.jar:git-SlimeWorldManager-"678eb15"]
        at net.minecraft.server.MinecraftServer$$Lambda$4614/0x00000000ca5f1018.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/106920313/214307511-2511b55d-785e-49e5-b9d9-53df34ccd076.png)

datapack are clear

### Actions to reproduce (if known)

I think is problem with 
```
player.setHealthScaled();
player.setHealthScale();
```
Only mythiclib using this

### Paper version

This server is running SlimeWorldManager version git-SlimeWorldManager-"cd92f60" (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: cd92f60)
Unknown version
Previous version: git-SlimeWorldManager-31 (MC: 1.19.3)

(fork from Paper 1.19.3)

### Other

This bug has been for a couple of version (from 1.17.1) and on 1.19.3 are still bothering my server.

In MythicLib config there is a "delay" before scaling hp, but its not really helpful

in my own plugin I also get this error when trying to scale hp, so it's not strictly related to mythic lib.

The error also doesn't always occur, but if it does, it always occurs right after the player enters

**Comment by Owen1212055** [comment]
Please try to reproduce with Paper.
