### ISSUE TITLE
ConfiguredStructure Registry returns null

### ISSUE THREAD

**Issue by maestro-denery** [PaperSpigot/Paper#8810]
### Expected behavior

`org.bukkit.Registry.CONFIGURED_STRUCTURE` should return `org.bukkit.Registry` instance. `Reference<>` fields in `io.papermc.paper.world.structure.ConfiguredStructure` shouldn't throw NPE when calling the `.value()` method.

### Observed/Actual behavior

`org.bukkit.Registry.CONFIGURED_STRUCTURE` returns null. `ConfiguredStructure.BASTION_REMNANT.value()` throws an NPE.

### Steps/models to reproduce

Create a new plugin with such a code:
```java
import io.papermc.paper.world.structure.ConfiguredStructure;
import org.bukkit.NamespacedKey;
import org.bukkit.Registry;
import org.bukkit.plugin.java.JavaPlugin;

public class MiscVanillaTweaks extends JavaPlugin {
    @Override
    public void onEnable() {
        Registry<ConfiguredStructure> configuredStructure = Registry.CONFIGURED_STRUCTURE;
        System.out.println(configuredStructure);

        System.out.println(ConfiguredStructure.BASTION_REMNANT);
        System.out.println(ConfiguredStructure.BASTION_REMNANT.value());
    }
}
```
See in the log:
```
[23:35:32 INFO]: null
[23:35:32 INFO]: ReferenceImpl[registry=null, key=minecraft:bastion_remnant]
[23:35:32 ERROR]: Error occurred while enabling MiscVanillaTweaks v1.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.Registry.get(org.bukkit.NamespacedKey)" because "this.registry" is null
	at io.papermc.paper.registry.ReferenceImpl.value(ReferenceImpl.java:15) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-384]
	at io.denery.tweaks.MiscVanillaTweaksPlugin.onEnable(MiscVanillaTweaksPlugin.java:64) ~[MiscVanillaTweaks-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-384]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-384]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.3.jar:git-Paper-384]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-384]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-384]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

(MiscVanillaTweaks is a testing plugin which contains only the testing code for this issue)

Plugins (1): MiscVanillaTweaks

There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

### Paper version

This server is running Paper version git-Paper-384 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 18fabc0)
You are running the latest version

### Other

The easy fix is to make more logic in the method `org.bukkit.craftbukkit.v1_19_R1.CraftRegistry#createRegistry(Class<B>, RegistryAccess)` which would return an instance of the registry for the given `ConfiguredStructure` class.

**Comment by Machine-Maker** [comment]
Yeah, that API needs to be deprecated and removed. Upstream added api for those and paper's hasn't been updated

**Comment by maestro-denery** [comment]
tbh I don't think deprecation in this case is even needed, I think we can remove it entirely, because it seems this API hasn't been working since its creation?.. And I doubt anyone has relied on classes of a broken API. Also, I'd still like to have Reference API class, but I'd like to not to have ReferenceImpl in the API in any form, because in https://github.com/PaperMC/Paper/pull/8789 I extend its functionality and make its implementation baked to NMS Holder<T>, and generally having Impl class in the API is bad

**Comment by Machine-Maker** [comment]
It was def working. In one of the mc version updates, it was broken when someone incorrectly changed the function to get the registry to the upstream version instead of registryFor

**Comment by Machine-Maker** [comment]
Closed by https://github.com/PaperMC/Paper/pull/8642
