### ISSUE TITLE
Crashes after 1.19.3 Paper version (Cannot invoke "net.minecraft.world.entity.Entity.dC()" because "entity" is null)

### ISSUE THREAD

**Issue by LoyalPineapple** [PaperSpigot/Paper#8814]
### Stack trace

Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.dC()" because "entity" is null
	at io.papermc.paper.chunk.system.entity.EntityLookup.getEntityStatus(EntityLookup.java:330)
	at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:190)
	at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304)
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1240)
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1344)
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1050)
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1034)
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:919)
	at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:583)
	at net.minecraft.server.level.ServerChunkCache.saveIncrementally(ServerChunkCache.java:608)
	at net.minecraft.server.level.ServerLevel.saveIncrementally(ServerLevel.java:1295)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1434)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Plugin and Datapack List

Custom

### Paper version

381

### Other

If the issue is not within Paper but is in a plugin, how would you pinpoint which part of a plugin is causing it?
Also, if it's a plugin's fault, then why wouldn't that show in the stack trace?

**Comment by lynxplay** [comment]
Basically means some plugin is messing with the internals of the server without properly updating
all of the state that it should.

Specifically, it seems like `com.destroystokyo.paper.util.maplist.EntityList` is somehow edited improperly, maintaining a larger count than it should, which leads to null elements being accessed in
```java
public void updateStatus(final ChunkHolder.FullChunkStatus status, final EntityLookup lookup) {
    this.status = status;

    final Entity[] entities = this.entities.getRawData();

    for (int i = 0, size = this.entities.size(); i < size; ++i) {
        final Entity entity = entities[i];
```
(from `io/papermc/paper/world/ChunkEntitySlices.java`). If you cannot replicate this without plugins, I'll close this as a plugin issue 👍

**Comment by LoyalPineapple** [comment]
I haven't seen this without plugins yet.

If I compile paper to throw an error where the EntityList is potentially edited by a plugin ouside of the tick thread, where would I place the throw?

**Comment by lynxplay** [comment]
I'll close this as a plugin caused issue then. Basically, you'll have to ensure in a custom paper build that nothing touches that
logic off the servers `io.papermc.paper.util.TickThread#isTickThread`.

How you do that is up to you :+1:
