### ISSUE TITLE
SkullMeta ItemStack equals error

### ISSUE THREAD

**Issue by SwordOfSouls** [PaperSpigot/Paper#8821]
### Expected behavior

For no error to occur and for the task to pass as usual.

### Observed/Actual behavior

`[UltimateGUI] Task #56 for UltimateGUI v2.0.6.1 generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTTagCompound.equals(Object)" because "this.serializedProfile" is null
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaSkull.equalsCommon(CraftMetaSkull.java:305) ~[paper-1.19.3.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftItemFactory.equals(CraftItemFactory.java:363) ~[paper-1.19.3.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftItemFactory.equals(CraftItemFactory.java:350) ~[paper-1.19.3.jar:git-Paper-384]
        at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:297) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.equals(ItemStack.java:278) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.soulsoftware.spigot.UltimateGUI.Listeners.impl.InventoryOpen$1.run(InventoryOpen.java:64) ~[UltimateGUI-Builder-2.0.6.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-384]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-384]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Steps/models to reproduce

1. Use [https://github.com/SoulsSoftware/Spigot-Core](SoulSoftware Core API) to create a skull. 
2. Try to use .equals on the returned ItemStack 
3. Error occurs

### Plugin and Datapack List

Plugins

- BetterHeads
- BKCommonLib
- LightCleaner
- LoneLibs
- mcMMO
- NBTAPI
- PlugMan
- PlugManX (PlugMan)
- Polymart
- ProtocolLib
- UltimateGUI
- ViaBackwards
- ViaRewind
- ViaVersion

No non vanilla Datapacks

### Paper version

This server is running Paper version git-Paper-384 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 18fabc0)
You are running the latest version
Previous version: git-Paper-307 (MC: 1.19.2)

### Other

Issue only started occurring recently with no changes to the API

**Comment by Machine-Maker** [comment]
This is a bug with whatever created that skull ItemStack. The serializedProfile and GameProfile fields are either both null, or both nonnull unless something is using reflection to set the fields.
