### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by p1gkk** [PaperSpigot/Paper#8825]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
[14:01:13] [ServerMain/INFO]: Building unoptimized datafixer
[14:01:20] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:01:30] [ServerMain/INFO]: Loaded 7 recipes
[14:01:34] [Server thread/INFO]: Starting minecraft server version 1.19.3
[14:01:34] [Server thread/INFO]: Loading properties
[14:01:34] [Server thread/INFO]: This server is running Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)
[14:01:34] [Server thread/WARN]: Couldn't load server icon
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "image" is null
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadServerIcon0(CraftServer.java:2353) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadServerIcon0(CraftServer.java:2341) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadIcon(CraftServer.java:1082) ~[paper-1.19.3.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.<init>(CraftServer.java:381) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.players.PlayerList.<init>(PlayerList.java:167) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(DedicatedPlayerList.java:16) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:203) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:01:34] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:01:34] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:01:35] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[14:01:36] [Server thread/INFO]: Default game type: SURVIVAL
[14:01:36] [Server thread/INFO]: Generating keypair
[14:01:36] [Server thread/INFO]: Starting Minecraft server on *:25565
[14:01:36] [Server thread/INFO]: Using epoll channel type
[14:01:36] [Server thread/INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.
[14:01:36] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux aarch64) cipher from Velocity.
[14:01:37] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:01:37] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[14:01:37] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[14:01:37] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[14:01:37] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[14:01:37] [Server thread/INFO]: Preparing level "world"
[14:01:39] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Loading NBT data
	at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:516) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:43) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:30) ~[?:?]
	at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:510) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:43) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:30) ~[?:?]
	at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:293) ~[?:?]
	at net.minecraft.nbt.NbtIo.read(NbtIo.java:238) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:58) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:33) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource.lambda$getLevelData$4(LevelStorageSource.java:234) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource.readLevelData(LevelStorageSource.java:197) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.getDataTag(LevelStorageSource.java:453) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:528) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[?:?]
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) ~[?:?]
	at net.minecraft.util.FastBufferedInputStream.fill(FastBufferedInputStream.java:94) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.util.FastBufferedInputStream.read(FastBufferedInputStream.java:42) ~[paper-1.19.3.jar:git-Paper-386]
	at java.io.DataInputStream.readFully(DataInputStream.java:201) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
	at net.minecraft.nbt.StringTag$1.load(StringTag.java:16) ~[?:?]
	at net.minecraft.nbt.StringTag$1.load(StringTag.java:15) ~[?:?]
	at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:510) ~[?:?]
	... 18 more
[14:01:39] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[?:?]
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) ~[?:?]
	at net.minecraft.util.FastBufferedInputStream.fill(FastBufferedInputStream.java:94) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.util.FastBufferedInputStream.read(FastBufferedInputStream.java:42) ~[paper-1.19.3.jar:git-Paper-386]
	at java.io.DataInputStream.readFully(DataInputStream.java:201) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:570) ~[?:?]
	at net.minecraft.nbt.StringTag$1.load(StringTag.java:16) ~[?:?]
	at net.minecraft.nbt.StringTag$1.load(StringTag.java:15) ~[?:?]
	at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:510) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:43) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:30) ~[?:?]
	at net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:510) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:43) ~[?:?]
	at net.minecraft.nbt.CompoundTag$1.b(CompoundTag.java:30) ~[?:?]
	at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:293) ~[?:?]
	at net.minecraft.nbt.NbtIo.read(NbtIo.java:238) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:58) ~[?:?]
	at net.minecraft.nbt.NbtIo.readCompressed(NbtIo.java:33) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource.lambda$getLevelData$4(LevelStorageSource.java:234) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource.readLevelData(LevelStorageSource.java:197) ~[?:?]
	at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.getDataTag(LevelStorageSource.java:453) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:528) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:01:39] [Server thread/ERROR]: This crash report has been saved to: /home/pi/mc_server/1.19.3/./crash-reports/crash-2023-01-30_14.01.39-server.txt
[14:01:39] [Server thread/INFO]: Stopping server
[14:01:39] [Server thread/INFO]: Saving players
[14:01:39] [Server thread/INFO]: Saving worlds
[14:01:39] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[14:01:39] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[14:01:39] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[14:01:39] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[14:01:39] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world' in 0.00s
[14:01:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[14:01:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[14:01:40] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[14:01:40] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[14:01:40] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[14:01:40] [Server thread/INFO]: [ChunkHolderManager] Saved 0 block chunks, 0 entity chunks, 0 poi chunks in world 'world_nether' in 0.00s
[14:01:40] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[14:01:40] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[14:01:40] [Server thread/INFO]: Flushing Chunk IO
[14:01:40] [Server thread/INFO]: Closing Thread Pool
[14:01:43] [Server thread/INFO]: Closing Server

### Plugin and Datapack List

None

### Actions to reproduce (if known)

Only me in the server I was in the sea opening chest ,somehow the server crashed.

### Paper version

Paper version git-Paper-386 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 4da844f)

### Other

None

**Comment by MWHunter** [comment]
[14:01:37] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

offline mode is not supported

**Comment by NoahvdAa** [comment]
Your level.dat file (in the world folder) seems to be corrupted. You could try replacing it with the backup file, level.dat_old. That might not be the only corrupted file though, since your server also seems to be having issues loading the icon, for example.

If you have any more issues, please use the discord or forums for support (but do keep in mind that we don't support piracy, as mentioned above).
