### ISSUE TITLE
Pterodactyl install error

### ISSUE THREAD

**Issue by megatron0001** [PaperSpigot/Paper#8854]
### Stack trace

java.lang.ExceptionInInitializerError
        at io.papermc.paper.world.structure.PaperConfiguredStructure.init(PaperConfiguredStructure.java:26)
        at net.minecraft.world.level.levelgen.structure.Structure.<clinit>(Structure.java:45)
        at net.minecraft.world.level.levelgen.structure.StructureSet$a.a(StructureSet.java:32)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.world.level.levelgen.structure.StructureSet$a.<clinit>(StructureSet.java:32)
        at net.minecraft.world.level.levelgen.structure.StructureSet.a(StructureSet.java:14)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.world.level.levelgen.structure.StructureSet.<clinit>(StructureSet.java:14)
        at net.minecraft.world.level.levelgen.structure.placement.StructurePlacement$a.a(StructurePlacement.java:131)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.world.level.levelgen.structure.placement.StructurePlacement$a.<clinit>(StructurePlacement.java:130)
        at net.minecraft.world.level.levelgen.structure.placement.StructurePlacement.a(StructurePlacement.java:31)
        at net.minecraft.world.level.levelgen.structure.placement.RandomSpreadStructurePlacement.b(RandomSpreadStructurePlacement.java:15)
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
        at net.minecraft.world.level.levelgen.structure.placement.RandomSpreadStructurePlacement.<clinit>(RandomSpreadStructurePlacement.java:15)
        at net.minecraft.world.level.levelgen.structure.placement.StructurePlacementType.<clinit>(StructurePlacementType.java:14)
        at net.minecraft.core.registries.BuiltInRegistries.n(BuiltInRegistries.java:231)
        at net.minecraft.core.registries.BuiltInRegistries.a(BuiltInRegistries.java:306)
        at net.minecraft.core.registries.BuiltInRegistries.lambda$createContents$54(BuiltInRegistries.java:326)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at net.minecraft.core.registries.BuiltInRegistries.b(BuiltInRegistries.java:325)
        at net.minecraft.core.registries.BuiltInRegistries.bootStrap(BuiltInRegistries.java:318)
        at net.minecraft.server.DispenserRegistry.a(DispenserRegistry.java:73)
        at net.minecraft.server.Main.main(Main.java:114)
        at org.bukkit.craftbukkit.Main.main(Main.java:302)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Server.getRegistry(java.lang.Class)" because "org.bukkit.Bukkit.server" is null
        at org.bukkit.Bukkit.getRegistry(Bukkit.java:2272)
        at org.bukkit.Registry.<clinit>(Registry.java:139)
        ... 27 more

### Plugin and Datapack List

None

### Actions to reproduce (if known)

Install papermc on pterodactyl

### Paper version

Cannot get

**Comment by dkbay** [comment]
Github issues aren't really for getting help (Especially not for unrelated projects), it's for reporting stuff that's actually broken.

Maybe you can find some help here: https://discord.com/invite/pterodactyl

**Comment by NoahvdAa** [comment]
Should be resolved in 5c87711, try downloading the latest build from [papermc.io](https://papermc.io/downloads) and uploading it as your server.jar.
