### ISSUE TITLE
JavaPlugin#getPlugin doesn't work with new plugin class loader

### ISSUE THREAD

**Issue by Akiranya** [PaperSpigot/Paper#8885]
### Expected behavior

I really love the new plugin loader system as it provides a isolated classloader feature which really helps mitigate the nasty dependency setup. So, I just started to migrate all of my plugins to the new system but I found a bug:

It should be able to call `JavaPlugin.getPlugin(clazz)` if using the `paper-plugin.yml`.

### Observed/Actual behavior

```
[01:11:08] [Server thread/INFO]: [ChatChat] Enabling ChatChat
[01:11:08] [Server thread/INFO]: [ChatChat] Enabled the EssentialsHook hook provided by: ChatChat.
[01:11:08] [Server thread/INFO]: [ChatChat] Enabled the TownyHook hook provided by: ChatChat.
[01:11:08] [Server thread/INFO]: [ChatChat] Enabled the VanillaVanishHook hook provided by: ChatChat.
[01:11:08] [Server thread/ERROR]: Error occurred while enabling ChatChat (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at at.helpch.chatchat.config.mapper.ChannelMapper.deserialize(ChannelMapper.java:66) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.config.mapper.ChannelMapMapper.deserialize(ChannelMapMapper.java:39) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.config.mapper.ChannelMapMapper.deserialize(ChannelMapMapper.java:19) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.libs.org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.libs.org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.config.ConfigFactory.create(ConfigFactory.java:78) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.config.ConfigFactory.channels(ConfigFactory.java:44) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.config.ConfigManager.channels(ConfigManager.java:64) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.config.ConfigManager.reload(ConfigManager.java:40) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.ChatChatPlugin.onEnable(ChatChatPlugin.java:99) ~[ChatChat-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:575) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:486) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: class at.helpch.chatchat.ChatChatPlugin is not initialized by class org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.getPlugin(JavaPlugin.java:427) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at at.helpch.chatchat.channel.ChatChannel.<init>(ChatChannel.java:43) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.config.DefaultConfigObjects.createDefaultChannel(DefaultConfigObjects.java:24) ~[ChatChat-1.0.jar:?]
	at at.helpch.chatchat.channel.ChatChannel.<clinit>(ChatChannel.java:22) ~[ChatChat-1.0.jar:?]
	... 25 more
[01:11:08] [Server thread/INFO]: [ChatChat] Disabling ChatChat
[01:11:08] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling ChatChat (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.isCancelled()" because "this.dataSaveTask" is null
	at at.helpch.chatchat.ChatChatPlugin.onDisable(ChatChatPlugin.java:148) ~[ChatChat-1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:575) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:486) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

Install the ChatChat plugin and let it start up!

this is the source code: https://github.com/Akiranya/ChatChat/blob/mewcraft/plugin/src/main/java/at/helpch/chatchat/channel/ChatChannel.java#L43

[ChatChat-1.0.zip](https://github.com/PaperMC/Paper/files/10796162/ChatChat-1.0.zip)

### Plugin and Datapack List

> pl
[01:11:20 INFO]: Paper Plugins: (3):
[01:11:20 INFO]:  - ChatChat, MewCore, MMOExt
[01:11:20 INFO]: Bukkit Plugins: (33):
[01:11:20 INFO]:  - BetterGUI, Brewery, ConnectorPlugin, CosmeticsCore, Debuggery, Essentials, EssentialsSpawn, ExcellentEnchants, GemsEconomy, helper
[01:11:20 INFO]:  HuskSync, InteractiveBooks, ItemsAdder, LoneLibs, LuckPerms, MewFishing, MewUtils, MMOBuffs, MMOItems, ModelEngine
[01:11:20 INFO]:  MythicLib, MythicMobs, NexEngine, PhantomWorlds, PlaceholderAPI, ProtocolLib, ProxyChatBridge, RPGInventory, Towny, TownyLink
[01:11:20 INFO]:  Vault, WorldEdit, WorldGuard
> datapack list
[01:39:28 INFO]: There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]
[01:39:28 INFO]: There are no more data packs available

### Paper version

Current: git-Purpur-1918 (MC: 1.19.3)*

**Comment by Akiranya** [comment]
Confirmed in the case of ChatChat plugin, it's been fixed by #8888

Thank you Machine-Maker!
