### ISSUE TITLE
stacktrace on reload plugin with PlugManX's source code 

### ISSUE THREAD

**Issue by Bruce0203** [PaperSpigot/Paper#8903]
### Stack trace

```
[22:08:08 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'inggame.jar' in folder 'plugins'
java.lang.IllegalStateException: Provider SpigotPluginProvider{path=plugins/inggame.jar, description=org.bukkit.plugin.PluginDescriptionFile@3b57b363, jarFile=java.util.jar.JarFile@1de337e, status=null, dependencyContext=null} attempted to add duplicate plugin identifier inggame v-de28ceac THIS WILL CREATE BUGS!!!
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage$1.applyContext(ServerPluginProviderStorage.java:28) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:125) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:63) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:121) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[Fusion-API-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.github.inggameteam.inggame.plugman.util.PluginUtil.load(PluginUtil.java:383) ~[inggame.jar:?]
        at io.github.inggameteam.inggame.plugman.util.PluginUtil.load(PluginUtil.java:357) ~[inggame.jar:?]
        at io.github.inggameteam.inggame.plugman.util.PluginUtil.reload(PluginUtil.java:481) ~[inggame.jar:?]
        at io.github.inggameteam.inggame.updateman.UpdateHelper$deploy$1$1.invoke(UpdateHelper.kt:49) ~[inggame.jar:?]
        at io.github.inggameteam.inggame.updateman.UpdateHelper$deploy$1$1.invoke(UpdateHelper.kt:64) ~[inggame.jar:?]
        at io.github.inggameteam.inggame.utils.ITaskKt.runNow$lambda$1(ITask.kt:53) ~[inggame.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:497) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[fusion-1.19.3.jar:git-Fusion-"474eaef"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:08:08 WARN]: org.bukkit.plugin.InvalidPluginException: Plugin didn't load any plugin providers?
[22:08:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.lambda$loadPlugin$1(PaperPluginInstanceManager.java:127)
[22:08:08 WARN]:        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[22:08:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:127)
[22:08:08 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82)
[22:08:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406)
[22:08:08 WARN]:        at inggame.jar//io.github.inggameteam.inggame.plugman.util.PluginUtil.load(PluginUtil.java:383)
[22:08:08 WARN]:        at inggame.jar//io.github.inggameteam.inggame.plugman.util.PluginUtil.load(PluginUtil.java:357)
[22:08:08 WARN]:        at inggame.jar//io.github.inggameteam.inggame.plugman.util.PluginUtil.reload(PluginUtil.java:481)
[22:08:08 WARN]:        at inggame.jar//io.github.inggameteam.inggame.updateman.UpdateHelper$deploy$1$1.invoke(UpdateHelper.kt:49)
[22:08:08 WARN]:        at inggame.jar//io.github.inggameteam.inggame.updateman.UpdateHelper$deploy$1$1.invoke(UpdateHelper.kt:64)
[22:08:08 WARN]:        at inggame.jar//io.github.inggameteam.inggame.utils.ITaskKt.runNow$lambda$1(ITask.kt:53)
[22:08:08 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[22:08:08 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:08:08 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1500)
[22:08:08 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:497)
[22:08:08 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1424)
[22:08:08 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1194)
[22:08:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[22:08:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Plugin and Datapack List

<img width="684" alt="image" src="https://user-images.githubusercontent.com/56539682/220916304-a20e9c24-64e2-42ab-9943-4a1b96762e37.png">

### Paper version

<img width="464" alt="image" src="https://user-images.githubusercontent.com/56539682/220916499-6ae337e8-9dc2-427e-9ec4-267910b188ea.png">

**Comment by Owen1212055** [comment]
Wait, you aren’t even using Paper. Please test to make sure you are able to reproduce this on our software.

**Comment by MrPowerGamerBR** [comment]
Can confirm that this bug also happens in Paper 1.19.4, with PlugManX and with PlugWoman.

This is probably due to the changes made in https://github.com/PaperMC/Paper/blob/master/patches/server/0013-Paper-Plugins.patch
