### ISSUE TITLE
Server Crash when plugin does any sql request

### ISSUE THREAD

**Issue by Ariouz** [PaperSpigot/Paper#8933]
### Stack trace

[17:09:24 INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
>....2023-03-03 17:10:33,374 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.slf4j.Log4jLogger caught java.lang.ThreadDeath logging ReusableSimpleMessage: Main thread terminated by WatchDog due to hard crash java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:960)
        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:803)
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:932)
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:234)
2023-03-03 17:10:33,377 Server thread ERROR An exception occurred processing Appender Async org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.ThreadDeath
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2017)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1983)
        at org.apache.logging.slf4j.Log4jLogger.error(Log4jLogger.java:313)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1273)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:960)
        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:803)
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:932)
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:234)
2023-03-03 17:10:33,383 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:960)
        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:803)
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:932)
        at org.spigotmc.WatchdogThread.run(WatchdogThread.java:234)
[17:10:33 INFO]: Stopping server

### Plugin and Datapack List

Luckperms, AngelSkyApi (which does the sql request)

### Actions to reproduce (if known)

Start server
Log in to make request execute

### Paper version

This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
You are running the latest version

### Other

Hey, i had a vps with lxc and everything was working nice. But for performance issues, i went on kvm.
However, the server crash when any sql request is made (event a simple SELECT in a 2 entries table).

**Comment by Ariouz** [comment]
Full log: https://paste.gg/p/anonymous/a46294d57f6b46b8b64a156302bdbde1

**Comment by clrxbl** [comment]
You should absolutely not do SQL I/O on the server thread.

**Comment by Ariouz** [comment]
I tried with async task but it keep freezing, it didn't do that before i don't understand why

**Comment by electronicboy** [comment]
Because your connection to the MySQL server is failing, and so it's blocking the thread until the socket times out
