### ISSUE TITLE
[SpigotLibraryLoader] failing cause it can't access repo.maven.apache.org:443

### ISSUE THREAD

**Issue by ProductiveAsparagus56** [PaperSpigot/Paper#9055]
### Expected behavior

repo.maven.apache.org:443 being accessible.

### Observed/Actual behavior

```java
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Error resolving libraries
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.19.4.jar:git-Paper-473]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-473]
	at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:150) ~[paper-1.19.4.jar:git-Paper-473]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.4.jar:git-Paper-473]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-473]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-473]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-473]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.19.4.jar:git-Paper-473]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-473]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.RuntimeException: Error resolving libraries
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:103) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-473]
	... 9 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at mysql:mysql-connector-java:jar:8.0.20
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-473]
	... 9 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at mysql:mysql-connector-java:jar:8.0.20
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:288) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-473]
	... 9 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for mysql:mysql-connector-java:jar:8.0.20
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:255) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-473]
	... 9 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact mysql:mysql-connector-java:pom:8.0.20 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.0.215, repo.maven.apache.org/151.101.64.215, repo.maven.apache.org/151.101.128.215, repo.maven.apache.org/151.101.192.215] failed: Read timed out
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:425) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-473]
	... 9 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact mysql:mysql-connector-java:pom:8.0.20 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.0.215, repo.maven.apache.org/151.101.64.215, repo.maven.apache.org/151.101.128.215, repo.maven.apache.org/151.101.192.215] failed: Read timed out
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73) ~[maven-resolver-util-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-473]
	... 9 more
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.0.215, repo.maven.apache.org/151.101.64.215, repo.maven.apache.org/151.101.128.215, repo.maven.apache.org/151.101.192.215] failed: Read timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.13.jar:4.5.13]
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:316) ~[maven-resolver-transport-http-1.7.3.jar:1.7.3]
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:272) ~[maven-resolver-transport-http-1.7.3.jar:1.7.3]
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:73) ~[maven-resolver-spi-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73) ~[maven-resolver-util-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-473]
	... 9 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.nio.ch.NioSocketImpl.timedRead(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(Unknown Source) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72) ~[httpclient-4.5.13.jar:4.5.13]
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:316) ~[maven-resolver-transport-http-1.7.3.jar:1.7.3]
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:272) ~[maven-resolver-transport-http-1.7.3.jar:1.7.3]
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:73) ~[maven-resolver-spi-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73) ~[maven-resolver-util-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262) ~[maven-resolver-connector-basic-1.7.3.jar:1.7.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:514) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:240) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171) ~[maven-resolver-provider-3.8.5.jar:3.8.5]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:538) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:523) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:410) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:362) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:349) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309) ~[maven-resolver-impl-1.6.3.jar:1.6.3]
	at org.bukkit.plugin.java.LibraryLoader.createLoader(LibraryLoader.java:100) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-473]
	... 9 more
```

### Steps/models to reproduce

Try and load any plugin that uses the SpigotLibraryLoader and contacts the maven repository.

### Plugin and Datapack List

Premiumvanish

### Paper version

This server is running Paper version git-Paper-473 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: fbf74ba)

### Other

I am running this in a docker container `https://github.com/itzg/docker-minecraft-server`.

I have tried accessing `https://www.google.com/` with curl inside the container to confirm it wasn't port 443 being blocked, but when i try `https://repo.maven.apache.org` it doesn't work, it does work when i try `repo,maven.apache.org`. on the host `https://repo.maven.apache.org` does work.

**Comment by MiniDigger** [comment]
there is nothing we can do to help you, you need to find out what inside of the container or docker is blocking access to that URL. can also try joining #paper-help on discord for further support
