### ISSUE TITLE
The git-Paper-473 (MC: 1.19.4) server does not work with symbolic link plugins directory

### ISSUE THREAD

**Issue by wangzhizhou** [PaperSpigot/Paper#9057]
### Expected behavior

papermc server can load the *.jar plugins from the symbolic link directory named plugins

### Observed/Actual behavior

papermc server cant load any *.jar plugins from the symbolic link directory named plugins
![image](https://user-images.githubusercontent.com/8174538/227995066-08a96e51-731d-4800-99a7-1ce4831e6b0d.png)

![image](https://user-images.githubusercontent.com/8174538/227994991-e02b5087-ecce-468f-a48a-35306df7fcdf.png)

### Steps/models to reproduce

https://user-images.githubusercontent.com/8174538/227998263-0528bb4f-73f7-4eb8-af9b-c572ab738b20.mp4

### Plugin and Datapack List

> plugins
[23:53:43 INFO]: Server Plugins (0):

### Paper version

> version 
[23:54:00 INFO]: Checking version, please wait...
[23:54:27 WARN]: java.net.ConnectException: Connection timed out
[23:54:27 WARN]: 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[23:54:27 WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
[23:54:27 WARN]: 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
[23:54:27 WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[23:54:27 WARN]: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[23:54:27 WARN]: 	at java.base/java.net.Socket.connect(Socket.java:633)
[23:54:27 WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[23:54:27 WARN]: 	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[23:54:27 WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[23:54:27 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[23:54:27 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[23:54:27 WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[23:54:27 WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[23:54:27 WARN]: 	at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:68)
[23:54:27 WARN]: 	at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:474)
[23:54:27 WARN]: 	at com.google.common.io.CharSource.openBufferedStream(CharSource.java:126)
[23:54:27 WARN]: 	at com.destroystokyo.paper.PaperVersionFetcher.fetchDistanceFromSiteApi(PaperVersionFetcher.java:90)
[23:54:27 WARN]: 	at com.destroystokyo.paper.PaperVersionFetcher.getUpdateStatusMessage(PaperVersionFetcher.java:61)
[23:54:27 WARN]: 	at com.destroystokyo.paper.PaperVersionFetcher.getVersionMessage(PaperVersionFetcher.java:35)
[23:54:27 WARN]: 	at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:204)
[23:54:27 WARN]: 	at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:188)
[23:54:27 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:54:27 INFO]: This server is running Paper version git-Paper-473 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: fbf74ba)
Error obtaining version information

**Comment by MiniDigger** [comment]
can you explain what you use to start the server? or just try via java -jar paper.jar?

**Comment by wangzhizhou** [comment]
orzmc is a cli tool which help me launch paper server, just like java -jar command

**Comment by wangzhizhou** [comment]
> 

use the java -jar paper-server.jar can also get the same result.

**Comment by wangzhizhou** [comment]
> I came across the same issue, where sym links stopped working after build 405 and up. Although I simply solved it by using the `--plugins <directory>` parameter instead.

This solution work for me, before this issue be fixed, I will use your solution. Thx

**Comment by lx78WyY0J5** [comment]
I confirm sym link work, this issue is on your side
Either plugins folder dont exist or is wrongly typed
Either the jar file isn't existing

Try using this

[LN-s](https://github.com/GHub-fr/server/blob/main/Serveurs/DataFolder/ln-s.sh)
[Start file with folder path](https://github.com/GHub-fr/server/blob/main/Serveurs/DataFolder/start.sh)
[The start file](https://github.com/GHub-fr/server/blob/main/Serveurs/Creatif/start.sh)
All using screen to be able to run multiple servers cmd shell

**Comment by Owen1212055** [comment]
Resolved in https://github.com/PaperMC/Paper/pull/9129
