### ISSUE TITLE
PlayerA gets kicked for PlayerB's invalid profile key

### ISSUE THREAD

**Issue by RunedFire** [PaperSpigot/Paper#9138]
### Expected behavior

PlayerA connects to the server, while PlayerB has been online for some time and during PlayerB's time on the server PlayerB's Profile Key has become invalid. PlayerA's profile key is valid and connection is established.

### Observed/Actual behavior

PlayerA connects to the server, while PlayerB is online and during PlayerB's time on the server PlayerB's Profile Key has become invalid. PlayerA's profile key is valid and connection is established but then is rejected because of PlayerB's invalid Profile Key.

Only when PlayerB is disconnected, can PlayerA successfully connect and go about their day on the server.

### Steps/models to reproduce

1. Leave one account (A) logged into the server and wait until the Profile Key has become invalid.
2. Once A's key has become invalid. Connect with a second account (B)
3. B will connect and subsequently get disconnected.
4. Check B's log for the disconnect. Log will state "Failed to validate profile key for player: 'A.username"

To affirm that A's invalid profile key is keeping B offline:
5. Disconnect A from the server
6. Attempt to connect to the server on B
7. B's connection is established and successful login.

### Plugin and Datapack List

None

### Paper version

[Sat 02:06:37 INFO] This server is running Paper version git-Paper-431 (MC:1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: e574412) 

### Other

This is an example of the output when this bug occurs. 

`[02:41:27] [Render thread/INFO]: Connecting to play.evolvedsurvival.org, 25565
[02:41:28] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[02:41:28] [Render thread/WARN]: Unknown custom packed identifier: minecraft:register
[02:41:29] [Render thread/WARN]: Ignoring player info update for unknown player 09f833dd-7158-4745-9663-9e5a1c381691
[02:41:29] [Render thread/WARN]: Ignoring player info update for unknown player 1291180b-232f-447d-994a-db5696b106e5
[02:41:29] [Render thread/WARN]: Ignoring player info update for unknown player b29ded14-83ae-407a-8ffa-6111f651aa21
[02:41:29] [Render thread/WARN]: Ignoring player info update for unknown player ec8b032c-b57f-4ae3-934e-bc2a3a7ddf64
[02:41:29] [Render thread/WARN]: Ignoring player info update for unknown player 083dee94-e3ed-4ba1-8553-2124634e9f2b
[02:41:29] [Render thread/WARN]: Ignoring player info update for unknown player 0faaf4da-2ffd-4378-9299-6b193221ba9c
[02:41:29] [Render thread/WARN]: Ignoring player info update for unknown player c125641d-61a3-4065-bc54-0ab5de6d8ff8
[02:41:29] [Render thread/ERROR]: Failed to validate profile key for player: 'ShanesWorld77'
bws$b: Expired profile public key. Check that your system time is synchronized, and try restarting your game.
	at bws.a(SourceFile:31) ~[minecraft-1.19.3-client.jar:?]
	at ti$a.a(SourceFile:35) ~[minecraft-1.19.3-client.jar:?]
	at eza.a(SourceFile:1722) ~[minecraft-1.19.3-client.jar:?]
	at eza.a(SourceFile:1703) ~[minecraft-1.19.3-client.jar:?]
	at eza.a(SourceFile:1696) ~[minecraft-1.19.3-client.jar:?]
	at wn.a(SourceFile:63) ~[minecraft-1.19.3-client.jar:?]
	at wn.a(SourceFile:20) ~[minecraft-1.19.3-client.jar:?]
	at uj.a(SourceFile:22) ~[minecraft-1.19.3-client.jar:?]
	at bbc.d(SourceFile:156) ~[minecraft-1.19.3-client.jar:?]
	at bbg.d(SourceFile:23) ~[minecraft-1.19.3-client.jar:?]
	at bbc.x(SourceFile:130) ~[minecraft-1.19.3-client.jar:?]
	at bbc.bq(SourceFile:115) ~[minecraft-1.19.3-client.jar:?]
	at ejf.f(SourceFile:1144) ~[minecraft-1.19.3-client.jar:?]
	at ejf.e(SourceFile:781) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:244) ~[minecraft-1.19.3-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[minecraft-1.19.3-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]`

**Comment by Doc94** [comment]
You try in last version?

**Comment by RunedFire** [comment]
Will be trying in 1.19.4, just takes time waiting on the profile key to become invalid. I'll update with my findings.

**Comment by RunedFire** [comment]
I have attempted to recreate the issue on 1.19.4. I have been unsuccessful. My alt's profile key expired and my main account could login regardless.
