### ISSUE TITLE
PlayerAdvancementDoneEvent throws IllegalArgumentException

### ISSUE THREAD

**Issue by Nolezor** [PaperSpigot/Paper#9148]
### Stack trace

```
[14:59:09 ERROR]: Could not pass event PlayerAdvancementDoneEvent to ChatUtilitiesPlus v1.0.0-SNAPSHOT
java.lang.IllegalArgumentException: Component adventure$content and String (json) content cannot both be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:22) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.network.protocol.game.ClientboundSystemChatPacket.<init>(ClientboundSystemChatPacket.java:26) ~[paper-1.19.4.jar:git-Paper-514]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:2838) ~[paper-1.19.4.jar:git-Paper-514]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:242) ~[adventure-api-4.13.1.jar:?]
        at net.kyori.adventure.audience.Audience.sendMessage(Audience.java:206) ~[adventure-api-4.13.1.jar:?]
        at me.nolezor.chatutilitiespluspaper.events.AdvancementEvent.sendMessage(AdvancementEvent.java:46) ~[ChatUtilitiesPlus-Paper.jar:?]
        at me.nolezor.chatutilitiespluspaper.events.AdvancementEvent.playerGetAdvancement(AdvancementEvent.java:26) ~[ChatUtilitiesPlus-Paper.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor34.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-514]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-514]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-514]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.PlayerAdvancements.award(PlayerAdvancements.java:246) ~[?:?]
        at net.minecraft.advancements.CriterionTrigger$Listener.run(CriterionTrigger.java:35) ~[?:?]
        at net.minecraft.advancements.critereon.SimpleCriterionTrigger.trigger(SimpleCriterionTrigger.java:73) ~[?:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.lambda$trigger$0(InventoryChangeTrigger.java:57) ~[?:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(InventoryChangeTrigger.java:53) ~[?:?]
        at net.minecraft.server.level.ServerPlayer$2.slotChanged(ServerPlayer.java:345) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:306) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:243) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.take(ServerPlayer.java:1332) ~[?:?]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:498) ~[?:?]
        at net.minecraft.world.entity.player.Player.touch(Player.java:630) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:596) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2975) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:275) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:715) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:358) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:592) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-514]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-514]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Plugin and Datapack List

![Plugins](https://user-images.githubusercontent.com/88346895/232791324-59ca3bf2-224f-4ad0-b643-ff1daf6fdac9.PNG)

### Actions to reproduce (if known)

@EventHandler
    public void playerGetAdvancement(PlayerAdvancementDoneEvent e) {
        e.message(null);
    }

### Paper version

This server is running Paper version git-Paper-514 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: dd216c1)
You are running the latest version

### Other

**Comment by electronicboy** [comment]
The code you showed isn't what was running inside of the JVM, 
```
        at me.nolezor.chatutilitiespluspaper.events.AdvancementEvent.sendMessage(AdvancementEvent.java:46) ~[ChatUtilitiesPlus-Paper.jar:?]
        at me.nolezor.chatutilitiespluspaper.events.AdvancementEvent.playerGetAdvancement(AdvancementEvent.java:26) ~[ChatUtilitiesPlus-Paper.jar:?]
        
```

You called Player#sendMesage with null, maybe theres an argument for better behavior here, i.e. throwing a more clear error, but, this isn't a paper issue as such

**Comment by Nolezor** [comment]
Oh yeah, now that I see it better (thanks btw) I think I got what the problem is, I'll try with a clean code to see if the problem persists and send an update.
