### ISSUE TITLE
 I keep getting these kinds of errors from players.

### ISSUE THREAD

**Issue by ByDestiniy** [PaperSpigot/Paper#9159]
### Expected behavior

[00:02:39] [Server thread/WARN]: Exception loading entity: 
net.minecraft.server.v1_16_R3.ReportedException: Loading entity NBT
	at net.minecraft.server.v1_16_R3.Entity.load(Entity.java:2193) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityTypes.lambda$a$2(EntityTypes.java:540) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.SystemUtils.a(SystemUtils.java:303) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityTypes.a(EntityTypes.java:537) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityTypes.b(EntityTypes.java:585) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityTypes.a(EntityTypes.java:566) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MobSpawnerAbstract.c(MobSpawnerAbstract.java:152) ~[patched_1.16.5.jar:git-Purpur-1171]
	at com.bgsoftware.superiorskyblock.nms.v1_16_R3.spawners.MobSpawnerAbstractNotifier.c(MobSpawnerAbstractNotifier.java:43) ~[?:?]
	at net.minecraft.server.v1_16_R3.TileEntityMobSpawner.tick(SourceFile:62) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.World.tickBlockEntities(World.java:990) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1183) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1567) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:505) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.EntityItem.loadData(EntityItem.java:381) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.Entity.load(Entity.java:2095) ~[patched_1.16.5.jar:git-Purpur-1171]
	... 16 more
[00:02:43] [Async Chat Thread - #298/INFO]: ? 0 ? ?????? Ersin4: bilmem
[00:02:52] [Server thread/INFO]: [Spartan] CloxTRAfk is absolutely using XRay x1 | 82ms | 19.8 TPS | silent: false, CloxTRAfk may be unfairly gathering golds. Surpassed average by 4931.83 points

### Observed/Actual behavior

I have no idea

### Steps/models to reproduce

no

### Plugin and Datapack List

![image](https://user-images.githubusercontent.com/131416603/233515902-b55d4eef-c669-4760-961a-27859e1f9559.png)

### Paper version

1.16.5

### Other

I keep getting these kinds of errors from players.

**Comment by ByDestiniy** [comment]
What is the solution to this problem

**Comment by Owen1212055** [comment]
1.16.5 is no longer supported.
