### ISSUE TITLE
Error report for Paper - java.lang.IllegalStateException: Asynchronous effect add!

### ISSUE THREAD

**Issue by 2279881513** [PaperSpigot/Paper#9171]
### Stack trace

java.lang.Throwable: null
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1127) ~[?:?]
at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1119) ~[?:?]
at net.minecraft.world.entity.monster.Spider.finalizeSpawn(Spider.java:180) ~[?:?]
at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$placeEntities$5(StructureTemplate.java:475) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.placeEntities(StructureTemplate.java:469) ~[?:?]
at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.placeInWorld(StructureTemplate.java:399) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.place(SinglePoolElement.java:115) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.place(PoolElementStructurePiece.java:90) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.postProcess(PoolElementStructurePiece.java:86) ~[?:?]
at net.minecraft.world.level.levelgen.structure.StructureStart.placeInChunk(StructureStart.java:89) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkGenerator.lambda$addVanillaDecorations$13(ChunkGenerator.java:572) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
at net.minecraft.world.level.chunk.ChunkGenerator.addVanillaDecorations(ChunkGenerator.java:571) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:661) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:656) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:172) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:304) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:83) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
[18:05:30] [Tuinity Chunk System Worker #0/ERROR]: [ChunkTaskScheduler] Chunk system error at chunk (352,1658), holder: NewChunkHolder{world=xm, chunkX=352, chunkZ=1658, entityChunkFromDisk=false, lastChunkCompletion={chunk_class=net.minecraft.world.level.chunk.ProtoChunk,status=minecraft:liquid_carvers}, currentGenStatus=minecraft:liquid_carvers, requestedGenStatus=minecraft:features, generationTask=ChunkProgressionTask{class: io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask, for world: xm, chunk: (352,1658), hashcode: 339032314, priority: COMPLETING, status: minecraft:features, scheduled: true}, generationTaskStatus=minecraft:features, priority=NORMAL, priorityLocked=false, neighbourRequestedPriority=NORMAL, effective_priority=NORMAL, oldTicketLevel=34, currentTicketLevel=34, totalNeighboursUsingThisChunk=9, fullNeighbourChunksLoadedBitset=4, chunkStatusRaw=0, currentChunkStatus=INACCESSIBLE, pendingChunkStatus=INACCESSIBLE, is_unload_safe=ticket_level, killed=false}, exception:
java.lang.Throwable: net.minecraft.ReportedException: Feature placement
at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.unrecoverableChunkSystemFailure(ChunkTaskScheduler.java:216) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.lambda$setGenerationTask$4(NewChunkHolder.java:1672) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at io.papermc.paper.chunk.system.scheduling.ChunkProgressionTask.complete0(ChunkProgressionTask.java:95) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at io.papermc.paper.chunk.system.scheduling.ChunkProgressionTask.complete(ChunkProgressionTask.java:75) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:102) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
Caused by: net.minecraft.ReportedException: Feature placement
at net.minecraft.world.level.chunk.ChunkGenerator.addVanillaDecorations(ChunkGenerator.java:649) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:661) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:656) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:172) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:304) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:83) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
... 4 more
Caused by: java.lang.IllegalStateException: Asynchronous effect add!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1127) ~[?:?]
at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1119) ~[?:?]
at net.minecraft.world.entity.monster.Spider.finalizeSpawn(Spider.java:180) ~[?:?]
at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$placeEntities$5(StructureTemplate.java:475) ~[?:?]
at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.placeEntities(StructureTemplate.java:469) ~[?:?]
at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.placeInWorld(StructureTemplate.java:399) ~[?:?]
at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.place(SinglePoolElement.java:115) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.place(PoolElementStructurePiece.java:90) ~[?:?]
at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.postProcess(PoolElementStructurePiece.java:86) ~[?:?]
at net.minecraft.world.level.levelgen.structure.StructureStart.placeInChunk(StructureStart.java:89) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkGenerator.lambda$addVanillaDecorations$13(ChunkGenerator.java:572) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar:?]
at net.minecraft.world.level.chunk.ChunkGenerator.addVanillaDecorations(ChunkGenerator.java:571) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:661) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(ChunkGenerator.java:656) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$12(ChunkStatus.java:172) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:304) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:83) ~[paper-1.19.2.jar:git-Paper-"476ef25"]
... 4 more

### Plugin and Datapack List

Plugins (32): AntiCropTrample*, Cameras, ChanLang, ChatEx*, CommandsOnDeath, CoreProtect, CustomCraftings, DieMsgQG, Ersatz*, ExcellentEnchants, GSit, InventoryRollbackPlus, JoinCommand, LuckPerms, Multiverse-Core, NexEngine, NoHelp*, OpenInv, PlaceholderAPI, ProtocolLib, ProtocolStringReplacer, RocketPlaceholders, SbPlaceholder*, Skript, SpawnLimit, SuperVanish, TAB, Tamablefoxes, Themis, ViaBackwards, ViaVersion, Xm
> datapack list
5 data packets have been enabled.：[vanilla（built-in）], [file/bukkit（world）], [file/rainbeau-s-ocean-villages-07172022.zip（world）], [file/rainbeau-s-ships-on-seas-07172022.zip（world）], [file/terralith-v2-3-2a.zip（world）]

### Actions to reproduce (if known)

I encountered an error while running my Minecraft server on Paper, and I believe it is related to the asynchronous effect add. The error message is "java.lang.IllegalStateException: Asynchronous effect add!" and it occurred in the LivingEntity.addEffect method. I would like to report this issue to the Paper team.

### Paper version

> version
[21:03:01 INFO]: This server is running Paper version git-Paper-"476ef25" (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25 on HEAD)
You are 321 version(s) behind
Previous version: git-Paper-135 (MC: 1.19.2)

**Comment by Warriorrrr** [comment]
Update to the latest version of paper, as this was already fixed by #8942.
