### ISSUE TITLE
Wrong weather/time after teleport in PlayerJoinEvent

### ISSUE THREAD

**Issue by Foorcee** [PaperSpigot/Paper#9219]
### Expected behavior

After teleporting the player to a new world, the player should be shown the weather from the new world.

### Observed/Actual behavior

When a player is teleported to another world in the PlayerJoinEvent, the weather from the old world is displayed to the player in the new world. The rain will only be shown to the one player.

### Steps/models to reproduce

Steps to reproduce:
1. Activate rain in the default world.
2. Create world "sun" with clear weather
3. Teleport player in PlayerJoinEvent from default world to world "sun
4. Player gets rain in world "sun

Expectations:
After 3: After teleport, clear weather should be displayed to the player.

### Plugin and Datapack List

WeatherTest:

```
public final class WeatherTest extends JavaPlugin implements Listener {

    private World rainWorld;
    private World sunWorld;

    @Override
    public void onEnable() {
        // Plugin startup logic
        rainWorld = Bukkit.getWorlds().get(0);
        rainWorld.setStorm(true);
        rainWorld.setThundering(true);
        rainWorld.setWeatherDuration(Integer.MAX_VALUE);

        sunWorld = Bukkit.createWorld(WorldCreator.name("sunWorld"));
        sunWorld.setGameRule(GameRule.DO_WEATHER_CYCLE, false);
        sunWorld.setThundering(false);
        sunWorld.setStorm(false);

        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onJoin(PlayerJoinEvent event) {
        Player player = event.getPlayer();
        player.teleport(sunWorld.getSpawnLocation());
    }

    @EventHandler
    public void onSneak(PlayerToggleSneakEvent event) {
        Player player = event.getPlayer();
        World world = player.getWorld();
        player.sendMessage("world: " + world.getName() + " storm: " + world.hasStorm() + " thundering: " + world.isThundering());
        player.sendMessage("player weather: " + player.getPlayerWeather());
    }
}
```

### Paper version

ver
[13:23:48 INFO]: Checking version, please wait...
[13:23:48 INFO]: This server is running Paper version git-Paper-530 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 9daa019)
You are 8 version(s) behind

### Other

Error in the console:

```
[12:39:11 INFO]: Foorcee joined the game
[12:39:12 INFO]: Foorcee[<ip address withheld>] logged in with entity id 148 at ([sunWorld]-32.0, 71.0, 32.0)
[12:39:13 ERROR]: Caught previously unhandled exception :
[12:39:13 ERROR]: Paper Async Command Builder Thread Pool - 0
java.util.ConcurrentModificationException: null
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]
        at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:475) ~[paper.jar:git-Paper-530]
        at net.minecraft.commands.CommandDispatcher.sendAsync(CommandDispatcher.java:441) ~[paper.jar:git-Paper-530]
        at net.minecraft.commands.CommandDispatcher.lambda$sendCommands$5(CommandDispatcher.java:414) ~[paper.jar:git-Paper-530]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by emilyy-dev** [comment]
to change the spawn location when a player joins you have to set it in (PlayerSpawnLocationEvent)[https://jd.papermc.io/paper/1.19/org/spigotmc/event/player/PlayerSpawnLocationEvent.html], that's the supported mechanism
