### ISSUE TITLE
Failed to save default config files

### ISSUE THREAD

**Issue by finsterdev** [PaperSpigot/Paper#9250]
### Expected behavior

I would expect to see the classic startup message, from my currently only plugin DiscordSRV

### Observed/Actual behavior

After I saw that the plugin hadn't created a foler I looked at the console's output, here it is:
[15:37:50 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[15:37:50 INFO]: Default game type: SURVIVAL
[15:37:50 INFO]: Generating keypair
[15:37:50 INFO]: Starting Minecraft server on *:25566
[15:37:50 INFO]: Using epoll channel type
[15:37:50 INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.
[15:37:50 INFO]: Paper: Using OpenSSL (Linux aarch64) cipher from Velocity.
[15:37:51 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'DiscordSRV-Build-1.26.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.RuntimeException: Failed to save default config files
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.19.4.jar:git-Paper-545]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-545]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.19.4.jar:git-Paper-545]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.4.jar:git-Paper-545]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:426) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-545]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to save default config files
        at github.scarsz.discordsrv.DiscordSRV.<init>(DiscordSRV.java:426) ~[DiscordSRV-Build-1.26.2.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-545]
        ... 9 more
Caused by: java.io.IOException: Failed to create directory /opt/minecraft/paper/plugins/DiscordSRV
        at github.scarsz.configuralize.Provider.saveDefaults(Provider.java:73) ~[DiscordSRV-Build-1.26.2.jar:?]
        at github.scarsz.configuralize.DynamicConfig.saveAllDefaults(DynamicConfig.java:90) ~[DiscordSRV-Build-1.26.2.jar:?]
        at github.scarsz.configuralize.DynamicConfig.saveAllDefaults(DynamicConfig.java:80) ~[DiscordSRV-Build-1.26.2.jar:?]
        at github.scarsz.discordsrv.DiscordSRV.<init>(DiscordSRV.java:424) ~[DiscordSRV-Build-1.26.2.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-545]
        ... 9 more

### Steps/models to reproduce

Currently unkown however I was thinking of resetting my bukkit and spigot YAML files

### Plugin and Datapack List

Plugins:
DiscordSRV

Datapaacks:
None installed.

### Paper version

Updated today, default paper 1.19.4-527

### Other

Yes I am running from what I know is the latest version of paper
I searched for 'Failed to save default config files' however no results were conclusive
Paper supports 1.19.4

**Comment by Machine-Maker** [comment]
This just looks like discordsrv can't create `/opt/minecraft/paper/plugins/DiscordSRV` for putting its own configuration file. I feel like its most likely a file permissions issue, or a discordsrv issue?

**Comment by electronicboy** [comment]
The plug-in is what threw the error, check file perms/speak to the plug-in dev, we have 0 control here

**Comment by finsterdev** [comment]
> The plug-in is what threw the error, check file perms/speak to the plug-in dev, we have 0 control here

thank you I will go to support now
