### ISSUE TITLE
NPE in isChatWarnings

### ISSUE THREAD

**Issue by SlimeDog** [PaperSpigot/Paper#9263]
### Expected behavior

Clean start-up as usual

### Observed/Actual behavior

```
[03:43:19] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0-SNAPSHOT-647
[03:43:20] [Server thread/ERROR]: [ProtocolLib] Error initializing plugin 'ProtocolLib-5.1.0-b647.jar' in folder 'plugins' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.comphenix.protocol.ProtocolConfig.isChatWarnings()" because the return value of "com.comphenix.protocol.ProtocolLibrary.getConfig()" is null
        at com.comphenix.protocol.error.DetailedErrorReporter.reportDetailed(DetailedErrorReporter.java:394) ~[ProtocolLib-5.1.0-b647.jar:?]
        at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:63) ~[ProtocolLib-5.1.0-b647.jar:?]
        at com.comphenix.protocol.error.DelegatedErrorReporter.reportDetailed(DelegatedErrorReporter.java:87) ~[ProtocolLib-5.1.0-b647.jar:?]
        at com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:186) ~[ProtocolLib-5.1.0-b647.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.4.jar:git-Paper-547]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.4.jar:git-Paper-547]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.19.4.jar:git-Paper-547]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-547]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:431) ~[paper-1.19.4.jar:git-Paper-547]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-547]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-547]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-547]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Steps/models to reproduce

- Update Paper to 1.19.4-547 from 1.19.4-546 (no other changes)
- Start server
- Read log

### Plugin and Datapack List

Many, but irrelevant to this issue

### Paper version

```
>version
[03:44:26] [Server thread/INFO]: 13 placeholder hook(s) registered!
[03:44:26] [Thread-38/INFO]: This server is running Paper version git-Paper-547 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: d8e0759)
You are running the latest version
```

**Comment by SlimeDog** [comment]
The only change to the server was Paper update.

**Comment by SlimeDog** [comment]
- Reverted to Paper to 1.19.4-546. Server started without error.
- Reinstalled Paper to 1.19.4-547. Server started without error.
