### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by MineTarkov** [PaperSpigot/Paper#9272]
### Expected behavior

I thought I would run it and it would work fine, I installed all the necessary plugins

### Observed/Actual behavior

As a result, the plugin turns off gives an error:
[22:59:08] [Server thread/ERROR]: Error occurred while enabling MistikAirDrop v1.0.0- Beta (Is it up to date?)
java.lang.NoClassDefFoundError: ru/soknight/lib/command/help/HelpMessageFactory
	at ru.mistikairdrop.commands.sub.CommandHelp.<init>(CommandHelp.java:31) ~[?:?]
	at ru.mistikairdrop.commands.SubcommandHandler.<init>(SubcommandHandler.java:32) ~[?:?]
	at ru.mistikairdrop.MistikAirDrop.registerCommands(MistikAirDrop.java:84) ~[?:?]
	at ru.mistikairdrop.MistikAirDrop.onEnable(MistikAirDrop.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-782]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-782]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-782]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-782]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-782]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-782]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: ru.soknight.lib.command.help.HelpMessageFactory
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-782]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-782]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 14 more

### Steps/models to reproduce

f

### Plugin and Datapack List

f

### Paper version

 
![image](https://github.com/PaperMC/Paper/assets/133810771/983c32aa-1a7b-40bb-9763-68356e631db7)

**Comment by electronicboy** [comment]
Unsupported version of paper

That's also classses missing from the plugin, so you'd need to speak to the plugin author

**Comment by MineTarkov** [comment]
Thank You
