### ISSUE TITLE
Console error on updating entity on entityaddtoworldevent

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9329]
### Expected behavior

No error

### Observed/Actual behavior

(coordinates censored with "*")

[14:23:19] [Server thread/ERROR]: Refusing to update position for entity GlowItemFrame['Glow Item Frame'/29379, uuid='b6c0794a-87ea-4870-b5d0-a11cb72084a4', l='ServerLevel[world_the_end]', x=*, y=31.50, z=*, cpos=[-*, -*], tl=0, v=true] to position (*, 31.5,*) since it is processing a section status update
java.lang.Throwable: null
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4535) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4524) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at net.minecraft.world.entity.decoration.ItemFrame.calculateBoundingBox(ItemFrame.java:115) ~[?:?]
	at net.minecraft.world.entity.decoration.ItemFrame.recalculateBoundingBox(ItemFrame.java:101) ~[?:?]
	at net.minecraft.world.entity.decoration.ItemFrame.onItemChanged(ItemFrame.java:392) ~[?:?]
	at net.minecraft.world.entity.decoration.ItemFrame.onSyncedDataUpdated(ItemFrame.java:382) ~[?:?]
	at net.minecraft.network.syncher.SynchedEntityData.set(SynchedEntityData.java:150) ~[?:?]
	at net.minecraft.network.syncher.SynchedEntityData.set(SynchedEntityData.java:142) ~[?:?]
	at net.minecraft.world.entity.decoration.ItemFrame.setItem(ItemFrame.java:348) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftItemFrame.setItem(CraftItemFrame.java:62) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftItemFrame.setItem(CraftItemFrame.java:56) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at com.viab.stufffixer.Fixer.onEntityAdded(Fixer.java:1246) ~[stufffixer-1.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor164.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:git-Paper-"f8cfdd4"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2724) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTickingEnd(ServerLevel.java:2653) ~[?:?]
	at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:266) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:195) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:305) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1263) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1338) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1382) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1366) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1319) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:433) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:855) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:429) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1329) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1427) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-"f8cfdd4"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
	
	
	
	

### Steps/models to reproduce

@EventHandler(priority = EventPriority.HIGHEST)
public void onEntityAdded(EntityAddToWorldEvent e) {
    Entity entity = e.getEntity();
    if (e.getEntityType() == EntityType.ITEM_FRAME || e.getEntityType() == EntityType.GLOW_ITEM_FRAME) {
        ItemFrame itemFrame = (ItemFrame) entity;
        ItemStack item = itemFrame.getItem();
        if (item.getType() != Material.AIR && item.hasItemMeta()) {
            DataFixer.fixItem(new ItemStack[] {item}, getNearestPlayer(itemFrame.getLocation()));
            if (!item.equals(itemFrame.getItem())) {
                itemFrame.setItem(item); // ERROR THROWN IN THIS LINE
            }
        }
    }

### Plugin and Datapack List

my plugin

### Paper version

This server is running Paper version git-Paper-"f8cfdd4" (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: f8cfdd4)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"956062a" (MC: 1.19.4)

the 1 version behind is just an api fix that released 2 minutes ago

**Comment by Machine-Maker** [comment]
This can probably be fixed by just delaying by a single tick. But unclear if its an issue we should fix regardless of that.

**Comment by electronicboy** [comment]
This event is fired in such a perilous place for modification of stuff, Im not sure if it's really tenable to promise too much in terms of safety here

**Comment by Warriorrrr** [comment]
Not really much that can be done here given from where the event is called, running the setItem a tick later like MM said is the easiest workaround for this issue.
