### ISSUE TITLE
Can't spawn a painting via world.spawnEntity()

### ISSUE THREAD

**Issue by ghost** [PaperSpigot/Paper#9374]
### Expected behavior

Should be able to spawn a painting, like in 1.19.4

### Observed/Actual behavior

[08:42:05 WARN]: java.lang.IllegalArgumentException: Cannot spawn an entity for org.bukkit.entity.Painting
[08:42:05 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftRegionAccessor.createEntity(CraftRegionAccessor.java:994)
[08:42:05 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:543)
[08:42:05 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:539)
[08:42:05 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftRegionAccessor.spawn(CraftRegionAccessor.java:525)
[08:42:05 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftRegionAccessor.spawnEntity(CraftRegionAccessor.java:433)

### Steps/models to reproduce

Call this code  
Entity entity = location.getWorld().spawnEntity(location, EntityType.PAINTING));

### Plugin and Datapack List

Custom plugin

### Paper version

This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)
You are running the latest version
Previous version: git-Paper-"fa8fa1c" (MC: 1.19.4)

**Comment by electronicboy** [comment]
1.20 is no longer supported, test on latest 1.20.1

**Comment by lynxplay** [comment]
I cannot replicate this.
```java
@EventHandler
public void on(final PlayerDropItemEvent event) {
    event.getPlayer().getWorld().spawnEntity(event.getPlayer().getLocation(), EntityType.PAINTING);
}
```
properly summons the painting.

**Comment by electronicboy** [comment]
The painting won't spawn if there isn't space for it is my understanding

**Comment by lynxplay** [comment]
Yea but that hasn't changed in the recent versions has it ? At least I cannot find any changes to HangingEntity#survives in 1.20.
You can always force it by explicitly preventing data randomisation from the looks of it.

**Comment by Machine-Maker** [comment]
So the logic for it actually did change in the upstream update to 1.19. See [this diff](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/64c15270e76475e68b2167d4bfba162a4a827fe0#src/main/java/org/bukkit/craftbukkit/CraftRegionAccessor.java?f=884).
