### ISSUE TITLE
Crash while kicked on autofishing. Illegalstack or paper issue?

### ISSUE THREAD

**Issue by Krisud** [PaperSpigot/Paper#9378]
### Stack trace

[00:37:07] [Server thread/INFO]: [IllegalStack/Log] §abalokbalok is spam fishing! ~casts~ casts without a 2 second break! @ Location{world=CraftWorld{name=survival},x=5316.095609435755,y=63.1875,z=-3999.6169096246,pitch=59.85007,yaw=88.05893}
[00:37:07] [Server thread/INFO]: balokbalok lost connection: Auto Clicker Fishing is not allowed on this server!
[00:37:07] [Server thread/INFO]: [Playtime] [STDOUT] Player : balokbalok Task id: 7567291
[00:37:07] [Server thread/INFO]: [Playtime] [STDOUT] Stopping timer for balokbalok
[00:37:07] [Server thread/INFO]: [Playtime] [STDOUT] Removed player balokbalok from the player list.
[00:37:07] [Server thread/INFO]: [Captain☆] balokbalok has left the server.
[00:37:08] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.dD()" because "entity" is null
	at net.minecraft.server.MinecraftServer.lambda$tickChildren$14(MinecraftServer.java:1485) ~[paper-1.20.1.jar:git-Paper-43]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$tickChildren$15(MinecraftServer.java:1484) ~[paper-1.20.1.jar:git-Paper-43]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1484) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-43]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-43]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:37:08] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2023-06-20_00.37.08-server.txt
[00:37:08] [Server thread/INFO]: Stopping server

### Plugin and Datapack List

AdvancedPortals, AuctionHouse, AutoPickup, BossShopPro, Chunky, Citizens, ClaimFly, CMILib, CommandItems, CoreProtect, DecentHolograms, eGlow, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, FastAsyncWorldEdit, floodgate, FreedomChat, GriefPrevention, GrimAC, GSit, IllegalStack, InteractiveChat, Jobs, LuckPerms, MyCommand, NerfPhantoms, NexEngine, PlaceholderAPI, PlayerParticles, PlayerWarps, Playtime, ProtocolLib, ResourceWorld, SilkSpawners, SimpleClans, SimpleGeyserVL, SkinsRestorer, TAB, Themis, Vault, ViaBackwards, ViaVersion, Votifier, WitherSound, WooMinecraft-OfflineOverride, WorldGuard, WorldGuardExtraFlags

Tested and all you need is illegalstack. Contacted the dev about it but no response yet. Is this a paper issue?

### Actions to reproduce (if known)

Use fishing rod, holding right-click at any water source to get kicked and server crashes right away.

### Paper version

[08:48:08 INFO]: This server is running Paper version git-Paper-43 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3756f5b)
You are running the latest version
Previous version: git-Paper-29 (MC: 1.20.1)

### Other

Server crash report: https://paste.gg/p/anonymous/4ee3f219e7b44cfba50a2d0e6c31037a
```[tasklist]
### Tasks
```

**Comment by EarthCow** [comment]
This is a problem with IllegalStack. Fishing works fine when it is not running.

**Comment by Warriorrrr** [comment]
The issue here seems to be caused by using Entity#remove from within a task scheduled on that entity, was able to reproduce the crash using the following snippet:
```java
entity.getScheduler().runDelayed(plugin, task -> entity.remove(), null, 60L)
```

**Comment by Warriorrrr** [comment]
can confirm that it no longer crashes with the above code after 990be1691b8b89295de56ed7ebda5d77aa43aac2

**Comment by Krisud** [comment]
No longer crashing. 
Illegalstack latest version did address this issue.
"Fixed a bug that would cause servers to crash when players used a fishingpole"
