### ISSUE TITLE
MariaDB 11 Breaking Changes for Many Plugins

### ISSUE THREAD

**Issue by DarkArc** [PaperSpigot/Paper#9381]
### Expected behavior

Many plugins currently piggyback on the MySQL connector bundled with Paper. This has historically worked "fine" and allowed plugins to interact with MariaDB databases.

### Observed/Actual behavior

As of Mariadb 11 that connector fails to connect. Here's an example from Logblock:

```
[17:55:51 INFO]: [de.diddiz.lib.com.zaxxer.hikari.HikariDataSource] LogBlock-Connection-Pool - Starting...
[17:55:51 ERROR]: [de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool] LogBlock-Connection-Pool - Exception during pool initialization.
java.sql.SQLException: Unknown system variable 'transaction_isolation'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-j-8.0.32.jar:8.0.32]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.32.jar:8.0.32]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824) ~[mysql-connector-j-8.0.32.jar:8.0.32]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444) ~[mysql-connector-j-8.0.32.jar:8.0.32]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[mysql-connector-j-8.0.32.jar:8.0.32]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-j-8.0.32.jar:8.0.32]
        at de.diddiz.lib.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[LogBlock.jar:?]
        at de.diddiz.lib.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.util.MySQLConnectionPool.getConnection(MySQLConnectionPool.java:44) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.getConnection(LogBlock.java:287) ~[LogBlock.jar:?]
        at de.diddiz.LogBlock.LogBlock.onEnable(LogBlock.java:98) ~[LogBlock.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.4.jar:git-Paper-509]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-509]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-509]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-509]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-509]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

- Run mariaidb
- Run paper
- Run a plugin using a jdbc connection string and the `DriverManager` to establish database connections

### Plugin and Datapack List

NA

### Paper version

NA

### Other

This is largely an issue to either bump the connector to a working version (assuming one exists), or provide clear guidance to plugin authors that they should be shipping their own database connectors.

See also:
- https://github.com/pop4959/LWCX/issues/220
- https://github.com/LogBlock/LogBlock/issues/868

**Comment by electronicboy** [comment]
Mariadb has added the support for this to work recently, afaik the only fix
here is to update mariadb or to downgrade the MySQL connector

**Comment by electronicboy** [comment]
https://mariadb.com/kb/en/changes-improvements-in-mariadb-11-1/

Apparently so, idk if there is a good solution for this, mariadb is in this
weird area of not being compatible with MySQL properly, ideally we'd bundle
the maria driver but afaik that just breaks some stuff in the inverse
direction

**Comment by DarkArc** [comment]
I'm just going to close this since 11.1 should be fixing it.
