### ISSUE TITLE
As soon as I use the portal to go to another world, the server goes down. (Sorry if it's a portal issue, I'll report as that-enviroment is  correctlly worked by Paper 1.20.1 #35)

### ISSUE THREAD

**Issue by mifjpn** [PaperSpigot/Paper#9403]
### Stack trace

First, I was able to join the "World" correctly.
However, when I try to go to "another world" in the portal, the server immediately goes down.
 (There is no problem with paper1.20.1 #35. I think this problem is occur from around #40.)
on Terminal----
[10:09:36 INFO]: UUID of player Fairy_Nakata is 5aabfa8d-2772-4d3d-89e0-689d7657441c
[10:09:36 INFO]: Fairy_Nakata joined the game
[10:09:36 INFO]: Fairy_Nakata[/192.168.0.12:39229] logged in with entity id 757 at ([world]113.5, 73.12159999847412, -44.5)
[10:09:44 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Ticking retired scheduler
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:147) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.MinecraftServer.lambda$tickChildren$14(MinecraftServer.java:1491) ~[paper-1.20.1.jar:git-Paper-52]
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1484) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-52]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-52]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:09:44 ERROR]: This crash report has been saved to: /home/mifjpn/minecraft1/paper1.20.1/./crash-reports/crash-2023-06-27_10.09.44-server.txt
[10:09:44 INFO]: Stopping server

[crash-2023-06-27_10.09.44-server.zip](https://github.com/PaperMC/Paper/files/11876996/crash-2023-06-27_10.09.44-server.zip)

### Plugin and Datapack List

> plugins
[10:51:49 INFO]: Server Plugins (14):
[10:51:49 INFO]: Paper Plugins:
[10:51:49 INFO]:  - HuskHomes
[10:51:49 INFO]: Bukkit Plugins:
[10:51:49 INFO]:  - ChairsReloaded, HuskSync, LuckPerms, Multiverse-Core, Multiverse-Portals, PvPManager, RandomTP, SimplePortals, ViaBackwards, ViaVersion
[10:51:49 INFO]:  WorldEdit, *WorldEditGlobalizer, WorldGuard
> datapack list
[10:52:30 INFO]: There are 28 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/1.19.x.data-bubblellaneous-v1.2b.zip (world)], [file/Craftable Tents 1.19.4.zip (world)], [file/Dragon Mount Datapack.zip (world)], [file/MGS_4.1.2_datapack (world)], [file/Momentum_Hookshot.zip (world)], [file/More TNT - Cheddar Studios (world)], [file/WASD Bows V2.2.1 MC_1.19.4.zip (world)], [file/WASD Camp Trader V1.4.6 MC_1.19.4.zip (world)], [file/WASD Crazy Swords V1.1.9 MC_1.19.4.zip (world)], [file/WASD Diamond Swords V1.1.9 MC_1.19.4.zip (world)], [file/WASD Libraries V7.0.3 MC_1.20.zip (world)], [file/WASD Moar Axes V1.3.2 MC_1.19.4.zip (world)], [file/WASD Moar Boots V1.8.4 MC_1.19.4.zip (world)], [file/WASD Moar Bosses V1.0.8 MC_1.19.4.zip (world)], [file/WASD Moar Crossbows V1.4.1 MC_1.19.4.zip (world)], [file/WASD Moar Diamonds V1.4.6 MC_1.19.4.zip (world)], [file/WASD Moar Helmets V1.6.2 MC_1.19.4.zip (world)], [file/WASD Moar Pickaxes V2.1.4 MC_1.19.4.zip (world)], [file/WASD Moar TNT V1.3.0 MC_1.19.4.zip (world)], [file/WASD Moar Totems V1.4.9 MC_1.19.4.zip (world)], [file/WASD Moar Wands V1.0.7 MC_1.19.4.zip (world)], [file/WASD Moar XP V1.0.3 MC_1.19.4.zip (world)], [file/WASD Swords V3.3.2 MC_1.19.4.zip (world)], [file/WASD YouTuber Swords V1.8.2 MC_1.19.4.zip (world)], [file/[1.19.x]-bubblevehicles-3.3c.zip (world)], [file/voxel-planes.zip (world)]
[10:52:30 INFO]: There are no more data packs available

### Actions to reproduce (if known)

First, I was able to join the "World" correctly.
However, when I try to go to "another world" in the portal, the server immediately goes down.
(There is no problem with paper1.20.1 #35. I think this problem is occur from around #40.)

### Paper version

> version
[11:00:13 INFO]: Checking version, please wait...
[11:00:15 INFO]: This server is running Paper version git-Paper-52 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 7103f81)
You are running the latest version
Previous version: git-Paper-35 (MC: 1.20.1)
> 

### Other

Thank you for your continued strong development.
I was an intensive tester for a certain period of time on another repository, so I know how difficult it is.
I will do my best to help.

**Comment by mifjpn** [comment]
#39 is OK
But #40  is NotGood
[crash-2023-06-29_03.24.25-server.txt](https://github.com/PaperMC/Paper/files/11898952/crash-2023-06-29_03.24.25-server.txt)

**Comment by mifjpn** [comment]
Hellow Triager.
to the triager.
I'm aware that certain data packs will break it.
But the latest version of spigot works.
As the fastest server in the Bukkit family, I think Paper is great.
Please be sincere.

**Comment by ocelotpotpie** [comment]
Hi, build #40 had some bugs, please update to 1.20.1 build #58, the current build.

**Comment by mifjpn** [comment]
Great result! .
This server is the only one where you can see ocean waves with physics mods + planes flying low!
wonderful!

I tried spigot and found the TPS to be low. I look forward to your future success.

thanks so much! !
