### ISSUE TITLE
`.remove()` method of entities called on `EntityDismountEvent` causes server to crash if triggered on player quit.

### ISSUE THREAD

**Issue by LoneDev6** [PaperSpigot/Paper#9420]
### Expected behavior

No crash.

### Observed/Actual behavior

Server crashes.

```
Description: Exception in server tick loop

java.lang.IllegalStateException: Already retired
	at io.papermc.paper.threadedregions.EntityScheduler.retire(EntityScheduler.java:66)
	at net.minecraft.world.entity.Entity.retireScheduler(Entity.java:4712)
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4697)
	at net.minecraft.server.players.PlayerList.lambda$remove$2(PlayerList.java:639)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:630)
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:584)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2123)
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2102)
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:818)
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1587)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps/models to reproduce

1. compile a plugin with my code
2. spawn an armorstand
3. interact to ride it
4. shift to stop riding
5. see no problems
6. now ride it again
7. quit the server while still riding it
8. see the server crash

### Plugin and Datapack List

```
There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
There are no more data packs available

Server Plugins (1):
Bukkit Plugins:
 - Test
```

### Paper version

This server is running Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)
You are running the latest version

### Other

The code works fine on Spigot and worked fine on previous Paper versions, so it has something to do with recent changes, probably [this logic](https://github.com/PaperMC/Paper/blob/437e8da700276d83f435f2d84295fbbc55a07f9c/patches/server/0977-Folia-scheduler-and-owned-region-API.patch#L90).

This seems to happen because the server triggers `EntityDismountEvent` right after `PlayerQuitEvent` because the vehicle is unloaded automatically by the server on player quit with this cause: `RemovalReason.UNLOADED_WITH_PLAYER` (found in `net.minecraft.server.players.PlayerList#remove(...)` code.

Code:
```JAVA
@Override
    public void onEnable()
    {
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    private void onPlayerInteractAtEntity(PlayerInteractAtEntityEvent e)
    {
        if(e.getRightClicked().getType() == EntityType.ARMOR_STAND)
        {
            System.out.println("PlayerInteractAtEntityEvent: riding vehicle");
            e.getRightClicked().setPassenger(e.getPlayer());
        }
    }

    @EventHandler
    private void onEntityDismount(EntityDismountEvent e)
    {
        if(e.getDismounted().getType() == EntityType.ARMOR_STAND)
        {
            System.out.println("EntityDismountEvent: removing vehicle");
            e.getDismounted().remove();
        }
    }
```

**Comment by LoneDev6** [comment]
Thanks a lot @kennytv ! ❤️
