### ISSUE TITLE
Cannot load any mods in 1.20

### ISSUE THREAD

**Issue by dbones** [PaperSpigot/Paper#9454]
### Stack trace

```
bones-minecraft-1  | [02:09:55 ERROR]: Detected invalid header for regionfile /data/./world/entities/r.-1.-1.mca! Cannot recalculate, removing local chunk (12,6) from header
dbones-minecraft-1  | [02:09:55 ERROR]: [ChunkDataTask] Failed to read chunk data for task: Task for world: 'world' at (-9,-4) type: ENTITY_DATA, hash: 765527463
dbones-minecraft-1  | java.lang.IllegalArgumentException: Negative position
dbones-minecraft-1  |   at sun.nio.ch.FileChannelImpl.read(Unknown Source) ~[?:?]
dbones-minecraft-1  |   at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:485) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:432) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at net.minecraft.world.level.chunk.storage.RegionFileStorage.getRegionFile(RegionFileStorage.java:144) ~[?:?] 
dbones-minecraft-1  |   at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:225) ~[?:?]
dbones-minecraft-1  |   at net.minecraft.server.level.ServerLevel.readEntityChunk(ServerLevel.java:456) ~[?:?]
dbones-minecraft-1  |   at net.minecraft.server.level.ServerLevel$3.readData(ServerLevel.java:416) ~[?:?]
dbones-minecraft-1  |   at io.papermc.paper.chunk.system.io.RegionFileIOThread$ChunkDataTask.run(RegionFileIOThread.java:1260) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.pollTasks(PrioritisedQueueExecutorThread.java:110) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  | [02:09:55 ERROR]: [ChunkLoadTask] Failed to load entity data for task: GenericDataLoadTask{class: io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$EntityDataLoadTask, world: world, chunk: (-9,-4), hashcode: 1148006351, priority: COMPLETING, type: ENTITY_DATA}, entity data will be lost
dbones-minecraft-1  | java.lang.IllegalArgumentException: Negative position
dbones-minecraft-1  |   at sun.nio.ch.FileChannelImpl.read(Unknown Source) ~[?:?]
dbones-minecraft-1  |   at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:485) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:432) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at net.minecraft.world.level.chunk.storage.RegionFileStorage.getRegionFile(RegionFileStorage.java:144) ~[?:?] 
dbones-minecraft-1  |   at net.minecraft.world.level.chunk.storage.RegionFileStorage.read(RegionFileStorage.java:225) ~[?:?]
dbones-minecraft-1  |   at net.minecraft.server.level.ServerLevel.readEntityChunk(ServerLevel.java:456) ~[?:?]
dbones-minecraft-1  |   at net.minecraft.server.level.ServerLevel$3.readData(ServerLevel.java:416) ~[?:?]
dbones-minecraft-1  |   at io.papermc.paper.chunk.system.io.RegionFileIOThread$ChunkDataTask.run(RegionFileIOThread.java:1260) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.pollTasks(PrioritisedQueueExecutorThread.java:110) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  |   at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:50) ~[paper-1.20.1.jar:git-Paper-64]
dbones-minecraft-1  | [02:09:55 WARN]: Region file ./world/entities/r.-1.-1.mca has an invalid sector at index: 0; size has to be > 0 
dbones-minecraft-1  | [02:09:55 ERROR]: Detected invalid header for regionfile /data/./world/entities/r.-1.-1.mca! Cannot recalculate, removing local chunk (0,0) from header
dbones-minecraft-1  | [02:09:55 WARN]: Backing up regionfile "/data/./world/entities/r.-1.-1.mca" to /data/./world/entities/r.-1.-1.mca.6605179565140931922.backup
dbones-minecraft-1  | [02:09:55 WARN]: Backed up the regionfile to /data/./world/entities/r.-1.-1.mca.6605179565140931922.backup      
dbones-minecraft-1  | [02:09:55 WARN]: Region file ./world/entities/r.-1.-1.mca has an invalid sector at index: 1; sector 7602176 is out of bounds
dbones-minecraft-1  | [02:09:55 ERROR]: Detected invalid header for regionfile /data/./world/entities/r.-1.-1.mca! Cannot recalculate, removing local chunk (1,0) from header
dbones-minecraft-1  | [02:09:55 WARN]: Region file ./world/entities/r.-1.-1.mca has an invalid sector at index: 2; sector 131072 is out of bounds
dbones-minecraft-1  | [02:09:55 ERROR]: Detected invalid header for regionfile /data/./world/entities/r.-1.-1.mca! Cannot recalculate, removing local chunk (2,0) from header
dbones-minecraft-1  | [02:09:55 WARN]: Region file ./world/entities/r.-1.-1.mca has an invalid sector at index: 3; size has to be > 0 
dbones-minecraft-1  | [02:09:55 ERROR]: Detected invalid header for regionfile /data/./world/entities/r.-1.-1.mca! Cannot recalculate, removing local chunk (3,0) from header
```

### Plugin and Datapack List

Citizens-2.0.32-b3123 (i have tried other mods, but this shows the problem)

### Actions to reproduce (if known)

run the following docker-compose (change the location of the volume map)

confirm the world is up

add the plugin and restart the work container.

```yaml
version: '3'
services:
  minecraft:
    image: "itzg/minecraft-server:java17"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MODE: "survival"
      SNOOPER_ENABLED: "false"
      HARDCORE: "false"
      SERVER_NAME: "bonescraft"
      SERVER_PORT: "25565"
      MOTD: "hi hi"
      MAX_PLAYERS: "50"
      VERSION: "1.20.1"
      MAX_WORLD_SIZE: "30000"
      MAX_MEMORY: "16G"
    ports:
      - "8123:8123"
      - "25565:25565"
      - "19132:19132/udp"

```

### Paper version

from the client
```
This server is running Paper version git-Paper-65 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: dadd8b5)
You are running the latest version
Previous version: git-Paper-64 (MC: 1.20.1)
```

server logs
```
dbones-minecraft-1  | [mc-image-helper] 02:04:09.177 INFO  : Resolved paper to version 1.20.1 build 64
```

### Other

this worked with 1.19.4

**Comment by MiniDigger** [comment]
your world seems corrupted, try a backup

**Comment by dbones** [comment]
its a brand new world

the steps above are exactly what im doing

**Comment by Machine-Maker** [comment]
I mean something corrupted or didn't save properly. We don't have an "official" docker image for Paper. If you can replicate this without using docker, just by downloading the jar and running a startup script, then it can be re-opened.
