### ISSUE TITLE
Paper's CraftPlayerProfile cannot be cast to Bukkit's CraftPlayerProfile

### ISSUE THREAD

**Issue by Coralise** [PaperSpigot/Paper#9455]
### Stack trace

java.lang.ClassCastException: class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @4d591d15)
        at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:79) ~[paper-1.20.1.jar:git-Paper-65]       
        at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:17) ~[paper-1.20.1.jar:git-Paper-65]       
        at me.coralise.players.PlayerListeners.onLogin(PlayerListeners.java:58) ~[CustomBansPlus.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-65]   
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:392) ~[?:?]    
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:277) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin and Datapack List

Only one: Custom Bans Plus

### Actions to reproduce (if known)

Use the PlayerProfile returned by the `OfflinePlayer#getPlayerProfile()` into the new banlist spigot created for their 1.20.1 API, the ProfileBanList. For example...

```java
BanList<PlayerProfile> pbl = Bukkit.getBanList(Type.PROFILE);
PlayerProfile pp = Bukkit.getOfflinePlayer(uuid).getPlayerProfile();

if (pbl.isBanned(pp)) { ... }
```
Errors out at `isBanned()`.

### Paper version

Latest version, Build #65.

**Comment by Machine-Maker** [comment]
Fixed with https://github.com/PaperMC/Paper/pull/9450

Kind of a duplicate, but not really cause it was just a comment on another issue.
