### ISSUE TITLE
Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by tanyaofei** [PaperSpigot/Paper#9490]
### Expected behavior

No crash or should tell plugin developer never play sound in async thread.

### Observed/Actual behavior

java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
	at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:79)
	at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:45)
	at net.minecraft.world.level.levelgen.BitRandomSource.nextFloat(BitRandomSource.java:49)
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:250)
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:214)
	at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:184)
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:627)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:502)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:848)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
	at java.base/java.lang.Thread.run(Thread.java:1589)

![IMG_0689](https://github.com/PaperMC/Paper/assets/46375450/015779e5-aa7e-457b-b649-e4fd049bddae)

### Steps/models to reproduce

I am writing a plugin that listen to AsyncChatEvent

These code will be running in the listener thread (which should be async).
```
server.playSound(Sound.sound(
                        org.bukkit.Sound.ENTITY_FIREWORK_ROCKET_LARGE_BLAST.key(),
                        Sound.Source.MASTER,
                        1.0F,
                        1.0F)
                );
```

Sometimes server will crash and close.

### Plugin and Datapack List

[quiz](https://github.com/tanyaofei/minecraft-quiz)

### Paper version

1.20.1-2014

### Other

May be we should not send sound in async thread ?

**Comment by electronicboy** [comment]
> should tell plugin developer never play sound in async thread

The API literally states that calling the API off the main thread is 100% unsupported and likely to cause issues, hence why we've been telling people this stuff for literally a decade. We should maybe consider taking a behavioral hit here in terms of using an alternative random source, not sure if it's worth it, it's not exactly a huge interest to scatter to the codebase with async catchers religiously

**Comment by Machine-Maker** [comment]
That method isn't threadsafe currently. You can just specify the OptionalLong in the Sound yourself so it doesn't use the overworld's thread unsafe random.

**Comment by tanyaofei** [comment]
> > should tell plugin developer never play sound in async thread
> 
> The API literally states that calling the API off the main thread is 100% unsupported and likely to cause issues, hence why we've been telling people this stuff for literally a decade. We should maybe consider taking a behavioral hit here in terms of using an alternative random source, not sure if it's worth it, it's not exactly a huge interest to scatter to the codebase with async catchers religiously

How could I known which Apis are not thread safe? The lack of any indication is causing a heavy burden on my development. Should I use the main thread for calling any apis?

**Comment by electronicboy** [comment]
General gist is that nothing in the API is thread safe unless it states (or, you can prove) otherwise, I thought that was noted on the docs, but apparently it's only done so on the bukkit dev docs.

**Comment by codeHusky** [comment]
Bump on this - would be good if this API was noted as not thread safe in the JD as we had a server crash because of this as well. Would've seen the note if it was there as I end up checking the JD for this method occasionally.
