### ISSUE TITLE
Fishing rod stuck/broken in all last build.

### ISSUE THREAD

**Issue by Zzheyd** [PaperSpigot/Paper#9515]
### Expected behavior

Fishing rod broken

### Observed/Actual behavior

Fishing rod broken, and need to disconnect and log for properly fishing again

### Steps/models to reproduce

I'm simply fishing in water, pop randomly idk how exactly :/
But for reproduce it, i can simply pull any citizen npc with my fishing rod

You can see this problem in my little video here:
https://www.youtube.com/watch?v=iUPzaeBRRyo&ab_channel=Zzheyd

### Plugin and Datapack List

Plugin: only CITIZEN for testing

### Paper version

With oldest build, we have no problem when u can see in this video:https://www.youtube.com/watch?v=LOy9UjNa0SU&ab_channel=Zzheyd

We have this problem only with new builds, problem appear AFTER build 41 of paper.

Builds 35 to 41 work fine, dont have this issue
Builds 42, 45 etc to 83 have this problem

### Other

With paper build 40 have see this error in console log hen i'm interact when citizens npc:

`[17:38:53] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInBlockPlace@1e63fbb0, suppressing error
java.lang.IllegalStateException: Already retired
	at io.papermc.paper.threadedregions.EntityScheduler.retire(EntityScheduler.java:66) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.world.entity.Entity.retireScheduler(Entity.java:4711) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4696) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.world.entity.Entity.remove(Entity.java:698) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.world.entity.projectile.FishingHook.remove(FishingHook.java:601) ~[?:?]
	at net.minecraft.world.entity.Entity.discard(Entity.java:680) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:567) ~[?:?]
	at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:32) ~[?:?]
	at net.minecraft.world.item.ItemStack.use(ItemStack.java:540) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:481) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2040) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-40]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-40]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

This error does not appear in build 41++++, idk why, but in game, problem is always here...

**Comment by Gorderok** [comment]
Have same problem, but i dont have any plugin :/
