### ISSUE TITLE
Packet encoding of packet ID 82 threw (skippable? false)

### ISSUE THREAD

**Issue by AgentSlim** [PaperSpigot/Paper#9518]
### Expected behavior

The player inventory is to be recovered from a serialized string

### Observed/Actual behavior

`
[Netty Epoll Server IO #0/ERROR]: Packet encoding of packet ID 82 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "trackedValues" is null
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.pack(ClientboundSetEntityDataPacket.java:17) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:38) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.20.1.jar:git-Paper-84]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.1.jar:git-Paper-84]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:476) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:450) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

### Steps/models to reproduce

Serializer Class
`
public class BukkitSerializer {

    /**
     * Return a serialized array of {@link ItemStack}s
     *
     * @param inventoryContents The contents of the inventory
     * @return The serialized inventory contents
     **/
    public static CompletableFuture<String> serializeItemStackArray(@NotNull ItemStack[] inventoryContents)
            throws DataSerializationException {
        return CompletableFuture.supplyAsync(() -> {
            if (inventoryContents.length == 0) {
                return "";
            }

            //Create an output stream that will be encoded into base 64
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();

            try (BukkitObjectOutputStream bukkitObjectOutputStream = new BukkitObjectOutputStream(byteArrayOutputStream)) {
                // Define the length of the inventory array to serialize
                bukkitObjectOutputStream.writeInt(inventoryContents.length);

                // Write each serialize each ItemStack to the output stream
                for (ItemStack inventoryItem : inventoryContents) {
                    bukkitObjectOutputStream.writeObject(serializeItemStack(inventoryItem));
                }

                //Return encoded data, using the encoded from SnakeYaml to get a ByteArray conversion
                return Base64Coder.encodeLines(byteArrayOutputStream.toByteArray());
            } catch (IOException e) {
                throw new DataSerializationException("Failed to serialize item stack data", e);
            }
        });
    }

    /**
     * Returns a {@link BukkitInventoryMap} from a serialized array of ItemStacks representing the contents of a player's inventory.
     *
     * @param serializedPlayerInventory The serialized {@link ItemStack} inventory array
     * @return The deserialized ItemStacks, mapped for convenience as a {@link BukkitInventoryMap}
     * @throws DataSerializationException If the serialized item stack array could not be deserialized
     */
    public static CompletableFuture<BukkitInventoryMap> deserializeInventory(@NotNull String serializedPlayerInventory)
            throws DataSerializationException {
        return CompletableFuture.supplyAsync(() -> new BukkitInventoryMap(deserializeItemStackArray(serializedPlayerInventory).join()));
    }

    /**
     * Returns an array of ItemStacks from serialized inventory data.
     *
     * @param serializeItemStackArray The serialized {@link ItemStack} array
     * @return The deserialized array of {@link ItemStack}s
     * @throws DataSerializationException If the serialized item stack array could not be deserialized
     * @implNote Empty slots will be represented by {@code null}
     */
    public static CompletableFuture<ItemStack[]> deserializeItemStackArray(@NotNull String serializeItemStackArray)
            throws DataSerializationException {
        return CompletableFuture.supplyAsync(() -> {
            // Return empty array if there is no inventory data (set the player as having an empty inventory)
            if (serializeItemStackArray.isEmpty()) {
                return new ItemStack[0];
            }

            // Create a byte input stream to read the serialized data
            try (ByteArrayInputStream byteInputStream = new ByteArrayInputStream(Base64Coder.decodeLines(serializeItemStackArray))) {
                try (BukkitObjectInputStream bukkitInputStream = new BukkitObjectInputStream(byteInputStream)) {
                    // Read the length of the Bukkit input stream and set the length of the array to this value
                    ItemStack[] inventoryContents = new ItemStack[bukkitInputStream.readInt()];

                    // Set the ItemStacks in the array from deserialized ItemStack data
                    int slotIndex = 0;
                    for (ItemStack ignored : inventoryContents) {
                        inventoryContents[slotIndex] = deserializeItemStack(bukkitInputStream.readObject());
                        slotIndex++;
                    }

                    // Return the finished, serialized inventory contents
                    return inventoryContents;
                }
            } catch (IOException | ClassNotFoundException e) {
                throw new DataSerializationException("Failed to deserialize item stack data", e);
            }
        });
    }

    /**
     * Returns the serialized version of an {@link ItemStack} as a string to object Map
     *
     * @param item The {@link ItemStack} to serialize
     * @return The serialized {@link ItemStack}
     */
    private static Map<String, Object> serializeItemStack(@Nullable ItemStack item) {
        return item != null ? item.serialize() : null;
    }

    /**
     * Returns the deserialized {@link ItemStack} from the Object read from the {@link BukkitObjectInputStream}
     *
     * @param serializedItemStack The serialized item stack; a String-Object map
     * @return The deserialized {@link ItemStack}
     */
    @SuppressWarnings("unchecked") // Ignore the "Unchecked cast" warning
    @Nullable
    private static ItemStack deserializeItemStack(@Nullable Object serializedItemStack) {
        return serializedItemStack != null ? ItemStack.deserialize((Map<String, Object>) serializedItemStack) : null;
    }
}
`

When the player lefts, the inventory is serialized and stored in the database.
Method: "serializeItemStackArray"

Joint the player becomes, the inventory should be restored from the database. 
Method: "deserializeInventory"

### Plugin and Datapack List

Self code

### Paper version

This server is running Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03)
You are running the latest version

**Comment by lynxplay** [comment]
Given that you seem to have some custom logic running from a plugin that presumably is not open source ? there is not much for us to do here.

The stacktrace implies that a invalid packet was attempted to be sent, which judging from a quick glance through the code, is never done by the server itself, each creation of the packet previously nullchecks the list passed.

If you can replicate a minimal replication plugin that presents this issue that we can look at, feel free to comment here so we can have another look, but for now this seems like a plugin issue that does not need debugging via github issues. You are free to jump onto our [discord](https://discord.gg/papermc) if you need help debugging.
