### ISSUE TITLE
Use /kill to kill a player then server output error and the player get in stuck

### ISSUE THREAD

**Issue by Hongshiits** [PaperSpigot/Paper#9540]
### Expected behavior

After /kill ,the player should rebirth fluently and no errors in consle.

### Observed/Actual behavior

the player death and stuck and server's errors

```
[22:14:02] [Server thread/INFO]: Hehonge issued server command: /gamemode creative
[22:14:02] [Server thread/INFO]: [Hehonge: Set own game mode to Creative Mode]
[22:14:02] [Server thread/INFO]: Hehonge issued server command: /gamemode survival
[22:14:02] [Server thread/INFO]: [Hehonge: Set own game mode to Survival Mode]
[22:14:18] [Server thread/INFO]: Hehonge issued server command: /help
[22:14:33] [Server thread/INFO]: Hehonge issued server command: /lp editor
[22:15:28] [Server thread/INFO]: Hehonge issued server command: /gamemode creative
[22:15:28] [Server thread/INFO]: [Hehonge: Set own game mode to Creative Mode]
[22:15:44] [Server thread/INFO]: Hehonge issued server command: /kill
[22:15:44] [Server thread/INFO]: Hehonge was killed
[22:15:44] [Server thread/INFO]: [Hehonge: Killed Hehonge]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: No key placement in MapLike[{config:{blacklist:[],block_placer:{type:"minecraft:simple_block_placer"},can_replace:0b,need_water:0b,project:0b,state_provider:{state:{Name:"minecraft:sweet_berry_bush",Properties:{age:"3"}},type:"minecraft:simple_state_provider"},tries:64,whitelist:[{Name:"minecraft:grass_block",Properties:{snowy:"false"}}],xspread:7,yspread:3,zspread:7},type:"minecraft:random_patch"}]; No key feature in MapLike[{config:{blacklist:[],block_placer:{type:"minecraft:simple_block_placer"},can_replace:0b,need_water:0b,project:0b,state_provider:{state:{Name:"minecraft:sweet_berry_bush",Properties:{age:"3"}},type:"minecraft:simple_state_provider"},tries:64,whitelist:[{Name:"minecraft:grass_block",Properties:{snowy:"false"}}],xspread:7,yspread:3,zspread:7},type:"minecraft:random_patch"}]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:65) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.levelgen.structure.StructureStart.loadStaticStart(StructureStart.java:57) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:750) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:349) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.20.1.jar:git-Paper-96]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: No key placement in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]; No key feature in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:65) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.levelgen.structure.StructureStart.loadStaticStart(StructureStart.java:57) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:750) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:349) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.20.1.jar:git-Paper-96]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: No key placement in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]; No key feature in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:65) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.levelgen.structure.StructureStart.loadStaticStart(StructureStart.java:57) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:750) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:349) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.20.1.jar:git-Paper-96]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: No key placement in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]; No key feature in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:65) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.levelgen.structure.StructureStart.loadStaticStart(StructureStart.java:57) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:750) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:349) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.20.1.jar:git-Paper-96]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: No key placement in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]; No key feature in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:65) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.levelgen.structure.StructureStart.loadStaticStart(StructureStart.java:57) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:750) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:349) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.20.1.jar:git-Paper-96]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: No key placement in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]; No key feature in MapLike[{config:{decorators:[],foliage_placer:{offset:{base:0,spread:2},radius:{base:2,spread:1},trunk_height:{base:1,spread:1},type:"minecraft:spruce_foliage_placer"},heightmap:"OCEAN_FLOOR",ignore_vines:1b,leaves_provider:{state:{Name:"minecraft:spruce_leaves",Properties:{distance:"7",persistent:"false"}},type:"minecraft:simple_state_provider"},max_water_depth:0,minimum_size:{limit:2,lower_size:0,type:"minecraft:two_layers_feature_size",upper_size:2},trunk_placer:{base_height:5,height_rand_a:2,height_rand_b:1,type:"minecraft:straight_trunk_placer"},trunk_provider:{state:{Name:"minecraft:spruce_log",Properties:{axis:"y"}},type:"minecraft:simple_state_provider"}},type:"minecraft:tree"}]
[22:16:05] [Tuinity Chunk System Worker #0/ERROR]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.lambda$new$0(PoolElementStructurePiece.java:52) ~[?:?]
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.load(PiecesContainer.java:65) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.levelgen.structure.StructureStart.loadStaticStart(StructureStart.java:57) ~[paper-1.20.1.jar:git-Paper-96]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.unpackStructureStart(ChunkSerializer.java:750) ~[?:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.loadChunk(ChunkSerializer.java:349) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:338) ~[paper-1.20.1.jar:git-Paper-96]
	at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.1.jar:git-Paper-96]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.20.1.jar:git-Paper-96]
[22:18:23] [Server thread/INFO]: Hehonge issued server command: /gamemode creative
[22:18:23] [Server thread/INFO]: [Hehonge: Set own game mode to Creative Mode]
[22:19:21] [Server thread/INFO]: Hehonge lost connection: Disconnected
[22:19:21] [Server thread/INFO]: Hehonge left the game
```

### Steps/models to reproduce

1,run /kill by the player himself
2,the player death
3,server consle output errors:
 

### Plugin and Datapack List

[10:32:57 INFO]: Server Plugins (6):
[10:32:57 INFO]: Bukkit Plugins:
[10:32:57 INFO]:  - AuthMe, Geyser-Spigot, LuckPerms, Multiverse-Core, ViaBackwards, ViaVersion

[10:33:59 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[10:33:59 INFO]: There are no more data packs available

### Paper version

[10:34:16 INFO]: Checking version, please wait...
[10:34:18 INFO]: This server is running Paper version git-Paper-96 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b14979e)

**Comment by pop4959** [comment]
This is a vanilla issue [MC-227945](https://bugs.mojang.com/browse/MC-227945) which has been reported numerous times, and is fairly harmless at that. This doesn't have anything directly to do with `/kill` although it is likely that loading the respawn chunks could have triggered it.
