### ISSUE TITLE
Server Crash Help Needed

### ISSUE THREAD

**Issue by SladeHazard** [PaperSpigot/Paper#9556]
### Stack trace

Time: 5/24/23 1:18 PM
Description: Ticking player

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1493)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at java.util.HashSet.<init>(HashSet.java:120)
	at com.google.common.collect.Sets.newHashSet(:258)
	at net.minecraft.server.v1_20_R1.AttributeModifiable.b(:204)
	at net.minecraft.server.v1_20_R1.AttributeModifiable.g(:186)
	at net.minecraft.server.v1_20_R1.AttributeModifiable.getValue(:176)
	at net.minecraft.server.v1_20_R1.EntityLiving.getArmorStrength(:1312)
	at net.minecraft.server.v1_20_R1.EntityPlayer.playerTick(:388)
	at net.minecraft.server.v1_20_R1.PlayerList.disconnect(:438)
	at net.minecraft.server.v1_20_R1.PlayerConnection.a(:1179)
	at net.minecraft.server.v1_20_R1.NetworkManager.handleDisconnection(:591)
	at net.minecraft.server.v1_20_R1.ServerConnection.c(:218)
	at net.minecraft.server.v1_20_R1.MinecraftServer.D(:995)
	at net.minecraft.server.v1_20_R1.DedicatedServer.D(:431)
	at net.minecraft.server.v1_20_R1.MinecraftServer.C(:778)
	at net.minecraft.server.v1_20_R1.MinecraftServer.run(:669)
	at java.lang.Thread.run(Thread.java:748)

### Plugin and Datapack List

I know the plugin that's causing this, just cannot figure out what exactly is the reason for it / what I need to change

### Actions to reproduce (if known)

happens randomly after 5 days of server uptime

### Paper version

1.20

**Comment by electronicboy** [comment]
That doesn't look like paper, and that error is something modifying what looks like attributes off the main thread
