### ISSUE TITLE
Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInUseItem@37288ab

### ISSUE THREAD

**Issue by tomkimberlin** [PaperSpigot/Paper#9719]
### Stack trace

```
[14:29:48 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInUseItem@37288ab, suppressing error
java.lang.IllegalArgumentException: Expected packet sequence nr >= 0
	at net.minecraft.server.network.ServerGamePacketListenerImpl.ackBlockChangesUpTo(ServerGamePacketListenerImpl.java:2195) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1986) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-170]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-170]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```
This occurred as a player lost connection for `Expected packet sequence nr >=0`.

### Plugin and Datapack List

AntiPopup, Chunky, CoreProtect, DiscordSRV, eBackup, Essentials, EssentialsChat, EssentialsSpawn, FirstJoinMessage, LuckPerms, Pl-Hide-Pro, PlaceholderAPI, ProtocolLib, spark, SuperVanish, UnexpectedSpawn, Vault, ViaBackwards, ViaVersion, Vulcan, WorldEdit, WorldGuard

### Paper version

git-Paper-170

I know it's not the latest version of Paper, but I am unable to update and try to reproduce because the error was caused by a player using a modified client, so I am reporting it anyway just in case.

**Comment by MiniDigger** [comment]
the player send a wrong packet. unless this can be reproduced with a vanilla client on latest paper, there is not much we can do.

**Comment by Warriorrrr** [comment]
A vanilla client won't ever send a sequence that's less than 0

**Comment by MachineBreaker** [comment]
The server after receiving the seq < 0 kicks the player but for any reason the server throws a IllegalArgumentException

**Comment by tomkimberlin** [comment]
> the player send a wrong packet. unless this can be reproduced with a vanilla client on latest paper, there is not much we can do.

Gotcha. The player was using a modified client so you hit the nail on the head. Feel free to close this issue if there is nothing to be done. Thanks!
