### ISSUE TITLE
UnmodifiableItemStack error

### ISSUE THREAD

**Issue by SlimeDog** [PaperSpigot/Paper#9733]
### Expected behavior

Clean loading of Shopkeepers plugin

### Observed/Actual behavior

```
[08:56:10] [Server thread/WARN]: [Shopkeepers] Failed to load shopkeeper '1': Shopkeeper data migration failed!
com.nisovin.shopkeepers.util.data.serialization.InvalidDataException: Item migration failed for trade offer 1: SKTradeOffer [resultItem=UnmodifiableItemStack{BLAZE_ROD x 1, UNSPECIFIC_META:{meta-type=UNSPECIFIC, display-name={"extra":[{"bold":false,"italic":true,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Bug Zapper"}],"text":""}, lore=[{"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"When in main hand:"}],"text":""}, {"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"dark_green","text":" 9 Attack Damage"}],"text":""}]}}, item1=UnmodifiableItemStack{FIRE_CHARGE x 48}, item2=UnmodifiableItemStack{ENDER_PEARL x 16}]
        at com.nisovin.shopkeepers.shopkeeper.offers.SKTradeOffer.migrateItems(SKTradeOffer.java:315) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.offers.SKTradeOffer.migrateOffers(SKTradeOffer.java:252) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.admin.regular.SKRegularAdminShopkeeper$1.migrate(SKRegularAdminShopkeeper.java:102) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.migration.ShopkeeperDataMigrator.migrate(ShopkeeperDataMigrator.java:124) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.migration.ShopkeeperDataMigrator.migrate(ShopkeeperDataMigrator.java:96) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.shopkeeper.ShopkeeperData.migrate(ShopkeeperData.java:80) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.loadShopkeeper(SKShopkeeperStorage.java:607) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.doReload(SKShopkeeperStorage.java:561) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.storage.SKShopkeeperStorage.reload(SKShopkeeperStorage.java:408) ~[Shopkeepers-2.17.2-b143.jar:?]
        at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:409) ~[Shopkeepers-2.17.2-b143.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-185]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-185]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-185]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-185]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-185]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-185]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-185]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-185]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-185]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Steps/models to reproduce

Paper-1.20.1-185
Citizens 2.0.32-SNAPSHOT (build 3204) or any recent build
Shopkeepers 2.17.2-SNAPSHOT+a1d4cfa3

- Update Paper-1.20.1-184 to Paper-1.20.1-185 (or subsequent -- tested through Paper-1.20.1-193)
- No other changes; specifically, no changes to Citizens or Shopkeepers
- Start server
- Read console log to discover error above

### Plugin and Datapack List

```
> plugins
[09:06:55 INFO]: Server Plugins (119):
[09:06:55 INFO]: Paper Plugins:
[09:06:55 INFO]:  - AdvancedServerList, ChessCraft, TreasureMapsPlus
[09:06:55 INFO]: Bukkit Plugins:
[09:06:55 INFO]:  - AcceptTheRules, Accuracy, AdminVault, AggressiveAnimals, AntiAFKPlus, BeeHivesTrees, BentoBox, BentoBox-Biomes, BentoBox-BSkyBlock, BentoBox-Challenges
[09:06:55 INFO]:  BentoBox-Level, BetterBees, BetterConcrete, BigDoors, BigDoorsOpener, BiomeRemap, BloodInMinecraft, BlueSlimeCore, Bolt, Bookshelf
[09:06:55 INFO]:  Chunky, ChunkyBorder, Citizens, CityWorld, CMILib, CombatLogX, CommandSigns, ConsoleSpamFix, Constructor, CoordinateTool
[09:06:55 INFO]:  CustomItemsLib, DarknessDamage, DecentHolograms, *DelayJoin, DeluxeMenus, Disease, Elevators, EntityCount, EntityDetection, Essentials
[09:06:55 INFO]:  EssentialsChat, EssentialsGeoIP, ExtraContexts, ExtraHardMode, FancyHolograms, FastCraft, FishyLecterns, ForceResourcepacks, GeoFurnace, GraveEntitySpawn
[09:06:55 INFO]:  HeadsInventory, HeadsPluginAPI, HeadSweeper, IllegalStack, Insights, InsightsWorldEditExtension, InvisibleItemFrames, ItemJoin, JSEngine, Lightnings
[09:06:55 INFO]:  LuckPerms, McEventCore, MeltDown, MobColors, MobHunting, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, MysticalBarriers
[09:06:55 INFO]:  NBTAPI, NetworkInterceptor, NoBlackSky, ntdLuckyBlock, PhatLoots, pHD, PlaceholderAPI, Plan, PluginControl, PluginManager
[09:06:55 INFO]:  PluginVersions, ProtocolLib, PyroLib, PyroWeatherPro, Quests, RealScoreboard, RedstoneProximitySensor, Residence, SavageDeathChest, SavageDeathCompass
[09:06:55 INFO]:  SavageGraveyards, SeaShells, Sentinel, *ServerTutorialPlus, Shopkeepers, SignBoard, SimpleCompass, Skript, spark, StatisticEditor
[09:06:55 INFO]:  StayPut, StreetLamps, SystemProperties, TabList, Telecom, Thirst, TreeFeller, V10Lift, Vault, VoidGen
[09:06:55 INFO]:  VoidSpawn, WhatIsThis, WhatPlugin, WorldEdit, WorldEditSelectionVisualizer, WorldGuard
> datapack list
[09:07:02 INFO]: There are 5 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)], [file/cityworld (world)], [file/crafting (world)], [file/TreasureMapsPlus (world)]
[09:07:02 INFO]: There are no more data packs available
```

### Paper version

```
> version
[09:06:22 INFO]: This server is running Paper version git-Paper-185 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 0c8e84c)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
```

### Other

Shopkeepers was last updated in June, and has worked through all interactions of Paper until now.

If Shopkeepers needs to change something to be compliant with latest Paper builds, I will post your response there.

**Comment by lynxplay** [comment]
It appears something is *overwriting* ItemStack here which is *explicitly* not permitted in the bukkit API.
https://github.com/Shopkeepers/Shopkeepers/issues/842#issuecomment-1722495785 sounds plausible, please have the authors of the shopkeeper plugin look into this before opening an issue on paper.

If this turns out to *actually* be a breaking change under our current API promises, feel free to comment here, we will reopen the issue, until then this is a invalid issue :+1:
