### ISSUE TITLE
Multiple entries with same key

### ISSUE THREAD

**Issue by StAnimaties** [PaperSpigot/Paper#9755]
### Stack trace

```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Multiple entries with same key: LootItemConditionRandomChance[probability=0.25]=poke:effect_checking/movechance and LootItemConditionRandomChance[probability=0.25]=golem:random_lc
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:286) ~[paper-1.20.2.jar:git-Paper-197]
	at org.bukkit.craftbukkit.Main.main(Main.java:324) ~[paper-1.20.2.jar:git-Paper-197]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: LootItemConditionRandomChance[probability=0.25]=poke:effect_checking/movechance and LootItemConditionRandomChance[probability=0.25]=golem:random_lc
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:378) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:372) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:246) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:133) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:572) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:600) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:587) ~[guava-32.1.2-jre.jar:?]
	at net.minecraft.world.level.storage.loot.LootDataManager.apply(LootDataManager.java:106) ~[paper-1.20.2.jar:git-Paper-197]
	at net.minecraft.world.level.storage.loot.LootDataManager.lambda$reload$2(LootDataManager.java:49) ~[paper-1.20.2.jar:git-Paper-197]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:66) ~[?:?]
	at net.minecraft.Util.blockUntilDone(Util.java:828) ~[?:?]
	at net.minecraft.Util.blockUntilDone(Util.java:817) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:254) ~[paper-1.20.2.jar:git-Paper-197]
	... 3 more

```

### Plugin and Datapack List

[Golems 1.1.zip](https://github.com/PaperMC/Paper/files/12709088/Golems.1.1.zip)
[PokeMobs 1.8.zip](https://github.com/PaperMC/Paper/files/12709091/PokeMobs.1.8.zip)

### Paper version

Paper 1.20.2-197
(Experimental Build 1 on https://papermc.io/downloads/paper)

Server couldn't start up so hope this suffices

**Comment by electronicboy** [comment]
Have you tested those packs on vanilla?

**Comment by StAnimaties** [comment]
I've ran both on a vanilla 1.20.2 test server for a few weeks, packs ran without issue on there

**Comment by catter1** [comment]
I can confirm. If you wish to test, I made two bare-bones datapacks that have duplicate predicates. Use them together on Vanilla and it works fine, but use them on Paper and it crashes with a similar error as StAnimaties shared.
[TestA.zip](https://github.com/PaperMC/Paper/files/12718521/TestA.zip)
[TestB.zip](https://github.com/PaperMC/Paper/files/12718520/TestB.zip)

**Comment by Machine-Maker** [comment]
Ok, I see the issue. Am working on a fix.
