### ISSUE TITLE
[1.20.2] Configurate 4.1.2 conflicts with snakeyaml 2.2

### ISSUE THREAD

**Issue by portlek** [PaperSpigot/Paper#9765]
### Expected behavior

'add-plugin' parameter should work on 1.20.2 version of paper.

### Observed/Actual behavior

Configurate that comes from paper's libraries do not work with the updated snakeyaml 2.2

### Steps/models to reproduce

create an empty paper server and use 'add-plugin' parameter to specify a plugin outside of the plugins folder.

this happens because configurate 4.1.2 does not support snakeyaml 2.2 and this is only the case when you use 'add-plugin' paramter because it tries to load the file using configurate.

### Plugin and Datapack List

no plugin, raw server issue.

### Paper version

This server is running Paper version git-Paper-201 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 298c478)
You are running the latest version
Previous version: git-Paper-196 (MC: 1.20.1)

### Other

```
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8.1+1) Host: Linux 6.1.0-12-amd64 (amd64)
Loading libraries, please wait...
2023-09-26 18:58:15,686 ServerMain WARN Advanced terminal features are not available in this environment
[18:58:16 ERROR]: [EntrypointUtil] Receiver class org.spongepowered.configurate.yaml.ConfigurateScanner does not define or inherit an implementation of the resolved method 'abstract void resetDocumentIndex()' of interface org.yaml.snakeyaml.scanner.Scanner.
java.lang.AbstractMethodError: Receiver class org.spongepowered.configurate.yaml.ConfigurateScanner does not define or inherit an implementation of the resolved method 'abstract void resetDocumentIndex()' of interface org.yaml.snakeyaml.scanner.Scanner.
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:238) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:224) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:156) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178) ~[snakeyaml-2.2.jar:?]
	at org.spongepowered.configurate.yaml.ConfigurateYaml.loadConfigurate(ConfigurateYaml.java:39) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:158) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.yaml.YamlConfigurationLoader.loadInternal(YamlConfigurationLoader.java:42) ~[configurate-yaml-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:155) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:63) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:56) ~[configurate-core-4.1.2.jar:?]
	at io.papermc.paper.plugin.provider.configuration.PaperPluginMeta.create(PaperPluginMeta.java:95) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.create(PaperPluginProviderFactory.java:52) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.provider.type.paper.PaperPluginProviderFactory.create(PaperPluginProviderFactory.java:23) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.provider.type.PluginFileType.getConfig(PluginFileType.java:77) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:70) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.provider.source.PluginFlagProviderSource.registerProviders(PluginFlagProviderSource.java:23) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.provider.source.PluginFlagProviderSource.registerProviders(PluginFlagProviderSource.java:13) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:104) ~[paper-1.20.2.jar:git-Paper-201]
	at net.minecraft.server.Main.main(Main.java:134) ~[paper-1.20.2.jar:git-Paper-201]
	at org.bukkit.craftbukkit.Main.main(Main.java:324) ~[paper-1.20.2.jar:git-Paper-201]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
As you can see, snakeyaml 2.2 introduced a new method called 'resetDocumentIndex' and configurate 4.1.2's ConfigurateScanner class does not implement that method which means configurate 4.1.2 does not support snaakeyaml 2.2. 4.2.0-SNAPSHOT is working fine because there is no longer a ConfigurateScanner class that implements the Scanner interface of snakeyaml.

**Comment by portlek** [comment]
this PR https://github.com/PaperMC/Paper/pull/9230 will solve the problem.

**Comment by Andre601** [comment]
I want to mention that this also happens if a plugin uses Configurate with the YamlConfigurationLoader and doesn't shade in (Or I assume define as a dependency to load in) their own SnakeYaml and Configurate to use... If that is even possible on a technical level.

Source: My plugin uses Configurate and I encounter this exact error myself.
