### ISSUE TITLE
Chunk corruption on Paper 1.20.2 experimental v214, possibly related to `ca.spottedleaf.dataconverter.minecraft.versions.V3568.convertMobEffectList`

### ISSUE THREAD

**Issue by lordofpipes** [PaperSpigot/Paper#9796]
### Expected behavior

All chunks should successfully upgrade

### Observed/Actual behavior

Many chunks fail to load and get reset to the blended chunks the seed would generate:
![comparison](https://github.com/PaperMC/Paper/assets/68424788/38ff050d-6463-44eb-b267-9338632a1431)

The following error message showing every time a chunk is corrupted:
```
[22:41:01 ERROR]: [ChunkLoadTask] Failed to parse chunk data for task: GenericDataLoadTask{class: io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask, world: world, chunk: (-125144,-124724), hashcode: 829558702, priority: COMPLETING, type: CHUNK_DATA}, chunk data will be lost
java.lang.NullPointerException: Cannot invoke "ca.spottedleaf.dataconverter.types.MapType.getList(Object, ca.spottedleaf.dataconverter.types.ObjectType)" because "data" is null
	at ca.spottedleaf.dataconverter.minecraft.versions.V3568.convertMobEffectList(V3568.java:119) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.versions.V3568$6.convert(V3568.java:220) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.versions.V3568$6.convert(V3568.java:197) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.IDDataType.convert(IDDataType.java:97) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.IDDataType.convert(IDDataType.java:15) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.walkers.generic.DataWalkerListPaths.walk(DataWalkerListPaths.java:29) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.IDDataType.convert(IDDataType.java:145) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.walkers.generic.WalkerUtils.convertList(WalkerUtils.java:35) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.versions.V2843.lambda$register$0(V2843.java:67) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:111) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:13) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convert(MCDataConverter.java:68) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convertTag(MCDataConverter.java:29) ~[paper-1.20.2.jar:git-Paper-214]
	at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:122) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.ChunkLoadTask$ChunkDataLoadTask.runOffMain(ChunkLoadTask.java:333) ~[paper-1.20.2.jar:git-Paper-214]
	at io.papermc.paper.chunk.system.scheduling.GenericDataLoadTask$ProcessOffMainTask.run(GenericDataLoadTask.java:307) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.20.2.jar:git-Paper-214]
	at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.20.2.jar:git-Paper-214]
```
[Here is the full latest.log](https://github.com/PaperMC/Paper/files/12812524/latest.log)

### Steps/models to reproduce

Load the following world:
Zip download: [minimal-test-case.zip](https://github.com/PaperMC/Paper/files/12812565/minimal-test-case.zip)
Github repository: https://github.com/lordofpipes/papermc-corruption-test-case

This world contains a single 1.20.1 region file (and its poi/entities counterparts) that has two chunks corrupted when loading it in 1.20.2.

Load the world with Paper 1.20.2 v214, run `op <username>`, `gamemode spectator <username>` in console.

Then run `/tp -2002303.70 88.09 -1995549.51 -152.41 31.65` ingame to get to the problem location.

(Note that there will be other areas that are cut off since this is just a single region file out of a larger world. Ignore these, the screenshotted location is where the problems are.)

### Plugin and Datapack List

None.

### Paper version

```
[23:23:59 INFO]: Checking version, please wait...
[23:23:59 INFO]: This server is running Paper version git-Paper-214 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 02cfaa8)
You are running the latest version
```

Configs are all default

**Comment by lordofpipes** [comment]
The following may be able to workaround this issue, and seems to clear up all of the corruption I was able to find:

**⚠️ I have no idea if this is an appropriate workaround, or if it's a kludge and turns out to silently drop mob related data. Use at your own risk and assume the worst! ⚠️**
```diff
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: lordpipe <lordpipe@protonmail.com>
Date: Wed, 4 Oct 2023 23:43:28 -0600
Subject: [PATCH] fix corruption bug


diff --git a/src/main/java/ca/spottedleaf/dataconverter/minecraft/versions/V3568.java b/src/main/java/ca/spottedleaf/dataconverter/minecraft/versions/V3568.java
index 98272d556a09e9f035005c6783ebb229c2c7157d..bd427f29b5ef6a9de9b571111afe5f34ebf4f840 100644
--- a/src/main/java/ca/spottedleaf/dataconverter/minecraft/versions/V3568.java
+++ b/src/main/java/ca/spottedleaf/dataconverter/minecraft/versions/V3568.java
@@ -116,6 +116,9 @@ public final class V3568 {
     }
 
     private static void convertMobEffectList(final MapType<String> data, final String oldPath, final String newPath) {
+        if (data == null) {
+            return;
+        }
         final ListType effects = data.getList(oldPath, ObjectType.MAP);
         if (effects == null) {
             return;
```

**Comment by kennytv** [comment]
Thank you for the detailled report, fixed

**Comment by lordofpipes** [comment]
Confirmed that cfe311d7a51eeb9e14c526f57efab9837f30c5d0 correctly updates all of the problem chunks I encountered.
