### ISSUE TITLE
Paper no longer works on AIX

### ISSUE THREAD

**Issue by TMinusBlastedRocket** [PaperSpigot/Paper#9802]
### Expected behavior

For some inexplicable reason, Paper and Spigot used to work on IBMs AIX (IBMs UNIX)  

### Observed/Actual behavior

Anything that uses a database breaks in comical fashion 

### Steps/models to reproduce

Buy a currently supported IBM PowerVM server (Power8 and newer (THAT IS NOT THE "L" SERIES))
Try to run paper
JDBC explodes violently 

### Plugin and Datapack List

Literally anything that uses SQL

### Paper version

Current 

### Other

Yes I know this is the "edge case brought to you by Satan", but AIX with POWER in the SMT1-4 modes is spectacular at running minecraft due to IBM creating a special java just for it (based on J9), excellent single threaded performance and an S tier vector calculation engine 

My proposed fix is to have a pure Java mode that doesn't use native librarys if possible and have it run automatically if a wack os/arch is detected 

Or just patch jdbc to build for AIX >w<

**Comment by electronicboy** [comment]
I mean, the only jdbc related thing we have that uses natives is sqlite, and that's pretty much out of our control, they don't have a "pure java mode"; we'd need the exception to see what to say, but, unsupported platform nobody here can work with, yada yada

**Comment by TMinusBlastedRocket** [comment]
IBM does maintain their own JDBC builds those should contain an AIX build you might be able to patch a driver in from

Btw the error is the classic "unknown platform"

**Comment by TMinusBlastedRocket** [comment]
[STDERR] [org.sqlite.SQLiteJDBCLoader] Failed to load native library through System.loadLibrary
[03:02:42 WARN]: java.lang.UnsatisfiedLinkError: Can't load sqlitejdbc
[03:02:42 WARN]:        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:1805)
[03:02:42 WARN]:        at java.base/java.lang.System.loadLibrary(System.java:767)
[03:02:42 WARN]:        at org.sqlite.SQLiteJDBCLoader.loadNativeLibraryJdk(SQLiteJDBCLoader.java:303)
[03:02:42 WARN]:        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:373)
[03:02:42 WARN]:        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:72)
[03:02:42 WARN]:        at org.sqlite.core.NativeDB.load(NativeDB.java:67)
[03:02:42 WARN]:        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:280)
[03:02:42 WARN]:        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:67)
[03:02:42 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
[03:02:42 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
[03:02:42 WARN]:        at org.sqlite.JDBC.createConnection(JDBC.java:104)
[03:02:42 WARN]:        at org.sqlite.JDBC.connect(JDBC.java:77)
[03:02:42 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
[03:02:42 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)

**Comment by TMinusBlastedRocket** [comment]
[03:02:42 WARN]: Caused by: java.lang.Exception: No native library found for os.name=AIX, os.arch=ppc64, paths=[/opt/freeware/jdk-17.0.8.1+1/lib/default:/opt/freeware/jdk-17.0.8.1+1/lib:/opt/freeware/jdk-17.0.8.1+1/lib/server:/opt/freeware/jdk-17.0.8.1+1/lib:/opt/freeware/jdk-17.0.8.1+1/../lib:/usr/lib64:/usr/lib]

**Comment by TMinusBlastedRocket** [comment]
also I am willing to give the paper team access to my current gen AIX system to fix this issue if they want to take on the challenge 

DM me on discord name: tminusblastedrocket

**Comment by TMinusBlastedRocket** [comment]
![Screenshot_20231006_104328_Discord.jpg](https://github.com/PaperMC/Paper/assets/35880366/12355e25-6db4-427e-af98-92a45a0ce65b)

Reposted from discord

**Comment by TMinusBlastedRocket** [comment]
For those that encounter this after me, the fix is to build sqllite-jdbc for AIX (using gcc with the -maix64 flag instead of -m64) and place the resulting files in /usr/lib, this will then be autodetected on startup and allow paper to work

**Comment by MiniDigger** [comment]
I will close this, as its not related to paper in any way (other than that we bundle that sqlite driver I think?)
ideally you would PR natives for AIX to the driver and we can pull it in I guess? then everybody can benefit from your fix.
other than that, there is nothing we can do here.
