### ISSUE TITLE
Error when opening custom menu, does not occur on regular spigot jar

### ISSUE THREAD

**Issue by 7rory768** [PaperSpigot/Paper#9873]
### Expected behavior

GUI to open

### Observed/Actual behavior

Player#openInventory(Inventory) causes the player falls through the void and is completely glitched

### Steps/models to reproduce

Open a custom GUI from a plugin

### Plugin and Datapack List

![image](https://github.com/PaperMC/Paper/assets/6015350/d4896fe0-82cd-4ce3-80d5-1da4c573e42c)

### Paper version

This server is running Paper version git-Paper-249 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 996d529)
You are running the latest version
Previous version: git-Paper-"6ebec37" (MC: 1.19)

### Other

Inventory is cached and items are inserted on plugin startup just fine. Error doesn't occur until trying to open the GUI for a player

```
[12:42:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'horses' in plugin RPGHorses v1.2.21
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.2.jar:git-Paper-249]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2207) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2167) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-249]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:510) ~[?:?]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:744) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:732) ~[paper-1.20.2.jar:git-Paper-249]
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:298) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:243) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.addSlotListener(AbstractContainerMenu.java:176) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.initMenu(ServerPlayer.java:681) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:374) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:345) ~[paper-1.20.2.jar:git-Paper-249]
        at org.plugins.rpghorses.players.HorseOwner.openStableGUIPage(HorseOwner.java:176) ~[RPGHorses.jar:?]
        at org.plugins.rpghorses.players.HorseOwner.openStableGUIPage(HorseOwner.java:171) ~[RPGHorses.jar:?]
        at org.plugins.rpghorses.commands.RPGHorsesCommand.onCommand(RPGHorsesCommand.java:388) ~[RPGHorses.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
[12:42:17 ERROR]: Entity threw exception at world:56.69999998807907,64.0,-22.58816074838962
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:510) ~[?:?]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:744) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:732) ~[paper-1.20.2.jar:git-Paper-249]
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:298) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:243) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:727) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1386) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:900) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-249]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Shynixn** [comment]
### Notes

I get the same error when I try to manually send a ClientboundSetEquipment Packet with an Skull_Item ItemStack containing the skin profile of a player to a target Armorstand Head Item Slot.


### Expected behavior

The Armorstand shows the item fine like on other spigot 1.20.2 versions.

### Observed/Actual behavior

The client crashes and disconnects from the server.

### Paper version

Observed the same in git-Paper-249 and git-Paper-248. The log below is from 248.

### Other

https://github.com/Shynixn/BlockBall/issues/471

```
[21:31:56 ERROR]: Packet encoding of packet ID 87 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:510) ~[?:?]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:744) ~[paper-1.20.2.jar:git-Paper-248]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:732) ~[paper-1.20.2.jar:git-Paper-248]
        at net.minecraft.network.FriendlyByteBuf.writeItem(FriendlyByteBuf.java:643) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundSetEquipmentPacket.write(ClientboundSetEquipmentPacket.java:47) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:42) ~[paper-1.20.2.jar:git-Paper-248]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.20.2.jar:git-Paper-248]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:31:56 INFO]: Shynixn lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.d()" because the return value of "java.util.Map$Entry.getValue()" is null
```

**Comment by lynxplay** [comment]
The plugin is using reflections to set a profile incorrectlly.
Spigot should be spamming you with a warning that a plugin is messing up.
Paper has yet to pull the "fix" spigot added for this, in reality the plugin is simply incorrectly using internals.

If you want to set the profile in a CraftMetaSkull, make sure to also update `serializedProfile` manually or by using `setProfile` instead.
