### ISSUE TITLE
Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null

### ISSUE THREAD

**Issue by SlimeDog** [PaperSpigot/Paper#9875]
### Expected behavior

Clean start-up and plugin usage, as occurred with Paper build 246 and prior

### Observed/Actual behavior

Errors reported on plugin enable or usage (depending on the plugin) for a number of plugins, including AdminVault and DeluxeMenus, similar in character to the following
```
[12:55:18] [Server thread/INFO]: [AdminVault] Enabling AdminVault v1.0.1
[12:55:18] [Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:148) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:659) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:60) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemFactory.ensureServerConversions(CraftItemFactory.java:492) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.inventory.ItemStack.ensureServerConversions(ItemStack.java:702) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:547) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:464) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:430) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:574) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
        at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at com.infermc.adminvault.diskHandler.fromDisk(diskHandler.java:74) ~[AdminVault-1.0.1-Alpha.jar:?]
        at com.infermc.adminvault.AdminVault.onEnable(AdminVault.java:47) ~[AdminVault-1.0.1-Alpha.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-249]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-249]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
and
```
[13:02:06] [Server thread/INFO]: rambeau issued server command: /deluxemenus open navigation4
[13:02:07] [Craft Scheduler Thread - 90 - DeluxeMenus/WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.14.0-DEV-167 generated an exception while executing task 26922
java.lang.NullPointerException: Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:148) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:659) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:60) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[paper-1.20.2.jar:git-Paper-249]
        at com.extendedclip.deluxemenus.menu.Menu.lambda$openMenu$5(Menu.java:442) ~[DeluxeMenus-1.14.0-b167.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-249]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-249]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps/models to reproduce

- Update Paper from build 246 to build 249 (or 248 or 247)
- Start server
- Observed ERROR or WARN messages in log

### Plugin and Datapack List

Many; list available if needed

### Paper version

```
> version
[15:39:40 INFO]: This server is running Paper version git-Paper-249 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 996d529)
You are running the latest version
Previous version: git-Paper-246 (MC: 1.20.2)
```

**Comment by Machine-Maker** [comment]
Ok, so the issue here, is a profile is trying to be deserialized that doesn't have a name.

**Comment by SlimeDog** [comment]
The various plugins haven't changed their usage. Only Paper has been updated.

**Comment by Machine-Maker** [comment]
> The various plugins haven't changed their usage. Only Paper has been updated

Yeah, I get that. This is all just caused by mojang making a name **and** uuid required for a gameprofile in 1.20.2 whereas previously it was a name **or** uuid.

**Comment by SlimeDog** [comment]
Ah. Thanks.

**Comment by iGabyTM** [comment]
> > The various plugins haven't changed their usage. Only Paper has been updated
> 
> Yeah, I get that. This is all just caused by mojang making a name **and** uuid required for a gameprofile in 1.20.2 whereas previously it was a name **or** uuid.

Would an empty name be valid or we have to provide one, like `Steve`? This is what we did and it worked: (I'm not sure what version of paper was used for testing)
```java
// Before
GameProfile profile = new GameProfile(UUID.randomUUID(), null);
// After
GameProfile profile = new GameProfile(UUID.randomUUID(), "");
```

**Comment by Leguan16** [comment]
> Would an empty name be valid or we have to provide one, like `Steve`? This is what we did to fix DeluxeMenus on 1.20.2 and it worked: (I'm not sure what version of paper was used for testing)
> ```java
> // Before
> GameProfile profile = new GameProfile(UUID.randomUUID(), null);
> // After
> GameProfile profile = new GameProfile(UUID.randomUUID(), "");
> ```
> 
Well it just can't be Null. What you provide as name doesn't matter. Paper also just uses an Empty string afaik.

**Comment by iGabyTM** [comment]
I'm asking because @SlimeDog said the error was produced with a dev version of DeluxeMenus that contains the fix https://ci.extendedclip.com/job/deluxemenus/167/
> Fixed 1.20.2 basehead issues - GameProfile requires NonNull Name (#204) ([commit: ee6b833](https://github.com/HelpChat/DeluxeMenus/commit/ee6b83394e1bb7a779c4417023581a1b977d03b4)) ([details](https://ci.extendedclip.com/job/deluxemenus/167/changes#ee6b83394e1bb7a779c4417023581a1b977d03b4) / [githubweb](https://github.com/extendedclip/DeluxeMenus/commit/ee6b83394e1bb7a779c4417023581a1b977d03b4))

**Comment by Leguan16** [comment]
This is not bukkit's fault. Mojang doesn't allow name OR uuid anymore.

**Comment by Leguan16** [comment]
null name is the problem. A fix already sets it to an Empty string if name is null.

**Comment by electronicboy** [comment]
> can we not just set a null name to an empty string and call it a day

Yes, however we are not going to modify mojangs auth lib to hack around plugins messing with unsupported internals

>  i heard there was a nag about "inconsistant skulls" added, seems kinda silly IMO.

Reflecting into skull meta to deal with profile related stuff has been broken in varying capacities for the past few years, as for why spigot doesn't just remove the applicable field that plugins reflect into and break them entirely rather than trying to after several years faux it back in when API has existed for long enough now, I have no idea, but, it's not on the API impl to try to work around plugins doing stuff which has been unsupported and has been warned against for years now.

**Comment by electronicboy** [comment]
https://jd.papermc.io/paper/1.20/org/bukkit/profile/class-use/PlayerProfile.html

**Comment by iGabyTM** [comment]
Is there anything we (plugin devs) can do about this warning?
```
[16:53:28 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
```

**Comment by electronicboy** [comment]
Yes, use the API properly
if you REALLY must use internals, then you'll need to make sure that you actually populate what iirc is the serialised profile field, see the internals for what goes on there, generally
