### ISSUE TITLE
Whisper with command block not working

### ISSUE THREAD

**Issue by Athar42** [PaperSpigot/Paper#9930]
### Expected behavior

When a command block is powered by a redstone signal with either of the following commands, it should send of whisper message to the nearby player.
Commands used : 
/tell @p TEST or /execute at @p run msg @p Test

Player get a whisper message from the server.

### Observed/Actual behavior

When a command block is powered by a redstone signal with either of the following commands, it failed.
/tell @p TEST
/execute at @p run msg @p Test

`[14:11:30 ERROR]: Thread Async Chat Thread - #0 failed main thread check: sendSystemMessage to a command block
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[paper-1.20.2.jar:git-Paper-197]
        at net.minecraft.world.level.BaseCommandBlock.sendSystemMessage(BaseCommandBlock.java:175) ~[?:?]
        at net.minecraft.commands.CommandSourceStack.sendChatMessage(CommandSourceStack.java:316) ~[?:?]
        at net.minecraft.server.commands.MsgCommand.sendMessage(MsgCommand.java:39) ~[?:?]
        at net.minecraft.server.commands.MsgCommand.lambda$register$0(MsgCommand.java:22) ~[?:?]
        at net.minecraft.commands.arguments.MessageArgument.lambda$resolveDisguisedMessage$2(MessageArgument.java:68) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

### Steps/models to reproduce

1- Prepare a 1.20.2 paper server (issue introduced since build 197 (present through build 280 included at least) - was working fine on 1.20.1 build 196)
2- Enable command block in the server configuration
3- Start the server
4- Log to the server and place a command block powered by a redstone signal (can be linked to a pressure plate, or just use a button on it)
5- Use one of the following command to execute : 
/tell @p TEST
OR
/execute at @p run msg @p Test
6- Trigger the command block with the selected activator method (button or anything else)
7- No message is whispered to the player and the server console display the error.

### Plugin and Datapack List

Vanilla server, no plugins or datapacks added.

### Paper version

This server is running Paper version git-Paper-279 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 274e54b)

### Other

I tested a lot of build release from 1.20.1 version (including latest 196 build) ==> The command block was working as expected.
Since 1.20.2 build 197 ==> The command block (with that specific chat whisper command) is not working anymore. Tested with build 280 too, not better.

Thanks for your support :)

**Comment by Owen1212055** [comment]
This is due to async chat, as we have to decorate/resolve message arguments on the chat chainer, which causes it to get moved to the async chat thread. This then however causes the callback logic to be done async, so we probably just need to bump it back to the main thread?

**Comment by Athar42** [comment]
Just wanter to thanks everyone involved in fixing this issue, that was really fast and it seems to be working like a charm again.
Thanks you thank you thank you 🥰
